<div class="ttinnnerpad"><h4><strong>1) What is Discard pile and stock pile?</strong></h4>
<p>The Discard Pile is the deck which is gathered from the discarded cards by the players in each round. This is where players place an unwanted card. The pile is face up and only the top card is seen. Players can also draw from this pile but cannot examine previous discards. The Discard pile re-mixes again when all the cards in the Stock are finished during the game and then the Discard pile is becoming the stock and the game continues.</p>
<p><b>Closed Deck:</b> After the cards have been distributed, the remaining pile is called closed cards (stock pile).</p>
<p><b>Stock pile:</b> The Stock deck is the leftover deck after the dealing of the cards to all players. From this deck the players draw a card at the beginning of each round, this indicates the turn of each player. When the Stock runs out we mix the Discard Pile which accumulated and turning it to the new Stock deck. The Stock deck is placed at the centre of the table and is accessible to all players.</p>
<p>Players can draw a single card from the stock pile on a turn. This pile is face down and none of the cards are seen so drawing from stock involves a higher degree of risk, chance or luck than the discard pile.</p>
<p class = "bottom">The most recent discarded card goes to the top of discard pile. Only top card can be picked from the either pile.</p>
<p>&nbsp;</p>
<h4><strong>2) What is Drop?</strong></h4>
<p>Players can choose not to play a particular Round before drawing the first card. This action is termed as Drop. A player can decide to drop from the game before his turn comes.</p>
<p><b>Initial drop:</b>if a player decides to drop the game in the very beginning before picking up a single card, it is called initial drop.</p>
<p class = "bottom"><b>Middle Drop:</b>Players can choose not to play after a Round starts by neither drawing nor discarding any cards. This action is termed as Middle Drop. </p>
<p>&nbsp;</p>
<h4><strong>3) What is Deadwood?</strong></h4>
<p>The term "deadwood" is used for cards which are not included in any meld (Sequences or sets) and are therefore unmatched. These are the cards which are left in the hands of the players after the last move in the game; the sum of these cards is counted to the iniquity of the same player who's left with the cards.</p>
<p>The deadwood count is the total value of those cards.</p>
<p>In case of show player must mandatorily have Life 1 and Life 2.</p>
<p class = "bottom">Failing to have life 1, all cards are considered as Deadwood. Failing to have Life 2, all cards, but life 1 are considered as deadwood.</p>
<p>&nbsp;</p>
<h4><strong>4) What is Lobby?</strong></h4>
<ul class = "bullet-normal">
	<li>List of all the game rooms are provided in details in lobby.</li>
	<li>The details include: Table id, Amount type, Entry fee, Min players, No. of players etc.</li>
	<li>JOIN: Next to every room there is a join button. On clicking, you become a spectator in that room.</li>
	<li>SIT: A sit button is provided in order to play the game. As you click on this button, you are given a chair on the game table. Once there are enough players on a table, the game begins. You cannot join a game in middle as a player.</li>
</ul>
<h4><strong>5) What is Sequence?</strong></h4>
<p>The purpose of the game is to complete a hand with most or all cards formed into Sets and/or Sequences. To make a Sequence a player should arrange three or more cards of the same suit in sequence, the order being A-2-3-4-5-6-7-8-9-10-J-Q-K-A: </p>
<table>
	<tr>
		<td><b>Example of a Valid Sequence</b></td>
		<td><b>Example of an Invalid Sequence</b></td>
	</tr>
	<tr>
		<td><b>3<span class="ttspade">&spades;</span>4<span class="ttspade">&spades;</span>5<span class="ttspade">&spades;</span></b></td>
		<td><b>3<span class="ttspade">&spades;</span>4<span class="ttclub">&clubs;</span>5<span class="ttheart">&hearts;</span></b></td>
	</tr>
	<tr>
		<td style="background:#fff"><b>10<span class="ttheart">&hearts;</span>J<span class="ttheart">&hearts;</span>Q<span class="ttheart">&hearts;</span>K<span class="ttheart">&hearts;</span></b></td>
		<td style="background:#fff"><b>10<span class="ttheart">&hearts;</span>J<span class="ttheart">&hearts;</span>Q<span class="ttdiamond">&diams;</span>K<span class="ttheart">&hearts;</span></b></td>
	</tr>
</table>
<h4><strong>6) What is a set?</strong></h4>
<p>A player can form a set by arranging three or four cards of the same rank/face value and different suits:
<table>
	<tr>
		<td><b>Example of a Valid Set</b></td>
		<td><b>Example of an Invalid Set</b></td>
	</tr>
	<tr>
		<td><b>A<span class="ttspade">&spades;</span>A<span class="ttheart">&hearts;</span>A<span class="ttclub">&clubs;</span></b></td>
		<td><b>A<span class="ttspade">&spades;</span>A<span class="ttheart">&hearts;</span>2<span class="ttclub">&clubs;</span></b></td>
	</tr>
	<tr>
		<td style="background:#fff"><b>K<span class="ttspade">&spades;</span>K<span class="ttheart">&hearts;</span>K<span class="ttclub">&clubs;</span>K<span class="ttdiamond">&diams;</span></b></td>
		<td style="background:#fff"><b>K<span class="ttspade">&spades;</span>K<span class="ttheart">&hearts;</span>Q<span class="ttdiamond">&diams;</span></b></td>
	</tr>
</table>
Combinations must not overlap - for example <span class="ttdiamond">&diams;</span>7<span class="ttdiamond">&diams;</span>8<span class="ttdiamond">&diams;</span>9<span class="ttspade">&spades;</span>9<span class="ttheart">&hearts;</span>9 is either a Sequence of diamonds with two spare 9's or a set of 9's with two spare diamonds. If a second <span class="ttdiamond">&diams;</span>9 or a <span class="ttclub">&clubs;</span>9 or a <span class="ttdiamond">&diams;</span>6 is added, the six cards form a Sequence and a set. Sets of 5 are not valid with/without a joker!
<p>Wild cards can be used to substitute for any desired card in a set or Sequence. For example if the turned up card is a <span class="ttclub">&clubs;</span>8 then <span class="ttdiamond">&diams;</span>3<span class="ttspade">&spades;</span>8<span class="ttheart">&hearts;</span>5 is a valid Sequence, and <span class="ttspade">&spades;</span>J<span class="ttdiamond">&diams;</span>J<span class="ttdiamond">&diams;</span>8 is a valid set since all 8's are wild.</p>
<p class = "bottom">A card can be used only once, either in a Set or in a Sequence. In other words, you cannot use the same card for both a Sequence and a Set. Note that in a Set, each card must be of the same rank and a different suit, however when two decks are used situations do arise where you have in your hand for example <span class="ttheart">&hearts;</span>K and <span class="ttheart">&hearts;</span>K - you cannot add to this <span class="ttclub">&clubs;</span>K to form a valid Set of three as the first two kings are of the same suit.</p>
<p>&nbsp;</p>
<h4><strong>7) What is melding?</strong></h4>
<p class = "bottom">Melding is the process by which cards are placed together to form sets (at least three cards of same rank) or sequences (at least three cards of same suit in consecutive rank).There is no laying melds on the table during play as this only happens when someone goes out. There is no knocking too in Indian Rummy. If the player manages to meld all his cards and has a zero deadwood count, and his hand meets the requirement of containing at least two sequences (one of which is pure, with no wild cards), only then may he go out. He does this by placing his melds on the table and discarding the final card (traditionally face down) to signal victory. At this point, other players display their melds and deadwood is counted up and scored accordingly. There are two kinds of combinations: Sequences and Sets.  A player wins the game by being the first to play all the cards in their hand by melding.</p>
<p>&nbsp;</p>
<h4><strong>8) What is Pure Sequence and Second Sequence?</strong></h4>
<ul class = "bullet-normal">
	<li>Life or Pure Sequence (Life1)
		<ul class = "bullet-normal-1"><li>It should be the order of not less than three cards of the same suite. Life1 shouldn't have a Joker.</li></ul>
	</li>
	<li>Second Life or Second Sequence (Life2) 
		<ul class = "bullet-normal-1"><li>It must be a sequence of at least three cards of the same suite. Life 2 may or may not have a joker.</li></ul>
	</li>
</ul>
<h4><strong>9) What is Count?</strong></h4>
<p class = "bottom">The total score of the deadwood is referred to as count. Count gets accumulated with each game. The maximum count a player can get in a game is 80 which is also known as full count! </p>
<p>&nbsp;</p>
<h4><strong>10) What are Win Combinations?</strong></h4>
<p>In order to have a winning combination, the player must have a Life, second life and other sets or Sequences. Different combinations for a win</p> 
<ul class ="bullet-normal">
	<li>2 Sequences of 3, a set or Sequence of 3, a set or Sequence of 4 </li>
	<li>One Sequence of 3, one Sequence of 4, 2 sets or Sequences of 3</li>
	<li>One Sequence of 5, one Sequence of 4, one set or Sequence of 4</li>
	<li>Two Sequences of 5, one set of 3</li>
</ul>
<h4><strong>11)  What happens if I join in the middle of a game?</strong></h4>
<p class="bottom">In a Pool game or Syndicate – The player who joins  in the middle of the game is given the same number of points (+1) that the  highest point holder in the game already has.</p>
<p>&nbsp;</p>
<h4><strong>11)  What happens if I join in the middle of a game?</strong></h4>
<p>In a Pool game or Syndicate – The player who joins  in the middle of the game is given the same number of points (+1) that the  highest point holder in the game already has.</p>
<p class = "bottom">For all other types of Rummy games (Rapid Rummy  &amp; Rummy Race) – The player begins at 0.</p>
<p>&nbsp;</p>
<h4><strong>12) For a player joining in the middle of the game, how is the prize money is  distributed?</strong></h4>
<p class = "bottom">As a new player joins an existing game, his table  entry will be added to the pot excluding the game service charges. If the  player wins, he/she is subject to winning the entire prize money on offer.</p>
<p>&nbsp;</p>
<h4><strong>13) What are Pool games (Syndicate) games?</strong></h4>
<p>Pool games are knockout games. The last player  standing wins the entire pot. As and when a player melds correctly- The points  that are left on the hands of the other players on the table are taken as the  score.</p>
<p class = "bottom">As and when the game progresses- The score may keep  increasing if the player loses/stays the same if he/she wins. The last person  to stay on the table without reaching the knockout score is declared the winner.</p>
<p>&nbsp;</p>
<h4><strong>14) What are 101 &amp; 201 Pool  games?</strong></h4>
<p class = "bottom">As explained in the previous question, as a player  gathers 101 points in a 101 pool game, He/she is knocked out. Similarly, the  same for 201 Pool games- As a player accumulates 201 points- He/She is knocked  out and does not have the chance of winning.</p>
<p>&nbsp;</p>
<h4><strong>15) Can players rejoin once they have been knocked out of a Pool game?</strong></h4>
<p>Yes, There are conditions under which a player may  rejoin after again paying the entry fee for the table.</p>
<ul class = "bullet-normal">
	<li><strong>For 101 Pool Game</strong>
		<ul class = "bullet-normal-1"><li>A player may rejoin the 101 Pool game after being  knocked out. This may only happen when an existing player (on the table) has a  maximum of 79 points. That would imply that the new player (rejoining/new  player) would start the game with 80 points.</li></ul>
	</li>
	<li><strong>For 201 Pool game</strong>
		<ul class = "bullet-normal-1"><li>A player may rejoin the 201 Pool game after being  knocked out. This may only happen when an existing player (on the table) has a  maximum of 174 points. That would imply that the new player(rejoining/new  player) would start the game with 175 points. </li></ul>
	</li>
</ul>
<p class = "bottom"><strong>Note:</strong> This will also apply to brand new players  wanting to join a room with existing players.</p>
<p>&nbsp;</p>
<h4><strong>16) What are the different forms of 13 card Rummy that are offered on TaashTime?</strong></h4>
<p>There are primarily three forms of 13 card Indian  Rummy offered on TaashTime:</p>
<ul class = "bullet-normal">
	<li><strong>Pool games</strong>
		<ul class = "bullet-normal-1"><li>These are knock out games. The players have to  ensure that they do not accumulate more than 101 points. At which point they  get eliminated. The last player remaining who does not get eliminated is  declared the winner.</li></ul>
	</li>
	<li><strong>Forward Ladder games – Rummy Race</strong>
		<ul class = "bullet-normal-1"><li>These games are a ‘’race to a particular score’’  games. The points are distributed based on the final meld. If a player has  melded correctly, then he/she gets the sum of the points that the other players  have in hand after final meld.</li></ul>
	</li>
	<li><strong>Money Per Point (MPP) games- Rapid Rummy</strong>
		<ul class = "bullet-normal-1"><li>These games are so called because for every game  that is played, a player receives the sum of the number of points (in total)  that are given to him by the losing players on the table. The denominations may  change for different MPP games. For eg. 10 ps per point, Rs 3 per point and so  on.</li></ul>
	</li>
</ul>
<h4><strong>17) How to leave the table?</strong></h4>
<p class = "bottom">Once the game has been completed and a winner has  been decided- The player may chose to close the window in the time frame within  which the new game shall be started. The counter will start ticking on the top  of the screen in the game room window.</p>
<p>&nbsp;</p>
<h4><strong>18) I have melded with the correct number of suits, why have I got 80 count and  Wrong meld?</strong></h4>
<p>Please make sure that you go through our How to Play  section. It has a very elaborate description on how to meld correctly. <br />
A wrong meld may happen in the following ways:</p>
<ul class ="bullet-normal">
	<li>Wrong meld due to incorrect melding of cards.</li>
	<li>Using AutoMeld feature and not correctly grouping the cards.</li>
</ul>
<p class = "bottom">Automeld is a feature which  enables the player to successfully ‘Show’ the grouped cards in hand. This  feature may not be used on a complete set of 13 cards. Always remember to sort  your cards before using the Automeld feature!</p>
<p>&nbsp;</p></div>
<?php
//$this->help();