<?php

//echo $this->form;
$this->dateform($this->from, $this->to, $this->fromHour, $this->toHour, $this->fromMinute, $this->toMinute, $this->fromPM, $this->toPM, $this->items);

if($this->paginator)
{
	if (count($this->paginator))
	{
		$linkArray = array();
		foreach($this->contents as $tableData)
		{
			$ids = explode('-', $tableData['Gamelog Id']);
			$linkArray[$tableData['Gamelog Id']] = array(
					'controller' => 'roulettelogdetails',
					'action' => 'index',
					'sessId' => $ids[0],
					'logId' => $ids[1],
			);
		}
		$linkFields = array('Gamelog Id', 'Outcome');
		$this->table($this->contents, $linkFields, $linkArray, '', array('Outcome' => 'Gamelog Id'), true);
		/*echo "<table cellpadding='0' cellspacing='2' border='1'>";
		echo "<tr><td><b>" . "Log Id" . "</b></td><td><b>". "Session Id" . "</b></td><td><b>" . 
		"Machine Id" . "</b></td><td><b>". "Bet Amount" . "</b></td><td><b>" . "Currency" . 
		"</b></td><td><b>" . "Win Amount" . "</b></td><td><b>" . "Amount Type" . "</b></td><td><b>" . 
		"PJP Win Status" . "</b></td><td><b>" . "PJP Win Amount" . "</b></td><td><b>" . "Date Time" . "</b></td></tr>";
		foreach($this->paginator as $logs)
		{
			echo "<tr><td>" . $logs ['log_id'] . "</td><td>" . $logs['session_id'] . 
			"</td><td>" . $logs['machine_id'] . "</td><td>" . $logs['bet_amount'] . 
			"</td><td>" . $logs['wagered_currency'] . "</td><td>" . $logs['win_amount'] . 
			"</td><td>" . $logs['amount_type'] . 
			"</td><td>" . $logs['pjp_winstatus'] . "</td><td>" . $logs['pjp_win_amount'] . 
			"</td><td>" . $logs['datetime']. "  </td></tr>";
		}*/
	}
	
	//$this->view->result = array($this->paginator, $this->date)
	//echo $this->paginationControl($this->paginator, 'Sliding', 'my_paginator_control.phtml', $this->view->date = "hi");
	echo $this->paginationControl($this->paginator, 'Sliding', 'my_paginator_control.phtml', array('myFromDate' => $this->fromDate, 'myToDate' => $this->toDate));
}

?>
