<?php 
$authSession = new Zenfox_Auth_Storage_Session();
$sessionData = $authSession->read();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Bingo</title>
<link rel="stylesheet" href="/css/bingobible/style.css" type="text/css" />
<link rel="stylesheet" href="/css/bingobible/common.css" type="text/css" />
<link rel="stylesheet" href="/css/bingobible/style-mobile.css"  type="text/css" />
<link rel="stylesheet" href="/css/bingobible/style-tablet-landscape.css"  type="text/css" />
<link rel="stylesheet" href="/css/bingobible/style-tablet-potrate.css"  type="text/css" />
<script type="text/javascript" src="/js/bingobible/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="/js/bingobible/jquery.bxslider.js"></script>
<script type="text/javascript" src="/js/bingobible/jquery.colorbox.js"></script>
<script type="text/javascript" src="/js/bingobible/custom.js"></script>

<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript" src="http://s.sharethis.com/loader.js"></script>
</head>
<body class="home-page">
<div class="header">
  <div class="top-ribbon">
   <div class="logo"><a href="/"><img src="/images/bingobible/logo.png" alt="logo-image"/></a></div>
   <?php 
   if($sessionData)
   {
   	?>
   	<div class="after-login">
   	<div class="game-page-img-3">
   	<p class="points">Seeramsetty</p>
   	<img id="profile-image" height="60" width="60" src="/images/bingobible/my-photo.png"></img>
   	<span id="notification">1</span>
   	<div class="my-profile">
   	<ul>
   	<li><a href="/auth/view">My Profile</a></li>
   	<li><a href="/auth/image">Set Profile Image</a></li>
   	<li class="supperation"></li>
   	<li><a href="">Settings</a></li>
   	<li><a href="/auth/view">Account</a></li>
   	<li><a href="/banking/deposit">Payment</a></li>
   	<li><a href="">Language</a></li>
   	<li></li>
   	<li><a href="/auth/logout">Logout</a></li>
   	</ul>
   	</div>
   	</div>
   	<div class="game-page-img-2">
   	<p class="points">Layman</p>
   	<p class="txt">Loyalty Points<br>2547500.00</p>
   	</div>
   	<div class="game-page-img-1">
   	<p class="points">£ 1,000.00</p>
   	<p class="cash">Cash <br><span>£ 500.00</span></p>
   	<p class="bonus">Bonus <br><span>£ 500.00</span></p>
   	</div>
   	</div>
   	<?php 
   }
   else
   {
   	?>
   	<div class="login-sec">
   	<form name="player-login-form" method="post" action="/auth/login">
   	<div class="input-fields">
   	<input type="text" Placeholder="Email" name="userName"/>
   	<input type="checkbox" /><p>Keep me logged in</p>
   	</div>
   	<div class="input-fields">
   	<input type="password" Placeholder="Password" name ="password"/>
   	<p  style="float:right;"><a href="/auth/forgotpassword">Forgot Password ?</a></p>
   	</div>
   	<input type="submit" name="login" value="Login" class="btn">
   	</form>
   	<a href="/auth/signup" class="btn-1">Sign Up</a>
   	</div>
   	<?php 
   }
	?>
  </div>
  <div class="menu-icon"><img src="/images/bingobible/menu-icon.png"></div>
  <div class="nav">
	<div class="menu">
    <ul id="menu">
    <li class="first-icon"><span>12568.00</span><span class="pad">Jackpot</span></li>
    <?php 
				    	$partial = array('menu.phtml','player');
						$this->navigation()->menu()->setPartial($partial);
						echo $this->navigation()->menu()->render(); 
						//echo $this->navigation()->menu();
					?>
    <!-- <li class="dropdown">Games
      <ul class="sub-menu">
       <li><a href="#">Plantsvs. Zombies Games</a></li>
       <li><a href="#">Bejeweld Games</a></li>
       <li><a href="#">Solitaire Bilts</a></li>
       <li><a href="#">Peggle Games</a></li>
       <li><a href="#">All Games</a></li>
       </ul>
    </li>
    <li>Banking</li>
    <li>Promotions</li>
    <li>Gallery</li> -->
    </ul>
   </div>
  </div>
</div>
<div id="socialicons">
<a href="#"><img src="/images/bingobible/fb-chat.png" /></a>
<a href="#"><img src="/images/bingobible/blog-chat.png"/></a>
<a href="#"><img src="/images/bingobible/fb-icon.png" /></a>
<a href="#"><img src="/images/bingobible/twitter-icon.png"/></a>
<a href="#"><img src="/images/bingobible/gplus-icon.png"/></a>
<a href="#"><img src="/images/bingobible/linkedin-icon.png"/></a>
<a href="#"><img src="/images/bingobible/pinterest-icon.png"/></a>
</div>
<div class="content">
<div class="content-top">
<div class="three-blck-sec">
  <div id="box-1">
		<center><p class="text">All New<br/> Bingo & Casino</p> </center>
		<center><p class="text-down">Tons Of Fun With Bingo</p></center>
  </div>
  <div id="box-2">
		<center><p class="text">Grand Prizes & Big Jackpots</p></center>
		<center><p class="text-down">Win With Your Bingo Buddies</p></center>
  </div>
  <div id="box-3">
		<center><p class="text">JOIN & GET £20 FREE</p></center>
		<form class="form" method="post" action="/auth/signup" enctype="application/x-www-form-urlencoded" name="player-signup" id="player-registration-form"><dl class="zend_form">
<ul><li>
<input type="text" placeholder="Username" class="box" value="" id="login" name="login"></li>
<li>
<input type="password" placeholder="Password" class="box" value="" id="password" name="password"></li>
<li>
<input type="password" placeholder="Confirm Password" class="box" value="" id="confirmPassword" name="confirmPassword"></li>
<li>
<input type="text" placeholder="Email" class="box" value="" id="email" name="email"></li>
<li>
<input type="hidden" value="0" name="terms"><input type="checkbox" class="chk-bx" checked="checked" value="1" id="terms" name="terms">
<div id="iagree"><p>I agree to <a href="/content/terms">Terms &amp; Conditions</a></p></div></li>
<li class="signup-button">
<button onclick="goToLogin('player-signup')" class="join-now" type="button" id="Signup" name="Signup">Join Now</button></li></ul></dl></form>
		<!-- form class="form">
			<input class="box" type="text" name="email" id="email" placeholder="username@domain.com" value=""width="200" size="30">
			<input class="box" type="password" name="password" id="password" placeholder="Password"  value=""width="200" size="30">
			<input class="box" type="password" name="confirm password" id="confirm password" placeholder="Confirm password"  value=""width="200" size="30">
			<input class="box" type="text" name="phone number" id="phone number" placeholder="Phone Number (Optional)" value=""width="200" size="30"><br/>
			<input class="chk-bx" type="checkbox" name="CB1" value="checkbox"><div id="iagree"><p>I agree to<span style="color:white;float:right;margin-right:18px;">Terms & Conditions</span></p></div>
			<input class="join-now"type="button" value="Join Now">
		</form-->
  </div>
</div>
</div>
<div class="content-middle">
  <div class="rect">
   <div class="rect-left">
   <h2>Play For Fun</h2>
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   </div>
   <div class="rect-right"><a href="/game">Checkout Our Games  ›</a></div>  
  </div>
   <div class="rect">
       <div class="rect-right-1 mar-rit"><a href="/game">Checkout Our Games  ›  </a></div>  
       <div class="rect-left no-mar">
       <h2>Win Cash Prizes</h2>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
  </div>
  <div class="rect">
   <div class="rect-left">
   <h2>Wherever You Are</h2>
   <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
   </div>
   <div class="rect-right-2"><a href="/game">Checkout Our Games  ›</a></div>  
  </div>
   <div class="rect">
       <div class="rect-right-2 mar-rit"><a href="/game">Checkout Our Games  ›  </a></div>  
       <div class="rect-left no-mar">
       <h2>Safe &amp; Secure</h2>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
  </div>
   <div class="btns"><a href="/game">Play Now</a> <a href="/auth/signup" class="free-btn">Free Sign Up</a></div>
   
<!--   <div class="social-btns">
  <span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_googleplus_large' displayText='Google +'></span>
<span class='st_linkedin_large' displayText='LinkedIn'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>
  </div>  -->
   
</div>
</div>
<div class="footer">
<div class="footer-main">
   <div class="footer-content">
    <div class="footer-column-1"><p>WE ACCEPT</p></div>
    <div class="footer-column-2">
	  <p><a href="/content/about">About Us</a></p>
	  <p><a href="/faq">FAQ</a></p>
	  <p><a href="/promotions/referfriend">Tell A Freind</a></p>
	</div>
    <div class="footer-column-3">
		<p><a href="/content/privacypolicy">Privacy Policy</a></p>
	    <p><a href="http://affiliate.bingobible.co.uk">Affiliates</a></p>
	    <p><a href="/content/rules">Rules</a></p>
	</div>
    <div class="footer-column-4">
	    <p><a href="/content/contact">Contact Us</a></p>
	    <p><a href="/content/terms">Terms of Use</a></p>	</div>
		   <div class="footer-column-5">
   </div>
   </div>


</div>
</div>


<!-- script type="text/javascript">stLight.options({publisher: "911b74ed-0178-43db-b71a-288ece655181", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<script>
var options={ "publisher": "911b74ed-0178-43db-b71a-288ece655181", "position": "right", "ad": { "visible": false, "openDelay": 5, "closeDelay": 0}, "chicklets": { "items": ["facebook", "twitter", "googleplus", "linkedin", "pinterest"]}};
var st_hover_widget = new sharethis.widgets.hoverbuttons(options);
</script-->
</body>
</html>
