<link rel="stylesheet" href="/css/global.css" />
<link rel="stylesheet" href="/css/jquery.treeview.css" />
<script type="text/javascript" src="/js/jquery/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery/js/jquery-ui.js" /></script>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script src="/js/jquery.treeview.js" type="text/javascript"></script>

<script type="text/javascript" src="/js/demo.js"></script>
<?php 
echo $this->helplinks($this->data, $this->helpContent);
if(!$this->noIndex)
{
	?>
<div id = "display_help">
<?php
echo $this->helpContent;
echo '<br>';
?>
<a href = "#" onclick='return popitup("/help/index", "1")'>Help-Index</a>
</div>
<?php
}


