<div class="middle-con">
	<div class="middle-con-left"></div>
	<div class="middle-con-right">
		<h3>100% Welcome Bonus</h3>
		<p>Join us and claim a 100% bonus on your first purchase today. Please note the following rules that apply to this offer.</p>
		<a href="#welcome-bonus">Read More...</a>
	</div>
</div>
<div class="middle-con">
	<div class="middle-con-left"></div>
	<div class="middle-con-right">
		<h3>Refer &amp; Earn</h3>
		<p>You can now earn credits by referring your friend to Ace2jak.com. When a friend you refer joins the game and converts to a Premium player, you will be credited with reward points. These reward points expire in 45 days from the date of issue.</p>
		<a href="#refer-earn">Read More...</a>
	</div>
</div>
<div class="middle-con">
	<div class="middle-con-left"></div>
	<div class="middle-con-right">
		<h3>Special Daily Tournaments</h3>
		<p>Register and grab the opportunity to make your day even more exciting. Play in our Special DailyTournamentsevery dayfor a chance to win up toLakhs. Do you have the skills? There is only one way to find out - Register Now! </p>
		<a href="#special-tournament">Read More...</a>
	</div>
</div>


<div class="fluid-content" id="welcome-bonus">
	<div class="head1">100% Welcome back</div>
	<p>Join us and claim a 100% bonus on your first purchase today. Please note the following rules that apply to this offer:</p>
	<ul>
		<li>Regular players converting to the Premium for the first time on this website only are eligible for this offer.</li>
		<li>This offer can be only used once.</li>
		<li>If the Bonuses issued are less than 100 then those bonuses will be released after 500 is wagered.</li>
		<li>100 real chips will be released for every 500 real chips youlay to play. (i.e you get 100 free chips when you play 1 game of 500, 5 games of 100 chips or 20 games of 25 chips)</li>
		<li>Max Bonus Issued will be Rs. 500/-. E.g., for a 2000 real chips purchase, the Bonus issued will be 500 real chips.</li>
		<li>The Bonus issued will be expired in 45 days from the date of issue.</li>
		<li>Each player is allowed only one account and multiple accounts if found will result in seizure of all bonus added.</li>
		<li>Enter the 100% ACE2JAK promotional codewhile making a purchase.</li>
		<li>This is a limited time offer and our conditions apply.</li>
		<li>Cash bonuses could be subject to withdrawal restrictions. All bonus plans must be governed by the additional terms and conditions applicable to that bonus plan which will apply in addition to the Terms.</li>
		<li>The details of various promotions organized on the Website can be found in the FAQs section on the Website.</li>
		<li>Eligibility and applicable conditions for the on-going promotional programs are provided in the Promotions section, which form a part of the Terms.</li>
		<li>Games offered under the Offers section may be cancelled or discontinued by Ace2jak at any time without notice without any liability whatsoever, except refund of entry fee, if applicable.</li>
	</ul>
</div>

<div class="fluid-content" id="refer-earn">
	<div class="head1">Refer &amp; Earn</div>
	<p>You can now earn credits by referring your friend to Ace2jak.com. When a friend you refer joins the game and converts to a Premium player, you will be credited with reward points. These reward points expire in 45 days from the date of issue.</p>
	<ul>
		<li>"A Referrer" is a registered player on Ace2jak.</li>
		<li>"A Referee" is an unregistered player at Ace2jak being referred to Ace2jak by "A Referrer".</li>
		<li>The "Refer &amp; Earn" is not valid in case the "Referee" already has an account on Ace2jak.</li>
		<li>To be eligible for the bonus, please ensure that the friends you invite use the link located in the invitation sent to them. This is the only way they can be linked to your account.</li>
		<li>A bonus amount of Rs 1000/- is added to the "Referer's" account.</li>
		<li>Cash bonuses are subject to withdrawal restrictions. All bonus plans must be governed by the additional terms and conditions applicable to that bonus plan which will apply in addition to the Terms.</li>
		<li>The details of various promotions organized on the Website can be found in the FAQs section on the Website.</li>
		<li>Eligibility and applicable conditions for the on-going promotional programs will be provided in the Offers section.</li>
		<li>Games offered under the Offers section may be cancelled or discontinued by Ace2jak at any time without notice without any liability whatsoever, except refund of entry fee, if applicable.</li>
	</ul>
	<div class="head2">Note</div>
	<p>To earn the referral bonus, your friends must be must be routed to the website by clicking the referral link sent by Ace2jak only.</p>
</div>

<div class="fluid-content" id="special-tournament">
	<div class="head1">Special Daily Tournaments</div>
	<p>Register and grab the opportunity to make your day even more exciting. Play in our Special DailyTournamentsevery dayfor a chance to win up toLakhs. Do you have the skills? There is only one way to find out - Register Now! </p>
	<p>Cash bonuses may be subject to withdrawal restrictions. All bonus plans must be governed by the additional terms and conditions applicable to that bonus plan which will apply in addition to the Terms.The details of various promotions organized on the Website can be found in the FAQs section on the Website.Eligibility and applicable conditions for the on-going promotional programs are provided in the Promotions section, which form a part of the Terms.Games offered under the Offers section may be cancelled or discontinued by Ace2jak at any time without notice without any liability whatsoever, except refund of entry fee, if applicable.</p>
</div>