
<div class="ttbingologin">
<?php

echo $this->form;
/*$facebookSession = new Zend_Session_Namespace('facebookAuth');
$facebookSession->unsetAll();

if($this->message)
{
	foreach($this->message as $message)
	{
		echo $message;
	}
}
if($this->facebookAuth)
{
	$siteHttpUrl = "http://". $_SERVER['HTTP_HOST'];
	$link = $siteHttpUrl . '/facebookauth/auth';
	?>
		<body onload='JavaScript:popitup("<?php echo $link;?>");'></body>			
	<?php
}
if($this->facebook)
{
	?>
	<html>
		<body onload="FB.login();"></body>
	</html>
	<?php
}*/
$this->facebook();

?></div>
