<h1>Terms And Conditions</h1>
By viewing or accessing <?=$this->companyName?> website, software, applications, products or services you expressly agree to the following Terms and Conditions detailed below. Your use of the <?=$this->companyName?> website and/or use of <?=$this->companyShortName?> games,software, applications, products or services signifies your acceptance of these Terms and Conditions and constitutes a legally binding acceptance of this agreement. If you do not agree to these conditions you are not allowed to access or use <?=$this->companyShortName?>  websites, games. Software, applications, products or services. <?=$this->companyShortName?>  reserves the right to modify, alter and update the content of these Terms and Conditions at anytime. 

Although <?=$this->companyShortName?>  attempts to ensure that all information contained on this website is error-free, we accept no liability for omissions, and reserve the right to change or alter the content of the site at anytime. <?=$this->companyShortName?>  does not make any warranty that the website is free from infection from viruses; nor does any provider of content to the site or their respective agents make any warranty as to the results to be obtained from use of the site.

Under no circumstances including, but not restricted to, negligence, shall <?=$this->companyShortName?>  or any third party content provider or their respective agents be liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use <?=$this->companyName?> web site, software and/or services, even if such party has been advised of the possibility of such damages.
you agree to assume all risk related to your use of <?=$this->companyShortName?>  websites and services, including but not restricted to, the risk of communications with other people or damage to your computer.

<h2>Age restrictions</h2> 
<?=$this->companyShortName?>  does not target the  <?=$this->companyName?> website or its services to users under 18 of age. There may be certain access restrictions placed on any under 18 year old users. You agree that if you assist users under 18 years old to access the Playdorm.com website or services, with your computer, internet enabled device, internet connection and/or facilities (whether owned, leased or borrowed) that you will assume full liability for any consequences and that under no circumstances including, but not to, negligence neither <?=$this->companyShortName?> ,any third party content provider nor their respective agents shall be liable for any direct, indirect, incidental, special or consequential damages arising out of the use of or inability to use the site by users under 18 years of age, even if such party has been advised of the possibility of such damages.
 
<?=$this->companyShortName?> accepts no responsibility for the links to or from its website and the inclusion of these links does not mean that <?=$this->companyShortName?> endorses the material or content of these sites.

<h2>Advertisments</h2>
Playdorm accepts no responsibility for any third party advertisements that may appear on Playdorm websites.





Disclaimer Regarding Third Party Games, Applications or services.
You hereby acknowledge and agree that any third party game, application or service that may be accessed via <?=$this->companyName?>, being provided to you by a third party provider and not by<?=$this->companyName?> . You hereby acknowledge and agree that your use of any such third party game, application or service may also be governed by such third party game, application or service provider's terms of use, license agreement, privacy policy, or other such agreement. Licenser expressly disclaims any liability in connection with any such third party games, applications or services or your use thereof.

<h2>User Rules</h2>
Users may be banned or accounts suspended or terminated on the entire <?=$this->companyName?> website or any game available on <?=$this->companyName?> if users use inappropriate language or inappropriate behavior as determined by <?=$this->companyName?>. Inappropriate language and/or inappropriate behavior is not allowed on <?=$this->companyName?> websites. <?=$this->companyName?> is not responsible for user content, postings, chat, and/or communications. Users are responsible for their own actions.
You agree not to do any of the following:

          Post, distribute, or otherwise make available or transmit any data, text, message, or computer file that we deem to be: (a) defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking; (b) bigoted, hateful, or racially offensive; (c) vulgar, obscene, or sexually explicit (language or images); or that (d) encourages or advocates illegal activity or the discussion of illegal activities with the intent to commit them; 

         Post, distribute, or otherwise make available or transmit any data, text, message, computer file, or other material that infringes and/or violates any right of a third party or any domestic or international law, rule, or regulation, including but not   to: (a) copyright, patent, trademark, or other proprietary rights; (b) right of privacy (specifically, you must not distribute another person's personal information of any kind without their express permission) or publicity; (c) any confidentiality obligation; 

        Advertise or sell any products, services or otherwise (whether or not for profit), or solicit others or use any Forum for commercial purposes of any kind, 

       Post, distribute, or otherwise make available or transmit any software or other computer files that contain a virus or other harmful component; 

       Impersonate any person or entity or misrepresent your identity or affiliation with any person or entity; 

      Engage in antisocial, disruptive, or destructive acts, including "flaming," "spamming," "flooding," "trolling," and "griefing" as those terms are commonly understood and used on the Internet; 

       Delete any legal notices, disclaimers, or proprietary notices such as copyright or trademark symbols, or modify any logos that you do not own or have express permission to modify;
              Post, distribute, or otherwise make available or transmit material or make statements that do not generally pertain to the designated topic or theme of any Forum. 

We reserve the right to remove any material, and if we deem appropriate, to turn over to law enforcement officials, any material, including message, e-mail, or posting, that is in violation of these Rules. We also reserve the right to remove messages, e-mails, or postings that do not pertain to the designated topic or theme of the service as determined by <?=$this->companyName?>. 