<div class="span-16" id="left-column">
 <div style="border:#CD222B solid 1px; margin:5px 0px 0px 0px ; padding:15px;border-radius:5px; "> <h3 style="text-align:center "><strong>Bingo Crush Loyalty Program</strong> </h3>
 <p>Bingo Crush offers you a unique Loyalty Program, which makes your play, time the most enjoyable. You will automatically become a member of our Loyalty Program once you register as a player.</p>
  <ul class="bullet-normal">
    <li> Get 1000 Loyalty Points (LP's) as soon as you register your account. </li>
    <li> Get 10 Loyalty Points (LP's) upon your first login of the day. That means you get 10 LP's everyday just for logging in.</li>
    <li> Every time you refer a friend you will get 500 LP's automatically credited to your account.</li>
    <li> Get 1 LP for every £2 wagered on Bingo.</li>
    <li> Get 1 LP for every £5 wagered on slots or casino games.</li>
    <li> Get 300% LP's on your first 3 deposits.</li>
    <li> Get equal amount of LP's as the bonus offered on all reloads</li>
  </ul>
 	 <table width="614" height="185"  style="font-weight:bold;border:1px solid #CD222B ">
 	   <tr>
 	     <td width="275">Registration</td>
 	     <td width="274">1000 LP's</td>
       </tr>
 	   <tr>
 	     <td>Daily Login</td>
 	     <td>10 LP's</td>
       </tr>
 	   <tr>
 	     <td>Refer a Friend</td>
 	     <td>500 LP's</td>
       </tr>
 	   <tr>
 	     <td>Wager £2 on Bingo</td>
 	     <td>1 LP</td>
       </tr>
 	   <tr>
 	     <td>Wager £5 on slots / casino games</td>
 	     <td>1 LP</td>
       </tr>
 	   <tr>
 	     <td>First 3 deposits</td>
 	     <td>300% LP's</td>
       </tr>
 	   <tr>
 	     <td>Reloads</td>
 	     <td>LP's equal to the bonus offered</td>
       </tr>
    </table>
 	 <p><strong>Converting points to bonus</strong></p>
 	 <p><strong>100 LP's = £1 Bonus</strong></p>
	 <img src="/images/bingocrush/egg5.png"  alt="Bingo" style="float:right;margin-top:-330px;" />
 	 <table width="614" height="203"  style="font-weight:bold;border:1px solid #CD222B">
 	   <tr>
 	     <td width="89">Loyalty Level</td>
 	     <td width="97">Loyalty Points</td>
 	     <td width="58">Can trade upto</td>
 	     <td width="80">Loyalty Bonus</td>
 	     <td width="69">Level up bonus</td>
 	     <td width="87">Special monthly bonus</td>
 	     <td width="88">Special Gifts / vouchers</td>
       </tr>
 	   <tr>
 	     <td>Level 1</td>
 	     <td>0 to 50,000</td>
 	     <td>5000</td>
 	     <td>0</td>
 	     <td>0</td>
 	     <td>0</td>
 	     <td>0</td>
       </tr>
 	   <tr>
 	     <td>Level 2</td>
 	     <td>50,001 to 100,000</td>
 	     <td>10000</td>
 	     <td>10.00%</td>
 	     <td>£10</td>
 	     <td>Yes</td>
 	     <td>0</td>
       </tr>
 	   <tr>
 	     <td>Level 3</td>
 	     <td>100,001 to 200,000</td>
 	     <td>15000</td>
 	     <td>25.00%</td>
 	     <td>£30</td>
 	     <td>Yes</td>
 	     <td>Yes</td>
       </tr>
 	   <tr>
 	     <td>Level 4</td>
 	     <td>200,001 and above</td>
 	     <td>20000</td>
 	     <td>40.00%</td>
 	     <td>£50</td>
 	     <td>Yes</td>
 	     <td>Yes</td>
       </tr>
    </table>
 	 <p>Rules:</p>
 	 
 	   <ol>
 	     <li>Players should have one deposit during the week to convert the LP's.</li>
       </ol>
 	 
  </div>
</div>
