<div class="ttdepolcont">
	<div id="inner-box">
<?php 
echo $this->form; 
echo $this->table($this->table1);
echo $this->table($this->table2);?>
<a href = "/withdrawal/modify/type/updateidentity">  UPDATE IDENTITY  </a>&nbsp;&nbsp;
<a href = "/withdrawal/modify/type/addbankdetails">  ADD BANK DETAILS  </a>&nbsp;&nbsp;
<a href = "/withdrawal/modify/type/mydetails">  MY DETAILS  </a><br/><br/>

<script type="text/javascript" >
changeIdProof()
</script>
</div>
</div>