<div class="ttpromom">
  <div class="ttpromot">
    <div class="ttpromoprizes">
      <div class="ttpromoprizes_l">
        <div>FIRST DEPOSITE BONANZA</div>
        <div class="ttpromopercent"><img src="/css/rummy.tld/images/ttpromoperce.png" width="178" height="74" />Bonus</div>
        <div class="ttpromowelbonus">Add Free upto Rs 500* from Welcome Bonus</div>
      </div>
      <div class="ttpromoprizes_r" >
        <div>TOURNAMENT PRIZES</div>
        <div class="ttpromowinamount"><img src="/css/rummy.tld/images/ttpromowinamount.png" width="256" height="69" /></div>
      </div>
    </div>
    <div class="ttpromotime">
      <div class="ttpromotime_l">
        <div class="ttpromotime2pm">
          <div class="ttpromotime2pm_l"><img src="/css/rummy.tld/images/ttpromo2pm.png" width="105" height="64"  alt="2pm Tournament"/></div>
          <div class="ttpromotime2pm_r">
            <div class="ttpromoentry">Entry Fee <span>FREE</span></div>
            <div><a href="http://taashtime.com/tournament/list"><img src="/css/rummy.tld/images/ttpromoregister.png" width="116" height="30" alt="2PM Register" title="Register" /></a></div>
          </div>
        </div>
        <div class="ttpromoworth">Prizes Worth T<span class="WebRupee">Rs</span> 500</div>
      </div>
      <div class="ttpromotime_r"><div class="ttpromotime2pm">
          <div class="ttpromotime2pm_l"><img src="/css/rummy.tld/images/ttpromo8pm.png" width="107" height="64" align="8PM Tournament" /></div>
          <div class="ttpromotime2pm_r">
            <div class="ttpromoentry">Entry Fee <br />
<span>T<span class="WebRupee">Rs</span> 10</span></div>
            <div><a href="http://taashtime.com/tournament/list"><img src="/css/rummy.tld/images/ttpromoregister.png" width="116" height="30"  alt="8PM Register" title="Register"/></a></div>
          </div>
        </div>
      <div class="ttpromoworth">Prizes Worth T<span class="WebRupee">Rs</span> 1500</div></div></div>
      <div class="ttpromoreadmore "><a href="http://taashtime.com/blog/" title="readmore">Read More</a></div>
  </div>
    <div class="ttpromob ">
	<div class="ttpromotandc">*T&C Apply</div>
    <div class="ttpromocards" ><img src="/css/rummy.tld/images/ttpromocards.png" width="196" height="107" alt="PlayingCards" /></div>
    <div class="ttpromoplay"><a href="http://taashtime.com/game"><img src="/css/rummy.tld/images/ttpromoplaybtn.png" width="238" height="75"  alt="PlayNow" title="PlayNow"/></a></div>
    </div>
</div>
	