<table width="600" border="0" align="center" cellpadding="0" cellspacing="0" 
style="font-family:Arial, Helvetica, sans-serif; font-size:12px; color:#375282">  <tr>    <td bgcolor="#f2f2f2" style=
"padding:10px 25px 0px 25px"><table width="100%" border="0" cellspacing="0" cellpadding="0">        <tr>          <td><table 
width="100%" border="0" cellspacing="0" cellpadding="0">              <tr>                <td height="50" valign="middle"><a 
href="http://taashtime.com/en_IN/game" target="_blank"><img src="http://taashtime.com/mailers/20120912/images/ttlogo_new.png" 
width="215" height="49" alt="TaashTime is your cash time" border="0"  /></a></td>                <td width="41%" rowspan="2" 
align="center" valign="middle"><img src="http://play.taashtime.com/mailers/20130909/ganesh.png"  alt="Ganesh Navratri Special" 
 />                                  <p style="margin:0px; padding:0px; text-align:center">&nbsp;
</p></td>              </tr>              <tr>                <td width="59%" valign="middle" style="font-size:15px; 
color:#375282"><p style="color:#ce461b; font-weight:bold; font-size:16px; padding:15px 0px 0px 10px; margin:0px"></p></td>              </tr>              <tr>              <td colspan="2" align="center" style="font-size:16px; 
color:#0f2544; font-family:Arial, Helvetica, sans-serif; text-align:center;">
Happy <b>Ganesh Chaturthi</b>! Amazing offers and Bonus bounty at Taashtime.com
<br/><br/>Celebrate Navratri fun with <b>Team Rummy!</b>
<br/>Be part of unique Rummy experience with <b>Team Rummy.</b><br />
Play your regular games. Win amazing prizes worth over <b>Rs.10,000</b>
<br/><br/>Win in Three Simple Steps
                <br/>
<ol>
        <li><a href="http://taashtime.com/leaderboard/registerplayer/leaderboardId/1">Join a Team for FREE.</a></li>
        <li>Play Regular Games and Make Points</li>
        <li>Team with Highest Points Wins</li>
</ol>

 <p style="color:#0f2544; margin:20px 0px 5px 0px; padding:0px; font-size:24px; font-weight:bold">
&ldquo;Team Win is Your Win!&rdquo;</p></center></td>              </tr>              <tr>                <td height=
"100" colspan="2" align="center" valign="middle" style="padding-bottom:5px; text-align:center;"><div style =" padding:0px;  margin:10px 0px 0px 0px; " ><a href="http://taashtime.com/leaderboard/registerplayer/leaderboardId/1" style = "padding:10px 20px 10px 20px; color:#fff; text-decoration:none; font-size:28px; font-weight:bold;  -webkit-border-radius: 10px;-moz-border-radius: 10px;border-radius: 10px;  border:1px solid #25729a; font-family:arial, helvetica, sans-serif;  text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; 
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #3093c7), color-stop(100%, #1c5a85));
 background-image: -webkit-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -moz-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -ms-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -o-linear-gradient(top, #3093c7, #1c5a85);
 background-image: linear-gradient(top, #3093c7, #1c5a85);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#3093c7, endColorstr=#1c5a85);">Join Team Rummy</a></div><!--br /><span style="font-size:12px">(Forgot password? <a href="http://taashtime.com/en_IN/auth/forgotpassword"
 style=" color:#375282" target="_blank">click here</a>)</span-->
<span style=
"font-size:12px;"><br/>Team Rummy ends on 19th September
</span><br /></td>              </tr>

<tr>
        <td colspan="2" align="center" style="font-size:16px; 
color:#0f2544; font-family:Arial, Helvetica, sans-serif; font-weight:bold; text-align:center;">

                All deposits today get 100% Bonus!
        </td>
</tr>

<tr>                <td height=
"100" colspan="2" align="center" valign="middle" style="padding-bottom:5px; text-align:center;"><div style =" padding:0px;  margin:10px 0px 0px 0px; " ><a href="http://taashtime.com/banking/deposit" style = "padding:10px 20px 10px 20px; color:#fff; text-decoration:none; font-size:28px; font-weight:bold;  -webkit-border-radius: 10px;-moz-border-radius: 10px;border-radius: 10px;  border:1px solid #25729a; font-family:arial, helvetica, sans-serif;  text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; text-align: center; color: #FFFFFF; 
 background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #3093c7), color-stop(100%, #1c5a85));
 background-image: -webkit-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -moz-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -ms-linear-gradient(top, #3093c7, #1c5a85);
 background-image: -o-linear-gradient(top, #3093c7, #1c5a85);
 background-image: linear-gradient(top, #3093c7, #1c5a85);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#3093c7, endColorstr=#1c5a85);">Deposit Now</a></div><!--br /><span style="font-size:12px">(Forgot password? <a href="http://taashtime.com/en_IN/auth/forgotpassword"
 style=" color:#375282" target="_blank">click here</a>)</span-->
<span style=
"font-size:12px;"><br/>Bonuses end on 9th September
</span><br /></td>              </tr>



</table></td>        </tr>



                </table></td>
</tr></table>