<?php

/**
 * AuditReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class AuditReport extends BaseAuditReport
{
	public function checkError($sourceId, $playerId)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($playerId);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->from('AuditReport a')
						->where('a.source_id = ?', $sourceId)
						->andWhere('a.player_id = ?', $playerId);
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return false;
		}
		if($result)
		{
			return array(
				'auditId' => $result[0]['audit_id'],
				'processed' => $result[0]['processed'],
				'error' => $result[0]['error']);
		}
		return NULL;
	}
	
	public function checkIfPresent($sourceId, $playerId)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($playerId);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
		           ->from('AuditReport t')
					->where('t.player_id = ?', $playerId)
					->andWhere('t.source_id = ?', $sourceId)
					->limit(1);
					
		if($query->count() != 1)
		{
			return false;
		}
		else 
		{
			return true;
		}
	}
}
