<?php

/**
 * BankDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BankDetails extends BaseBankDetails
{
	public function insertdetails($playerid,$nameasonbank,$bank,$BankAccountNumber,$ifsccode,$branch)
	{
		$connName = Zenfox_Partition::getInstance()->getConnections($playerid);
		$partition = Doctrine_Manager::getInstance()->getConnection($connName);
			
			
		
		$this->name = $nameasonbank;
		$this->branch = $branch;
		$this->name_of_bank = $bank;
		$this->ifsc_code = $ifsccode;
		$this->account_no = $BankAccountNumber;
		
		$jsonarray["name"] = $nameasonbank;
		$jsonarray["branch"] = $branch;
		$jsonarray["bank_name"] = $bank;
		$jsonarray["ifsc_code"] = $ifsccode;
		$jsonarray["account_number"] = $BankAccountNumber;
		
		$jsonobj = Zend_Json_Encoder::encode($jsonarray);
		
		$this->json_details = $jsonobj;
		$this->save($partition);
		
	}
	
	
	public function getbankid($playerid,$nameasonbank,$bank,$BankAccountNumber,$ifsccode,$branch)
	{
		$connName = Zenfox_Partition::getInstance()->getConnections($playerid);
		$partition = Doctrine_Manager::getInstance()->getConnection($connName);

		$query = Zenfox_Query::create($partition)
			->select('max(bd.id)')
			->from('BankDetails bd');
		
		$result = $query->fetchArray();
	
		return $result[0]["max"];
	}
}