<?php

/**
 * CefGamelogArchive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CefGamelogArchive extends BaseCefGamelogArchive
{
	public function getGamelog($sessionId, $archiveId)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($sessionId);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->select('cga.gamelog')
					->from('CefGamelogArchive cga')
					->where('cga.archive_id = ?', $archiveId);
					
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return false;
		}
		return $result[0]['gamelog'];
		
	}
}