<?php

/**
 * CefGamelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CefGamelog extends BaseCefGamelog
{
	public function getArchiveId($gameFlavour, $sessionId, $gameId)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($sessionId);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->select('cg.archive_id')
					->from('CefGamelog cg')
					->where('cg.game_flavour = ?', $gameFlavour)
					->andWhere('cg.session_id = ?', $sessionId)
					->andWhere('cg.game_id = ?', $gameId);
					
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return false;
		}
		if($result)
		{
			return $result[0]['archive_id'];
		}
	}
}