<?php

/**
 * gamelogSlot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class GamelogSlot extends BaseGamelogSlot
{
	public function getSlotlogDetails($logId, $sessionId, $playerId)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($playerId);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->from('GamelogSlot gs')
						->where('gs.log_id = ?', $logId)
						->andWhere('gs.session_id = ?', $sessionId)
						->andWhere('gs.player_id = ?', $playerId);
						
		try
		{
			$data = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return false;
		}
		if($data)
		{
			foreach($data as $result)
			{
				return array(
					'logId' => $result['log_id'],
					'sessionId' => $result['session_id'],
					'playerId' => $result['player_id'],
					'machineId' => $result['machine_id'],
					'frontendId' => $result['frontend_id'],
					'betAmount' => $result['bet_amount'],
					'generatedNumbers' => $result['win_string'],
					'selectedNumbers' => $result['bet_lines'],
					'winString' => $result['win_lines'],
					'winAmount' => $result['win_amount'],
					'datetime' => $result['datetime'],
					'amountType' => $result['amount_type'],
					'pjpWinstatus' => $result['pjp_winstatus'],
					'pjpId' => $result['pjp_id'],
					'pjpRng' => $result['pjp_rng'],
					'pjpWinAmount' => $result['pjp_win_amount'],
					'wageredCurrency' => $result['wagered_currency'],
					'runningMachineId' => $result['running_machine_id'],
					'gameFlavour' => $result['game_flavour'],
					'spinType' => $result['spin_type']);
			}
		}
		return NULL;
	}
}