<?php

/**
 * Kyc
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Kyc extends BaseKyc
{
		public function insertidproof($playerid,$kycdocument,$path)
		{
				$connName = Zenfox_Partition::getInstance()->getConnections($playerid);
			$partition = Doctrine_Manager::getInstance()->getConnection($connName);
			
			
			$this->player_id = $playerid;
			$this->kyc_document = $kycdocument;
			$this->document_path = $path;
			$this->save($partition);
			
		}
}