<?php

/**
 * MarketItemCategories
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class MarketItemCategories extends BaseMarketItemCategories
{
	public function getDataByCategoryId($categoryId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);

		$query = Zenfox_Query::create()
		->from('MarketItemCategories mk')
		->where('mk.category_id = ?', $categoryId);

		try
		{
			$data = $query->fetchArray();

		}
		catch(Exception $e)
		{
			return false;
		}

		if($data)
		{				
			return array(
					'name'	=> $data[0]['name'],
			);					
		}
		return false;
		
	}
	public function getData()
	{

		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);

		$query = Zenfox_Query::create()
		->from('MarketItemCategories mk');

		try
		{
			$data = $query->fetchArray();

		}
		catch(Exception $e)
		{
			return false;
		}

		if($data)
		{
			foreach($data as $key=>$datum)
			{
				$result[$key]['categoryId'] = $datum['category_id'];
				$result[$key]['name'] = $datum['name'];
				$result[$key]['specialAttribute'] = $datum['special_attribute'];
			}
			return $result;
		}
		return false;
		
	}
	public function insert($categoryName,$specialAttribute)
	{
		
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		$marketItem = new MarketItemCategories();
		$marketItem->name = $categoryName;
		$marketItem->special_attribute = $specialAttribute;		
		$marketItem->save();
		


	}
}