<?php

/**
 * UrlRecords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class UrlRecords extends BaseUrlRecords
{
	public function addRecords($playerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$date = new Zend_Date();
		$date->setTimezone('Asia/Calcutta');
		$currentTime = $date->get(Zend_Date::W3C);
		
		$hostAddress = 'http://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
		$referrerUrl = "";
		if(isset($_SERVER['HTTP_REFERER']))
		{
			$referrerUrl = $_SERVER['HTTP_REFERER'];
		}
		$clientIp = Zend_Controller_Front::getInstance()->getRequest()->getClientIp();
		
		try
		{
			$urlRecords = new UrlRecords();
			$urlRecords->referrer_url = $referrerUrl;
			$urlRecords->url = $hostAddress;
			$urlRecords->client_ip = $clientIp;
			$urlRecords->datetime = $currentTime;
			$urlRecords->player_id = $playerId;
			$urlRecords->save();
		}
		catch(Exception $e)
		{
			return false;
			//Zenfox_Debug::dump($e, 'e', true, true);
		}
	}
}
