<?php
foreach($this->tickets as $message)
{
	echo $this->translate("From: ") . $message['user_id'] . "  ";
	echo $this->translate("Message: ") . $message['reply_msg'] . "  " . $message['time'];
	$id = $message['ticket_id'];
	?><br></br><?php
}
?>
<br></br>
<a href ="<?php echo $this->url(array(
						'controller' => 'affiliateticket',
						'action' => 'reply',
						'ticket_id' => $id,
						'id' => $message['user_id']
				));
?>">
<?php echo $this->translate("Reply");?></a>