<?php 

//$this->table($this->leaderboardconf);
//Zenfox_Debug::dump($this->leaderboardconf);
?>


<div style="margin-top:10px">
                <div style="font-size:28px;text-align:center;color:#004298;font-family:Copperplate Gothic"><?=$this->leaderboardconf["title"]?></div>
        <div style="padding:10px 0px 10px 0px;">        <div style="float:left;"><a href="/leaderboard/rummyteams/leaderboardId/<?=$this->leaderboardconf["leader_board_id"]?>"><img width="80" height="25" src="/css/rummy.tld/images/back-button-01.png"></a></div>
                <div style="text-align:right;font-size:14px;font-family:Arial;color:#004298">From : <?=$this->leaderboardconf["start_time"]?> - To : <?=$this->leaderboardconf["end_time"]?></div></div>
<div>
                <div style="float:left;padding:10px 0px 10px 0px;">
                        <table id="leaderboeardteams" style="border:4px solid #004298;" >
                                <tr >
                                        <th class="lbtheadings" style="width:75px">Rank</th>
                                        <th class="lbtheadings" style="width:175px">Team Name</th>
                                        <th class="lbtheadings" style="width:300px">
                                                        <div style="width:300px;border:px solid" >
                                                                <div style="width:200px;float:left;border:0px solid">Players</div>
                                                                <div style="width:100px;float:left;text-align:right;border:0px solid">Scores</div>
                                                 </div>

                                        </th>


                                </tr>

                                <tr cellpadding="0" style="border:0px solid #004298;">
                                        <td style="text-align:center;border-right:2px solid #004298;background:#fff;width:75px"><img src="/images/rummy.tld/leaderboardteams/<?=$this->teamdata["Position"] ?>.png"></td>
                                        <td style="text-align:center;font-size:18px;font-family:Arial;color:#004298;border-right:2px solid #004298;background:#fff;width:175px"><b><?=$this->teamdata["team_name"] ?></b></td>
                                        <td style="padding:0px">
                                         <div style="width:364px;border:0px solid;font-weight:bold;color:#000" >
                                         <?php
                                                $length = count($this->teamdata["player_data"]);

                                                $index = 0;

					 	  if($length == 0)
                                                {
                                                        ?>
                                                        <div style="width:360px;border:2px solid;border-bottom:none;font-weight:bold;height:30px;background:#abc3dd;line-height:30px" >
                                                        <div style="width:200px;border:0px solid;font-weight:bold;float:left;text-align:center;height:30px;line-height:30px" >&nbsp;</div>
                                                        <div style="width:160px;border:0px solid;font-weight:bold;text-align:center;float:right;height:30px;line-height:30px" >&nbsp;</div>
                                                </div>                                                                  <?php
                                                }

                                                while($index < $length)
                                                {

                                                        if($index % 2 == 0)
                                                        {
                                                                ?>
                                                                <div style="width:364px;border:0px solid;font-weight:bold;height:30px;background:#abc3dd;line-height:30px" >
                                                                <?php
                                                        }
                                                        else
                                                        {
                                                                ?>
                                                                <div style="width:364px;border:0px solid;font-weight:bold;height:30px;line-height:30px" >
                                                                <?php
                                                        }

                                                        ?>
                                                                <div style="width:210px;float:left;border:0px solid;font-size:15px;text-align:center;"><?=$this->teamdata["player_data"][$index]["Login"] ?></div>
                                                                <div style="width:80px;float:left;text-align:right;font-size:15px;border:0px solid"><?=$this->teamdata["player_data"][$index]["Score"] ?></div>
                                                        </div>
                                                        <?php
                                                        $index++;
                                                }
                                         ?>
                                                </div>
                                                
                                                
                  <div style="width:364px;border-bottom:none;font-weight:bold;height:30px;background:#004298;line-height:30px" >
                       <div style="width:200px;font-weight:bold;float:left;text-align:center;height:30px;line-height:30px;color:#fff;font-size:18px" >Total Score</div>
            <div style="width:160px;border:0px solid;font-weight:bold;text-align:center;float:right;height:30px;line-height:30px;color:#fff;font-size:18px" ><?=$this->teamdata["Score"] ?>				</div>
                                                </div>
                                        </td>

                                </tr>

                        </table>

                </div>
                </div>
</div>



