<?php 

//$this->table($this->leaderboardconf);
//Zenfox_Debug::dump($this->leaderboardconf);

if(!$this->homePage)
{
?>


<div style="margin-top:10px"> 
		<div style="font-size:28px;text-align:center;color:#004298;font-family:Copperplate Gothic"><?=$this->leaderboardconf["title"]?></div>
				<div style="float:left;padding:10px 0px 10px 0px;"><a href="/leaderboard/registerplayer/leaderboardId/<?=$this->leaderboardconf["leader_board_id"]?>"><img width="80" height="25" src="/css/rummy.tld/images/back-button-01.png"></a></div>
		
		<div style="text-align:right;font-size:14px;font-family:Arial;padding:10px 0px 10px 0px;color:#004298">From : <?=$this->leaderboardconf["start_time"]?> - To : <?=$this->leaderboardconf["end_time"]?></div>
		<div>
		<div style="border:4px solid #004298;">
			<table id="leaderboardteams" >
				<tr >
					<th class="lbtheadings">Rank</th>
					<th class="lbtheadings">Team Name</th>
					<th class="lbtheadings">Top Players</th>
					<th class="lbtheadings">Scores</th>
					<th class="lbtheadings">Total Scores</th>
				</tr>
				<?php 
				$index = 0;
				while($index < $this->leaderboardconf["no_of_teams"])
				{
				
				if($index+1  == $this->leaderboardconf["no_of_teams"])
				{
					?>
					<tr cellpadding="0" style="border:px solid #004298;height:50px;border-bottom:none">
				<?php 
				}
				else
				{
					?>
					<tr cellpadding="0" style="border:px solid #004298;height:50px;border-bottom:2px solid #004298">
					<?php 
				}
				?>
					<td style="text-align:center;"><img src="/images/rummy.tld/leaderboardteams/<?=$this->teamdata[$index]["Position"] ?>.png"></td>		
					<td style="text-align:center;font-size:18px;font-family:Arial;color:#004298"><b><?=$this->teamdata[$index]["team_name"] ?></b></td>
					<td >
						 <div style="background:" class="lbtnames"><?=$this->teamdata[$index]["player_data"][0]["Login"] ?></div>
						<div style="text-align:center" class="lbtnames"><?=$this->teamdata[$index]["player_data"][1]["Login"] ?></div>
						<div style="text-align:center" class="lbtnames"><?=$this->teamdata[$index]["player_data"][2]["Login"] ?></div>
						<div style="text-align:center">&nbsp;</div>						
					</td>
					<td>
						<div style="text-align:center" class="lbtscores"><?=$this->teamdata[$index]["player_data"][0]["Score"] ?></div>
						<div style="text-align:center" class="lbtscores"><?=$this->teamdata[$index]["player_data"][1]["Score"] ?></div>
						<div style="text-align:center" class="lbtscores"><?=$this->teamdata[$index]["player_data"][2]["Score"] ?></div>
						<div style="text-align:center"><a href = /leaderboard/rummyteamdata/leaderboardId/<?=$this->leaderboardconf["leader_board_id"] ?>/teamId/<?=$this->teamdata[$index]["team_id"] ?>>more</a></div>
					</td>
					<td style="text-align:center;font-size:18px;font-family:Arial;color:#004298"><?=$this->teamdata[$index]["Score"] ?></td>
				</tr>
				<?php 
				$index++;
				}
				?>
			</table>
		</div>
		</div>
</div>

<?php 
}
else
{
	?>
	<div style="padding:2px;height:30px;font-size:16px;text-align:center;color:#fff;background:#004298;font-family:tahoma,Arial,Helvetica,sans-serif,Verdana,Arial,Helvetica,sans-serif;font-weight: bold;"><?=$this->leaderboardconf["title"]?> </br>TEAM RUMMY</div>
	<table id="leaderboardteams" style="border:1px solid #004298;height:240px;margin-top:0px;">
				<tr style="border-bottom:2px solid #004298;" >
					<th style="font-size:14px;text-align:center;color:#fff;background:#004298;height:35px">Team Name</th>
					<th style="font-size:14px;text-align:center;color:#fff;background:#004298;height:35px">Total Scores</th>
				</tr>
	<?php 
				$index = 0;
				while($index < $this->leaderboardconf["no_of_teams"])
				{
				?>
				
					<tr  style="height:35px;border:1px solid #004298">
					
					<td style="text-align:center;font-size:18px;font-family:Arial;color:#004298;border-left:1px solid #004298"><b><?=$this->teamdata[$index]["team_name"] ?></b></td>
					
					<td style="text-align:center;font-size:18px;font-family:Arial;color:#004298;border-right:1px solid #004298"><?=$this->teamdata[$index]["Score"] ?></td>
				</tr>
				<?php 
				$index++;
				}
				?>
				<tr style="height:5px;"><td  style="text-align:right;font-size:12px;font-family:Arial;color:#fff;margin-right:10px;background:#004298;height:5px"><div >&nbsp;</div></td><td style="font-size:12px;text-align:center;color:#fff;background:#004298;height:5px"><div > <a style="color:#fff;" href = /leaderboard/rummyteams/leaderboardId/<?=$this->leaderboardconf["leader_board_id"]  ?> > More Details </a></div></td></tr>
				
	</table>
	
	
	
	
	
	
	<?php 
}
?>

