<?php
if($this->analytics == 'google')
{
	$trackerId = $this->trackerId;
	?>
	<script type="text/javascript">
	var trackerId = <?=$trackerId?>;
	var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
	document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
	try {
	var pageTracker = _gat._getTracker("UA-<?=$trackerId?>-1");
	pageTracker._trackPageview();
	} catch(err) {}
	
	</script>
<?php 
}