<script>
function openGame(url, width, height) {
    var leftPosition, topPosition;
    //Allow for borders.
    leftPosition = (window.screen.width / 2) - ((width / 2) + 10);
    //Allow for title and status bars.
    topPosition = (window.screen.height / 2) - ((height / 2) + 50);
    //Open the window.
    window.open(url, "game","status=no,height=" + height + ",width=" + width + ",resizable=yes,left="
    + leftPosition + ",top=" + topPosition + ",screenX=" + leftPosition + ",screenY="
    + topPosition + ",toolbar=no,menubar=no,scrollbars=no,location=no,directories=no");
}
</script>

<?php 
	if($this->form)
    {
	   	?>
	   	<div class="buttons">
	   		<a class="playnow" onclick="openGame('/game', 1000, 675)" href="#" id="">PLAY NOW</a>
			<!-- <a href="/game" class="playnow">PLAY NOW</a> -->
			<!-- <a href="" class="download">DOWNLOAD</a> -->
		</div>
		<div class="raummy-register">
			<h2>Play Rummy Now!</h2>
			<?php
	    		echo $this->form;
	    	?>
		</div>
	    <?php 
    }