<script>
$(document).ready(function(){
 /* alert("ready");*/
  $(".option-header").click(function(){
	  $(".option-examples").hide();
	  var par_id = $(this).next().show();	  
 /* var par_id = $(this).parent().attr("id");
  $("#"+par_id+".option-examples").show();*/
  });
})

</script>
<div id="ttwidget-docs" style=" border:0px" >
  <div style="display:none">

    <ul>
      <li><a href="#demo"><span></span></a></li>
      <li><a href="#source"><span></span></a></li>
    </ul>
  </div>
  <div >
    <div class="ttcolactive" style="background:none repeat scroll 0 0 #9CB6D7;font-size:12px;font-weight:bold;padding:5px 0 5px 5px;vertical-align: middle;">General</div>
    <div style="pa dding:10px">
      <ul class="options-list">
        <li id="my 5000 FunCoins" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#my 5000 FunCoins">How do I get my 5000 FunCoins? </a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">As soon as a player registers on the Website through the Homepage- a confirmation link is sent to the provided email ID. On clicking on the validation link and logging in, the player’s account will automatically be credited with 5000 FunCoins. </p>
          </div>
        </li>
        <li id="Welcome Bonus" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Welcome Bonus">How do I claim my Welcome Bonus of TR 25? </a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Once the player logs in, he can fill in his profile details. As soon as the profile details are completed accurately, the TR 25 is automatically credited to the person's account</p>
          </div>
        </li>
        <li id="get Bonus" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#get Bonus">Do I have to deposit in order to get Bonus Rs. 25?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>No, A player will automatically be credited Rs. 25 on following the instructions explained in the previous question.</p>
          </div>
        </li>
        <li id="option-animated" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#option-animated">Can family members play with their Individual ID’s from the same computer?</a></h3>
          </div>
          
          <div class="option-examples" style="display: none;">
            <p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
          </div>
          <div class="option-description" style="display: none;"> </div>
        </li>
        <li id="option-autoHeight" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#option-autoHeight">What is the referral programme and how does it work?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>When an existing TaashTime account holder refers another new player to join, it is known as a referral. In this case, as the new member registers on TaashTime - The referrer's account is automatically credited with 25 TR as initial Buddy Bonus. A player can earn up to TR 500 from each buddy they refer (reflected in their Buddy Bonus Due) . With each deposit made by the Buddy, the referrer receives 25% of the amount.</p>
            <p>The referred player receives their Welcome Bonus.</p>
          </div>
        </li>
        <li id="withdraw money" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#withdraw money">How can I withdraw money?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">In order to withdraw, the profile details must be filled and the Identity Verification process must be completed. For more details on terms of withdrawal, please check out Withdrawal Terms to learn more.</p>
          </div>
        </li>
        <li id="how I can resolve it" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#how I can resolve it"> I have an issue, how I can resolve it?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">There are several ways in which you can resolve your issue. You can create a new complaint here or contact Live Help or write to support @ taashtime.com. Our customer support team is always looking to help you out! </p>
          </div>
        </li>
        <li id="welcome bonus is missing" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#welcome bonus is missing">My welcome bonus is missing from my balance, where is it?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Bonus is credited to a new player’s account only  when the account is activated. The player must make sure to click on the  confirmation link which is sent to the Email ID, which was used to register on  TaashTime.</p>
          </div>
        </li>
        <li id="close my account" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#close my account">How do I close my account?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Please send an email to <a href="mailto:support@taashtime.com">support@taashtime.com</a>. We shall serve you in the best possible way.</p>
          </div>
        </li>
        <li id="credited to my account" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#credited to my account">What do I do when Game winnings are not credited to my account?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Players on TaashTime have many customer support  tools in order to get in touch with TaashTime. Along with tickets which may be  submitted on the website for it to be action items, there is also Live Help  and/or email to <a href="mailto:support@taashtime.com">support@taashtime.com</a>.</p>
          </div>
        </li>
        <li id="guys located" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#guys located">Where are you guys located?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">We are located on 402, Chandra  Residency, Road No. 1, Banjara Hills, Hyderabad, AP</p>
          </div>
        </li>
        <li id="internet connection" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#internet connection">I just lost internet connection in the middle of the game. Will I lose everything that I have wagered on the game?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">If the player regains connection in the middle of the  game; it is possible for the player to rejoin the game. However, if the  connection does not return during the span of the game, the game will switch to  Autoplay and in the event of losing- the player stands to lose the entire  wager.</p>
          </div>
        </li>
        <li id="arranging the cards" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#arranging the cards">While arranging the cards, the table disappeared. What happens to the pot and do I lose all the money?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Let us check our records. If other  players experienced similar issues, we would in all likeliness cancel the game  and return everyone’s money back to them.</p>
          </div>
        </li>
        <li id="calculate the prize money" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#calculate the prize money">How to calculate the prize money and claims?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">The Terms &amp; Conditions mentioned on the website  clearly mention the withdrawal terms and the ways of claim. Please refer to  them to know more in detail.</p>
          </div>
        </li>
        <li id="card comes as the open Joker" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#card comes as the open Joker">What is the joker if the ‘’joker’’ card comes as the open Joker?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">The card Ace is taken as Joker.</p>
          </div>
        </li>
        <li id="minimum amount you can deposit" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#minimum amount you can deposit">What is the minimum amount you can deposit?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">The minimum deposit is<span class="WebRupee"> Rs. </span>25 through Net Banking  and INR 250 through Credit Cards</p>
          </div>
        </li>
        <li id="maximum amount you" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#maximum amount you">What is the maximum amount you can withdraw?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">The maximum amount a player can withdraw is<span class="WebRupee"> Rs. </span>5000  at a time. Please check out <a href="/content/terms">Terms and Conditions</a> to learn more.</p>
          </div>
        </li>
        <li id="access my account" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#access my account">Why can’t I access my account?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">In the case when a player cannot access his/her  TaashTime account, it usually could be a problem with a forgotten password or  the validation/confirmation email. Please ensure that you click on the  confirmation link before logging in for the first time. For further queries,  Please contact <a href="mailto:support@taashtime.com">support@taashtime.com</a>.</p>
          </div>
        </li>
      </ul>
    </div>
    <div class="ttcolactive" style="background:none repeat scroll 0 0 #9CB6D7;font-size:12px;font-weight:bold;padding:5px 0 5px 5px;vertical-align: middle;">Games</div>
    <div style="pa dding:10px">
      <ul class="options-list">
        <li id="Discard pile and stock" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Discard pile and stock">What is Discard pile and stock pile?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>The Discard Pile is the deck which is gathered from the discarded cards by the players in each round. This is where players place an unwanted card. The pile is face up and only the top card is seen. Players can also draw from this pile but cannot examine previous discards. The Discard pile re-mixes again when all the cards in the Stock are finished during the game and then the Discard pile is becoming the stock and the game continues.</p>
            <p><b>Closed Deck:</b> After the cards have been distributed, the remaining pile is called closed cards (stock pile).</p>
            <p><b>Stock pile:</b> The Stock deck is the leftover deck after the dealing of the cards to all players. From this deck the players draw a card at the beginning of each round, this indicates the turn of each player. When the Stock runs out we mix the Discard Pile which accumulated and turning it to the new Stock deck. The Stock deck is placed at the centre of the table and is accessible to all players.</p>
            <p>Players can draw a single card from the stock pile on a turn. This pile is face down and none of the cards are seen so drawing from stock involves a higher degree of risk, chance or luck than the discard pile.</p>
            <p class="bottom">The most recent discarded card goes to the top of discard pile. Only top card can be picked from the either pile.</p>
          </div>
        </li>
        <li id="What is Drop" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is Drop"> What is Drop?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>Players can choose not to play a particular Round before drawing the first card. This action is termed as Drop. A player can decide to drop from the game before his turn comes.</p>
            <p><b>Initial drop:</b>if a player decides to drop the game in the very beginning before picking up a single card, it is called initial drop.</p>
            <p class="bottom"><b>Middle Drop:</b>Players can choose not to play after a Round starts by neither drawing nor discarding any cards. This action is termed as Middle Drop. </p>
          </div>
        </li>
        <li id="What is Deadwood" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is Deadwood">What is Deadwood?</a></h3>
          </div>
          
          <div class="option-examples" style="display: none;">
            <p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
            
            <p>The term "deadwood" is used for cards which are not included in any meld (Sequences or sets) and are therefore unmatched. These are the cards which are left in the hands of the players after the last move in the game; the sum of these cards is counted to the iniquity of the same player who's left with the cards.</p>
            <p>The deadwood count is the total value of those cards.</p>
            <p>In case of show player must mandatorily have Life 1 and Life 2.</p>
            <p class="bottom">Failing to have life 1, all cards are considered as Deadwood. Failing to have Life 2, all cards, but life 1 are considered as deadwood.</p>
         
          </div>
          <div class="option-description" style="display: none;"> </div>
        </li>
        <li id="What is Lobby" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is Lobby">What is Lobby?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <ul class="bullet-normal">
              <li>List of all the game rooms are provided in details in lobby.</li>
              <li>The details include: Table id, Amount type, Entry fee, Min players, No. of players etc.</li>
              <li>JOIN: Next to every room there is a join button. On clicking, you become a spectator in that room.</li>
              <li>SIT: A sit button is provided in order to play the game. As you click on this button, you are given a chair on the game table. Once there are enough players on a table, the game begins. You cannot join a game in middle as a player.</li>
            </ul>
          </div>
        </li>
        <li id="What is Sequence" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is Sequence">What is Sequence?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>The purpose of the game is to complete a hand with most or all cards formed into Sets and/or Sequences. To make a Sequence a player should arrange three or more cards of the same suit in sequence, the order being A-2-3-4-5-6-7-8-9-10-J-Q-K-A: </p>
            <table>
              <tbody>
                <tr>
                  <td><b>Example of a Valid Sequence</b></td>
                  <td><b>Example of an Invalid Sequence</b></td>
                </tr>
                <tr>
                  <td><b>3<span class="ttspade">♠</span>4<span class="ttspade">♠</span>5<span class="ttspade">♠</span></b></td>

                  <td><b>3<span class="ttspade">♠</span>4<span class="ttclub">♣</span>5<span class="ttheart">♥</span></b></td>
                </tr>
                <tr>
                  <td style="background:#fff"><b>10<span class="ttheart">♥</span>J<span class="ttheart">♥</span>Q<span class="ttheart">♥</span>K<span class="ttheart">♥</span></b></td>
                  <td style="background:#fff"><b>10<span class="ttheart">♥</span>J<span class="ttheart">♥</span>Q<span class="ttdiamond">♦</span>K<span class="ttheart">♥</span></b></td>
                </tr>
              </tbody>
            </table>
          </div>
        </li>
        <li id="What is a set" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is a set"> What is a set?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>A player can form a set by arranging three or four cards of the same rank/face value and different suits: </p>
            <table>
              <tbody>
                <tr>
                  <td><b>Example of a Valid Set</b></td>
                  <td><b>Example of an Invalid Set</b></td>
                </tr>
                <tr>
                  <td><b>A<span class="ttspade">♠</span>A<span class="ttheart">♥</span>A<span class="ttclub">♣</span></b></td>
                  <td><b>A<span class="ttspade">♠</span>A<span class="ttheart">♥</span>2<span class="ttclub">♣</span></b></td>
                </tr>
                <tr>
                  <td style="background:#fff"><b>K<span class="ttspade">♠</span>K<span class="ttheart">♥</span>K<span class="ttclub">♣</span>K<span class="ttdiamond">♦</span></b></td>
                  <td style="background:#fff"><b>K<span class="ttspade">♠</span>K<span class="ttheart">♥</span>Q<span class="ttdiamond">♦</span></b></td>
                </tr>
              </tbody>
            </table>
            Combinations must not overlap - for example <span class="ttdiamond">♦</span>7<span class="ttdiamond">♦</span>8<span class="ttdiamond">♦</span>9<span class="ttspade">♠</span>9<span class="ttheart">♥</span>9 is either a Sequence of diamonds with two spare 9's or a set of 9's with two spare diamonds. If a second <span class="ttdiamond">♦</span>9 or a <span class="ttclub">♣</span>9 or a <span class="ttdiamond">♦</span>6 is added, the six cards form a Sequence and a set. Sets of 5 are not valid with/without a joker!
            <p>Wild cards can be used to substitute for any desired card in a set or Sequence. For example if the turned up card is a <span class="ttclub">♣</span>8 then <span class="ttdiamond">♦</span>3<span class="ttspade">♠</span>8<span class="ttheart">♥</span>5 is a valid Sequence, and <span class="ttspade">♠</span>J<span class="ttdiamond">♦</span>J<span class="ttdiamond">♦</span>8 is a valid set since all 8's are wild.</p>
            <p class="bottom">A card can be used only once, either in a Set or in a Sequence. In other words, you cannot use the same card for both a Sequence and a Set. Note that in a Set, each card must be of the same rank and a different suit, however when two decks are used situations do arise where you have in your hand for example <span class="ttheart">♥</span>K and <span class="ttheart">♥</span>K - you cannot add to this <span class="ttclub">♣</span>K to form a valid Set of three as the first two kings are of the same suit.</p>
          </div>
        </li>
        <li id=" What is melding" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="# What is melding"> What is melding?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Melding is the process by which cards are placed together to form sets (at least three cards of same rank) or sequences (at least three cards of same suit in consecutive rank).There is no laying melds on the table during play as this only happens when someone goes out. There is no knocking too in Indian Rummy. If the player manages to meld all his cards and has a zero deadwood count, and his hand meets the requirement of containing at least two sequences (one of which is pure, with no wild cards), only then may he go out. He does this by placing his melds on the table and discarding the final card (traditionally face down) to signal victory. At this point, other players display their melds and deadwood is counted up and scored accordingly. There are two kinds of combinations: Sequences and Sets.  A player wins the game by being the first to play all the cards in their hand by melding.</p>
          </div>
        </li>
        <li id="Pure Sequence" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Pure Sequence">What is Pure Sequence and Second Sequence?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <ul class="bullet-normal">
              <li>Life or Pure Sequence (Life1)
                <ul class="bullet-normal-1">
                  <li>It should be the order of not less than three cards of the same suite. Life1 shouldn't have a Joker.</li>
                </ul>
              </li>
              <li>Second Life or Second Sequence (Life2)
                <ul class="bullet-normal-1">
                  <li>It must be a sequence of at least three cards of the same suite. Life 2 may or may not have a joker.</li>
                </ul>
              </li>
            </ul>
          </div>
        </li>
        <li id="What is Count" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#What is Count">What is Count?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">The total score of the deadwood is referred to as count. Count gets accumulated with each game. The maximum count a player can get in a game is 80 which is also known as full count! </p>
          </div>
        </li>
        <li id="Win Combinations" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Win Combinations">What are Win Combinations?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>In order to have a winning combination, the player must have a Life, second life and other sets or Sequences. Different combinations for a win</p>
            <ul class="bullet-normal">
              <li>2 Sequences of 3, a set or Sequence of 3, a set or Sequence of 4 </li>
              <li>One Sequence of 3, one Sequence of 4, 2 sets or Sequences of 3</li>
              <li>One Sequence of 5, one Sequence of 4, one set or Sequence of 4</li>
              <li>Two Sequences of 5, one set of 3</li>
            </ul>
          </div>
        </li>
        <li id="join in the middle" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#join in the middle">What happens if I join in the middle of a game?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">In a Pool game or Syndicate &ndash; The player who joins  in the middle of the game is given the same number of points (+1) that the  highest point holder in the game already has.</p>
          </div>
        </li>
        <li id="join in the middle of" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#join in the middle of">What happens if I join in the middle of a game?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>In a Pool game or Syndicate &ndash; The player who joins  in the middle of the game is given the same number of points (+1) that the  highest point holder in the game already has.</p>
            <p class="bottom">For all other types of Rummy games (Rapid Rummy  &amp; Rummy Race) &ndash; The player begins at 0.</p>
          </div>
        </li>
        <li id="prize money is distributed" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#prize money is distributed">For a player joining in the middle of the game, how is the prize money is distributed?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">As a new player joins an existing game, his table  entry will be added to the pot excluding the game service charges. If the  player wins, he/she is subject to winning the entire prize money on offer.</p>
          </div>
        </li>
        <li id="cPool games" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Pool games">What are Pool games (Syndicate) games?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>Pool games are knockout games. The last player  standing wins the entire pot. As and when a player melds correctly- The points  that are left on the hands of the other players on the table are taken as the  score.</p>
            <p class="bottom">As and when the game progresses- The score may keep  increasing if the player loses/stays the same if he/she wins. The last person  to stay on the table without reaching the knockout score is declared the winner.</p>
          </div>
        </li>
        <li id="101 & 201 Pool games" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#101 & 201 Pool games"> What are 101 & 201 Pool games?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">As explained in the previous question, as a player  gathers 101 points in a 101 pool game, He/she is knocked out. Similarly, the  same for 201 Pool games- As a player accumulates 201 points- He/She is knocked  out and does not have the chance of winning.</p>
          </div>
        </li>
        <li id="players rejoin once" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#players rejoin once">Can players rejoin once they have been knocked out of a Pool game?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>Yes, There are conditions under which a player may  rejoin after again paying the entry fee for the table.</p>
            <ul class="bullet-normal">
              <li><strong>For 101 Pool Game</strong>
                <ul class="bullet-normal-1">
                  <li>A player may rejoin the 101 Pool game after being  knocked out. This may only happen when an existing player (on the table) has a  maximum of 79 points. That would imply that the new player (rejoining/new  player) would start the game with 80 points.</li>
                </ul>
              </li>
              <li><strong>For 201 Pool game</strong>
                <ul class="bullet-normal-1">
                  <li>A player may rejoin the 201 Pool game after being  knocked out. This may only happen when an existing player (on the table) has a  maximum of 174 points. That would imply that the new player(rejoining/new  player) would start the game with 175 points. </li>
                </ul>
              </li>
            </ul>
            <p class="bottom"><strong>Note:</strong> This will also apply to brand new players  wanting to join a room with existing players.</p>
          </div>
        </li>
        <li id="different forms of 13 card Rummy" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#different forms of 13 card Rummy">What are the different forms of 13 card Rummy that are offered on TaashTime?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>There are primarily three forms of 13 card Indian  Rummy offered on TaashTime:</p>
            <ul class="bullet-normal">
              <li><strong>Pool games</strong>
                <ul class="bullet-normal-1">
                  <li>These are knock out games. The players have to  ensure that they do not accumulate more than 101 points. At which point they  get eliminated. The last player remaining who does not get eliminated is  declared the winner.</li>
                </ul>
              </li>
              <li><strong>Forward Ladder games &ndash; Rummy Race</strong>
                <ul class="bullet-normal-1">
                  <li>These games are a ‘’race to a particular score’’  games. The points are distributed based on the final meld. If a player has  melded correctly, then he/she gets the sum of the points that the other players  have in hand after final meld.</li>
                </ul>
              </li>
              <li><strong>Money Per Point (MPP) games- Rapid Rummy</strong>
                <ul class="bullet-normal-1">
                  <li>These games are so called because for every game  that is played, a player receives the sum of the number of points (in total)  that are given to him by the losing players on the table. The denominations may  change for different MPP games. For eg. 10 ps per point,<span class="WebRupee"> Rs. </span>3 per point and so  on.</li>
                </ul>
              </li>
            </ul>
          </div>
        </li>
        <li id="leave the table" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#leave the table"> How to leave the table?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Once the game has been completed and a winner has  been decided- The player may chose to close the window in the time frame within  which the new game shall be started. The counter will start ticking on the top  of the screen in the game room window.</p>
          </div>
        </li>
        <li id="80 count and Wrong meld" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#80 count and Wrong meld">I have melded with the correct number of suits, why have I got 80 count and Wrong meld?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>Please make sure that you go through our How to Play  section. It has a very elaborate description on how to meld correctly. <br>
              A wrong meld may happen in the following ways:</p>
            <ul class="bullet-normal">
              <li>Wrong meld due to incorrect melding of cards.</li>
              <li>Using AutoMeld feature and not correctly grouping the cards.</li>
            </ul>
            <p class="bottom">Automeld is a feature which  enables the player to successfully ‘Show’ the grouped cards in hand. This  feature may not be used on a complete set of 13 cards. Always remember to sort  your cards before using the Automeld feature!</p>
          </div>
        </li>
      </ul>
    </div>
    <div class="ttcolactive" style="background:none repeat scroll 0 0 #9CB6D7;font-size:12px;font-weight:bold;padding:5px 0 5px 5px;vertical-align: middle;">Technical</div>
    <div style="pa dding:10px">
      <ul class="options-list">
        <li id="My screen keeps on flickering" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#My screen keeps on flickering">I have a problem with connecting and the games are very slow. My screen keeps on flickering, Why?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">This may be a minor technical issue with the  browser. You may refresh your browser and ensure you have an undisturbed  internet connection.</p>
          </div>
        </li>
        <li id="player to play on TaashTime" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#player to play on TaashTime">What are the minimum requirements for a player to play on TaashTime?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">This may be the fault of your internet service  provider. If the problem persists, Contact their customer support.  Additionally, we would like to hear about any problems that you may have.  Please contact <a href="mailto:support@taashtime.com">support@taashtime.com</a></p>
            . </div>
        </li>
        <li id="try at the same page" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#try at the same page">Why does it say ‘’welcome back’’ and ‘’you seem to entering an unauthorised zone, login and try at the same page.</a></h3>
          </div>
          
            
         
          <div class="option-examples" style="display: none;">
            <p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
          	<p class="bottom">In such a situation, you just need to log  in and try to access the page.</p>
          </div>
          <div class="option-description" style="display: none;"> </div>
        </li>
        <li id="getting the login page" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#getting the login page">I am already logged in but I’m still getting the login page?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Can you please let us know on which page  this is happening? Based on the answer, we either tell them that they are not  logged in or we are looking into the issue.</p>
          </div>
        </li>
        <li id="sizes do you accept" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#sizes do you accept">I wish to put up a picture of mine instead of the avatar, What types of files and file sizes do you accept?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">We are currently working on this. The specifications shall  be uploaded on the site soon.</p>
          </div>
        </li>
        <li id="displayed on the profile" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#displayed on the profile">Is my display pic supposed to be displayed on the profile?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Yes, your display picture shall be displayed on your  profile.</p>
          </div>
        </li>
      </ul>
    </div>
    <div class="ttcolactive" style="background:none repeat scroll 0 0 #9CB6D7;font-size:12px;font-weight:bold;padding:5px 0 5px 5px;vertical-align: middle;">Security</div>
    <div style="pa dding:10px">
      <ul class="options-list">
        <li id="data is protected" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#data is protected">How do I know that user data is protected on TaashTime?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">Please take a look at our Privacy Policy on the  website. It is very clearly defined as to how serious we are about data  protection.</p>
          </div>
        </li>
        <li id="TaashTime is not fake" class="option">
          <div class="option-header">
           	 <h3 class="option-name"><a href="#TaashTime is not fake"> How do I know that TaashTime is not fake?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">TaashTime is an SSL certified website by StartCom  which is an SSL certification authority. It ensures that the authenticity and  functions of the website are conducive to a safe internet browsing environment.</p>
          </div>
        </li>
        <li id="money not illegal" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#money not illegal">How is rummy for money not illegal?</a></h3>
          </div>
         
            
          <div class="option-examples" style="display: none;">
          	<p class="bottom">According to numerous legal judgements in  the country, Rummy is termed as a game of skill and <strong>NOT LUCK</strong>. Please refer to Legalities on the website for more  detailed information.</p>
          <p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
          </div>
            
          </div>
           <div class="option-description" style="display: none;">
        </li>
        <li id="find who runs TaashTim" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#find who runs TaashTim">Where can I find who runs TaashTime?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">TaashTime is run by Fortuity  Infotech.</p>
          </div>
        </li>
      </ul>
    </div>
    
    <div class="ttcolactive" style="background:none repeat scroll 0 0 #9CB6D7;font-size:12px;font-weight:bold;padding:5px 0 5px 5px;vertical-align: middle;">Auto Play</div>
    <div style="pa dding:10px">
      <ul class="options-list">
        <li id="my 5000 FunCoins" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Auto Play">What is Auto Play? </a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">In case of disconnection and for idle players, computer plays on behalf of that player. It basically picks up a card and discards the same card. </p>
          </div>
        </li>
        <li id="Welcome Bonus" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Early Drop">What is Early drop in Auto Play? </a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p class="bottom">If it is the first turn and the player is not connected, computer makes an early drop on behalf of the player.</p>
          </div>
        </li>
        <li id="get Bonus" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Mid Drop">What is Mid Drop in Auto Play?</a></h3>
          </div>
          <div class="option-examples" style="display: none;">
            <p>In case of disconnection or for idle player, the site automatically picks up a card from the closed deck and discards the same card on behalf of the user. This is done to make sure other players on the table are not inconvenienced by your internet connection problems. To avoid any loss of game by the user, the site drops (mid-drops) the user after 3 consecutive auto play turns. This ensures that even though you have temporary internet connections, you can log back into the game in the stipulated time and in case of prolonged outage, it ensures that as a player you end up with a relatively lesser points.</p>
          </div>
        </li>
        <li id="option-animated" class="option">
          <div class="option-header">
            <h3 class="option-name"><a href="#Fair Play">What is Fair Play?</a></h3>
          </div>
          
          <div class="option-examples" style="display: none;">
            <p>In games like tournament as time is an important factor, it is not fair for other players to get delayed because of one player's bad internet connection or if the player chooses not to play. To ensure fair play policies, the site follows its auto play policy very strictly and any money or points lost in the process will not be refunded.</p>
          </div>
          <div class="option-description" style="display: none;"> </div>
        </li>
      </ul>
    </div>
    
  </div>
</div>
<!-- div class="ttinnnerpad"><h4><strong>1) How do I claim my Welcome Bonus of Rs. 25?</strong></h4>
<p class = "bottom">As soon as a player  registers on the Website through the Homepage- a confirmation link is sent to  the provided email ID. On clicking on the validation link and logging in, the  player’s account will automatically be credited with Rs 25 Bonus.</p>
<p>&nbsp;</p>
<h4><strong>2) Do I have to deposit in order to get Bonus Rs. 25?</strong></h4>
<p class = "bottom">No, A player will automatically  be credited Rs 25 on following the instructions explained in the previous question.</p>
<p>&nbsp;</p>
<h4><strong>3) Can family members play with their Individual ID’s from the same computer?</strong></h4>
<p class = "bottom">Yes, Family members can play with their Individual  Ids from the same computer. Only one ID may be created for every unique email  address.</p>
<p>&nbsp;</p>
<h4><strong>4) What is the referral programme and how does it work?</strong></h4>
<p class = "bottom">When an existing TaashTime account holder refers  another new player to join, it is known as a referral. In this case, as the new  member registers on TaashTime- The referrer is automatically credited with  Bonus chips of 25 (in the event of the first log in of the referred player).  Welcome bonus is different for the referrer as well (See question 1)</p>
<p>&nbsp;</p>
<h4><strong>5) How can I withdraw money?</strong></h4>
<p class = "bottom">Please check out <a href = "/content/terms">Terms and Conditions</a> to learn more.</p>
<p>&nbsp;</p>
<h4><strong>6) My welcome bonus is missing from my balance, where is it?</strong></h4>
<p class = "bottom">Bonus is credited to a new player’s account only  when the account is activated. The player must make sure to click on the  confirmation link which is sent to the Email ID, which was used to register on  TaashTime.</p>
<p>&nbsp;</p>
<h4><strong>7) How do I close my account?</strong></h4>
<p class = "bottom">Please send an email to <a href="mailto:support@taashtime.com">support@taashtime.com</a>. We shall serve you in the best possible way.</p>
<p>&nbsp;</p>
<h4><strong>8) What do I do when Game winnings are not credited to my account?</strong></h4>
<p class = "bottom">Players on TaashTime have many customer support  tools in order to get in touch with TaashTime. Along with tickets which may be  submitted on the website for it to be action items, there is also Live Help  and/or email to <a href="mailto:support@taashtime.com">support@taashtime.com</a>.</p>
<p>&nbsp;</p>
<h4><strong>9) Where are you guys located?</strong></h4>
<p class = "bottom">We are located on 402, Chandra  Residency, Road No. 1, Banjara Hills, Hyderabad, AP</p>
<p>&nbsp;</p>
<h4><strong>10) I just lost internet connection in the middle of the game. Will I lose  everything that I have wagered on the game?</strong></h4>
<p class = "bottom">If the player regains connection in the middle of the  game; it is possible for the player to rejoin the game. However, if the  connection does not return during the span of the game, the game will switch to  Autoplay and in the event of losing- the player stands to lose the entire  wager.</p>
<p>&nbsp;</p>
<h4><strong>11) While arranging the cards, the table disappeared. What happens to the pot and  do I lose all the money?</strong></h4>
<p class = "bottom">Let us check our records. If other  players experienced similar issues, we would in all likeliness cancel the game  and return everyone’s money back to them.</p>
<p>&nbsp;</p>
<h4><strong>12) How to calculate the prize money and claims?</strong></h4>
<p class = "bottom">The Terms &amp; Conditions mentioned on the website  clearly mention the withdrawal terms and the ways of claim. Please refer to  them to know more in detail.</p>
<p>&nbsp;</p>
<h4><strong>13) What is the  joker if the ‘’joker’’ card comes as the open Joker?</strong></h4>
<p class = "bottom">The card Ace is taken as Joker.</p>
<p>&nbsp;</p>
<h4><strong>14) What is the minimum amount you can deposit?</strong></h4>
<p class = "bottom">The minimum deposit is Rs. 25 through Net Banking  and INR 250 through Credit Cards</p>
<p>&nbsp;</p>
<h4><strong>15) What is the maximum amount you can withdraw?</strong></h4>
<p class = "bottom">The maximum amount a player can withdraw is Rs. 5000  at a time. Please check out <a href = "/content/terms">Terms and Conditions</a> to learn more.</p>
<p>&nbsp;</p>
<h4><strong>16) Why can’t I access my account?</strong></h4>
<p class = "bottom">In the case when a player cannot access his/her  TaashTime account, it usually could be a problem with a forgotten password or  the validation/confirmation email. Please ensure that you click on the  confirmation link before logging in for the first time. For further queries,  Please contact <a href="mailto:support@taashtime.com">support@taashtime.com</a>.</p>
<p>&nbsp;</p></div-->





