<div class="ttinnnerpad"><h4><strong>1) How do I know that user data is protected on TaashTime?</strong></h4>
<p class = "bottom">Please take a look at our Privacy Policy on the  website. It is very clearly defined as to how serious we are about data  protection.</p>
<p>&nbsp;</p>
<h4><strong>2) How do I know that TaashTime is not fake?</strong></h4>
<p class = "bottom">TaashTime is an SSL certified website by StartCom  which is an SSL certification authority. It ensures that the authenticity and  functions of the website are conducive to a safe internet browsing environment.</p>
<p>&nbsp;</p>
<h4><strong>3) How is rummy for money not illegal?</strong></h4>
<p class = "bottom">According to numerous legal judgements in  the country, Rummy is termed as a game of skill and <strong>NOT LUCK</strong>. Please refer to Legalities on the website for more  detailed information.</p>
<p>&nbsp;</p>
<h4><strong>4) Where can I find who runs TaashTime?</strong></h4>
<p class = "bottom">TaashTime is run by Fortuity  Infotech.</p>
<p>&nbsp;</p></div>