<div style="border:1px solid #CD222B;border-radius:5px;">
<div id="ttwidget-docs"  >
  <div style="display:none">
    <ul>
      <li><a href="#demo"><span></span></a></li>
      <li><a href="#source"><span></span></a></li>
    </ul>
  </div>
  <div >
    <div style="text-align:center;margin-bottom:30px;"><div class="TTBingogameName TTBingoBtnmargt">Frequently Asked Question’s</div></div>
    <div class="ttcolactive">1)	Getting Started</div>
    <div style="padding:10px">
      <div class="option-examples" style="display: none;">
        <p class="bottom">As soon as a player registers on the Website through the Homepage- a confirmation link is sent to the provided email ID. On clicking on the validation link and logging in, the player’s account will automatically be credited with 5000 FunCoins. </p>
      </div>
      <ol class="options-list">
        <li><a href="#g1"> Is there a free signup bonus?
         
          
        
        </a></li>
        <li><a href="#g2"> How do I get started at Bingo Bible?
          
        </a></li>
        <li><a href="#g3"> How do I change or update information?
          
        </a></li>
        <li><a href="#g4"> I’ve forgotten my password or user name, how can I get it back?
          
        </a></li>
        <li><a href="#g5"> Do I have to spend ages downloading lots of software?
          
        </a></li>
        <li><a href="#g6"> Can I withdraw money won with my free sign up bonus? </a></li>
      </ol>
    </div>
    <div class="ttcolactive">2)	Security &amp; Privacy</div>
    <div style="pa dding:10px">
      <ol class="options-list">
        <li><a href="#s1"> Is it legal to play online bingo?
         
        </a></li>
        <li><a href="#s2"> When I log in will my real name remain anonymous?
          
        </a></li>
        <li><a href="#s3"> Is my personal data safe and secure?
          
         
        </a></li>
        <li><a href="#s4"> What is encryption?  Why is it important?</a></li></ol></div>
  </div>
      </ul>
    
  <div class="ttcolactive">3)	Banking	</div>
    <div style="pa dding:10px">
      <ol class="options-list">
        <li><a href="#b1"> What payment methods do you accept?
          
        </a></li>
        <li><a href="#b2"> What is the minimum amount I can deposit?
         
        </a></li>
        <li><a href="#b3"> How will my transactions appear on my bank or credit card?
          
        </a></li>
        <li><a href="#b4"> What is the minimum amount I can withdraw?
         
        </a></li>
        <li><a href="#b5"> I have made a withdrawal, when will the money be in my bank account or on my credit card? </a></li>
      </ol>
    </div>
    <div class="ttcolactive">4)	Game Play</div>
    <div style="pa dding:10px">
      <ol class="options-list">
        <li><a href="#gp1"> Is there any wagering /play through requirement for the withdrawals?</a>
          
        </li>
        <li><a href="#gp2"> How can I trust the games to be fair?
          
        </a></li>
        <li><a href="#gp3"> What happens if I lose connection during an online bingo game?</a>
         
        </li>
        <li><a href="#gp4"> What happens if there is more than one bingo winner?
          
        </a></li>
        <li><a href="#gp5"> Can employees or family members of employees play the Bingo Bible?</a></li>
        <li><a href="#gp6"> Can I play any other games at Bingo Bible?</a></li>
      </ol>
    </div>
    <div class="ttcolactive">5)	Support</div>
    <div style="pa dding:10px">
      <ol class="options-list">
        <li><a href="#sp1"> Can I self-exclude? </a></li>
        <li><a href="#sp2"> How can I contact the support team? </a></li>
      </ol>
    </div>
    <div class="ttcolactive">6)	Chat Games &amp; Bonuses</div>
    <div style="pa dding:10px">
      <ol class="options-list">
        <li><a href="#cg1"> What are chat games? </a></li>
        <li><a href="#cg2"> What are Bingo Bucks? </a></li>
        <li><a href="#cg3"> What chat games does Bingo Bible offer? </a></li>
        <li><a href="#cg4"> What are the chat rules?</a></li>
        <li><a href="#cg5"> How much Chat Bonus Bucks can I win at Bingo Bible?</a></li>
        <li><a href="#cg6"> How can I find out if I’ve maxed out on my Chat BBs?</a></li>
        <li><a href="#cg7"> What should I do if my BBs from the previous day’s chat are not credited?</a> </li>
      </ol>
    </div>
  </div>
  <div class="descrtn">
  	<div id="g1">
    <h4>Is there a free signup bonus?</h4>
    <p style="margin-left:10px;margin-right: 10px;">At Bingo Bible, we want you to join us for our exciting games in a friendly and secure environment. We offer a free £20 for you to try our games and to feel the rush of playing.  It gets better; our welcome package contains 500% bonus on your first deposit. </p>
  	<p style="margin-left:10px;margin-right: 10px;">Deposit £10 &amp; get £50. You get to play with £60 for a deposit of a tenner.</p>
  	<p style="margin-left:10px;margin-right: 10px;">We want you to win and feel the excitement!</p>
  	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="g2">
   	  <h4>How do I get started at Bingo Bible?</h4>	
      <p style="margin-left:10px;margin-right: 10px;">It just takes a minute of your time to get started at bingo bible. Simply click on “Join now” on the top menu or fill in our short registration form which you find on the homepage and you’re almost ready to join the excitement. Once we’ve verified your email address, enter the credentials that you’ve chosen to login in the text fields located at the top of the page &amp; click on login.  Your account will be credited with £20 instantly &amp; you can play all the games that are available on our site (Bingo 90&amp;75, more than 20 different slot games, Keno &amp; Roulette).
        
      </p>
      <p  class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="g3">
    	<h4>How do I change or update information?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">In order to update your information, click on the avatar image which you see on the top right corner of each page of Bingo Bible once you’re logged in. Click on Profile option and can edit your information. You can also contact the customer support to make any changes. For security reasons, it’s mandatory and your own responsibility to provide accurate information. If found any irrelevant or false information, Bingo Bible has the right to close the account with immediate effect and forfeit all the account balance. Any changes to debit or credit card details must be made through customer support.</p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="g4">
    	<h4>I’ve forgotten my password or user name, how can I get it back?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">Happens to the best of us, you can use the “Forgot Password link” at the top of the page, reset password link will be emailed to your registered email address. Through the link you can reset password for yourself.</p>
    	<p style="margin-left:10px;margin-right: 10px;">Please note: Your account information should be kept in utmost confidentiality. Bingo Bible is not responsible for any misuse of your account or account activity. We suggest you to change your password for every 30 days in order to be more secure and safe. </p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="g5">
    	<h4>Do I have to spend ages downloading lots of software?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Absolutely not! Bingo Bible is a non-download bingo game, so you're ready to get straight into the action as soon as you have registered. Just click the “Games” link at the top of any page on the site to enter the games area. The only requirement is that you have at least Flash version 8 or above to run the game software. If you do not, you must download it first from the Flash website <a href="http://get.adobe.com/flashplayer/">http://get.adobe.com/flashplayer/</a></p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="g6">
    	<h4>Can I withdraw money won with my free sign up bonus?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">Free sign up bonus is given to all the new players. We want all our players to first check the site, play our games & once comfortable then play with real money. Therefore any winnings from free sign up bonus can’t be withdrawn. </p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="s1">
    	<h4>Is it legal to play online bingo?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">You must be over 18 to play online bingo. If you do not live in the UK, you should check the laws for your particular country or state before playing online bingo games.  Players found to be under 18 will be declared void and no winnings will be paid out. We at BingoBible will do our best to ensure that we do not permit under 18's to play bingo online. See terms and conditions for further details.</p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="s2">
    	<h4>When I log in will my real name remain anonymous?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">Yes. All your personal information is kept confidential. When you register at Bingo Bible you will be asked to choose a Username and this will be the name displayed to other online bingo players</p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="s3">
    	<h4>Is my personal data safe and secure?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">Yes. Bingo Bible ensures that all your personal information,transaction details and history are kept safe & secure by using SSL Security Certificate. Your information is submitted on heavily encrypted pages, and cannot be obtained by anyone.</p>
    	<p style="margin-left:10px;margin-right: 10px;">At Bingo Bible, we hate spam as much as you, that’s why we treat your email address with the utmost care. This means we do not sell, rent or lease our data lists to third parties and certainly under no circumstances do we provide your personal information to any third party individual, government agency, or company at any time.</p>
    	<p style="margin-left:10px;margin-right: 10px;">So how do we use your email?</p>
    	<p style="margin-left:10px;margin-right: 10px;">Your experience at Bingo Bible is very important to us and we are committed to building a long-lasting relationship with you. Like any great relationship, we believe in communication that’s based on honesty, respect and trust.</p>
    	<p style="margin-left:10px;margin-right: 10px;">Email Communications:</p>
    	<p style="margin-left:10px;margin-right: 10px;">Upon registration to Bingo Bible, we send you an email so that you may activate your new account.</p>
    	<p style="margin-left:10px;margin-right: 10px;">We may send emails regarding new policy updates, site updates, promotions and new alerts that may be important to you and your account at Bingo Bible.</p>
    	<p style="margin-left:10px;margin-right: 10px;">We may send you a service announcement regarding your deposit in the form of a purchase confirmation.</p>
    	<p style="margin-left:10px;margin-right: 10px;">To unsubscribe from emails:</p>
    	<p style="margin-left:10px;margin-right: 10px;">You can instantly unsubscribe from future promotional emails from within a Bingo Bible email you may have received – or -</p>
    	<p style="margin-left:10px;margin-right: 10px;">You can send <a href="mailto:support@bingobible.co.uk">support@bingobible.co.uk</a> an email request and we will unsubscribe your email id within 5 days from the requested date.</p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="s4">
    	<h4>What is encryption? Why is it important?</h4>
    	<p style="margin-left:10px;margin-right: 10px;">Encryption refers to algorithmic schemes that encode information into non-readable form which provides privacy. The receiver uses a “key” to decrypt the message, returning it to its original form. Again, Bingo Bible uses industry standard encryption technology, the same kind of security that you’ll find when performing online banking. Encryption is important to keep information safe and out of the hands of malicious third parties.</p>
    	<p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="b1">
    <h4>What payment methods do you accept?</h4>
    <p style="margin-left:10px;margin-right: 10px;">At Bingo Bible, we accept most payment methods. The credit and debit cards we accept are Visa, Visa Electoron, Delta, Switch, Solo, Master card and Maestro. We also accept Ukash.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="b2">
    <h4>What is the minimum amount I can deposit?</h4>
    <p style="margin-left:10px;margin-right: 10px;">You can deposit as little as £5 at one time using Ukash and £10 using other deposit options. But please remember that you will not receive a deposit bonus on any deposits of less than £10</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="b3">
    <h4>How will my transactions appear on my bank or credit card?</h4>
    <p style="margin-left:10px;margin-right: 10px;">The description of our deposits and withdrawals will appear as “Aqua Pay London” on your bank statement. </p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="b4">
    <h4>What is the minimum amount I can withdraw?</h4>
    <p style="margin-left:10px;margin-right: 10px;">The minimum amount you can withdraw from your Bingo account is £40.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="b5">
   	  <h4>I have made a withdrawal, when will the money be in my bank account or on my credit card?</h4>
    <p style="margin-left:10px;margin-right: 10px;">All withdrawal transactions are processed on Tuesdays & Fridays. Your Bank or Credit Card Company may take up to 6 working days to complete the process from the date of approval. Bingo Bible reserves the right to delay and/or stop the processing of withdrawal requests until final approval has been received for any outstanding deposit transactions. All withdrawals will be processed to the card used on the site for deposits.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp1">
    <h4>Is there any wagering /play through requirement for the withdrawals?</h4>
    <p style="margin-left:10px;margin-right: 10px;">We love giving out lots of bonuses just as much as our players love to get them! To read more about our wagering requirements, please visit our 
	<a href="http://bingobible.co.uk/content/rules">rules page.</a></p>
    <p style="margin-left:10px;margin-right: 10px;">Again, these wagering requirements have been put in place to prevent our bonus system from being abused and to deliver to our players the opportunities to win big! With this in mind, Bingo Bible also monitors accounts with repeat deposits versus cashout requests. In our fair judgment and at management’s discretion, if it is determined that there is an intent to abuse the bonus program, a players bonus ability will be deactivated. Repeat offenders of our bonus program will be forced to forfeit their account balance and have their account permanently disabled.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp2">
    <h4>How can I trust the games to be fair?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Bingo Bible is licensed and regulated to offer online gaming services under the laws of Costa Rica through Progaming Winners Online Pvt Ltd and we adhere to their strict regulations on fair gaming. All games on this site are fully audited and extensively tested to ensure fair play and honest pay outs. As part of our commitment to fair play, all our gaming software systems use a Random Number Generator (‘RNG’) to make sure all game outcome results are truly random.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp3">
    <h4>What happens if I lose connection during an online bingo game?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Don't worry. If you lose your connection during a game of online bingo or any other instant games, the game will be played on the servers and your balance will be adjusted according to your win.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp4">
    <h4>What happens if there is more than one bingo winner?</h4>
    <p style="margin-left:10px;margin-right: 10px;">If there is more than one winner, the bingo cash prize will be divided equally between all the winners. If one player gets Bingo on two cards they will receive two times the value of the divided share of the prize.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp5">
    <h4>Can employees or family members of employees play the Bingo Bible?</h4>
    <p style="margin-left:10px;margin-right: 10px;">No. Although all our games are fair and cannot be influenced by players, promotions must be kept secure and so anyone who may have inside knowledge of promotions is not allowed to participate.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="gp6">
    <h4>Can I play any other games at Bingo Bible?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Yes, we offer a variety of instant win and casino games at Bingo Bible and you can play them all using your Bingo Bible username and password</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="sp1">
    <h4>Can I self-exclude?</h4>
   	  <p style="margin-left:10px;margin-right: 10px;">If at any time during your play you feel that you are spending too much then we kindly request that you either reduce your limits or suspend your account. Should you wish to suspend your account then please contact our Customer Support team stating the amount of time you would like your account closed for. We aim to deal with your request within 48 hours. Please note that we will not be held responsible for your actions while your account remains open.</p>
   	  <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="sp2">
    	<h4>How can I contact the support team?</h4>
   	  <p style="margin-left:10px;margin-right: 10px;">The Bingo Bible Customer Support Team is available to answer any questions you may have about your account or the game. You can speak to one of our Customer Support Agents by visiting the live help or can email us @ support@bingobible.co.uk. We surely will try our best to reply within 24 hours.</p>
   	  <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg1">
    <h4>What are chat games?</h4>
    <p style="margin-left:10px;margin-right: 10px;">We’re all about having fun while you play bingo. So we decided to offer a bunch of chat games that you can participate while playing online bingo. When you play a chat game, you get the chance to win bonus money, also called Bingo Bucks (BBs), which will be added to your account at the end of each chat host’s shift. Our friendly chat hosts will be more than welcoming and willing to answer any questions you might have about each of the chat games that Bingo Bible offers.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg2">
    <h4>What are Bingo Bucks?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Bingo Bucks are our way of giving “You”, the player more chances to win! By participating in our chat games, you can accrue more money to use when you play our great games. </p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg3">
    <h4>What chat games does Bingo Bible offer?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Looking to read up on a certain chat game? You can do so by visiting our chat games page. If you have a favourite chat game that we don’t have listed here, or even an original idea for a chat game that you’d like to play during your stay with us, please contact us and have your say!</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg4">
    <h4>What are the chat rules?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Only active bingo players without a pending withdrawal will be eligible to receive Bingo Bucks.</p>
    <p style="margin-left:10px;margin-right: 10px;">Accumulated Bingo Bucks cannot exceed 100% of the previous deposit. Once this limit is reached, another deposit is required to be eligible to win chat games or you’ve to wait for the next day. However minimum of one deposit is required in the last 7 days, failing which, no bingo bucks will be credited.</p>
    <p style="margin-left:10px;margin-right: 10px;">Players must be in chat before the game begins in order to qualify.</p>
    <p style="margin-left:10px;margin-right: 10px;">The CH on duty has the final authority on who qualifies and who doesn’t.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg5">
    <h4>How much Chat Bonus Bucks can I win at Bingo Bible?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Bingo Bucks (BBs) are only awarded to players who are actually playing the bingo game at the time of a chat game. As long as you meet this requirement, you will be awarded up to 100% of your previous deposit on a particular day. (e.g. if your last deposited is 100,you have the opportunity to receive 100 BBs without depositing again on that particular day.). However minimum of one deposit is required in the last 7 days, failing which, no chat bingo bucks will be credited.    </p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg6">
    <h4>How can I find out if I’ve maxed out on my Chat BBs?</h4>
    <p style="margin-left:10px;margin-right: 10px;">The easiest way to tell is by checking your reconcile report by going to Reports &gt;&gt; Reconcile. If you have any questions regarding your active status and eligibility for chat BBs, feel free to contact our 24/7 Live help service or email us as <a href="mailto:support@bingobible.co.uk">support@bingobible.co.uk</a></p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
    <div id="cg7">
    <h4>What should I do if my BBs from the previous day’s chat are not credited?</h4>
    <p style="margin-left:10px;margin-right: 10px;">Firstly please check to see if you have “maxed” by looking under the Reconcile Report. If you feel you have not, feel free to contact our 24/7 Live help service or email us as <a href="mailto:support@bingobible.co.uk">support@bingobible.co.uk.</a> Support will reply to you with a resolution within 24 hours.</p>
    <p class="gap"><a href="#ttwidget-docs">Back to top</a></p>
    </div>
  </div><!--descrtn-->
</div>

</div>
