<div class="zenfox-content">
<div class="heading2"> Withdrawal Policy</div>

<p>

In order for a player to be able to withdraw money from <?=$this->frontendShortName?>, they need to meet the conditions as explained hereunder:

<ol>

<li>The player must have deposited a minimum of TaashCash 100</li>

<li>The player must have played in at least one cash game</li>

<li>They player should have a balance of 500 + the amount the player wishes to withdraw</li>

<li>The player can withdraw a minimum of TaashCash 100 and a maximum of TaashCash 5000 per withdrawal</li>

<li>The player can withdraw for free only once in a month. Any further request for withdrawal attracts processing charges of TaashCash 100 per additional request. </li>

<li>Putting up a withdrawal request where the player does not meet the required conditions will result in

<ul>

<li>Rejection of withdrawal</li>

<li>An automatic deduction of TaashCash 100 from their real balance </li>

<li>Deduction of part or all of the bonus available with the player as decided by the management of <?=$this->frontendShortName?></li>

</ul></li>

<li>Withdrawals are processed once a week on <?=$this->processingDay?>. </li>

<li>Withdrawals submitted post 12:00 PM on <?=$this->processingPreviousDay?> shall be processed during the next week’s cycle. </li>

<li>Upon the successful processing of a withdrawal application, the money due shall be sent by check to the address provided by the player, as per the records of the site. </li>

<li>The amount a player can withdraw is displayed in the player’s profile.</li>

</ol></p>

<div class="heading2"> Withdrawal conditions </div> 

<ul>

<li>The player should have played at least one cash game</li>

<li>The player should have at least 3 times the number of Taash Points as the sum of deposit and bonus awarded with the same. </li>

<li>Bonus can be converted to real money once a month.</li>

<li>Bonus gets converted to real money at a conversion rate of 10 bonus points = 1 TaashCash </li>

</ul>



<div class="heading2"> What are Taash Points? </div>

<ul>

<li>Every game you enter with either TT money or real money, you accumulate Taash Points. </li>

<li>For every unit of real money you put into game play, you get one Taash Point for the same. </li>

<li>For every unit of TT money you put in, you get 0.5 Taash points. </li>

</ul>

</div>
