<div class="content-top"><center><h2 style="font-family:Verdana; font-size:32px;margin-bottom: -58px;">Upgrade to Bingo Bible Pro</h2></center>
	<div class="three-deposit-blck">
	<div id="deposit-page-box-1">
		<p class="top-text">High Roller</p>
		<p class="middle-text">£ 100</p>
		<p class="bottom-text">Bet Big to Win BIg</p>
		<p class="line-text"><span>300%</span> Deposit Bonus</p>
		<p class="line-text"><span>30%</span>  Loyalty Bonus</p>
		<p class="line-text"><span>500</span>  Loyalty Points</p>
		<p></p>
		<p class="line-text"><span>£3 + 25%</span>
		<br/>Referral Bonus</p>
		<p class="deposit-btn">Deposit</p>
		<p class="last-line-text"><span>Instant</span> Withdrawal**</p>
	</div>
	<div id="deposit-page-box-2">
		<p class="box2-top-text">Player</p>
		<p class="box2-middle-text">Only £ 50</p>
		<p class="box2-bottom-text">Sweet Deal</p>
		<p class="box2-line-text"><span>300%</span> Deposit Bonus</p>
		<p class="box2-line-text"><span>30%</span> Loyalty Bonus</p>
		<p class="box2-line-text"><span>250</span> Loyalty Points</p>
		<p class="box2-line-text"><span>£3 + 25%</span><br/>Referral Bonus</p>
		<p class="box2-deposit-btn">Deposit</p>
	</div>
	<div id="deposit-page-box-3">
		<p class="top-text">Starter</p>
		<p class="middle-text">£ 20</p>
		<p class="bottom-text">Most Common</p>
		<p class="line-text"><span>200%</span> Deposit Bonus</p>
		<p class="line-text"><span>25%</span> Loyalty Bonus</p>
		<p class="line-text"><span>50</span> Loyalty Points</p>
		<p class="line-text"><span>£2 + 20%</span><br/>Referral Bonus</p>
		<p class="deposit-btn">Deposit</p>
	</div>
	<div id="deposit-page-box-4">
		<p class="top-text">Custom</p>
		<p class="middle-text"><select class="date"name="date">
		<option value="1">01</option>
		<option value="2">02</option>
		<option value="3">03</option>
		<option value="4">04</option>
		</select></p>
		<p class="bottom-text">Define A Deal</p>
		<p class="line-text"><span>100%</span> Deposit Bonus</p>
		<p class="line-text"><span>20%</span> Loyalty Bonus</p>
		<p class="line-text"><span>20</span> Loyalty Points</p>
		<p class="line-text"><span>£2 + 20%</span><br/>Referral Bonus</p>
		<p class="deposit-btn">Deposit</p>
		
	</div>
 </div>
</div>
<div class="content-bottom">
	<form class="deposit-form">
		
		<div id="cards"><input class="radio-btn1"type="radio" name="payment" value="cards">
		<img src="/images/bingobible/american-express.jpg">
		<img src="/images/bingobible/visa.jpg">
		<img src="/images/bingobible/master-card.jpg">
		<img src="/images/bingobible/jcb.jpg"></div><div id="paypal"><input class="radio-btn2"type="radio" name="payment" value="paypal">
	  <img src="/images/bingobible/pay-pal.jpg"></div>
		<p class="form-text">This credit card has been declined</p>
		<label for="cardnum">Card number</label>
		<input class="cardnum"type="text" name="card.no" id="cardnum" value=""size="30" >
        <div id="postal">
		<label for="postal-code">Postal Code</label>
        <input class="postal-code" type="text" name="postalcode" id="postalcode" value="" size="30" ></div>
		<div id="security"><label for="security-code">Security Code<div id="ques"><img src="/images/bingobible/quest.png"/></div></label><input class="security-code" type="text" name="securitycode" id="postalcode" value="" size="30" ></div>
        <div id="Expiration"><label for="expiry-date">Expiration Date</label>		
		<select class="date"name="date">
		<option value="1">01</option>
		<option value="2">02</option>
		<option value="3">03</option>
		<option value="4">04</option>
		</select>
		<select class="year" name="year">
		<option value="2015">2015</option>
		<option value="2016">2016</option>
		<option value="2017">2017</option>
		<option value="2018">2018</option>
		</select></div>
		<label for="country">Country</label>
		<select class="country" name="country">
		<option value="">India</option>
		<option value="">Afganistan</option>
		<option value="">Pakistan</option>
		<option value=""></option>
		</select>
		<p class="form-deposit-btn">Deposit</p>
	</form>
<!--<textarea rows="4" cols="50"></textarea> -->
</div>
</div>