<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Bingo Crush Gifts</title>
<style>
img{border:0px;}
</style>
</head>
<body>
  <table width="750" cellpadding="0" cellspacing="0" style="margin:auto; border:1px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 10px">
  </div>
  <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
  <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
  </td></tr>
  <tr><td>
 <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px  0px 0px 10px">
  </div>
  <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
   <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
  </td></tr>
   <tr><td>
 <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px  0px 0px 10px">
  </div>
  <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
   <div style="width:240px;height:375px;border:1px solid;float:left;margin:10px 0px 0px 0px">
  </div>
  </td></tr>
   </table>
</body>
</html>
