<!--<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title>Bingo Crush Monthly Newsletter</title>-->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
    <!--[if IE 7]>
    <style type="text/css">
        #vtab > ul > li.selected{
            border-right: 1px solid #fff !important;
        }
        #vtab > ul > li {
            border-right: 1px solid #ddd !important;
        }
        #vtab > div { 
            z-index: -1 !important;
            left:1px;
        }
    </style>
    <![endif]-->
    <style type="text/css">
     /* <!--  body {
            background: #fff;
            font-family: verdana;
            padding-top: 50px;
        }-->*/
        #vtab {
            /*margin: auto;*/
            width: 750px;
            height: 100%;
			float:left;
			
			 }
        #vtab > ul > li {
            width: 110px;
            height: 15px;
            background-color:#FAFAFA !important;
            list-style-type: none;
            display: block;
            text-align: center;
            margin: auto;
            padding-bottom: 10px;
            border: 1px solid #fff;
            position: relative;
            border-right: none;
            /*opacity: .3;*/
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=30)";
            filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=30);
			color:#E82C0C !important;
			font-weight:bold;cursor:pointer;
			
        }
       #vtab > ul > li.selected {
            opacity: 1;
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
            filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
            border: 1px solid #ddd;
            border-right: none;
            z-index: 10;
            background-color: #E82C0C !important;
            position: relative;
			color:#FFF !important;
        }
        #vtab > ul {
            float: left;
            width: 110px;
            text-align: left;
            display: block;
            margin: auto 0;
            padding: 0;
            position: relative;
            top: 30px;
        }
        #vtab > div {
            background-color: #ffffff;
            margin-left: 110px;
            border: 1px solid #ddd;
            min-height: 500px;
            padding: 12px;
            position: relative;
            /*z-index: 9;*/
            -moz-border-radius: 20px;
			max-height:auto;
			width:614px;
        }
        #vtab > div > h4 {
            color: #800;
            font-size: 1.2em;
            border-bottom: 1px dotted #800;
            padding-top: 5px;
            margin-top: 0;
        }
      
		img{border:0px;}
        a{border:none;}
       .pa{font-family:Arial, Helvetica,sans-serif;font-size:12px;margin-left:5px }
    </style>

    <script type="text/javascript">
        $(function() {
            var $items = $('#vtab>ul>li');
            $items.click(function() {
                $items.removeClass('selected');
                $(this).addClass('selected');

                var index = $items.index($(this));
                $('#vtab>div').hide().eq(index).show();
            }).eq(6).click();
        });
    </script>

<!--</head>-->
<!--<body>-->
    <div id="vtab" style="border:1px #E82C0C solid;background-color:#fff;">
        <ul>
            <li >July Month</li>
            <li >July Mid Month</li>
			<li >August Month</li>
			<li >Aug Mid Month</li>
			<li>September Month</li>
	     	<li>Sept Mid Month</li>
			<li>October Month</li>
        </ul>
		
        <div>
           <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:0px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>JULY News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:0;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title1.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px">Dear Player,<br/><br/>

We Thank you for being part of Bingo Crush. With all your support and faith, we had a very successful first month of operation. We hope to foresee many more months & years progressing our way in to the bingo world and assure you the best online bingo experience. On this eve, we have credited a free &#163;5 to your account. <a href="http://bingocrush.co.uk">Login now</a>.</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	

	
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">Bingolite</td>
				<td width="50%">20 bonus</td>
				</tr>
				<tr>
				<td width="50%">Gangnum </td>
				<td width="50%">20 bonus</td>
				</tr>
				<tr>
				<td width="50%">smudgieslucky</td>
				<td width="50%">20 bonus</td>
				</tr>
				<tr>
				<td width="50%">maggiemay67</td>
				<td width="50%">20 bonus</td>
				</tr>
				<tr>
				<td width="50%">dorris57 </td>
				<td width="50%">20 bonus</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			<tr>
			<td width="50%">sheshe49</td>
			<td width="50%">25 cash</td>
			</tr>
			<tr>
			<td width="50%">sharpee667788 </td>
			<td width="50%">25 cash</td>			
			</tr>
			<tr>
			<td width="50%">gorgeousgar</td>
		    <td width="50%">25 cash</td>
			</tr>
			<tr>
			<td width="50%">daveloz1</td>
			<td width="50%">25 cash</td>
			</tr>
			<tr>
			<td width="50%">Bingoty </td>
			<td width="50%">25 cash</td>
			</tr>
			
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="20%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >"GORGEOUSGAR"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_fri.png"  alt="friday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_sat.png" alt="saturay promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_tues.png" alt="tuesday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle1.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe1.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
   Chicken Pie by Donna Hay.<br>
   <br>
   <strong>chicken pie</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>1 quantity (350g shortcrust pastry (see recipe)</li>
     <li>375g puff pastry</li>
	 </ul>
	 <br>

    <p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold">filling</p><br><br>
	<ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li> 1 tablespoon oil</li>
    <li> 2 leeks, chopped</li>
    <li> 1kg chicken thigh fillets, cut into 2cm (3/4 in) cubes</li>
    <li> 3 cups chicken stock<br>
    <li> <sup>3</sup>/<sub>4</sub> cup (180ml) dry white wine</li>
    <li> 250g small button mushrooms, halved</li>
    <li> 2 tablespoons chopped flat-leaf parsley</li>
    <li> 2 tablespoons cornflour (cornstarch)</li>
    <li> <sup>1</sup>/<sub>4</sub> cup (60ml) water</li>
   <li>  sea salt and cracked black pepper</li>
    <li> 1 egg, lightly beaten</li>
    </ul>
	<br>
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">Procedure :</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
To make the filling, cook the oil and leek in a saucepan over medium&#45;high heat for 3 minutes or until soft.<br><br> 

Add the chicken, stock and wine.<br><br>

 Simmer, uncovered, for 45 minutes or until tender. <br><br>

Add the mushrooms and parsley to the pan and cook for 5 minutes.<br><br>

 Blend the cornflour and water to a smooth paste, add to the pan and cook, stirring, for 5 minutes or until the mixture thickens and returns to a simmer.<br><br> 

Add the salt and pepper. Set aside to cool.<br><br>

Roll out the shortcrust pastry on a lightly floured surface to 3 mm (1/8 in) thick and line the base of a deep 24cm (91/2 in) pie tin. <br><br>

Spoon in the cooled filling. Roll out the puff pastry to 3&#45;4 mm (1/8 in) thick. <br><br>

Cut a shape from the middle of the pastry as an air hole. Place the pastry top onto the pie. <br><br>

Trim and press the edges together to seal and brush the top with a little egg. <br><br>

Bake at 180&deg;C (350&deg;F) for 40 minutes or until golden and crisp. <br><br>

Serves 6.</p>

   </p>
   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
   
  
		 

   
   </table>
        </div>
        <div>
           <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:0px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>JULY News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:0;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<!--<tr><td colspan="2">
	<p class="pa">Dear Player,<br/><br/>
Greetings from Bingo crush!<br /><br/>

We are almost half way through this month and happy to see many winners in our rooms. Congratulations to all our winners and we thank all our players for their great support and faith which headed us to reach our 1st month of celebrations. To celebrate this happiest moment, we have a free Fiver (&#163;5) waiting for you. <a href="http://bingocrush.co.uk">Login now</a> and free &#163;5 login bonus will be credited to your account instantly.
 </p>
	</td></tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>-->
	
    	<tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000;">
	<td colspan="2">&nbsp;Special Attractions of the Month</td>
	</tr>
	<tr><td colspan="2">
	<p class="pa"><b>Introducing Free Games : </b>Bingo Crush Team is all excited with the launch of FREE GAMES. Now at <a href="http://bingocrush.co.uk/">bingocrush.co.uk</a>, you can play bingo absolutely free. Free 90 ball bingo worth &#163;2 each game will be played randomly from 6pm to 11pm.<br /><br />

<b>5p games in 75 Bingo :</b> We have reduced the card price in 75 ball bingo. Now you can buy cards at just 0.05 pence. This offers all players to buy more cards and enjoy playing bingo for long hours<br /><br />

<b>New Slot Launched - "Fruit Fantasy" :</b> Login now and Go for a reel spin on our newly launched slot game "Fruit Fantasy". The new 9 line 5 reel slot game comes with Free spins, scatter & wild payouts. Check out now.</p>
	</td></tr>
	
	
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
	
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">Bingolite</td>
				<td width="50%">200 Cash</td>
				</tr>
				<tr>
				<td width="50%">sir123 </td>
				<td width="50%">200 Cash</td>
				</tr>
				<tr>
				<td width="50%">Play</td>
				<td width="50%">150 Cash</td>
				</tr>
				<tr>
				<td width="50%">Gangnum</td>
				<td width="50%">135 Cash</td>
				</tr>
				<tr>
				<td width="50%">Jhony</td>
				<td width="50%">115 Cash</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			<tr>
			<td width="50%">comfykaff</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Gorgeousgar </td>
			<td width="50%">10 cash</td>			
			</tr>
			<tr>
			<td width="50%">djlynch27</td>
		    <td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Indy2013</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">sir123 </td>
			<td width="50%">10 cash</td>
			</tr>
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="20%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >"GORGEOUSGAR"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_fri.png"  alt="friday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_sat.png" alt="saturay promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_tues.png" alt="tuesday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle2.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe2.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
     <p class="pa"><strong>Ingredients :</strong></p><br><br>
    <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li> 3 tbsp blueberry crush</li>
    <li> 1 cup roughly chopped white chocolate</li>
	
    <li> <sup>1</sup>/<sub>4</sub> cup milk</li>
    <li> 1 tbsp powdered sugar</li>
    <li> 1 <sup>1</sup>/<sub>2</sub> cups beaten whipped cream</li>
    <li> <sup>1</sup>/<sub>4</sub> tsp vanilla essence</li>
    <li> <sup>1</sup>/<sub>2</sub> tsp lemon juice</li>
   
    </ul>
	<br>
	<p class="pa"><strong>To Garnish :</strong></p><br><br>
	 <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
	 <li>2 chocolate fans</li>
	 </ul><br>
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">Method :</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
Combine the chocolate and milk in a microwave-safe bowl and microwave on high for 30 seconds. Remove; mix well until no lumps remain.<br><br> 

Strain the mixture using a sieve and keep aside.<br><br>

Combine the sugar and the beaten whipped cream in a deep bowl and fold gently.<br><br>

Add the chocolate-milk mixture and fold gently.<br><br>

Add the vanilla essence, lemon juice and blueberry crush and fold gently.<br><br> 

Pour equal quantities of the mixture into 4 individual bowls/glasses and refrigerate for 2 to 3 hours or till the mousse sets.<br><br>

Garnished with chocolate fans and serve chilled.

</p>

   </p>
   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
   
  
		 

   
   </table>
        </div>
		
       <div>
	      <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:0px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>AUGUST News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:999;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title3.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px">Dear Player,<br/>
    <br/>Warm Greetings from Bingo Crush!</br><br/>

We hope that your experience with Bingo Crush has been enjoyable. We are overwhelmed with your enthusiastic participation and feel proud to have lots of winners in our space in this short term. This month we have scheduled few interesting games like free bingo, fixed pots, and new slots games along with loads of exciting new promotions. We assure you the best online bingo with the best offers at all times. <br /><br />
To get you started, we have a free Fiver (&#163;5) waiting for you. Log in now and free &#163;5 bonus will be credited to your account instantly.<br /><br />Happy gaming!<a href="http://bingocrush.co.uk">Login now</a>.</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	

	
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">Gangnam</td>
				<td width="50%">250 Cash</td>
				</tr>
				<tr>
				<td width="50%">Play</td>
				<td width="50%">100 Cash</td>
				</tr>
				<tr>
				<td width="50%">Foxycat1</td>
				<td width="50%">50 Cash</td>
				</tr>
				<tr>
				<td width="50%">Jennyblue</td>
				<td width="50%">30 Cash</td>
				</tr>
				<tr>
				<td width="50%">Mutley61</td>
				<td width="50%">30 Cash</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			<tr>
			<td width="50%">capppac</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">sallieb</td>
			<td width="50%">10 cash</td>			
			</tr>
			<tr>
			<td width="50%">bruno12</td>
		    <td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">jennyblue</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Bingoty</td>
			<td width="50%">10 cash</td>
			</tr>
			
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="47%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >"BINGOLITE"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_thu3.jpg"  alt="thursday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_fri3.jpg" alt="Friday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_sat3.jpg " alt="saturay promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle3.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe3.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
   Four Cheese Pizza.<br>
   <br>
   <strong>Ingredients:</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>1  Wholemeal Pizza Base</li>
     <li>1 Cup Pizza Sauce</li>
     <li>butter or oil for greasing</li>
	 </ul>
	 <br>

    <p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold">For the topping: </p><br>
	<ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li> 2 cups chopped leeks  </li>
    <li> 3 cloves garlic ,chopped</li>
    <li> a pinch of nutmeg powder</li>
    <li> 1 tbsp butter or oil<br>
    <!--<li> <sup>3</sup>/<sub>4</sub> cup (180ml) dry white wine</li>-->
    <li> salt to taste</li>
    
    </ul>
     <br>
    <p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold">For baking:</p><br>
	<ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li> 1/4 cup grated pepper cheese  </li>
    <li> 1/4 cup grated garlic cheese</li>
    <li> 1/4 cup grated paprika cheese</li>
    <li> 1/4 cup grated mozzrella cheese  <br>
    </ul>
    
	<br>
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal"><b>Method :</b>
<br /><br /><b>For topping :</b><br />
</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
Heat the butter in a pan.<br><br> 

Add the leeks, garlic, nutmeg and salt and stir-fry for 3 to 4 minutes. Keep aside.<br><br>

<font style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold" >For Pizza :</font><br><br>

Place one pizza base on a greased baking tray.<br><br>

Spread half the pizza sauce and half the topping on it.<br><br> 

Divide each of the cheeses into 2 equal portions and place them on the pizza in such a way that each type of cheese occupies one quarter of the pizza.<br><br>

Bake in a pre-heated oven at 200&deg;C (400&deg;F) for 15 to 20 minutes or till the base is evenly browned.<br><br>

Repeat with the remaining ingredients to make another pizza.<br><br>

Serve hot.

   </p>
   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
   
  
		 

   
   </table>
	   </div>
	   <div>
	     <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:1px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>Mid August Newsletter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:999;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title4.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px; padding:5px;" >Dear Player,<br/>
    <br/>Greetings from Bingo Crush!</br><br/>
    We appreciate your participation in BINGO CRUSH and encourage you to remain part of our community. 
    Join us this August for special "Bingo crush Balloon Fiesta" and great promotions along with newly launched slots. 
    This could be your Lucky Month, So Buy your cards and cross your fingers to win amazing CASH PRIZE and BONUS.
     Cheers for all our Winners ! <br/><br/>
     To get you started, we have a free Fiver (&#163;5) waiting for you.</p>
        <a href="http://bingocrush.co.uk/" target="_blank" style="text-decoration:none;">
        <div style="border-radius:10px; background-color:#390; border:#3C0 solid 2px; margin-left:5px; padding:5px; width:110px; 
        font-family:Arial, Helvetica, sans-serif; font-weight:bold; text-align:center; color:#FFF;"> LOGIN NOW</div></a> 
        <p style="font-family:Arial, Helvetica,sans-serif;font-size:12px; padding:5px;">Free &#163;5 bonus will be credited to your account instantly.
        <br/> <br/>Happy Gaming!</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	

	
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">Toffeeo123</td>
				<td width="50%">25 Cash</td>
				</tr>
				<tr>
				<td width="50%">Bingobingo</td>
				<td width="50%">25 Cash</td>
				</tr>
				<tr>
				<td width="50%">win4epls</td>
				<td width="50%">15 Cash</td>
				</tr>
				<tr>
				<td width="50%">Franquiro</td>
				<td width="50%">15 Cash</td>
				</tr>
				<tr>
				<td width="50%">Kel19771</td>
				<td width="50%">15 Cash</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			<tr>
			<td width="50%">Dexter</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Play</td>
			<td width="50%">10 cash</td>			
			</tr>
			<tr>
			<td width="50%">Sir123</td>
		    <td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Jhony</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Bingolovers</td>
			<td width="50%">10 cash</td>
			</tr>
			
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="20%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" style="text-transform:uppercase;" >"Play"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 Cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_sun4.jpg"  alt="Sunday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_mon4.jpg" alt="Monday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_tue4.jpg " alt="Tuesday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle4.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe4.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
   EASY TOMATO SOUP<br>
   <br>
   <strong>Ingredients:</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>1 Onion</li>
     <li>1 carrot</li>
     <li>1 potato</li>
     <li>1 can or 400 gms chopped tomatoes </li>
     <li>500ml water</li>
     <li>1 veg stock cube </li>
     <li>1/2 x 5ml spoon dried chilli flakes</li>
     <li>1 x 15ml tomato puree</li>
     <li>1 Tbsp Butter</li>
     <li>Salt to taste</li>
	 </ul>
	 <br>

    <p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold">Method: </p><br><br>
	<ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li>Slice the onion, carrot and potato.  </li>
    <li>Heat butter in a sauce pan and add all the ingredients.</li>
    <li>Saute everything together, add water and bring it to boil.</li>
    <li>Add the chopped tomatoes, stock, tomato puree, salt and dried chilli flakes.</li>
    <!--<li> <sup>3</sup>/<sub>4</sub> cup (180ml) dry white wine</li>-->
    <li>Simmer it for 20 minutes and remove from the flame.</li>
    <li>Pour the mixture into the liquidiser and blend until smooth.</li>
    <li>Serve hot.</li>
    
    </ul>
    
   <!-- <p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:bold">For baking:</p><br><br>
	<ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
    <li> 1/4 cup grated pepper cheese  </li>
    <li> 1/4 cup grated garlic cheese</li>
    <li> 1/4 cup grated paprika cheese</li>
    <li> 1/4 cup grated mozzrella cheese  <br>
    <!--<li> <sup>3</sup>/<sub>4</sub> cup (180ml) dry white wine</li>-->
    </ul>
    
	<br>

   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
   </table>
	</div>
	<!-- september-->
		<div>
	  <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:1px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>September News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:999;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title5.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px">Dear Player,<br/>
    <br/>Welcome to our September Month Newsletter. </br><br/>

This month we have lots of interesting weekly promotions along with an amazing Bingo Crush Boat Tourney. So keep an eye out in your email this month for further details and win big.<br /><br /> Hearty Congratulations to all our August month winners! We value your relationship with Bingo Crush and we look forward for many more Winners this month.
<br /><br />
So what are you waiting for? Login and Be the next one to win!<br /><br />

Happy gaming!<a href="http://bingocrush.co.uk">Login now</a>.</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	

	
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">Fruityfruity</td>
				<td width="50%">250 Cash</td>
				</tr>
				<tr>
				<td width="50%">Play</td>
				<td width="50%">100 Cash</td>
				</tr>
				<tr>
				<td width="50%">Gangnum</td>
				<td width="50%">50 Cash</td>
				</tr>
				<tr>
				<td width="50%">Comfykaff</td>
				<td width="50%">35 Cash</td>
				</tr>
				<tr>
				<td width="50%">Royaltyxx</td>
				<td width="50%">20 Cash</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			<tr>
			<td width="50%">Dexter</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Play</td>
			<td width="50%">10 cash</td>			
			</tr>
			<tr>
			<td width="50%">Supermumof9xx</td>
		    <td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Sanna1975</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">Kelstar</td>
			<td width="50%">10 cash</td>
			</tr>
			
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="47%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >" Fruityfruity"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_mon5.jpg"  alt="monday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_tue5.jpg" alt="tuesday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/promotions"><img src="http://bingocrush.co.uk/images/bingocrush/news_sun5.jpg " alt="sunday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle5.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe5.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
   Banana and Honey Muffins<br>
   <br>
   <strong>Ingredients:</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>1 cup wholemeal self-raising flour</li>
     <li>1 cup self-raising flour</li>
     <li>2 teaspoons baking powder</li>
	 <li>1 teaspoon ground cinnamon</li>
	 <li><sup>1</sup>/<sub>4</sub> cup raw sugar</li>
	 <li><sup>1</sup>/<sub>2</sub> cup desiccated coconut</li>
	 <li>1 cup mashed banana</li>
	 <li><sup>1</sup>/<sub>3</sub> cup honey</li>
	 <li><sup>1</sup>/<sub>4</sub> cup extra-light olive oil</li>
	 <li>2 eggs, lightly whisked</li>
	 <li><sup>1</sup>/<sub>3</sub> cup honey yoghurt</li>
	 <li><sup>1</sup>/<sub>4</sub> cup shredded coconut, toasted</li>
	 </ul>
	 <br>

   
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal"><b>Method :</b>
<br />
</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
Preheat oven to 200&deg;C. Lightly grease a 12-hole <sup>1</sup>/<sub>3</sub>-cup capacity muffin pan.<br><br>

Sift flours, baking powder and cinnamon into a bowl. Stir in sugar and desiccated coconut. Make a well in the center.<br><br> 

Whisk banana, <sup>1</sup>/<sub>4</sub> cup honey, oil, egg and yoghurt in a jug. Pour into well. Gently fold until just combined. Three-quarter fill muffin holes with mixture. Bake for 15 to 20 minutes or until a skewer inserted into the centre comes out clean. Stand for 5 minutes in pan. Turn onto a wire rack.<br><br>

Heat remaining honey in microwave on HIGH (100%) for 20 seconds. Brush tops of warm muffins with warm honey. Sprinkle with toasted coconut. <br /><br />
Serve warm.


   </p>
   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
   </table>
    </div>
<!-- september mid month-->
	<div>
     <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:1px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>September mid News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:999;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title6.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px">Dear Player,<br/><br/>

Warm Greetings from Bingo Crush!<br /><br/>

Stepping into the second half of September with an excitement of announcing our great winners so far!
<br /><br />
To get you started, we have a free Fiver (&#163;5) waiting for you.</p>
<a style="text-decoration:none;" target="_blank" href="http://bingocrush.co.uk/">
<div style="border-radius:10px; background-color:#390; border:#3C0 solid 2px; margin-left:5px; padding:5px; width:110px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; text-align:center; color:#FFF;"> LOGIN NOW</div>
</a><p style="font-family:Arial, Helvetica,sans-serif;font-size:12px; padding:5px;">
Free &#163;5 bonus will be credited to your account instantly.         
<br />
<br /> Play around to win the promotional winning rewards and 
star awards along with an exciting offers in the upcoming days.Bingo crush would like to hear what you have to say! So if you have any comments or suggestions, please drop us a line at <a href="mailto:support@bingocrush.co.uk">support@bingocrush.co.uk</a> Look out for our next big promotion coming up soon.</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
			<td width="50%">sir123</td>
			<td width="50%">260 cash</td>
			</tr>
			<tr>
			<td width="50%">DEXTER</td>
			<td width="50%">230 cash</td>			
			</tr>
			<tr>
			<td width="50%">gangnam</td>
		    <td width="50%">175 cash</td>
			</tr>
			<tr>
			<td width="50%">play4fun</td>
			<td width="50%">50 cash</td>
			</tr>
			<tr>
			<td width="50%">player19581</td>
			<td width="50%">10 cash</td>
			</tr>			
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			 <tr>
				<td width="50%">chick76</td>
				<td width="50%">10 Bonus</td>
				</tr>
				<tr>
				<td width="50%">player19581</td>
				<td width="50%">10 Bonus</td>
				</tr>
				<tr>
				<td width="50%">gangnam</td>
				<td width="50%">10 Bonus</td>
				</tr>
				<tr>
				<td width="50%">jhony</td>
				<td width="50%">10 Bonus</td>
				</tr>
				<tr>
				<td width="50%">fruityfruity</td>
				<td width="50%">10 Bonus</td>
				</tr>
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="20%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >"DEXTER"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_mon5.jpg"  alt="monday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_tue5.jpg" alt="tuesday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_sun5.jpg" alt="sunday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle6.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe6.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
   BLT Sandwich.<br>
   <br>
   <strong>Ingredients :</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>250g lean bacon, rind removed</li>
     <li>4 tbs good-quality mayonnaise</li>
	 <li>2 tsp Dijon mustard</li>
	 <li>8 slices organic grain bread</li>
	 <li>175g iceberg lettuce, shredded</li>
	 <li>2 large tomatoes, sliced</li>
	 <li>1 large avocado, sliced</li>
	 <li>chips, to serve</li>
	 </ul>
	 <br>

   
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">Method :</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
Grill the bacon until crisp, then transfer to a plate lined with paper towel to drain.<br><br> 

Combine the mayonnaise and mustard in a bowl. Toast the bread and spread with half the mayonnaise mixture. Divide the lettuce between 4 slices of bread. Add bacon, tomato and avocado, drizzle with remaining mayonnaise, then top with remaining bread. Secure with a cocktail stick, or wrap in greaseproof paper.<br><br>

Serve the BLT with kettle chips warmed in the oven for 5 minutes.

</p>

   </p>
   </td>
   </tr>    
    </table>
   </td>
   </tr>
  </table>
	</div>
	
	
	<div>
	    <table width="600" cellpadding="0" cellspacing="0" style="margin:auto; border:1px #f2f2f2 solid;background-color:#ffffff">
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;color:red">
  <tr><td>October News Letter</td></tr>
  </table>
  </tr></td>
  <tr height="10"><td></td></tr>
  <tr><td>
  <table align="center" cellpadding="0" cellspacing="0" width="481" border="0" style="font-family:Arial, Helvetica, sans-serif;z-index:999;border-collapse:collapse;border:2px solid #FF0000;">
    <tr>
	  <td colspan="2">
	  <table width="100%" cellpadding="0" cellspacing="0">
	  <tr>
	   <td width="30%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/logonewsletter.png" alt="Bingo Crush Logo"/></a></td>
	   <td width="70%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/top_title7.jpg" alt="Bingo Crush Newsletter"/></a></td>
	  </tr>
	  </table>
	  </td>
	  
	</tr>
		<tr>
	<td colspan="2" align="center"><hr style="color:#FF0000" width="450"/></td>
	</tr>
	<tr><td colspan="2">
	<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px">Dear Player,<br/><br/>

Warm greetings from Bingo Crush!<br /><br/>

Join us this spooky October month and take advantage of all our special Halloween Promotions and Weekly promotions to win huge Cash and Bonus. Lots of interesting and fun filled contest waits for you, so keep an eye on our website and enjoy the treat.
<br /><br />
Special Congratulations to all our September Month Promotional Winners and Star Winners. <br/><br/>
Don't worry if you are not one among them, this month would be your Lucky month and you could be our "Special Winner". So, Login now and Buy your cards to maximize your chance of winning.  To get you started, we have a free Fiver (&#163;5) waiting for you.</p>


<a style="text-decoration:none;" target="_blank" href="http://bingocrush.co.uk/">
<div style="border-radius:10px; background-color:#390; border:#3C0 solid 2px; margin-left:5px; padding:5px; width:110px; font-family:Arial, Helvetica, sans-serif; font-weight:bold; text-align:center; color:#FFF;"> LOGIN NOW</div>
</a>
<p style="font-family:Arial, Helvetica,sans-serif;font-size:12px; padding:5px;">
Free &#163;5 bonus will be credited to your account instantly.       
</p>
	</td></tr>
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	<tr>
	<td width="50%" >
	 <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Promotional Winners</font>
	 </td>
	<td>
	<font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Lucky Winners</font>
	</td>
	</tr>
	
	<tr>
	<td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td>
	</tr>
	
	<tr>
	<td colspan="2">
			<table width="100%" cellpadding="0" cellspacing="0">
			<tr>
			<td width="48%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px;">
				<tr>
				<td width="50%">nik</td>
				<td width="50%">310 Cash</td>
				</tr>
				<tr>
				<td width="50%">play4fun</td>
				<td width="50%">286 Cash</td>
				</tr>
				<tr>
				<td width="50%">kaleemac</td>
				<td width="50%">188 Cash</td>
				</tr>
				<tr>
				<td width="50%">bingobingo</td>
				<td width="50%">100 Cash</td>
				</tr>
				<tr>
				<td width="50%">gangnam</td>
				<td width="50%">100 Cash</td>
				</tr>
				</table>
	
	       </td>
	       <td width="10%"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></td>
	      <td width="45%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px" >
			 <tr>
			<td width="50%">carol49</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">storm1</td>
			<td width="50%">10 cash</td>			
			</tr>
			<tr>
			<td width="50%">vidalia222</td>
		    <td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">meat10</td>
			<td width="50%">10 cash</td>
			</tr>
			<tr>
			<td width="50%">karenhyde02</td>
			<td width="50%">10 cash</td>
			</tr>			
			</table></td>
			</tr>
			</table>
	    	</td>
			
			
	
   </tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
   <tr>
   <td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:4px;" border="0">
           <tr style="font-family:Arial, Helvetica, sans-serif;font-size:16px;padding-left:0px; font-weight:bold;color:#FF0000">
		   <td width="20%">Player Of The Month</td>
		   <td width="1%"></td>
		   <td width="55%">Deal Of The Week</td>
		   </tr>
			<tr>
			<td width="20%">
				<table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px;padding-left:14px; font-weight:bold">
				<tr>
				<td width="50%">Congratulations<br />
				               <font color="#1e7be2" >"play4fun"</font> on winning <br />
							   <font color="#1e7be2">&#163;25 cash</font></td>
				<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/avtar.png" alt="avatar"/></a></td>
				</tr>
				</table>
	
	       </td>
	       <td width="1%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/V_line.png"/></a></td>
	      <td width="55%">
			 <table width="100%" style="font-family:Arial, Helvetica, sans-serif;font-size:12px; font-weight:bold" >
			<tr>
			<td width="50%"><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/50.png" alt="50%"/></a></td>
			<td width="50%">Make a Deposit and get 50% additional bonus from apart from your regulars </td>
			</tr>
			</table></td>
			</tr>
			</table>
			
			
   
   </td>
   </tr>
    
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
    <tr>
   <td colspan="2">
   <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Up Coming Promotions</font>
   </td></tr>
   <tr height="5"><td></td></tr>
   <tr><td colspan="2">
   <table width="100%" cellpadding="0" cellspacing="0">
   <tr>
   <td width="13"></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_sun7.jpg"  alt="monday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_tue7.jpg" alt="tuesday promotion"/></a></td>
   <td><a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/news_thu7.jpg" alt="sunday promotion"/></a></td>
  
   </tr>
    </table>
   </td></tr>
   <tr>
   <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/puzzle7.jpg"  alt="Puzzle"/></a>
   </td>
   </tr>
    <tr><td colspan="2" align="center"><hr style="color:#f2f2f2" width="450"/></td></tr>
     <tr>
   <td colspan="2">
    <font style="color:#FF0000;font-size:14px;font-weight:bold">&nbsp;&nbsp;Recipe Of The Week</font>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <a href="http://bingocrush.co.uk/"><img src="http://bingocrush.co.uk/images/bingocrush/recipe7.jpg"  alt="Recipe"/></a>
   </td>
   </tr>
   
   <tr>
   <td colspan="2">
   <p style="color:#000000;font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
  The Tomato Sauce.<br>
   <br>
   <strong>Ingredients :</strong><br><br>
     <ul style="font-weight:normal;margin:-20px 0px 0px -25px;line-height:20px;font-size:12px;">
     <li>2 cups blanched , deseeded and chopped</li>
     <li>tomato</li>
	 <li>2 tbsp oil</li>
	 <li>1 bayleaf</li>
	 <li>6 whole peppercorns</li>
	 <li><sup>1</sup>/<sub>4</sub> cup finely chopped capsicum</li>
	 <li>1 tsp dried oregano</li>
	 <li><sup>1</sup>/<sub>4</sub> cup tomato puree</li>
	 <li><sup>1</sup>/<sub>4</sub> cup tomato ketchup</li>
	 <li>1 tsp sugar</li>
	 <li>salt to taste</li>
	 </ul>
	 <br>
   </p>
<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">Method :</p>

<p style="font-size:12px;font-family:Arial, Helvetica, sans-serif;font-weight:normal">
Heat the oil in a broad non-stick pan, add the bayleaf and peppercorns and saute on a medium flame for a few seconds.<br><br> 

Add the capsicum and saute for a few more minutes.<br><br>

Add the tomatoes and 1/2 cup of water and simmer on a medium flame for 5 to 7 minutes, while stirring occasionally.<br><br>
Add the oregano, tomato puree, tomato ketchup, sugar and salt, mix well and cook for 2 to 3 minutes, while stirring occasionally. Keep aside.

</p>

   </p>
   </td>
   </tr>
   
    
    </table>
   </td>
   </tr>
  </table>
	</div>
	
	
	</div>
	</div>
<!--</body>
</html>-->