<div id="ttwidget-docs" style=" border:0px" >
  <div style="display:none">
    <ul>
      <li><a href="#demo"><span></span></a></li>
      <li><a href="#source"><span></span></a></li>
    </ul>
  </div>
  <div class="aboutus_div">
       <div class="TTBingogameName TTBingoBtnmargt">Referral </div><!--class="ttcolactive"-->
	   
    <div style="padding:10px">
    <?php 
    if($this->url)
    {
    	?>
    	<p style="font-weight:bold;font-size:18px;line-height:30px;color:#8C0000">Your Referral URL : <?=$this->url ?></p>
    	<br/>
    	<?php
    }
    ?>
     <p style="font-weight:bold;line-height:30px;">Bingo is always more fun when played among friends and relatives.  So why wait, Introduce your friends now to Bingo Crush and treat yourself with free cash. It is very simple, all you have to do is, enter the email addresses of your friends in the below form and click on submit, an invitation will be sent to your friends. Once your friend registers & activates his/her account, you get:</p>
      <ol class="options-list">
        <li><a href="#g1">a) An instant &#163;2 will be credited to your account. 
         
          
        
        </a></li>
        <li><a href="#g2">b) Once your friend deposits, you get a straight 30% of their deposit credited as cash in to your account instantly.
          
        </a></li>
        
      </ol>
	  
	  <p style="font-weight:bold;line-height:30px;">This offer is valid for all his/her deposits for the first 30 days from the date of his/her first deposit.</p>
	  		
	  <div style="font-weight:bold;line-height:30px;">Rules</div>

        <ol class="options-list">
        <li><a href="#g1">1) There is a limit of 20 referrals per month. 
         
          
        
        </a></li>
        <li><a href="#g2">2) A referrer needs to be a funded player for him/her to be eligible for the referral bonus.
          <!--<img src="/images/bingocrush/egg2.png"  alt="Bingo" style="float:right;margin-top:-100px;"/>-->
        </a></li>
        
      </ol>

<?php 
echo $this->form;
?>
    </div>
    
   
  </div>
      </ul>
    
 
   
   
   
 
</div>

