<div class="zenfox-content">
<div class="heading1">
	Contact Us
</div>
<!--style>
.address {
list-style-image:none;
list-style-position:outside;
list-style-type:none;
margin:0;
padding:0;
}

.address p
{
color: #737d7d;
background-color: #e6f0f0;
background-image: none;
background-repeat: repeat;
background-attachment: scroll;
background-position: 0pt 0pt;
background-clip: border-box;
background-origin: padding-box;
background-size: auto auto;
border-top-width: 1px;
border-right-width-value: 1px;
border-right-width-ltr-source: physical;
border-right-width-rtl-source: physical;
border-bottom-width: 1px;
border-left-width-value: 1px;
border-left-width-ltr-source: physical;
border-left-width-rtl-source: physical;
border-top-style: solid;
border-right-style-value: solid;
border-right-style-ltr-source: physical;
border-right-style-rtl-source: physical;
border-bottom-style: solid;
border-left-style-value: solid;
border-left-style-ltr-source: physical;
border-left-style-rtl-source: physical;
border-top-color: #cccccc;
border-right-color-value: #cccccc;
border-right-color-ltr-source: physical;
border-right-color-rtl-source: physical;
border-bottom-color: #cccccc;
border-left-color-value: #cccccc;
border-left-color-ltr-source: physical;
border-left-color-rtl-source: physical;
margin-bottom: 20px;
overflow-x: hidden;
overflow-y: hidden;
padding-top: 10px;
padding-right: 10px;
padding-bottom: 10px;
padding-left: 10px;
border-top-left-radius: 10px;
border-top-right-radius: 10px;
border-bottom-right-radius: 10px;
border-bottom-left-radius: 10px;
text-shadow: #ffffff;
}
</style-->
<div class="address">
<div class="heading3"></div>
<p>
<?php
$address = split(",",$this->companyAddress);
foreach ($address as $addr)
{
	print $addr.","."<br>";
}
?>
Fortuity Infotech Pvt. Ltd.<br>
support@nationalrummy.com
</p>
</div>
