<div class="zenfox-content">
<div class="heading2">Introduction</div> 

<p>

	This user agreement (the &quot;Agreement&quot;) is an agreement between you (the &quot;User&quot;, &quot;you&quot; and &quot;your&quot;) and <?=$this->operationsCompanyName?> (the &quot;Company&quot;,&quot;the Operator&quot;, &quot;us&quot;, &quot;we&quot; and &quot;our&quot;) which governs your use of the <?=$this->frontendName?>&#39;s services (&quot;Services&quot;) through their website (&quot;the Website&quot; or &quot;the site&quot;). Your use of the services provided by <?=$this->frontendName?> is subject to these Terms and Conditions (&quot;Terms&quot;).

	<p>If any of these Terms is determined to be unlawful, invalid, void, voidable or unenforceable for any reason by any judicial or quasi - judicial body in <?=$this->operationsJurisdiction?>, it will not affect the validity and enforceability of the remaining Terms.
	</p>

<p>
Our failure or delay to act or exercise any right or remedy with respect to a breach of any of these Terms by you does not waive our rights to act with respect to any prior, concurrent, subsequent or similar breaches.
</p>

<p>
If a competition or tournament is organized by us on the Website, it shall be governed by these Terms and any supplementary terms and conditions which may be specifically applied for a competition or tournament.
</p>

<p>
If you do not agree to the following Terms or any future alterations or modifications to these Terms you may discontinue use of the Website and any Services offered by it. 
</p>

</p>
<div class="heading2">General Rules</div> 
<p>
These are the general terms and conditions associated with using the website and services offered by <?=$this->frontendName?> (also refered as <?=$this->frontendShortName?>) and they apply to all the games and activities provided by the same. Specific game rules are detailed in the relevant sections. </p>
<ol>
<li>By opening an account with <?=$this->frontendName?>, you confirm that you have read the terms of service, you understand all the terms and you agree to follow them.</li>
<li>In case of any confusion in the interpretation of rules because of minor differences in meaning from translating to other languages, the English interpretation of the rules prevails.</li>
<li>It is your responsibility to read, know the rules and to abide by them. </li>
<li>The terms and conditions contained herein may be amended/modified/updated only by <?=$this->frontendName?>. These ammendments will come into effect immediately upon posting and it is your sole responsibility to update yourself on the Terms of Service every time you play. </li>
<li>By opening an account with <?=$this->frontendShortName?> you acknowledge that you are using the services of the same at your own discretion and risk. You ascertain that you do not consider the game, the site or any other content on the same to be offensive, objectionable, unfair or indecent. </li>
<li>Accepting any winnings from <?=$this->frontendShortName?> automatically allows the site to use your name for advertising without additional compensation to you. </li>
<li><?=$this->frontendShortName?> can add/remove/modify any of the games or other content on the site at their own discretion, at any point of time. </li> 
</ol>


<div class="heading2">Restrictions on Users</div> 
<ol>
<li>The services of <?=$this->frontendShortName?> are meant for individuals who are above 18 or the legal age in your jurisdiction </li>
<li>Participation in the games is open only to residents of legal jurisdictions. By registering on <?=$this->frontendShortName?> and using its services, you acknowledge and ascertain that you are a resident of a jurisdiction where such activity is legal. </li>
<li>You may only create one account to access the site with and to play games with. Failure to comply with the same can result in cancellation of any bets, reduction of betting limits, suspension or termination of one or all the accounts held by you.  </li>
</ol>


<div class="heading2">Player Responsibilities</div> 
<ol>
<li>By registering to <?=$this->frontendShortName?> you acknowledge that the site is meant for entertainment only and not for professional use and you would abide by the same.  </li>
<li>You will play on the site on your own behalf and not on behalf of any other person or entity (legal or not).</li>
<li>You will provide true, complete and accurate information about yourself to the site. You will update all personal and contact information on the site as applicable immediately.</li>
<li>You are completely responsible for any chat, posts, content or communication that you post on the site. </li>
<li>You are completely responsible for reporting and accounting for any taxes applicable to you under the relevant laws of your jurisdiction for any winnings you may receive from <?=$this->frontendShortName?>. </li>
<li>You acknowledge and ascertain that all money deposited by you into your account on <?=$this->frontendShortName?> is not tainted with any illegality and specifically does not originate from an illegal activity or source. </li>
<li>You shall not be involved in any fraudulent, collusive, fixing or other unlawful activity in relation to Your or third parties&#39; participation in any of the Games and shall not use any software-assisted methods or techniques or hardware devices for Your participation in any of the Games</li>
<li>It is your sole responsibility to securely keep your username and password safe. <?=$this->frontendShortName?> is not responsible if the player forgets, misplaces,loses the username and/or password or is otherwise unable to enter their website to use their services. <?=$this->frontendShortName?> is not obligated to store or restore any username and/or passwords to any user.  </li>
<li>We recommend that you keep your username and password secret from others. It is your responsibility to ensure others including spouse, children, parents, friends or other family members do not use your account to play with the same. <?=$this->frontendShortName?> shall not be responsible for any abuse to the account done by a third party. </li>
<li>It is your responsibility to ensure that there is no abuse of the site through your account or by you off the site. Any abuse of the site, its contents can result in suspension or termination of the account. </li>
<li>In case of any issue faced with the service at any point of time, you need to official raise a complaint within 14 days in writing for it to be deemed a valid complaint.  </li>
</ol>
<div class="heading2">Content Restrictions</div> 
<p>Users are responsible for their own actions, content, posts, chats and other forms of communication. You agree not to do any of the following: 
<ol>
<li>Post, distribute, or otherwise make available or transmit any data, text, message, or computer file that we deem to be 
	<ol>
	<li>defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking</li>
	<li>bigoted, hateful, racially offensive or offensive to certain communities</li>
	<li>vulgar, obscene, or sexually explicit (language or images) </li>
	<li> encouraging or advocating illegal activity or the discussion of illegal activities with the intent to commit them </li>	
	</ol>
</li>
<li> Post, distribute, or otherwise make available or transmit any data, text, message, computer file, or other material that infringes and/or violates any right of a third party or any domestic or international law, rule, or regulation, including but not restricted to
	<ol> 
	<li>copyright, patent, trademark, or other proprietary rights </li>
	<li>right of privacy (specifically, you must not distribute another person&#39;s personal information of any kind without their express permission) or publicity </li>
	<li>any confidentiality obligation</li>
	</ol>
</li>
<li> Advertise or sell any products, services or otherwise (whether or not for profit), or solicit others or use any Forum for commercial purposes of any kind </li>
<li> Post, distribute, or otherwise make available or transmit any software or other computer files that contain a virus or other harmful component</li>
<li> Impersonate any person or entity or misrepresent your identity or affiliation with any person or entity</li>
<li> Engage in antisocial, disruptive, or destructive acts, including &quot;flaming,&quot; &quot;spamming,&quot; &quot;flooding,&quot; &quot;trolling,&quot; and &quot;griefing&quot; as those terms are commonly understood and used on the Internet</li>
<li> Delete any legal notices, disclaimers, or proprietary notices such as copyright or trademark symbols, or modify any logos that you do not own or have express permission to modify</li>
<li> Post, distribute, or otherwise make available or transmit material or make statements that do not generally pertain to the designated topic or theme of any Forum</li>
</ol>
<p>We reserve the right to remove any material, and if we deem appropriate, to turn over to law enforcement officials, any material, including message, e-mail, or posting, that is in violation of these Rules. We also reserve the right to remove messages, e-mails, or postings that do not pertain to the designated topic or theme of the service as determined by <?=$this->frontendShortName?>.</p>




<div class="heading2"> Game Admission</div> 
<p>The customer may participate in a game only if they have sufficient funds (bonus or real) in their account balance. No credit shall be provided by <?=$this->frontendShortName?> or the Company.</p>


<div class="heading2"> Deposit Policy</div> 
<ol>
<li>Players must be registered on the site in order to make a deposit. </li>
<li>The minimum deposit allowed into the player&#39;s account is <?echo "TaashCash"//=$this->frontendCurrency?> <?=$this->frontendMinDeposit?>. </li>
<li>Players must deposit using their own financial instruments i.e. Bank Accounts, Debit Cards, Credit Cards etc.</li>
<li>Deposits are final and once made cannot be revoked or cancelled </li>
<li>Deposits are accepted in all the methods supported by the software as listed on the deposits page. </li>
<li>$frontendShortName has the right to request for the player&#39;s address and identification proofs. Failing to receive these, the player&#39;s account may be suspended or terminated.</li>
<li>Identification is required in order to make any payments in cash to the company. The company has the rights to request any or all of the following documents with every cash payment. </li>
<ul>
<li>PAN Card Details </li>
<li>Passport Copy</li>
<li>Latest internet and/or telephone and/or power and/or utility bill (along with Rental Agreement in case of a rented house/appartment)</li>
<li>Driver&#39;s license</li>
<li>Employment identification card</li>
<li>Voter ID card</li>
<li>Bank Statements for the last three months</li>
<li>Any other address or identity proofs  </li>
</ul>
<li><?=$this->frontendShortName?> reserves the right to refuse a deposit from any player, thereby disallowing them to participate in cash tournaments</li>
</ol>

<div class="heading2"> Bonus Policy</div> 
<p>Different bonus rules and terms apply for different game categories. Whenever a Bonus is offered, detailed and specific rules will be published along with the same on the relevant page. Please refer to the relevant pages for details on bonus terms and conditions.</p>




<div class="heading2"> Banking Norms</div> 
<ol>
<li>If the player&#39;s account is unused for a period of 180 days, all the winnings in the account shall be nullified. </li>
<li>If the player&#39;s account is unused for a period of 30 months, any unused real money in the account shall be sent to the player by check at their last updated address or credited to their credit card as deemed appropriate by the management. </li>
<li>In order to avoid fradulent transactions, it is mandated that the player use only their accounts, credit/debit cards to deposit on the site. Violation of the same may require the management to either suspend or terminate the account.  </li>
<li>Withdrawals can be received through check or credited to the account from where the deposit occured or the credit card from where the deposit occured. </li>
</ol>


<div class="heading2"> Account Cancellation</div> 
<ol>
<li>Failure to comply with any of the terms laid out above may result in the termination of your account at the sole discretion of the management.  </li>
<li>Fradulent usage, wrong comments about site/company automatically provides rights to the company to provide all your personal and credit card details along with playing patterns etc. to other operators, banks, credit card companies etc. In such circumstances, the management at its own discretion may terminate the account of the player. </li>
<li>In the event that the Company believes a user of the Service is abusing or attempting to abuse a bonus or other promotion, or is likely to benefit through abuse or lack of good faith from a gambling policy adopted by the Company, then the Company may, at its sole discretion, deny, withhold or withdraw from any user any bonus or promotion, or rescind any policy with respect to that user, either temporarily or permanently, or terminate that user&#39;s access to the Services and/or block that user&#39;s account.</li>
<li>In the event that the Company believes a user has broken the Content Restrictions </li>
<li>Your account may be suspended or terminated at the sole discretion of the management under the following conditions
<ol>
<li>If you make a chargeback on any of the trasactions done by you on the site</li>
<li>If there is an alternate entity other than yourself using the account to play or use the services of <?=$this->frontendShortName?></li>
<li>If there is any attempt to cheat/defraud $frontendShortName or bypass the terms of service or the rules of any game in spirit or in letter. </li>
<li>If against the rules specified for the game, you play as a group or in concert with others</li>
<li>You fail to comply with the rules of any of the games</li>
</ol></li>
<li>In case your account is terminated/cancelled, you forego your rights to all bonuses, winnings, and deposits made into <?=$this->frontendShortName?></li>
<li>Legal action may also be considered in case of any fraudulent activity or breach of any of the terms mentioned above or the rules of any games. </li>
</ol>


<div class="heading2"> Limitation of Liability </div> 
<ol>
<li>The customer shall hold <?=$this->frontendShortName?>, its employees, officers, directors, licensees, distributors, wholesalers, affiliates, subsidiaries, advertising, promotion or other agencies, media partners, agents and retailers harmless and shall fully indemnify the same from any and all costs, expenses, liabilities and damages whatsoever that may arise as a result of customer&#39;s 
<ul>
<li>entry, use, or reuse of the Web site,</li>
<li>use of any materials at the Web site, </li>
<li>entry, use, or reuse of the Websites&#39; Server, or </li> 
<li>participation in the games. </li>
</ul>
</li>
<li>The customer understands that <?=$this->frontendShortName?> takes no responsibility whatsoever, direct or indirect, for losses that may occur to the customer when using the the services of the same. <?=$this->frontendShortName?> will not be liable in the following scenarios:
<ul>
<li>In the event of a force majeure</li>
<li>In the event of the cancellation of a game for any reason</li>
<li>Failure of <?=$this->frontendShortName?>&#39;s central computer system or any part there of, delays, losses, errors or omissions resulting from failure of any telecommunications or any other data transmission system</li>
<li>An outbreak of hostilities, riot, civil disturbance, acts of terrorism</li>
<li>The acts of government or authority (including refusal or revocation of any license or consent)</li>
<li>Fire, explosion, flood, theft, malicious damage, strike, lockout or industrial action of any kind.</li>
</ul></li>
<li><?=$this->frontendShortName?> shall not be liable for computer malfunctions nor attempts by the customer to participate in the games by methods, means or ways not intended by <?=$this->frontendShortName?>. The terms and conditions contained herein represents the complete, final and exclusive agreement between the customer and <?=$this->frontendShortName?> and supersedes and merges all prior agreements, representations and understandings between the customer and <?=$this->frontendName?>
<ul>
<li>It is each customer&#39;s responsibility to ensure that they comply with their own local laws with regard to gaming</li>
<li>All customers, without exception need to be of legal adult age or at least 18 years of age</li>
<li>We advice all customers to print this page and keep it at an easily accessible place</li>
</ul></li>
</ol>



<div class="heading2"> Notes and Disclaimers</div> 
<ol>
<li>The management at <?=$this->frontendShortName?> reserve the right to entrance on to the site and may remove or disallow any person from using the any or all services on the site including login to the site.   </li>
<li>Company Employees, their family and associated partners are not allowed to use the company&#39;s services</li>
<li>All outcomes are random and determined by the most preferred RNG algorithm - Mercennes Twister. This RNG is certified by <?=$this->certificationCompanyName?></li>
<li>The site does not promise to run all the time, accurately etc. (Indemnity clause)</li>
<li>In all cases of discrepency, server is always right</li>
<li>Any materials (documents etc.) received from the site are automatically void if they are torn, mutilated, illegible, incorrect etc. Liability of materials from the Games containing any errors is only limited to the replacement of the same</li>
<li>Any materials/documents submitted for receiving a prize become the property of <?=$this->frontendShortName?>. <?=$this->frontendShortName?> is not responsible for for lost, late, illegible, incomplete, damaged, mutilated, misdirected, or postage due mail, requests, prize claims or entries. </li>
<li>In order to keep a safe record of all transactions, Customers are encouraged to keep a printed copy of all transaction data, game rules, payment methods etc. in an easily accessible location. </li>
<li>The terms, conditions and game rules are governed by the sole discretion of the management and may be altered, removed or added to at any time. </li>
<li>The terms and conditions as stated above are final and supersede any previous agreements, representations and understandings between you and The Company with regards to play on <?=$this->frontendShortName?></li>
</ol>




</p>
</div>
