<div style="border:1px solid #CD222B;border-radius:5px;">
<div class="TTBingogameName TTBingoBtnmargt">Forgot Password ??</div>
<div><p>Please enter your user name or registered email address, We will email you a link to reset your password instantly.
</p></div>
<?php
echo $this->form;
?>
<div><p>P.S.Make sure you add "support@bingocrush.co.uk" to your contact list so that you can receive our emails directly to your inbox.</p></div>
</div>