<div class="zenfox-content">
<div  class="heading1">Game Rules</div>
	<p>
		Rummy is played with several flavors and variations. The version of rummy played in this site, Taashtime.com, is detailed below. 
	</p>
	<div  class="heading2">Types of Games</div>
		<p>
			There are commonly two types of games played on this site.
			<ul>
				<li><a href="#sitngoT">Sit n' Go Tournaments</a></li>
				<li><a href="#stakeT">Stake Tournaments</a></li>
			</ul>
			These games are played other than actual <a href="#tournaments">multi-tier tournaments</a>. Those games and their rules will be discussed in detail in the <a href="#tournaments"> tournaments </a>section.
		</p>
		<div  class="heading3" >Pot Matches</div>
		<p>
			Matches where players play until they cross a pre-set number of points are called Pot Matches. With each hand dealt, players accrue points for their deadwood (or count). When the accumulated count is above the pre-set limit, the player is eliminated. The game ends when there is only one person below the pre-set number of points (i.e. the last man standing).
		</p>
		<div  class="heading3" ><a name="sitngoT">Sit N' Go Tournaments</a></div>
		<p>
			These are typically unscheduled matches that can be played by a casual visitor. These are typically played until players cross a pre-set level of points. The last man standing (below the level of points) is the winner. Typically the pre-set point levels are 101, 201, 301, 401 and 501. As soon as a player reaches these levels, they are out of the game.
		</p>
		<p><b>Terms</b></p>
			<ul>
				<li>Players may choose to leave the room at any point of time. On doing so, they automatically forfeit the game. </li>
				<li>New players may enter a game while it is in progress. They will have to pay the entry fee and will be started off with additional points</li>
				<li>The points awarded to players joining games in progress are number of rounds x points per early drop</li>
				<li>If the points to enter the game is higher than the existing pre-set limit, players are not allowed to join the game</li>
				<li>There is no limit on the number of times a player can re-enter a game</li>
			</ul>			
		
		<p>	
			Suppose there are 4 rounds played, they are given 4 x 20 = 80 points to start them off in the game as they are joining a game already in progress. 
		</p>
		<p><b>Winnings</b></p>
		<p>All the entry fee is pooled in. The winner (last man standing) is paid a sum of the total in the pool after subtracting the management fee.</p>
		<div  class="heading3" ><a name="stakeT">Stake Tournaments</a></div>
		<p> 
			These games are typically played for a pre-set number of rounds. A round is defined as number of deals as there are number of players. If there are 4 (four) players, cards must be dealt at least 4 times and each player should get the opportunity to start the game. 
		</p>
			<p><b>Terms</b></p>
			<ul>
				<li>The number of rounds a game will go on is pre-set and displayed along with the tournament infomormation </li>
				<li>No new players may enter a game while it is in progress. </li>
				<li>No players may leave the table before the pre-set number of rounds are completed. </li>
				<li>The cost per point is also pre-determined and explicitly mentioned</li>
			</ul>
		<p>
		<p><b>Winnings</b></p>
			<p>At the end of each hand dealt, there is a winner and all the others have certain points. For each point they have, they owe the pre-determined cost per point x number of points to the winner. 
			For example, if the cost per point is INR. 0.50 and the players counts are 25, 45 and 80, then they respectively owe INR 12.50, 22.50 and 40 to the winner. All winnings are credited to the player after subtracting management fee. 
		</p>	
<div  class="heading1"><a name="tournaments">Tournaments</a></div>	
	<div  class="heading2">Types of Tournaments</a></div>
	<p>
		There are different kinds of tournaments supported in this site. The different kinds are defined below. They are not mutually exclusive. A single tournament may have many of the properties described below. 
	</p>
		<div  class="heading3" >Multi-Tier Tournaments</div>
		<p>
			Tournaments which have multiple levels before the finals are referred to as multi-tier tournaments. 
			All players start at the lowest tier and have to win in order to progress to the next tier. 
			For example, in a 5-tier tournament, everyone starts at tier 5. There are 'n' number of tables in this tier with a match on each one. The winners on each table are promoted to the next tier. 
			In order to arrive at the finals (tier 1), the player has to win matches at their assigned table in Tier 5, Tier 4, Tier 3 and Tier 2 before joining the final match at Tier 1.
		</p>
		<div  class="heading3" >Multiple Entry Tournament</div>
		<p>
			In a multiple entry tournament, a player can enter the tournament multiple times in the same tier. For example, if player A loses in his first game at tier 1, he may choose to re-enter the tournament at tier 1.
		</p>	
		<div  class="heading3" >Elimination Tournament</div>
		<p>
			In elimination tournaments, a player can participate in only one game in a tier. If they lose that game, they are eliminated from the tier. 
		</p>
		<div  class="heading3" >Double Elimination Tournament</div>
		<p>
			In a double elimination tournament, a player would have to lose twice in order to be eliminated. These types of tournaments are rare.
		</p>
		<div  class="heading3" >Lateral Entry Tournaments</div>
		<p>
			In certain tournaments, players may enter laterally i.e. at a higher tier than at which the tournament started. Typically, there is a lateral entry fee that is charged based on the tier at which the player enters. The management of the tournament decides till which tier there are lateral entries and in what quantities. 
		</p>
		<div  class="heading3" >Guaranteed Tournaments</div>
		<p>
			In guaranteed tournaments, the prize money is a guaranteed amount. This amount is pre-set before the beginning of each tournament and provided specifically in the tournament lobby.
		</p>
		<div  class="heading3" >Bonus Tournaments</div>
		<p>
			These tournaments are played using bonus money only. The winnings are also in bonus money only. If not explicitly mentioned, all tournaments are real money. 
		</p>
		<div  class="heading3" >Last Man Standing Toournaments</div>
		<p>
			Tournaments in which each match played is a pot match are last man standing tournaments.
		</p>
		
	<div  class="heading2">Tournament Entry Fees</div>
	<p>
		In order to enter any tournament, the player has to buy chips. All entrants into the tournament are allowed to purchase only a certain number of chips. A typical tournament has a tournament entry fee which is split among the contribution money, the management fee and any other fee contributing to the tournament. So a typical tournament with a INR 200 entry fee, there is an INR 25 management fee. In the lobby, it would be shown as a INR 225 entry tournament. The exact split is specified in the tournament details. 
		All the contribution money is pooled and the winners are awarded their winning amounts through this pool.
	</p>
</div>