<div class="ttinnnerpad"><h2><strong>Introduction</strong></h2>
<p>This user agreement (the "Agreement") is an agreement between you (the "User", "you" and "your") and <?php echo $this->operationsCompanyName; ?> (the "Company","the Operator", "us", "we" and "our") which governs your use of the <?php echo $this->frontendName; ?>'s services ("Services") through their website ("the Website" or "the site"). Your use of the services provided by <?php echo $this->frontendName; ?> is subject to these Terms and Conditions ("Terms").</p>
<p>If any of these Terms is determined to be unlawful, invalid, void, voidable or unenforceable for any reason by any judicial or quasi - judicial body in <?php echo $this->operationsJurisdiction; ?>, it will not affect the validity and enforceability of the remaining Terms.</p>
<p>Our failure or delay to act or exercise any right or remedy with respect to a breach of any of these Terms by you does not waive our rights to act with respect to any prior, concurrent, subsequent or similar breaches.</p>
<p>If a competition or tournament is organized by us on the Website, it shall be governed by these Terms and any supplementary terms and conditions which may be specifically applied for a competition or tournament.</p>
<p class = "bottom">If you do not agree to the following Terms or any future alterations or modifications to these Terms you may discontinue use of the Website and any Services offered by it.</p>
<p>&nbsp;</p>
<h3><strong>General Rules</strong></h3>
<p>These are the general terms and conditions associated with using the website and services offered by <?php echo $this->frontendName; ?> (also refered as <?php echo $this->frontendShortName; ?>) and they apply to all the games and activities provided by the same. Specific game rules are detailed in the relevant sections.</p>
<ul class="bullet-normal">
	<li>By opening an account with <?php echo $this->frontendName; ?>, you confirm that you have read the terms of service, you understand all the terms and you agree to follow them.</li>
	<li>In case of any confusion in the interpretation of rules because of minor differences in meaning from translating to other languages, the English interpretation of the rules prevails.</li>
	<li>It is your responsibility to read, know the rules and to abide by them.</li>
	<li>The terms and conditions contained herein may be amended/modified/updated only by <?php echo $this->frontendName; ?>. These ammendments will come into effect immediately upon posting and it is your sole responsibility to update yourself on the Terms of Service every time you play.</li>
	<li>By opening an account with <?php echo $this->frontendShortName; ?> you acknowledge that you are using the services of the same at your own discretion and risk. You ascertain that you do not consider the game, the site or any other content on the same to be offensive, objectionable, unfair or indecent. </li>
	<li>Accepting any winnings from <?php echo $this->frontendShortName; ?> automatically allows the site to use your name for advertising without additional compensation to you.</li>
	<li><?php echo $this->frontendShortName; ?> can add/remove/modify any of the games or other content on the site at their own discretion, at any point of time. </li> 
</ul> 
<h3><strong>Restrictions on Users</strong></h3>
<ul class="bullet-normal">
	<li>The services of <?php echo $this->frontendShortName; ?> are meant for individuals who are above 18 or the legal age in your jurisdiction </li>
	<li>Participation in the games is open only to residents of legal jurisdictions. By registering on <?php echo $this->frontendShortName; ?> and using its services, you acknowledge and ascertain that you are a resident of a jurisdiction where such activity is legal. </li>
	<li>You may only create one account to access the site with and to play games with. Failure to comply with the same can result in cancellation of any bets, reduction of betting limits, suspension or termination of one or all the accounts held by you.  </li>
</ul>
<h3><strong>Player Responsibilities</strong></h3>
<ul class="bullet-normal">
	<li>By registering to <?php echo $this->frontendShortName; ?> you acknowledge that the site is meant for entertainment only and not for professional use and you would abide by the same. </li>
	<li>You will play on the site on your own behalf and not on behalf of any other person or entity (legal or not).</li>
	<li>You will provide true, complete and accurate information about yourself to the site. You will update all personal and contact information on the site as applicable immediately.</li>
	<li>You are completely responsible for any chat, posts, content or communication that you post on the site. </li>
	<li>You are completely responsible for reporting and accounting for any taxes applicable to you under the relevant laws of your jurisdiction for any winnings you may receive from <?php echo $this->frontendShortName; ?>. </li>
	<li>You acknowledge and ascertain that all money deposited by you into your account on <?php echo $this->frontendShortName; ?> is not tainted with any illegality and specifically does not originate from an illegal activity or source. </li>
	<li>You shall not be involved in any fraudulent, collusive, fixing or other unlawful activity in relation to Your or third parties' participation in any of the Games and shall not use any software-assisted methods or techniques or hardware devices for Your participation in any of the Games</li>
	<li>It is your sole responsibility to securely keep your username and password safe. <?php echo $this->frontendShortName; ?> is not responsible if the player forgets, misplaces,loses the username and/or password or is otherwise unable to enter their website to use their services. <?php echo $this->frontendShortName; ?> is not obligated to store or restore any username and/or passwords to any user.  </li>
	<li>We recommend that you keep your username and password secret from others. It is your responsibility to ensure others including spouse, children, parents, friends or other family members do not use your account to play with the same. <?php echo $this->frontendShortName; ?> shall not be responsible for any abuse to the account done by a third party. </li>
	<li>It is your responsibility to ensure that there is no abuse of the site through your account or by you off the site. Any abuse of the site, its contents can result in suspension or termination of the account. </li>
	<li>In case of any issue faced with the service at any point of time, you need to official raise a complaint within 14 days in writing for it to be deemed a valid complaint.  </li>
</ul>
<h3><strong>Content Restrictions</strong></h3>
<p>Users are responsible for their own actions, content, posts, chats and other forms of communication. You agree not to do any of the following:</p>
<ul class="bullet-normal">
	<li>Post, distribute, or otherwise make available or transmit any data, text, message, or computer file that we deem to be 
		<ul class="bullet-normal-1">
			<li>defamatory, abusive, harassing, insulting, threatening, or that could be deemed to be stalking</li>
			<li>bigoted, hateful, racially offensive or offensive to certain communities</li>
			<li>vulgar, obscene, or sexually explicit (language or images) </li>
			<li> encouraging or advocating illegal activity or the discussion of illegal activities with the intent to commit them </li>
		</ul>
	</li>
	<li> Post, distribute, or otherwise make available or transmit any data, text, message, computer file, or other material that infringes and/or violates any right of a third party or any domestic or international law, rule, or regulation, including but not restricted to
		<ul class="bullet-normal-1">
			<li>copyright, patent, trademark, or other proprietary rights </li>
			<li>right of privacy (specifically, you must not distribute another person's personal information of any kind without their express permission) or publicity </li>
			<li>any confidentiality obligation</li>
		</ul>
	</li>
	<li> Advertise or sell any products, services or otherwise (whether or not for profit), or solicit others or use any Forum for commercial purposes of any kind </li>
	<li> Post, distribute, or otherwise make available or transmit any software or other computer files that contain a virus or other harmful component</li>
	<li> Impersonate any person or entity or misrepresent your identity or affiliation with any person or entity</li>
	<li> Engage in antisocial, disruptive, or destructive acts, including "flaming," "spamming," "flooding," "trolling," and "griefing" as those terms are commonly understood and used on the Internet</li>
	<li> Delete any legal notices, disclaimers, or proprietary notices such as copyright or trademark symbols, or modify any logos that you do not own or have express permission to modify</li>
	<li> Post, distribute, or otherwise make available or transmit material or make statements that do not generally pertain to the designated topic or theme of any Forum</li>
</ul>
<p class = "bottom">We reserve the right to remove any material, and if we deem appropriate, to turn over to law enforcement officials, any material, including message, e-mail, or posting, that is in violation of these Rules. We also reserve the right to remove messages, e-mails, or postings that do not pertain to the designated topic or theme of the service as determined by <?php echo $this->frontendShortName; ?>.</p>
<p>&nbsp;</p>
<h3><strong>Game Admission</strong></h3>
<p class = "bottom">The customer may participate in a game only if they have sufficient funds in their account balance. No credit shall be provided by <?php echo $this->frontendShortName; ?> or the Company. The management at <?php echo $this->frontendShortName; ?> reserve the right to entrance on to the site and may remove or disallow any person from using the any or all services on the site including login to the site.</p>
<p>&nbsp;</p>
<!-- h3><strong>Deposit Policy</strong></h3>
<ul class="bullet-normal">
	<li>Players must be registered on the site in order to make a deposit. </li>
	<li>The minimum deposit allowed into the player's account is <?php echo $this->frontendCurrency; ?> <?php echo $this->frontendMinDeposit; ?>. </li>
	<li>Players must deposit using their own financial instruments i.e. Bank Accounts, Debit Cards, Credit Cards etc.</li>
	<li>Deposits are final and once made cannot be revoked or cancelled </li>
	<li>Deposits are accepted in all the methods supported by the software as listed on the deposits page. </li>
	<li><?php echo $this->frontendShortName; ?> has the right to request for the player's address and identification proofs. Failing to receive these, the player's account may be suspended or terminated.</li>
	<li>Identification is required in order to make any payments in cash to the company. The company has the rights to request any or all of the following documents with every cash payment.
		<ul class="bullet-normal-1">
			<li>PAN Card Details </li>
			<li>Passport Copy</li>
			<li>Latest internet and/or telephone and/or power and/or utility bill (along with Rental Agreement in case of a rented house/appartment)</li>
			<li>Driver's license</li>
			<li>Employment identification card</li>
			<li>Voter ID card</li>
			<li>Bank Statements for the last three months</li>
			<li>Any other address or identity proofs  </li>
		</ul>
	</li>
	<li><?php echo $this->frontendShortName; ?> reserves the right to refuse a deposit from any player, thereby disallowing them to participate in cash tournaments</li>
</ul>
<h3><strong>Bonus Policy</strong></h3>
<p>The website offers a very generous Bonus Program. The program is created in order to encourage players to play more on the site! In order to ensure that players do not misuse the bonus provided to them, there are some guidelines for the same. </p>
<ul class="bullet-normal">
	<li>Bonus is provided to the player based on their loyalty level and the deposit they make</li>
	<li>Bonus can be converted to real money <?php echo $this->bonusConversionTimePeriod; ?>.</li>
	<li>Bonus gets converted to real money at a conversion rate of <?php echo $this->bonusConversionRate; ?> TaashBonus = 1 TaashCash </li>
	<li>At the time of withdrawing, the player's bonus amount should be less than the their real balance (post withdrawal). </li>
</ul>
<h3><strong>Refund Policy</strong></h3>
<ul class="bullet-normal">
	<li> If the player has deposited on the site and has not played any games, upon the request of the player, the amount unused shall be refunded to the player after recouping the processing fee</li>
	<li> The player must apply for a refund by raising a ticket with the customer support team on the site or by sending a mail with all appropriate details to <?php echo $this->supportEmailID; ?>.  </li>
	<li> Once the player applies for a refund and provides all the necessary details, the refund shall be processed within 2 weeks </li>
	<li> For General Withdrawal Rules, click here </li>
</ul>
<h3><strong>Banking Norms</strong></h3>
<ul class="bullet-normal">
	<li>If the player's account is unused for a period of 180 days, all the winnings in the account shall be nullified. </li>
	<li>If the player's account is unused for a period of 30 months, any unused real money in the account shall be sent to the player by check at their last updated address or credited to their credit card as deemed appropriate by the management. </li>
	<li>In order to avoid fradulent transactions, it is mandated that the player use only their accounts, credit/debit cards to deposit on the site. Violation of the same may require the management to either suspend or terminate the account.  </li>
	<li>Withdrawals can be received through check or credited to the account from where the deposit occured or the credit card from where the deposit occured. </li>
</ul-->


<h2><strong>Transaction Terms</strong></h2>
<h3><strong>General Terms</strong></h3>
<ul class="bullet-normal">
	<li> TaashCash or TaashBonus or TaashCoins has no value other than this site or other sites as specified by the management. </li>
	<li> TaashCash, TaashBonus or TaashCoins can not be traded on or off the site </li>
	<li> Neither of TaashCash, TaashBonus nor TaashCoins are a currency and should be looked at as currencies. They are simply different kinds of tokens used to play on the site. </li> 
	<li>In order to avoid fradulent transactions, it is mandated that the player use only their accounts, credit/debit cards to deposit on the site. Violation of the same may require the management to either suspend or terminate the account.  </li>
	<li> In case there are any discrepencies in between any players, with any of the service providers or with the software, all decisions made by the management are final </li>
</ul>
<h3><strong>TaashCoins Policy</strong></h3>
<ul class="bullet-normal"> 
	<li>TaashCoins are tokens provided on TaashTime to play Fun Games on the site. </li>
	<li>TaashCoins can be purchased using TaashCash. The rate shall be mentioned to you at the TaashCoins purchase page.</li>
	<li>TaashCoins can not be exchanged for TaashCash. They can only be used to play games that accept TaashCoins as the entry fee.</li>
	<li>TaashCoins can not be transferred to or exchanged with any other players for any material benefit.</li>
	<li>TaashCoins can not be traded on this site or any other.</li>
	<li>TaashCoins have no value anywhere else other than this site.</li>
	<li>In order to recharge their TaashCoins account, players can also use any schemes that award TaashCoins such as Refer a Friend.</li>
</ul>

<h3><strong>Bonus Policy</strong></h3>
<ul class="bullet-normal">
	<li> You will receive Bonus from various promotions including Joining Bonus, Purchase Bonus, Loyalty Bonus etc. and all bonus amounts shall be credited to your Bonus Due account only. The amount in the Bonus Due account shall reflect all the outstanding Bonus that you can potentially claim from the site.</li>
	<li> A portion of the Bonus Due is awarded to you every time you play a real money game. The Bonus Awarded is converted to TaashCash and can be used to play more games</li>
	<li> The amount in the Bonus Due account is know as TaashBonus. It is converted to TaashCash at the rate of 1:1 i.e. 100 TaashBonus = 100 TaashCash</li>
	<li>Prior to making a deposit, there is a cap on the amount earned from any Bonus awarded to the player of TaashCash 500. Any amount won/earned above TaashCash 500 shall be nullified. Players are expected to purchase and then win real money games.</li>
	<li> Upon making the first purchase, any amount won using the joining bonus shall be converted to the Bonus Due account. </li>
	<li> No withdrawals can be made from the Bonus Due account at any point of time</li>
</ul>
<h3><strong>Transactions Policy</strong></h3>
<ul class="bullet-normal">
	<li> Players can deposit only with Indian Credit/Debit Cards or through Indian Banks or pay by cash to our appointed Agent(s) in Cash Collection at Premises mode. </li>
	<li> All cash transactions are made towards the purchase of TaashCash only. 
	<li> The conversion of INR to TaashCash is fixed at 1:1. i.e. For every 100 INR purchase, you will receive 100 TaashCash into your account on Taashtime.</li>
	<li> Your account on the site will only get updated after we get a confirmation from our payment service provider about the receipt of the funds and verification of the same</li>
	<li>The site has the right to request for the player's address and identification proofs. Failing to receive these, the player's account may be suspended or terminated.</li>
	<li>The company has the rights to request any or all of the following documents with every  payment.
		<ul class="bullet-normal-1">
			<li>PAN Card Details </li>
			<li>Passport Copy</li>
			<li>Latest internet and/or telephone and/or power and/or utility bill (along with Rental Agreement in case of a rented house/appartment)</li>
			<li>Driver's license</li>
			<li>Employment identification card</li>
			<li>Voter ID card</li>
			<li>Bank Statements for the last three months</li>
			<li>Any other address or identity proofs  </li>
		</ul>
	</li>
	<li>The site reserves the right to refuse a deposit from any player, thereby disallowing them to participate in money game and/or tournaments</li>
</ul>
<div style="margin-left:60px;">
	<h4><strong> Cash Collection at Premises</strong></h4>
	<ul class="bullet-normal">
		<li> Player can choose to request cash collection at premises by placing an order on the site Banking page</li>
		<li>  The player is required to enter all details accurately in order to process the request</li>
		<li>  Players are requested to provide land marks to make the collection process easy</li>
		<li>  All requests made after 11 AM shall be processed the following day</li>
		<li>  Players are requested to ensure their contact number is functional and that they are reachable at said number. </li>
		<li>  The minimum amount to avail the Cash Collection at Premises service would be INR 1000</li>
		<li>  It is the responsibility of the Player to tender the exact amount to the Agent.</li>
	</ul>
	<h4><strong>Credit/Debit Cards</strong></h4>
	<ul class="bullet-normal">
		<li> Players can pay through Credit/Debit cards at any point of time during the day. </li>
		<li> Players shall be required to verify their Mobile numbers prior to making such a deposit.</li>
		<li> The minimum transaction amount for this payment method is INR 250.</li>
	</ul>
</div>
<h3><strong>Inactivity Policy</strong></h3>
<ul class="bullet-normal">
	<li> If the Bonus Due account is inactive (i.e. no amount from Bonus Due is converted to TaashCash) for a period of twenty days, you shall be intimated of the same through an email sent to the email id provided by you. If the Bonus Due account is not activated before the end of a further 10 days from the day the mail is sent to you, the amount in your Bonus Due account is set to Zero (INR 0.0/- only).</li> 
	<li> If the TaashCash account is inactive i.e. no money games played with TaashCash for 180 days, you shall be intimated of the same to the email provided by you.</li> 
	<li> Subsequently at the beginning of each month for a period of 12 months, should the TaashCash account continue to be inactive, the amount in the TaashCash account shall be depreciated by the higher of 20% of the existing TaashCash balance or TaashCash 50.</li>
	<li> At the end of these 12 months, the remaining TaashCash shall be converted to INR and this amount shall be donated to a charity/NGO as per the decision of the management.</li>
	<li> Should the player return within these 12 months, their account shall be restored with the balance as of that date. </li>
	<li> All amounts depreciated shall be considered as forfeited by the Player. </li>
	<li> Should the player wish to reinstate the amounts prior to the commencement of depreciation, the player can do so by paying a reinstatement fee of INR 250. </li>
</ul>
<h3><strong>Refund Policy</strong></h3>
<ul class="bullet-normal">
	<li> If the player has deposited on the site and has not used any TaashCash, upon the request of the player, the amount unused shall be refunded to the player after recouping the processing fee</li>
	<li> The player must apply for a refund by raising a ticket with the customer support team on the site or by sending a mail with all appropriate details to the Support Team.  </li>
	<li> Once the player applies for a refund and provides all the necessary details, the refund shall be processed within 2 weeks </li>
	<li> For General Withdrawal Rules, click <a href ="/content/withdrawterms">here!</a> </li>
</ul>
<h3><strong>Account Cancellation or Suspension</strong></h3>
<ul class="bullet-normal">
	<li>Failure to comply with any of the terms laid out above may result in the termination of your account at the sole discretion of the management.  </li>
	<li>Fradulent usage, wrong comments about site/company automatically provides rights to the company to provide all your personal and credit card details along with playing patterns etc. to other operators, banks, credit card companies etc. In such circumstances, the management at its own discretion may terminate the account of the player. </li>
	<li>In the event that the Company believes a user of the Service is abusing or attempting to abuse a bonus or other promotion, or is likely to benefit through abuse or lack of good faith from a gambling policy adopted by the Company, then the Company may, at its sole discretion, deny, withhold or withdraw from any user any bonus or promotion, or rescind any policy with respect to that user, either temporarily or permanently, or terminate that user's access to the Services and/or block that user's account.</li>
	<li>In the event that the Company believes a user has broken the Content Restrictions </li>
	<li>Your account may be suspended or terminated at the sole discretion of the management under the following conditions
		<ul class="bullet-normal-1">
			<li>If you make a chargeback on any of the trasactions done by you on the site</li>
			<li>If there is an alternate entity other than yourself using the account to play or use the services of <?php echo $this->frontendShortName; ?></li>
			<li>If there is any attempt to cheat/defraud <?php echo $this->frontendShortName; ?> or bypass the terms of service or the rules of any game in spirit or in letter. </li>
			<li>If against the rules specified for the game, you play as a group or in concert with others</li>
			<li>You fail to comply with the rules of any of the games</li>
		</ul>
	</li>
	<li>In case your account is terminated/cancelled, you forego your rights to all bonuses, winnings, and deposits made into <?php echo $this->frontendShortName; ?></li>
	<li>Legal action may also be considered in case of any fraudulent activity or breach of any of the terms mentioned above or the rules of any games. </li>
</ul>
<h3><strong>Limitation of Liability</strong></h3>
<ul class="bullet-normal">
	<li>The customer shall hold <?php echo $this->frontendShortName; ?>, its employees, officers, directors, licensees, distributors, wholesalers, affiliates, subsidiaries, advertising, promotion or other agencies, media partners, agents and retailers harmless and shall fully indemnify the same from any and all costs, expenses, liabilities and damages whatsoever that may arise as a result of customer's
		<ul class="bullet-normal-1">
			<li>entry, use, or reuse of the Web site,</li>
			<li>use of any materials at the Web site, </li>
			<li>entry, use, or reuse of the Websites' Server, or </li> 
			<li>participation in the games. </li>
		</ul>
	</li>
	<li>The customer understands that <?php echo $this->frontendShortName; ?> takes no responsibility whatsoever, direct or indirect, for losses that may occur to the customer when using the the services of the same. <?php echo $this->frontendShortName; ?> will not be liable in the following scenarios:
		<ul class="bullet-normal-1">
			<li>In the event of a force majeure</li>
			<li>In the event of the cancellation of a game for any reason</li>
			<li>Failure of <?php echo $this->frontendShortName; ?>'s central computer system or any part there of, delays, losses, errors or omissions resulting from failure of any telecommunications or any other data transmission system</li>
			<li>An outbreak of hostilities, riot, civil disturbance, acts of terrorism</li>
			<li>The acts of government or authority (including refusal or revocation of any license or consent)</li>
			<li>Fire, explosion, flood, theft, malicious damage, strike, lockout or industrial action of any kind.</li>
		</ul>
	</li>
	<li> <?php echo $this->frontendShortName; ?> shall not be liable for computer malfunctions nor attempts by the customer to participate in the games by methods, means or ways not intended by <?php echo $this->frontendShortName; ?>. The terms and conditions contained herein represents the complete, final and exclusive agreement between the customer and <?php echo $this->frontendShortName; ?> and supersedes and merges all prior agreements, representations and understandings between the customer and <?php echo $this->frontendName; ?>
		<ul class="bullet-normal-1">
			<li>It is each customer's responsibility to ensure that they comply with their own local laws with regard to gaming</li>
			<li>All customers, without exception need to be of legal adult age or at least 18 years of age</li>
			<li>We advice all customers to print this page and keep it at an easily accessible place</li>
		</ul>
	</li>
</ul>
<h3><strong>Notes and Disclaimers</strong></h3>
<ul class="bullet-normal">
	<li>The management at <?php echo $this->frontendShortName; ?> reserve the right to entrance on to the site and may remove or disallow any person from using any or all services on the site including login to the site.</li>
	<li>All outcomes are random and determined by the most preferred RNG algorithm - Mercennes Twister. 
	<!-- This RNG is certified by <?php //echo $this->certificationCompanyName; ?>
	-->
	</li>
	<li>In case of any discrepency, the server logs shall be deemed to be the ultimate truth and management reserves the right to act accordingly</li>
	<li>Any materials (documents etc.) received from the site are automatically void if they are torn, mutilated, illegible, incorrect etc. Liability of materials from the Games containing any errors is only limited to the replacement of the same</li>
	<li>Any materials/documents submitted for receiving a prize become the property of <?php echo $this->frontendShortName; ?>. <?php echo $this->frontendShortName; ?> is not responsible for for lost, late, illegible, incomplete, damaged, mutilated, misdirected, or postage due mail, requests, prize claims or entries. </li>
	<li>In order to keep a safe record of all transactions, Customers are encouraged to keep a printed copy of all transaction data, game rules, payment methods etc. in an easily accessible location. </li>
	<li>The terms, conditions and game rules are governed by the sole discretion of the management and may be altered, removed or added to at any time. </li>
	<li>The terms and conditions as stated above are final and supersede any previous agreements, representations and understandings between you and The Company with regards to play on <?php echo $this->frontendShortName; ?></li>	
</ul>
<h3 id="ipl"><strong>IPL Bonus Rules</strong></h3>
<ul class="bullet-normal">
	<li>Voting will close half an hour before the match ends.</li>
	<li>All bonuses will be credited on next day of the match.</li>
	<li>Bonus is eligible only for deposits for the day.</li>
	<li>Management decision is final.</li>
	<li>Cancellation of any offer is at management's decreation.</li>
</ul></div>
