<?php

$siteHttpUrl = "http://". $_SERVER['HTTP_HOST'];

$gameId = $this->gameId;
$sessionId = $this->sessionId;
$playerId = $this->playerId;
$flavour = $this->flavour;
$gameConfig = $siteHttpUrl . '/games/multi-player/rummy/indian-rummy/config.txt';
$logSwfFile = $siteHttpUrl . '/games/multi-player/rummy/indian-rummy/log.swf';

?>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>	 	
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
		<!--script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script-->
	</head>
	<body>
		<div id="fb-root"></div>
		<div id="flashContent">
			<h1>You need at least Flash Player 9.0 to view this page.</h1>
			<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p>
		</div>  
		<script type="text/javascript">
			//alert("Flashvars");
			//Dynamic publishing with swfObject 
			var flashvars = {};
			flashvars.game_id = '<?php echo $gameId; ?>';
			flashvars.session_id = '<?php echo $sessionId; ?>';
			flashvars.player_id = '<?php echo $playerId; ?>';
			flashvars.game_flavour = '<?php echo $flavour; ?>';
			flashvars.game_config = '<?php echo $gameConfig; ?>';
			flashvars.currency = 'INR';
			flashvars.frontend_id = '1';
			flashvars.locale = 'en_IN';
			//A 'name' attribute with the same value as the 'id' is REQUIRED for Chrome/Mozilla browsers
			swfobject.embedSWF("<?php echo $logSwfFile; ?>", "flashContent", "800", "600", "9.0", null,flashvars, null, {name:"flashContent"})
			swfobject.addParam("wmode", "transparent"); 			
		</script>
		<h1>TaashTime</h1>
	</body>
</html>