<?php /*
<html>
	<head>
	</head>
	<body>
		<div id="fb-root"></div>
      <script src="http://connect.facebook.net/en_US/all.js">
      </script>
      <script>
         FB.init({ 
            appId:'250870833286', cookie:true, 
            status:true, xfbml:true 
         });

         //FB.ui({ method: 'feed', 
           // message: 'zenfox games are super-cool'});
      </script>      
      <fb:like href="http://www.facebook.com/pages/Zen-fox/168248703230999" layout="button_count" show_faces="true" width="450" font="verdana"></fb:like>
      <script type="text/javascript">
      function loadUrl()
      {
    	  top.location.href = 'http://apps.facebook.com/zen-fox/game';
      }
      </script>
<a href = "#" onClick="loadUrl()">Click Here</a>

<?php
	if($this->gameGroups)
	{
		?>
		<script type="text/javascript">
			<!--
			function popitup(url)
			{
				newwindow=window.open(url,'name','fullscreen');
				if (window.focus) {newwindow.focus()}
				return false;
			}
			//-->
		</script>
		<?php
		//echo "<table cellpadding='0' cellspacing='2' border='1'>";
		foreach($this->gameGroups as $gameGroup)
		{
			foreach($gameGroup as $groupName => $flavour)
			{
				foreach($flavour as $flavourName => $machine)
				{
					echo $flavourName;
					echo "<br>";
					foreach($machine as $machineDetails)
					{
						$runningMachineId = $machineDetails['runningMachineId'];
						$link = "http://apps.facebook.com/" . $this->appName . "/game/flavour/" . $machineDetails['gameFlavour'] . "/machineId/" . $runningMachineId . "/amountType/" . $machineDetails['amountType'];
						$image = "/images/thumbnails/" . $machineDetails['gameFlavour'] . "_" . $runningMachineId . ".jpg";
                        ?>
                        <a href='#' id='this' onclick='return popitup("<?php echo $link; ?>")'><?php echo $machineDetails['machineName'];?>
							<img src = '<?php echo $image; ?>'/>
						</a>
                        <?php
					}
				echo "<br>";
				}
			}
		}
	}
	else
	{/*
        $game_id = 1;
        $game_flavour = 'RU_US';
        $login = $this->login;
        $passKey = md5($game_id . md5($this->phpsessid));
        $xml_config = 'http://demo.logicdice.com/games/single-player/lan_enu.xml';
        $string = "game_id=$game_id&game_flavour=$game_flavour&". "login=$login|$game_id|$game_flavour&pass_key=$passKey
        &xml_config=$xml_config&amount_type=REAL&currency=USD&frontend_id=1&locale=en_US";
		?>
		<fb:swf swfbgcolor="000000" imgstyle="border-width:3px; border-color:white;"
		swfsrc='http://demo.logicdice.com/games/single-player/roulette.swf'
		imgsrc='http://demo.logicdice.com/games/single-player/roulette.swf' width='768' height='480' flashvars="<?php echo
		$string ?>"/>
		<?php
		
		
	}
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="550" height="400" id="WebContainerLobby" align="middle">
     <param name="allowScriptAccess" value="sameDomain" />
     <param name="allowFullScreen" value="false" />
     <!--param name="movie" value="/games/multi-player/lobby/WebContainerLobby.swf" />
     <param name="FlashVars" value="xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" /-->
     <param name="movie" value="/games/container/web-container.swf" />
     <param name="FlashVars" value="xml_config=/games/container/config.txt&lobby_swf_path=/games/container/components/lobby/rummy-lobby/lobby.swf" />
     <param name="quality" value="high" />
     <param name="bgcolor" value="#ffffff" />
     <param name="wmode" value="transparent" />
     <!--embed src="/games/multi-player/lobby/WebContainerLobby.swf" flashVars = "xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" quality="high" bgcolor="#000000"-->
     <embed src="/games/container/web-container.swf" flashVars = "xml_config=/games/container/config.txt&lobby_swf_path=/games/container/components/lobby/rummy-lobby/lobby.swf" quality="high" bgcolor="#000000"
                 width="670" height="502" name="Web Container" align="middle"
                 play="true"
                 loop="false"
                 quality="high"
                 allowScriptAccess="sameDomain"
                 type="application/x-shockwave-flash"
                 pluginspage="http://www.adobe.com/go/getflashplayer" 
                 wmode="transparent"
                 >
             </embed>
             </object>
      
	</body>
</html>
*/
if($this->loginUrl)
{
	echo "<script type='text/javascript'>top.location.href = '$this->loginUrl';</script>";
}

?>
