<?php
$affiliateDetails = $this->affiliateDetails;
echo '<br><b>Profile Details</b><br>';
echo "<table border = '1'>";
foreach($affiliateDetails as $key => $value)
{
	if($key != 'affiliateId' && $key != 'passWord' && $key != 'masterId' && $key != 'masterId' && $key != 'created'  && $key != 'enabled' && $key != 'affiliateFrontendId' && $key != 'affiliateFrontendId' && $key != 'balance' && $key != 'masterContribution' && $key != 'masterDeduction' && $key != 'buddyBalance')
	{
		echo '<tr>';
		echo '<td>'.$key.'</td>';
		echo '<td>'.$value.'</td>';
		echo '</tr>';
	}
}
echo '</table>';
?>

<a href = "<?php echo $this->url(array(
							'controller' => 'affiliatemanage',
							'action' => editprofile,
							'id' => $affiliateDetails['affiliateId']
							));
			?>">
	<?php  print('Edit Profile');?>
</a>