<h2><strong>AFFILIATES PROGRAMS</strong></h2>
<p><h3><strong>Please read the updated Affiliate Terms and Conditions here:</strong></h3></p>
<p class = "bottom"><a href = "http://taashtime.tld/content/terms">http://taashtime.tld/content/terms</a></p>
<p>&nbsp;</p>
<h3><strong>Earn money promoting our rummy affiliate program</strong></h3>
<p>If you enjoy playing at Taashtime and own a website or blog, why not earn money while helping to promote the best online rummy site on the web? The Taashtime affiliate program is a great way to tell your friends and visitors about Taashtime, while you are rewarded for your efforts in spreading the word about us.</p> 
<p>If you own or operate a website, blog or other such site, you can be an affiliate for Taashtime. We will supply you with marketing banners and links that you can put on your website. Every time a visitor signs up through one of your Taashtime affiliate links, you get credited! Just write to us and take a look at the potential you can be making by promoting our site!!</p>
<p class = "bottom">Get started today as a Taashtime affiliate, apply now at support@taashtime.com! If you application is approved, you will receive all the information to get you started. Good luck and thanks for your interest in promoting Taashtime, the best online Rummy site on the web.</p>
<p>&nbsp;</p>