<div style="margin-top:10px">
                <div style="font-size:28px;text-align:center;color:#004298;font-family:Copperplate Gothic"><?=$this->leaderboardconf["title"]?></div>
                <div style="text-align:right;font-size:14px;font-family:Arial;color:#004298">From : <?=$this->leaderboardconf["start_time"]?> - To : <?=$this->leaderboardconf["end_time"]?></div></div>
<div>
<div style="font-size:22px;text-align:center;color:#004298;font-family:Copperplate Gothic"><?="Team Summary"?></div>
<?php 

$this->table($this->teamsdata);
?>
<div style="font-size:22px;text-align:center;color:#004298;font-family:Copperplate Gothic"><?="Team Wise Data"?></div>

<?php 
foreach ($this->teamsdata as $teamWiseData)
{
	?>
	<div style="font-size:18px;text-align:left;color:#004298;font-family:Copperplate Gothic"><?="Team Name = ".$teamWiseData["team_name"]?></div>
	<?php 
	
	$this->table($teamWiseData["player_data"]);
}
//Zenfox_Debug::dump($this->leaderboardconf);
?>



