<div class="fluid-content">
	<div class="head1">FAQs</div>
	
	<div class="head2">How do I get my 5000 FunCoins?</div>
	<p>When you register on the Ace2jak website through the Homepage, a confirmation link is sent to the email ID you have provided to us. When you click on the validation link and log in, then your account will automatically be credited with 5000 FunCoins.</p>
	
	<div class="head2">How do I claim my Welcome Bonus of TR 25?</div>
	<p>Once the player logs in, he can fill in all of his profile details. The TR 25 is automatically credited to the person's account, as soon as the profile details are completed accurately.</p>
	
	<div class="head2">Do I have to deposit in order to get Bonus Rs.25?</div>
	<p>No, a player is automatically be credited Rs.25 on following the instructions explained in the previous question.</p>
	
	<div class="head2">Can family members play with their Individual IDs from the same computer?</div>
	<p>Yes, all family members can play with their Individual Ids created from the same computer. Only one ID should be created for every unique email address.</p>
	
	<div class="head2">What is the referral program and how does it work?</div>
	<p>When an existing Ace2jak account holder refers another new player to join, it is known as a referral. In this case, as the new member registers on Ace2jak - The referrer's account is automatically credited with 25 TR as initial Buddy Bonus. A player can earn up to TR 500 from each buddy they refer reflected in their Buddy Bonus Due. With each deposit made by the Buddy, the referrer receives 25% of the amount. The referred player receives their Welcome Bonus.</p>
	
	<div class="head2">How can I withdraw money?</div>
	<p>For a player to withdraw the profile details must be filled and the Identity Verification process must be completed. For more details on terms of withdrawal, please check out Withdrawal Terms to learn more.</p>
	
	<div class="head2">I have an issue, how I can resolve it?</div>
	<p>There are multiple ways in which you can resolve your issue. You can create a new complaint here or contact Live Help or write to support @Ace2jak.com. Our customer support team is always looking to help you out!</p>
	
	<div class="head2">My welcome bonus is missing from my balance, where is it?</div>
	<p>A bonus is credited to a new player’s account only when the account is activated. The player must make sure to click on the confirmation link which is sent to the Email ID, which was used to register on Ace2jak.</p>
	
	<div class="head2">Where are you guys located?</div>
	<p>Srinture Technologies India Private Limited,<br/>Level:-1, AM@10, MB TOWERS,<br/>Road:-10,Banjarahills,<br/>Hyderabad-500034,<br/>Andhrapradesh, India.</p>
	
	<div class="head2">I just lost internet connection in the middle of the game. Will I lose everything that I have wagered on the game?</div>
	<p>If you regain connection in the middle of the game; it is possible for you to rejoin the game. However, if the connection does not return during the span of the game, the game will switch to Auto play and in the event of losing- the player stands to lose the entire wager.</p>
	
	<div class="head2">While arranging the cards, the table disappeared. What happens to the pot and do I lose all the money?</div> 
	<p>In such an event, please let et us check our records. If other players experienced similar issues, we would in all likeliness cancel the game and return everyone’s money back to them.</p>
	
	<div class="head2">How do I close my account?</div>
	<p>Please send an email to support@Ace2jak.com. We shall serve you in the best possible way.</p>
	
	<div class="head2">What do I do when Game winnings are not credited to my account?</div>
	<p>The players on Ace2jak have many customer support tools in order to get in touch with Ace2jak. Along with tickets which may be submitted on the website for it to be action items, there is also Live Help and/or email to support@Ace2jak.com.</p>
	
	<div class="head2">How to calculate the prize money and claims?</div>
	<p>The Terms & Conditions mentioned on the website clearly mention the withdrawal terms and the ways of claim. Please refer to them to know more in detail.</p>
	
	<div class="head2">What is the joker if the ‘’joker’’ card comes as the open Joker?</div>
	<p>In such a case, the card Ace is taken as Joker.</p>
	
	<div class="head2">What is the minimum amount you can deposit?</div>
	<p>The minimum deposit is Rs.25 through Net Banking and INR 250 through Credit Cards</p>
	
	<div class="head2">What is the maximum amount you can withdraw?</div>
	<p>At any point, the maximum amount a player can withdraw is Rs.5000. Please check out our Terms and Conditions to learn more.</p>
	
	<div class="head2">Why can’t I access my account?</div>
	<p>In an unfortunate event when a player cannot access his/her Ace2jak account, it usually could be a problem with a forgotten password or the validation/confirmation email. Please ensure that you click on the confirmation link before logging in for the first time. For further queries, Please contactsupport@Ace2jak.com.</p>
	
	<div class="head2">What is Discard pile and stock pile?</div>
	<p>The Discard Pile is the deck which is gathered from the discarded cards by the players in each round. This is where players place an unwanted card. The pile is face up and only the top card is seen. Players can also draw from this pile but cannot examine previous discards. The Discard pile re-mixes again when all the cards in the Stock are finished during the game and then the Discard pile is becoming the stock and the game continues.</p>
	<p><b>Closed Deck:</b> After the cards have been distributed, the remaining pile is called closed cards (stock pile).</p>
	<p><b>Stock pile:</b> The Stock deck is the leftover deck after the dealing of the cards to all players. From this deck the players draw a card at the beginning of each round; this indicates the turn of each player. When the Stock runs out we mix the Discard Pile which accumulated and turning it to the new Stock deck. The Stock deck is placed at the centre of the table and is accessible to all players.
	<br/>Players can draw a single card from the stock pile on a turn. This pile is face down and none of the cards are seen so drawing from stock involves a higher degree of risk, chance or luck than the discard pile.<br/>The most recent discarded card goes to the top of discard pile. Only top card can be picked from the either pile.</p>
	
	<div class="head2">What is Drop?</div>
	<p>Players can choose not to play a particular Round before drawing the first card. This action is termed as Drop. A player can decide to drop from the game before his turn comes.</p>
	<p><b>Initial drop:</b> If a player decides to drop the game in the very beginning before picking up a single card, it is called initial drop.</p>
	<p><b>Middle Drop:</b> Players can choose not to play after a Round starts by neither drawing nor discarding any cards. This action is termed as Middle Drop.</p>	
	
	<div class="head2">What is Deadwood?</div>
	<p>The term "deadwood" is used for cards which are not included in any meld (Sequences or sets) and are therefore unmatched. These are the cards which are left in the hands of the players after the last move in the game; the sum of these cards is counted to the iniquity of the same player who's left with the cards.<br/>The deadwood count is the total value of those cards.
	<br/>In case of show player must mandatorily have Life 1 and Life 2.<br/>Failing to have life 1, all cards are considered as Deadwood. Failing to have Life 2, all cards, but life 1 are considered as deadwood.
	<br/>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
	
	<div class="head2">What is Lobby?</div>
	<p>List of all the game rooms are provided in details in lobby. The details include: Table id, Amount type, Entry fee, Min players, No. of players etc.</p>
	<p><b>JOIN:</b> Next to every room there is a join button. On clicking, you become a spectator in that room.</p>
	<p><b>SIT:</b> A sit button is provided in order to play the game. As you click on this button, you are given a chair on the game table. Once there are enough players on a table, the game begins. You cannot join a game in middle as a player.</p>
	
	<div class="head2">What is Sequence?</div>
	<p>The purpose of the game is to complete a hand with most or all cards formed into Sets and/or Sequences. To make a Sequence a player should arrange three or more cards of the same suit in sequence, the order being A-2-3-4-5-6-7-8-9-10-J-Q-K-A:
	<br/>Example of a Valid Sequence Example of an Invalid Sequence
	<br/>3♠4♠5♠ 3♠4♣5♥
	<br/>10♥J♥Q♥K♥ 10♥J♥Q♦K♥</p>
	
	<div class="head2">What is a set?</div>
	<p>A player can form a set by arranging three or four cards of the same rank/face value and different suits:
	<br/>Example of a Valid Set Example of an Invalid Set
	<br/>A♠A♥A♣ A♠A♥2♣
	<br/>K♠K♥K♣K♦ K♠K♥Q♦ Combinations must not overlap - for example ♦7♦8♦9♠9♥9 is either a Sequence of diamonds with two spare 9's or a set of 9's with two spare diamonds. If a second ♦9 or a ♣9 or a ♦6 is added, the six cards form a Sequence and a set. Sets of 5 are not valid with/without a joker!
	<br/>Wild cards can be used to substitute for any desired card in a set or Sequence. For example if the turned up card is a ♣8 then ♦3♠8♥5 is a valid Sequence, and ♠J♦J♦8 is a valid set since all 8's are wild.
	<br/>A card can be used only once, either in a Set or in a Sequence. In other words, you cannot use the same card for both a Sequence and a Set. Note that in a Set, each card must be of the same rank and a different suit, however when two decks are used situations do arise where you have in your hand for example ♥K and ♥K - you cannot add to this ♣K to form a valid Set of three as the first two kings are of the same suit.</p>
	
	<div class="head2">What is melding?</div>
	<p>Melding is a process by which cards are placed together to form sets (at least three cards of same rank) or sequences (at least three cards of same suit in consecutive rank).There is no laying melds on the table during play as this only happens when someone goes out. There is no knocking too in Indian Rummy. If the player manages to meld all his cards and has a zero deadwood count, and his hand meets the requirement of containing at least two sequences (one of which is pure, with no wild cards), only then may he go out. He does this by placing his melds on the table and discarding the final card (traditionally face down) to signal victory. At this point, other players display their melds and deadwood is counted up and scored accordingly. There are two kinds of combinations: Sequences and Sets. A player wins the game by being the first to play all the cards in their hand by melding.</p>
	
	<div class="head2">What area Pure Sequence and Second Sequence?</div>
	<p>Life or Pure Sequence (Life1) should be the order of not less than three cards of the same suite. Life1 shouldn't have a Joker.
	<br/>Second Life or Second Sequence (Life2)must be a sequence of at least three cards of the same suite. Life 2 may or may not have a joker.</p>
	
	<div class="head2">What is Count?</div>
	<p>The total score of the deadwood is referred to as count. Count gets accumulated with each game. The maximum count a player can get in a game is 80 which is also known as full count!</p>
	
	<div class="head2">What are Win Combinations?</div>
	<p>In order to have a winning combination, the player must have a Life, second life and other sets or Sequences. Different combinations for a win are as follows:</p>
	<ul>
		<li>2 Sequences of 3, a set or Sequence of 3, a set or Sequence of 4</li>
		<li>One Sequence of 3, one Sequence of 4, 2 sets or Sequences of 3</li>
		<li>One Sequence of 5, one Sequence of 4, one set or Sequence of 4</li>
		<li>Two Sequences of 5, one set of 3</li>
	</ul>
	
	<div class="head2">What happens if I join in the middle of a game?</div>
	<p>In a Pool game or Syndicate – The player who joins in the middle of the game is given the same number of points (+1) that the highest point holder in the game already has.</p>
	
	<div class="head2">What happens if I join in the middle of a game?</div>
	<p>In a Pool game or Syndicate – The player who joins in the middle of the game is given the same number of points (+1) that the highest point holder in the game already has.
	<br/>For all other types of Rummy games (Rapid Rummy & Rummy Race) – The player begins at 0.</p>
	
	<div class="head2">For a player joining in the middle of the game, how is the prize money is distributed?</div>
	<p>As a new player joins an existing game, his table entry will be added to the pot excluding the game service charges. If the player wins, he/she is subject to winning the entire prize money on offer.</p>

	<div class="head2">What are Pool games (Syndicate) games?</div>
	<p>Pool games are knockout games. The last player standing wins the entire pot. As and when a player melds correctly- The points that are left on the hands of the other players on the table are taken as the score.
	<br/>As and when the game progresses- The score may keep increasing if the player loses/stays the same if he/she wins. The last person to stay on the table without reaching the knockout score is declared the winner.</p>
	
	<div class="head2">What are 101 &amp; 201 Pool games?</div>
	<p>As explained in the previous question, as a player gathers 101 points in a 101 pool game, He/she is knocked out. Similarly, the same for 201 Pool games- As a player accumulates 201 points- He or she is knocked out and does not have the chance of winning.</p>
	
	<div class="head2">Can players rejoin once they have been knocked out of a Pool game?</div>
	<p>Yes, there are conditions under which a player may rejoin after again paying the entry fee for the table.
	<br/>For 101 Pool Game a player may rejoin the 101 Pool game after being knocked out. This may only happen when an existing player (on the table) has a maximum of 79 points. That would imply that the new player (rejoining/new player) would start the game with 80 points.
	<br/>For 201 Pool gamea player may rejoin the 201 Pool game after being knocked out. This may only happen when an existing player (on the table) has a maximum of 174 points. That would imply that the new player (rejoining/new player) would start the game with 175 points.</p>
	<p><b>Note:</b> This will also apply to brand new players wanting to join a room with existing players.</p>
	
	<div class="head2">What are the different forms of 13 card Rummy that are offered on Ace2jak?</div>
	<p>There are primarily three forms of 13 card Indian Rummy offered on Ace2jak:</p>
	<p><b>Pool games</b>These are knock out games. The players have to ensure that they do not accumulate more than 101 points. At which point they get eliminated. The last player remaining who does not get eliminated is declared the winner.</p>
	<p><b>Forward Ladder games – Rummy Race</b>these games are a ‘’race to a particular score’’ games. The points are distributed based on the final meld. If a player has melded correctly, then he/she gets the sum of the points that the other players have in hand after final meld.</p>
	<p><b>Money Per Point (MPP) games- Rapid Rummy</b>These games are so called because for every game that is played, a player receives the sum of the number of points (in total) that are given to him by the losing players on the table. The denominations may change for different MPP games. For eg. 10 ps per point, Rs. 3 per point and so on.</p>

	<div class="head2">How to leave the table?</div>
	<p>Once the game has been completed and a winner has been decided- The player may chose to close the window in the time frame within which the new game shall be started. The counter will start ticking on the top of the screen in the game room window.</p>
	
	<div class="head2">I have melded with the correct number of suits, why have I got 80 count and Wrong meld?</div>
	<p>Please make sure that you go through our How to Play section. It has a very elaborate description on how to meld correctly. </p>
	<p><b>A wrong meld may happen in the following ways:</b></p>
	<ul>
		<li>Wrong meld due to incorrect melding of cards.</li>
		<li>Using Auto meld feature and not correctly grouping the cards.</li>
	</ul>
	<p>Auto meld is a feature which enables the player to successfully ‘Show’ the grouped cards in hand. This feature may not be used on a complete set of 13 cards. Always remember to sort your cards before using the Auto meld feature!</p>
	
	<div class="head2">I have a problem with connecting and the games are very slow. My screen keeps on flickering, why?</div>
	<p>This may be a minor technical issue with the browser. You may refresh your browser and ensure you have an undisturbed internet connection.</p>
	
	<div class="head2">What are the minimum requirements for a player to play on Ace2jak?</div>
	<p>This may be the fault of your internet service provider. If the problem persists, Contact their customer support. Additionally, we would like to hear about any problems that you may have. Please contact support@Ace2jak.com</p>
	
	<div class="head2">Why does it say ‘’welcome back’’ and ‘’you seem to entering an un-authorized zone, login and try at the same page?</div>
	<p>Well, in such a situation, you just need to log in and try to access the page.</p>
	<p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
	
	<div class="head2">I am already logged in but I’m still getting the login page?</div>
	<p>Can you please let us know on which page this is happening? Based on the answer, we either tell them that they are not logged in or we are looking into the issue.</p>
	
	<div class="head2">I wish to put up a picture of mine instead of the avatar, what types of files and file sizes do you accept?</div>
	<p>We are currently working on this. The specifications shall be uploaded on the site soon.</p>
	
	<div class="head2">Is my display pic supposed to be displayed on the profile?</div>
	<p>Yes, a display picture you desire shall be displayed on your profile.</p>
	
	<div class="head2">How do I know that user data is protected on Ace2jak?</div>
	<P>Please take a look at our Privacy Policy on the website. It is very clearly defined as to how serious we are about data protection.</P>
	
	<div class="head2">How do I know that Ace2jak is not fake?</div>
	<p>Ace2jak is an SSL certified website by StartCom which is an SSL certification authority. It ensures that the authenticity and functions of the website are conducive to a safe internet browsing environment.</p>
	
	<div class="head2">How is rummy for money not illegal?</div>
	<p>According to numerous legal judgments in the country, Rummy is termed as a game of skill and NOT LUCK. Please refer to Legalities on the website for more detailed information.</p>
	<p>Yes, Family members can play with their Individual Ids from the same computer. Only one ID may be created for every unique email address.</p>
	
	<div class="head2">Where can I find who runs Ace2jak?</div>
	<p>Ace2jak is run by Fortuity Infotech</p>
	
</div>