<?php
if($this->form)
{
	?><div id = "invite-friends-form">
		<div id="inner-box">
	    <div class="ttdepolcont ttinvitebg ">
	    <div class="ttinvitehead">Invite Friends
	    <!-- div class="ttclosebtn"><a href="#" onclick="closeInviteForm()"><img src="/css/rummy.tld/images/ttinviteclose.gif" border="0"/></a></div-->
	    
	    </div>
	   
	    <div class="ttinvitebginn">
	    
		<?php
		echo $this->form;
		?>
	    
	    </div>
	  
		</div>
	    </div>  
	    </div>
	    <?php 
}