<div class="ttdepolcont ttinnnerpad" id="createprofile">
  <div id="inner-box">
    <p><strong>We love to hear from our Taashtimers- Angry, sad, disappointed, betrayed, happy, loving us or simply confused!!</strong></p>
    <p>So open a ticket given below, writing the subject and the message, we'll get right back to you. Frequently, people ask us the same questions over and over. So check this list of <a href = "/faq">frequently asked questions</a> before you write us. But still if you have a doubt write to us anyways!</p>
    <?php
echo $this->form;
echo $this->message;
?>
  </div>
</div>
<!-- div class="ttdepolnextback">
  <div class="ttdepolnext">
    <input type="button" style="display:none" class="ttdepolconfbtn" value="Confirm Order" name="input2">
    <input type="button" id="submit" class="ttdepolnextbackbtn" value="Submit" name="">
  </div>
</div-->
