 <?php
 
echo $this->message;
?>

   <script type="text/javascript">
 
 if(document.getElementById("game_name-element").style.display)
 {
		 document.getElementById("prev-label").style.display = "block";
		 document.getElementById("prev-element").style.display = "block";

		
 }
 else
 {
	 document.getElementById("prev-label").style.display = "none";
	 document.getElementById("prev-element").style.display = "none";

	
 }
	
 </script>
 
