<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
                                    <!--Links and meta data-->
        <link rel="shortcut icon" href="/images/rummy.tld/favicon.ico" mce_href="/images/rummy.tld/favicon.ico" type="image/x-icon"/>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Playdorm: The most fun dorm online</title>


                                        <!--script files-->
        <?$this->headLink()->appendStylesheet('/AdminLTE-master/css/AdminLTE.css') ?>
        <?$this->headLink()->appendStylesheet('/AdminLTE-master/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') ?>
        <?$this->headLink()->appendStylesheet('/css/daterangepicker/daterangepicker-bs3.css') ?>
        <?$this->headLink()->appendStylesheet('/css/datepicker/datepicker3.css') ?>
        <?$this->headLink()->appendStylesheet('/css/jvectormap/jquery-jvectormap-1.2.2.css') ?>
        <?$this->headLink()->appendStylesheet('/css/morris/morris.css') ?>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <?//$this->headLink()->appendStylesheet('/css/bootstrapcdn.css') ?>
        <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="//code.ionicframework.com/ionicons/1.5.2/css/ionicons.min.css" rel="stylesheet" type="text/css" /-->
        <?//$this->headLink()->appendStylesheet('/css/ionicframework.css') ?>
        <? $this->headLink()->appendStylesheet('/SpryAssets/SpryAccordion.css') ?>
        <? $this->headLink()->appendStylesheet('/SpryAssets/SpryTabbedPanels.css') ?>
        <? $this->headLink()->appendStylesheet('/SpryAssets/SpryTabbedPanel.css') ?>

        <?php /*Echo the headlink after appending everything*/?>
        <?= $this->headLink()?>

        <?php /*Appending the files before echoing*/?>
        <? $this->headScript()->appendFile('/SpryAssets/SpryTabbedPanels.js') ?>
        <? $this->headScript()->appendFile('/SpryAssets/SpryTabbedPanel.js') ?>
        <? $this->headScript()->appendFile('/SpryAssets/SpryAccordion.js') ?>
        <? $this->headScript()->appendFile('/js/menu.js') ?>
        <? $this->headScript()->appendFile('/js/analyticsforms.js') ?>
        <? $this->headScript()->appendFile('/js/jquery.clockpick.js') ?>
        <? $this->headScript()->appendFile('/js/element.js') ?>
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>

    </head>

    <header class="header">
            <a href="index.html" class="logo">          <!--For the logo at the top right hand corner of the screen-->
                AdminPortal
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="navbar-right">
                                                    <!--Navigation bar at the top-->
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i><span>Player</span></a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-gamepad"></i><span>Game Management</span></a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-usd"></i><span>Finance</span></a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bar-chart-o"></i><span>Analytics</span></a>
                        </li>
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-group"></i><span>Affiliates</span></a>
                        </li>
                    </ul>
                </div>
            </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
            <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                    <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="/AdminLTE-master/img/avatar5.png" class="img-circle" alt="User Image" />
                    </div>
                    <div class="pull-left info">
                        <p>Hello, Admin</p>
                    </div>
                </div>
                <?php echo $this->navigation()->menu(); ?>
            </section>
                                            <!--Sidebar-->
        </aside>
                    <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
                                    <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    Dashboard
                    <small>Control panel</small>
                </h1>
                <ol class="breadcrumb">
                    <i class="fa fa-dashboard"></i>
                    <?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?>
                </ol>
            </section>

                                        <!-- Main content -->
            <section class="content">
                                        <!-- Main row -->
                <div class="row">
                                         <!-- Left col -->
                    <div class="col-lg-7 col-lg-push-1"> 
                        <div class="box box-warning" id="form-box">
                            <div class="flash-messenger">
                                <div class="box-header">
                                    <h2 id="form-heading">Title</h2>
                                    <br><br>
                                    <?=$this->flashMessenger(); ?><!--Php line to include the main text/form of the html-->
                                </div>
                            </div>
                            <?=$this->layout()->content ?>
                        </div> 
                    </div>       
                </div>             
                                        <!--Active tab region-->
            </section>          <!-- /.Left col -->
            <section class="col-lg-5 connectedSortable"> 
            </section>
                                 <!-- /.row (main row) -->

                              <!-- /.content -->
        </aside>                        <!-- /.right-side -->
    </div>                              <!-- ./wrapper -->



    <body>
                                        <!-- Including JQuery -->
        <?php
            $this->JQuery()->enable();
            if($this->JQuery()->isEnabled())
            {
                $this->JQuery()->setUiLocalPath($this->baseUrl()."/js/jquery-ui-1.8.10.custom.min.js")
                                ->addStylesheet($this->baseUrl()."/js/jquery/css/custom-theme/jquery-ui.css");
                echo $this->JQuery();
            }
        ?>
        <?php /*Echo the headscript after appending everything*/?>
        <?= $this->headScript()?>
        <?= $this->headMeta()?>

        <script type="text/javascript">
          <!--
          var TabbedPanels1 = new Spry.Widget.TabbedPanel("TabbedPanels1");
          var Accordion1 = new Spry.Widget.Accordion("Accordion1");
          //-->
        </script>
    </body>
</html>