<?php
/*
<!--img src="/css/felicity/images/tournament_ad.png" width="630" height="835" border="0" usemap="#tournament" />

<map name="tournament">
<area shape="rect" coords="464,165,597,230" href="/tournament/register/" />

</map-->

<table width="630" border="0" align="center" cellpadding="0" cellspacing="0">

  <tr>

    <td width="22" background="http://taashtime.com/mailers/2012-01-20/images/n5lshadow.png">&nbsp;</td>

    <td width="586" valign="top" bgcolor="#fff"><table width="100%" border="0" cellspacing="0" cellpadding="0">

        <tr>

          <td  valign="top" bgcolor="#FFFFFF"  ><table width="100%" border="0" cellspacing="0" cellpadding="0">

              <tr>

                <td align="center"  valign="top"><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/03-02-2012/images/tournamentshivratri.jpg" width="600" height="250" alt="TaashTime" title="TaashTime" border="0" /></a></td>

              </tr>

              <tr>

                <!--             <td align="right" style="padding:10px 10px 0px 0px" ><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/2012-01-20/images/n6playnow.gif" width="112" height="26" style=" background:#0F0; color:#000; font-weight:bold;  font-size:20PX; "  alt="PLAY NOW" title="PLAY NOW" border="0" /></a></td>

   -->

                <td align="right" style="padding:10px 10px 0px 0px" ></td>

              </tr>

              <tr>

                <td  valign="top" style="padding-left:20px; color:#112F85; font-weight:normal;  font-size:16px; font-family:Verdana, Geneva, sans-serif">
                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:10px 20px 0px 0px; margin:0px">Keeping up with the tradition of Shivratri, We are excited to announce <span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">Night Tournaments</span> for this special ocassion starting Monday, 20th February 2012.<br>

                   </p>

                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:10px 20px 0px 0px; margin:0px; font-weight:normal"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">Register Once, Get Two Free Entries! <a href="http://taashtime.com/tournament/register" style="text-decoration:none">Register Now</a></span><br><br>You can now play <span style="color:#112F85; font-size:13px; font-weight:bold; font-family:Verdana, Geneva, sans-serif">Two free tournaments</span> with one click registration & Win Cash Prizes worth <span style="color:#112F85; font-size:13px; font-weight:bold; font-family:Verdana, Geneva, sans-serif">Rs 3,000!</span></p>

                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; margin:0px 0px 5px 0px;  padding:10px 0px 0px 0px;">To Register, just Log on to the <a href="http://taashtime.com/tournament" style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; font-weight:bold; margin:0px; padding:0px 0px 0px 0px; text-decoration:none">Taashtime Tournament Page</a> now!!!</p></td>

              </tr>

              <tr>

                <td height="5"></td>

              </tr>

              <tr>

                <td height="1" bgcolor="#e8bfbf"></td>

              </tr>

              <tr> </tr>

              <tr>

                <td  style="padding:0px; color:#24377e; font-weight:normal;  font-size:1px; height:5px;  font-family:Verdana, Geneva, sans-serif"></td>

              </tr>

              <tr>

                <td height="5"></td>

              </tr>

              <tr>

              <tr>

                <td align="center"><table border="1" cellpadding="2" cellspacing="0"  style="font-size:12px; font-family:Arial, Helvetica, sans-serif; color:#484848; border:#666 solid 1px; border-collapse:collapse" width="92%" >

                 <h1 style="color:#112F85;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:10px 20px 0px 0px; margin:0px"><u>TaashTime 3-Level Tournament Structure</u></h1><br><tbody>

                      <tr height="20">

                        <td width="64" height="20" align="center"></td>

                        <td align="center"><strong style="color:#112F85">Direct Entry </strong></td>

                        <td align="center" ><strong style="color:#112F85">Starting Balance</strong></td>

                        <td align="center"><strong style="color:#112F85">Min Balance</strong></td>

                        <td align="center"><strong style="color:#112F85"> Chips per point</strong></td>

                      </tr>

                      <tr height="20">

                        <td height="20" align="center"><strong style="color:#112F85">Level 1</strong></td>

                        <td align="center"><strong style="color:green; font-size:14PX">FREE</strong></td>

                        <td align="center">4000</td>

                        <td align="center"> - </td>

                        <td align="center">5</td>

                      </tr>

                      <tr height="20">

                        <td height="20" align="center"><strong style="color:#112F85">Level 2</strong></td>

                        <td align="center">10 TaashCash

</td>

                        <td align="center">5000</td>

                        <td align="center">4800</td>

                        <td align="center">10</td>

                      </tr>

                      <tr height="20">

                        <td height="20" align="center"><strong style="color:#112F85">Level 3</strong></td>

                        <td align="center">50 TaashCash</td>

                        <td align="center">7000</td>

                        <td align="center">6500</td>

                        <td align="center">20</td>

                     </tr>

					 </tr>

					 

					  

					   

                    </tbody>

                  </table></td>

              </tr>



			  <tr>

				<td><p style="color:#000; font-weight: bold; margin: 0; line-height: 15px; padding:0px 0px 20px 30px; font-size: 11px;font-family: Verdana, Geneva, sans-serif; line-height:18px; text-align:center"><br><u>Tournament Rules</u>

		<ul style="color:#000; font-weight: bold; margin: 0; line-height: 15px; padding:0px 0px 20px 30px; font-size: 11px;font-family: Verdana, Geneva, sans-serif; line-height:18px; text-align:left"><li>Min Balance - Minimum Balance required to Play the Level. For eg: If player has 4800 Tournament Chips or more at the end of Level 1, You will advance to Level 2.</li>  

		<li>You shall receive 4000 Tournament Coins on registration. All players are eligible to win Rs 3000 in Cash Prizes!.</li>

		<li>Each Level 45 Minutes - 15 Minute recess before next level.</li>

		<li>All TaashCash players on TaashTime.com will be able to directly Join in Levels 2 & Levels 3 with nominal entry fees of Rs 10 TaashCash and Rs 50 TaashCash respectively.</li>

		<li>Results shall be announced in Next week's TaashTime Newsletter.</li>

		<li>All games played are Coin Value Per Point (STAKE) games. </ul></p></td>

			  </tr>

              <tr>

                <td height="1" bgcolor="#e8bfbf"></td>

              </tr>

              <tr  bgcolor="#FFFFFF">

                <td height="10" ></td>

              </tr>

            </table></td>

        </tr>

        <tr>

          <td  valign="top"    ></td>

        </tr>

        <tr>

          <td bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="0">

              <tr>

                <td width="51%" height="235" align="center" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/r.png" ><img src="http://taashtime.com/mailers/2012-01-20/images/rummysymbol.png" width="203" height="117" alt="Challenge" title="Challenge"   />

                  <p><a href="http://taashtime.com/tournament/register"><img src="http://taashtime.com/mailers/2012-02-11/images/enterNow.png" width="161" height="37" style=" background:#FFF; color:#FFF; font-weight:bold;  font-size:22PX; "  alt="PLAY NOW" title="PLAY NOW" border="0" /></a></p></td>

                <td width="49%" valign="top" style="padding-right:10px"><table width="100%" border="0" cellspacing="0" cellpadding="0">

                    <tr>

                      <td   valign="top" style=" color:#112F85; margin:0px; padding:0px; font-weight:bold;  font-size:17px; font-family:Verdana, Geneva, sans-serif">Shivratri Night Tournaments</td>

                    </tr>

                    <tr>

                      <td width="37%" valign="top" style="margin:0px; padding:0px"><ul style="padding:10px 0px 0px 20px; margin:0px; line-height:18px;">

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:16px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000; line-height:25px">Tournament I - Monday Night

                            <p style="margin:0px; padding:0px; font-size:13px; font-weight:normal; color:#000; line-height:18px"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">9 PM to Midnight. </p>

                          </li>

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:16px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000; line-height:25px">Tournament II - After Monday Midnight

                            <p style="margin:0px; padding:0px; font-size:13px; font-weight:normal; color:#000; line-height:18px"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">1 AM to 4 AM</span><br><span style="color:#445eb3; font-size:15px; font-weight:bold; color:#112F85"> <br>DATE: 20th - 21st February, 2012.</span></p>

                        <br><br></ul></td>

                    </tr>

                  </table></td>

              </tr>

            </table></td>

        </tr>

        <!--       <tr>

          <td style="padding:0px 20px 0px 30px" bgcolor="#FFFFFF" ><table width="100%" border="0" cellspacing="0" cellpadding="0">

              <tr>

                <td width="160" height="190" valign="top"  background="http://taashtime.com/mailers/2012-01-20/images/n6_winnerslist.gif" style="background-repeat:no-repeat" ><table border="0" cellspacing="0" cellpadding="0">

                    <tr>

                      <td  height="71" align="center" valign="middle" style="margin:0px; padding:0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif">RULES</td>

                    </tr>

                    <tr>

                      <td width="161" align="center" valign="top"><ol style="padding:10px 0px 0px 45px; line-height:18px; margin:0px;">

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">All Stake Games</li>

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">30 minute levels</li>

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">KshytriyaMa.. </li>

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">ROC K ERS</li>

                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">Anand Singh</li>

                        </ol>

                        <p style="margin:0px; padding:0px 20px 0px 0px;  font-family:Verdana, Geneva, sans-serif; font-size:12px; text-align:right"></p></td>

                    </tr>

                  </table></td>

                <td width="20">&nbsp;</td>

                <td width="160" align="center" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/n6_gamesplayed.gif" style="background-repeat:no-repeat"><p style="margin:0px; padding:10px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif; line-height:18px;"><br></p>

                  <p style="margin:0px; padding:0px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif"> </p>

                  <p style="margin:0px; padding:0px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85;  font-family:Verdana, Geneva, sans-serif">VENUE</p>

                  <p style="margin:0px; padding:10px 0px 0px 0px; font-size:20px; font-weight:bold; color:#000; font-family:Verdana, Geneva, sans-serif "><br><a href =http://felicity.taashtime.com>At your comfort</a></p></td>

                <td width="20">&nbsp;</td>

                <td width="160" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/invite.png" style="background-repeat:no-repeat"><table border="0" cellspacing="0" cellpadding="0" width="100%">

                    <tr>

                      <td  height="74" align="center" valign="middle" style="margin:0px; padding:0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif">Date/Time</td>

                    </tr>

					<tr>

                      <td align="center" valign="top"><a href="#" style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; margin:0px; padding:0px 0px 0px 0px; text-decoration:none"><br />

                        </a></td>

                    </tr>

                  </table></td>

                <td width="23" >&nbsp;</td>

              </tr>

            </table></td>

        </tr>

        <tr bgcolor="#FFFFFF"><td>&nbsp;</td></tr>

        <tr>

          <td height="1" bgcolor="#e8bfbf"></td>

        </tr>

        

        <tr>

          <td height="1" bgcolor="#e8bfbf"></td>

        </tr>

        <tr>

         

        </tr>

  -->

        <tr>

          <td bgcolor="#e7dbdb"><table width="100%" border="0" cellspacing="0" cellpadding="0">

              <tr>

                <!--                <td width="10%">&nbsp;</td>

                <td width="17%"><a href="http://www.facebook.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5facebooklike.png" width="74" height="33"  alt="Like us on Facebook" title="Like us on Facebook"  border="0"/></a></td>

                <td width="10%"><a href="http://twitter.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5twitter.png" width="33" height="33" alt="tweet" title="tweet" border="0" /></a></td>

                <td width="9%"><a href="http://www.orkut.co.in/Community?cmm=118716610"><img src="http://taashtime.com/mailers/2012-01-20/images/n5orcut.png" width="33" height="33" alt="orkut" title="orkut" border="0" /></a></td>

                <td width="12%"><a href="http://digg.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5digg.png" width="56" height="33"  alt="digg us" title="digg us" border="0"/></a></td>

                <td width="42%" height="52" valign="middle"><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/2012-01-11/mailerimages2/images/rummyplaynow-01.png" width="200" height="28" alt="PLAY RUMMY NOW"  title="PLAY RUMMY NOW" border="0" style="color:#000; font-weight:bold; font-size:22PX; "/></a></td>

-->

              </tr>

            </table></td>

        </tr>

        <tr>

          <td height="1" bgcolor="#FFFFFF"></td>

        </tr>

        <tr> </tr>

        <!--tr>

          <td he ight="50" align="center" valign="middle" bgcolor="#000" style="color:#fff; font-size:10PX;   font-family:Verdana, Geneva, sans-serif;">This email is meant for #email#. You have received this message because you are a registered member on TaashTime. If you did not find this message useful, please use this link to <a href="http://taashtime.com/index/unsubscribe/emailId/#email#" style="color:#FFF; text-decoration:underline; font-size:12px">UNSUBSCRIBE </a></td>

        </tr-->

      </table></td>

    <td width="22" background="http://taashtime.com/mailers/2012-01-20/images/n5rshadow.png">&nbsp;</td>

  </tr>

</table>
*/
?>


<table id="tournament-table" width="630" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td width="22" background="http://taashtime.com/mailers/2012-01-20/images/n5lshadow.png">&nbsp;</td>
    <td width="586" valign="top" bgcolor="#fff"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td  valign="top" bgcolor="#FFFFFF"  ><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td align="center"  valign="top"><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/03-02-2012/images/tournamentshivratri.jpg" width="600" height="250" alt="TaashTime" title="TaashTime" border="0" /></a></td>
              </tr>
              <tr>
                <!--             <td align="right" style="padding:10px 10px 0px 0px" ><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/2012-01-20/images/n6playnow.gif" width="112" height="26" style=" background:#0F0; color:#000; font-weight:bold;  font-size:20PX; "  alt="PLAY NOW" title="PLAY NOW" border="0" /></a></td>
   -->
                <td align="right" style="padding:10px 10px 0px 0px" ></td>
              </tr>
              <tr>
                <td  valign="top" style="padding-left:20px; color:#112F85; font-weight:normal;  font-size:16px; font-family:Verdana, Geneva, sans-serif">Dear <span style="color:#112F85; font-size:15px; font-weight:bold"><?=$this->name?>, </span>
                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:10px 20px 0px 0px; margin:0px">Keeping up with the tradition of Sivaratri, We are excited to announce <span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">Night Tournaments</span> for this special ocassion starting Monday, 20th February 2012.<br>
                   </p>
                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:10px 20px 0px 0px; margin:0px; font-weight:normal"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">Registrations Open! <a href="http://taashtime.com/tournament/register" style="text-decoration:none">Register Now</a></span><br><br>You can now play <span style="color:#112F85; font-size:13px; font-weight:bold; font-family:Verdana, Geneva, sans-serif">Two free tournaments</span> with one click registration & Win Cash Prizes worth <span style="color:#112F85; font-size:13px; font-weight:bold; font-family:Verdana, Geneva, sans-serif">Rs 3,000!</span></p>
                  <p style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; margin:0px 0px 5px 0px;  padding:10px 0px 0px 0px;">To Register, just Log on to the <a href="http://taashtime.com/tournament" style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:13px; font-weight:bold; margin:0px; padding:0px 0px 0px 0px; text-decoration:none">Taashtime Tournament Page</a> now!!!</p></td>
              </tr>
              <tr>
                <td height="5"></td>
              </tr>
              <!--tr>
                <td height="1" bgcolor="#e8bfbf"></td>
              </tr-->
              <tr> </tr>
              <tr>
                <td  style="padding:0px; color:#24377e; font-weight:normal;  font-size:1px; height:5px;  font-family:Verdana, Geneva, sans-serif"></td>
              </tr>
              <tr>
                <td height="5"></td>
              </tr>
              <tr>
              <tr>
                <td align="center">
				<table border="1" cellpadding="2" cellspacing="0"  style="font-size:12px; font-family:Arial, Helvetica, sans-serif; color:#484848; border:#666 solid 1px; border-collapse:collapse" width="92%" >
                 <tbody>
					  <tr>
					  <td colspan=6><p style="color:#112F85;  font-family:Verdana, Geneva, sans-serif; font-size:13px; padding:0px 2px 0px 0px; margin:0px" align="center"><u><b>TaashTime 3-Level Tournament Structure</b></u></p><br></td>
					  </tr>
                      <tr height="20">
                        <td width="64" height="20" align="center"> Enter in <u>ANY</u> level</td>
                        <td align="center"><strong style="color:#112F85">Direct Entry </strong></td>
                        <td align="center" ><strong style="color:#112F85">Starting Balance</strong></td>
                        <td align="center"><strong style="color:#112F85">Min Balance</strong></td>
                        <td align="center"><strong style="color:#112F85"> Chips per point</strong></td>
						<td align="center"><strong style="color:#112F85">Start Time</strong></td>
                      </tr>
                      <tr height="20">
                        <td height="20" align="center"><strong style="color:#112F85">Level 1</strong></td>
                        <td align="center"><strong style="color:green; font-size:14PX">FREE</strong></td>
                        <td align="center">4000</td>
                        <td align="center"> - </td>
                        <td align="center">5</td>
						<td align="center">9 PM and 1 AM</td>
                      </tr>
                      <tr height="20">
                        <td height="20" align="center"><strong style="color:#112F85">Level 2</strong></td>
                        <td align="center">10 TaashCash
</td>
                        <td align="center">5000</td>
                        <td align="center">4800</td>
                        <td align="center">10</td>
						<td align="center">10 PM and 2 AM</td>
                      </tr>
                      <tr height="20">
                        <td height="20" align="center"><strong style="color:#112F85">Level 3</strong></td>
                        <td align="center">50 TaashCash</td>
                        <td align="center">7000</td>
                        <td align="center">6500</td>
                        <td align="center">20</td>
						<td align="center">11 PM and 3 AM</td>
                     </tr>
                  </tbody>
                </table></td>
              </tr>

			  <tr>
				<td style="padding-right: 40px; text-align:justify;"><p style="color:#000; font-weight: bold; margin: 0; line-height: 15px; padding:0px 0px 20px 30px; font-size: 11px;font-family: Verdana, Geneva, sans-serif; line-height:18px; text-align:center"><br><u>Tournament Rules</u>
		<ul style="color:#000; font-weight: bold; margin: 0; line-height: 15px; padding:0px 0px 20px 30px; font-size: 11px;font-family: Verdana, Geneva, sans-serif; line-height:18px; text-align:left"><li>Min Balance - Minimum Balance required to Play the Level. For eg: If player has 4800 Tournament Chips or more at the end of Level 1, You will advance to Level 2.</li>  
		<li>You shall receive 4000 Tournament Coins on registration. All players are eligible to win Rs 3000 in Cash Prizes!.</li>
		<li>Each Level 45 Minutes - 15 Minute recess before next level.</li>
		<li>All TaashCash players on TaashTime.com will be able to directly Join in Levels 2 & Levels 3 with nominal entry fees of Rs 10 TaashCash and Rs 50 TaashCash respectively.</li>
		<li>Results shall be announced in Next week's TaashTime Newsletter.</li>
		<li>All games played are Coin Value Per Point (STAKE) games. </ul></p></td>
			  </tr>
              <!--tr>
                <td height="1" bgcolor="#e8bfbf"></td>
              </tr-->
              <tr  bgcolor="#FFFFFF">
                <td height="10" ></td>
              </tr>
            </table></td>
        </tr>
        <tr>
          <td  valign="top"    ></td>
        </tr>
        <tr>
          <td bgcolor="#FFFFFF"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="51%" height="235" align="center" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/r.png" ><img src="http://taashtime.com/mailers/2012-01-20/images/rummysymbol.png" width="203" height="117" alt="Challenge" title="Challenge"   />
                  <p><a href="http://taashtime.com/tournament/register"><img src="http://taashtime.com/mailers/2012-02-11/images/enterNow.png" width="161" height="37" style=" background:#FFF; color:#FFF; font-weight:bold;  font-size:22PX; "  alt="PLAY NOW" title="PLAY NOW" border="0" /></a></p></td>
                <td width="49%" valign="top" style="padding-right:10px"><table width="100%" border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td   valign="top" style=" color:#112F85; margin:0px; padding:0px; font-weight:bold;  font-size:16px; font-family:Verdana, Geneva, sans-serif">Sivaratri Night Tournaments</td>
                    </tr>
                    <tr>
                      <td width="37%" valign="top" style="margin:0px; padding:0px"><ul style="padding:10px 0px 0px 20px; margin:0px; line-height:18px;">
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:13px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000; line-height:25px">Tournament I - Monday Night
                            <p style="margin:0px; padding:0px; font-size:13px; font-weight:normal; color:#000; line-height:18px"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">9 PM to Midnight. </p>
                          </li>
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:13px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000; line-height:25px">Tournament II - After Monday Midnight
                            <p style="margin:0px; padding:0px; font-size:13px; font-weight:normal; color:#000; line-height:18px"><span style="color:#445eb3; font-size:13px; font-weight:bold; color:#112F85">1 AM to 4 AM</span><br><span style="color:#445eb3; font-size:15px; font-weight:bold; color:#112F85"> <br>DATE: 20th - 21st February, 2012.</span></p>
                        <br><br></ul></td>
                    </tr>
                  </table></td>
              </tr>
            </table></td>
        </tr>
        <!--       <tr>
          <td style="padding:0px 20px 0px 30px" bgcolor="#FFFFFF" ><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="160" height="190" valign="top"  background="http://taashtime.com/mailers/2012-01-20/images/n6_winnerslist.gif" style="background-repeat:no-repeat" ><table border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td  height="71" align="center" valign="middle" style="margin:0px; padding:0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif">RULES</td>
                    </tr>
                    <tr>
                      <td width="161" align="center" valign="top"><ol style="padding:10px 0px 0px 45px; line-height:18px; margin:0px;">
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">All Stake Games</li>
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">30 minute levels</li>
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">KshytriyaMa.. </li>
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">ROC K ERS</li>
                          <li style=" font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; padding:0px; margin:0px;  text-align:left; color:#000">Anand Singh</li>
                        </ol>
                        <p style="margin:0px; padding:0px 20px 0px 0px;  font-family:Verdana, Geneva, sans-serif; font-size:12px; text-align:right"></p></td>
                    </tr>
                  </table></td>
                <td width="20">&nbsp;</td>
                <td width="160" align="center" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/n6_gamesplayed.gif" style="background-repeat:no-repeat"><p style="margin:0px; padding:10px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif; line-height:18px;"><br></p>
                  <p style="margin:0px; padding:0px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif"> </p>
                  <p style="margin:0px; padding:0px 0px 0px 0px; font-size:14px; font-weight:bold; color:#112F85;  font-family:Verdana, Geneva, sans-serif">VENUE</p>
                  <p style="margin:0px; padding:10px 0px 0px 0px; font-size:20px; font-weight:bold; color:#000; font-family:Verdana, Geneva, sans-serif "><br><a href =http://felicity.taashtime.com>At your comfort</a></p></td>
                <td width="20">&nbsp;</td>
                <td width="160" valign="top" background="http://taashtime.com/mailers/2012-01-20/images/invite.png" style="background-repeat:no-repeat"><table border="0" cellspacing="0" cellpadding="0" width="100%">
                    <tr>
                      <td  height="74" align="center" valign="middle" style="margin:0px; padding:0px; font-size:14px; font-weight:bold; color:#112F85; font-family:Verdana, Geneva, sans-serif">Date/Time</td>
                    </tr>
					<tr>
                      <td align="center" valign="top"><a href="#" style="color:#000;  font-family:Verdana, Geneva, sans-serif; font-size:12px; font-weight:bold; margin:0px; padding:0px 0px 0px 0px; text-decoration:none"><br />
                        </a></td>
                    </tr>
                  </table></td>
                <td width="23" >&nbsp;</td>
              </tr>
            </table></td>
        </tr>
        <tr bgcolor="#FFFFFF"><td>&nbsp;</td></tr>
        <tr>
          <td height="1" bgcolor="#e8bfbf"></td>
        </tr>
        
        <tr>
          <td height="1" bgcolor="#e8bfbf"></td>
        </tr>
        <tr>
         
        </tr>
  -->
        <tr>
          <td bgcolor="#e7dbdb"><table width="100%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <!--                <td width="10%">&nbsp;</td>
                <td width="17%"><a href="http://www.facebook.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5facebooklike.png" width="74" height="33"  alt="Like us on Facebook" title="Like us on Facebook"  border="0"/></a></td>
                <td width="10%"><a href="http://twitter.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5twitter.png" width="33" height="33" alt="tweet" title="tweet" border="0" /></a></td>
                <td width="9%"><a href="http://www.orkut.co.in/Community?cmm=118716610"><img src="http://taashtime.com/mailers/2012-01-20/images/n5orcut.png" width="33" height="33" alt="orkut" title="orkut" border="0" /></a></td>
                <td width="12%"><a href="http://digg.com/taashtime"><img src="http://taashtime.com/mailers/2012-01-20/images/n5digg.png" width="56" height="33"  alt="digg us" title="digg us" border="0"/></a></td>
                <td width="42%" height="52" valign="middle"><a href="http://taashtime.com/game"><img src="http://taashtime.com/mailers/2012-01-11/mailerimages2/images/rummyplaynow-01.png" width="200" height="28" alt="PLAY RUMMY NOW"  title="PLAY RUMMY NOW" border="0" style="color:#000; font-weight:bold; font-size:22PX; "/></a></td>
-->
              </tr>
            </table></td>
        </tr>
        <tr>
          <td height="1" bgcolor="#FFFFFF"></td>
        </tr>
        <tr> </tr>
        <tr>
          <!--td he ight="50" align="center" valign="middle" bgcolor="#000" style="color:#fff; font-size:10PX;   font-family:Verdana, Geneva, sans-serif;">This email is meant for <?=$this->email?>. You have received this message because you are a registered member on TaashTime. If you did not find this message useful, please use this link to <a href="http://taashtime.com/index/unsubscribe/emailId/<?=$this->email?>" style="color:#FFF; text-decoration:underline; font-size:12px">UNSUBSCRIBE </a></td-->
        </tr>
      </table></td>
    <td width="22" background="http://taashtime.com/mailers/2012-01-20/images/n5rshadow.png">&nbsp;</td>
  </tr>
</table>


