<?php 
$url = '/comments/show/pages/';
$pageAddress = '/' . $this->pageAddress;
//print($pageAddress);
$firstPageLink = $url . $this->first . '/url'. $pageAddress;
$prevPageLink = $url . $this->previous . '/url'. $pageAddress;
$nextPageLink = $url . $this->next . '/url'. $pageAddress;
$lastPageLink = $url . $this->last . '/url'. $pageAddress;

if ($this->pageCount): ?>
<div class="pagination">

<!-- First page link -->
<?php if (isset($this->previous)): ?>
<a class = "comments" href="<?= $firstPageLink; ?>">&lt;&lt; First</a> |
<?php else: ?>
<span class="disabled">First</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a class = "comments" href="<?= $prevPageLink; ?>">&lt; Previous</a> |
<?php else: ?>
<span class="disabled">Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?>
<a class = "comments" href="<?= $url . $page . '/url'. $pageAddress; ?>"><?= $page; ?></a> |
<?php else: ?>
<?= $page; ?> |
<?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a class = "comments" href="<?= $nextPageLink; ?>">Next &gt;</a> |
<?php else: ?>
<span class="disabled">Next</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
<a class = "comments" href="<?= $lastPageLink; ?>">Last &gt;&gt;</a>
<?php else: ?>
<span class="disabled">Last</span>
<?php endif; ?>

</div>
<?php endif; ?>