<?
/**
 * Main layout file. Modify this to alter whole look of the site
 */
require_once APPLICATION_PATH . '/modules/player/forms/LanguageForm.php';
require_once APPLICATION_PATH . '/modules/player/forms/LoginForm.php';
require_once APPLICATION_PATH . '/modules/player/forms/CommentsForm.php';
require_once APPLICATION_PATH . '/modules/player/forms/RegistrationForm.php';

$decorator = new Decorator();
$registrationForm = new Player_RegistrationForm();
$registrationForm->setAction('/auth/signup');
$registrationForm->registration('registration');
$registrationForm = $decorator->addDecorators($registrationForm, 'signup');

$authSession = new Zenfox_Auth_Storage_Session();
$sessionData = $authSession->read();
echo $this->headMeta();
?>
<? /* This line outputs the doctype we set in the bootstrap */ ?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="google-site-verification" content="Yh27V2AJP-RkfhmY1WYCrldRoNLIoCuyFQ3YaVJaWfg" />
<?=$this->title() ?>
<!-- <link href="/css/bingocrush/bingo.css" rel="stylesheet" type="text/css" />
<link href="/css/bingocrush/menu.css" rel="stylesheet" type="text/css" /> -->
<link href="/css/bingocrush/bingo_minify.css" rel="stylesheet" type="text/css" />
<style>
#christmas{
        position:fixed;
        top:0px;
        left:0px;
        bottom:0px;
        right:0px;
        margin:auto;
        background:rgba(0,0,0,0.3);
        z-index:100;
        display:none;
}
#christmas-image{
        left: 25%;
    position: absolute;
	cursor:pointer;
}
</style>
<link rel="shortcut icon" href="http://bingocrush.co.uk/images/bingocrush/favicon.ico" type="image/x-icon" />
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="/css/bingocrush/ie-only.css" />
<link rel="shortcut icon" href="http://bingocrush.co.uk/images/bingocrush/favicon.ico" type="image/x-icon" />
<![endif]-->


<script type="text/javascript" src="/js/bingocrush/jquery-1.8.3.min.js" ></script>
<!-- Right Click Disable -->
<!-- script type='text/javascript'>
$(document).ready(function(){
$(document).bind("contextmenu",function(e){
return false;
});
});
</script-->
<?php ?>
<script type="text/javascript" src="/js/bingocrush/jquery.thumbhover.js"></script>
<script type="text/javascript" src="/js/bingocrush/menu.js"></script>
<script type="text/javascript" src="/js/bingocrush/SpryAssets/SpryTabbedPanel.js"></script>
<script type="text/javascript" src="/js/bingocrush/SpryAssets/SpryAccordion.js"></script>
<script type="text/javascript" src="/js/bingocrush/jquery.placeholder.js"></script>
<script type="text/javascript" src="/js/bingocrush/jquery_comments.js"></script>
<script type="text/javascript" src="/js/bingocrush/login.js"></script>
<script type="text/javascript" src="/js/bingocrush/form.js"></script>
<?php ?>
<script type="text/javascript" src="/js/bingocrush/yahoo-min.js"></script>
<script type="text/javascript" src="/js/bingocrush/event-min.js"></script>
<script type="text/javascript" src="/js/bingocrush/connection_core-min.js"></script>
<!--script type="text/javascript" src="/js/bingocrush/jquery_bingo_minify.js?v=1.2"></script>
<script type="text/javascript" src="/js/bingocrush/SpryAssets/jquery_spryassets_minify.js?v=1.1"></script--> 

<!--Google Analytics-->
<script>
 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

 ga('create', 'UA-27546725-4', 'bingocrush.co.uk');
 ga('send', 'pageview');

</script>
<script>
function openChristmas(){
        document.getElementById("christmas").style.display = "block";
}
function closeChristmas(){
        document.getElementById("christmas").style.display = "none";
}
</script>

<!-- script type="text/javascript">
  $(document).ready(function() {
    $('input,textarea').placeholder();
 });
</script-->


<!-- faq js-->

<!-- script src="/js/bingocrush/demos.js" type="text/javascript"></script-->
<script type="text/javascript">
	$(window).load(function(){
		  $(".TTBingoUserInfo,.TTBingoUserInfo img.prof-arrow , img.TTBingoUserInfo").click(function(){
						
			
			if ($('.TTBingo-index').hasClass('prof-inactive')) 
					{
						$('.TTBingo-index').removeClass('prof-inactive').addClass('prof-active');
					} 
					else if ($('.TTBingo-index').hasClass('prof-active')) 
					{
						$('.TTBingo-index').removeClass('prof-active').addClass('prof-inactive');
					}
			});
              
		});
    
</script>
 
<script type="text/javascript">
var TabbedPanels1 = new Spry.Widget.TabbedPanel("TabbedPanels1");
</script>
<script type='text/javascript'>//<![CDATA[ 
$(window).load(function(){
var stPt = 0, elToShow = 1; //showing 5 elements

var $nav_wrapper = $('.nav-wrapper');
var $list = $nav_wrapper.find('div'); //get the list of div's
var $copy_list = [];
var copy_lgt = $list.length - elToShow;

//call to set thumbnails based on what is set
initNav();
function initNav() {
   var tmp;
   for (var i = elToShow; i < $list.length; i++) {
      tmp = $list.eq(i);
      $copy_list.push(tmp.clone());
      tmp.remove();
   }
}

$('.next').click (function () {
    $list = $nav_wrapper.find('div'); //get the list of div's
        
    //move the 1st element clone to the last position in copy_list
    $copy_list.splice(copy_lgt, 0, $list.eq(0).clone() ); //array.splice(index,howmany,element1,.....,elementX)
    
    //kill the 1st element in the div
    $list.eq(0).remove();
    
    //add to the last
    $nav_wrapper.append($copy_list.shift());
});

$('.prev').click (function () {
    $list = $nav_wrapper.find('div'); //get the list of li's
        
    //move the 1st element clone to the last position in copy_li
    $copy_list.splice(0, 0, $list.eq(elToShow-1).clone()); //array.splice(index,howmany,element1,.....,elementX)
    
    //kill the 1st element in the UL
    $list.eq(elToShow-1).remove();
    
    //add to the last
    $nav_wrapper.prepend($copy_list.pop());

});

});//]]>  

</script>
<script>
function goToHomePage()
{
	 window.location.href = "/";
}
</script>
</head>
<body>
<!-- div id="fb-root"></div>
<script src="/js/facebook.js"></script-->
<div id = "message_box">
  <div class = "ui-widget-content ui-corner-all">
   
    <?php
         	$frontController = Zend_Controller_Front::getInstance();
	  		$controller = $frontController->getRequest()->getControllerName();
	  		if($controller != 'comments')
	  		{
	  			$form = new Player_CommentsForm();
	  			//echo $form;
	  			//echo $this->action('show', 'comments');
	  		}
//  		$commentsForm = new Player_CommentsForm();
//  echo $commentsForm;
  ?>
  </div>
</div>
<!--div id="christmas" style="overflow-y:scroll;height:100%">
                                                                                <img src="/images/bingocrush/Birthday.jpg" id="christmas-image" width="40%" height="100%" border="0" onclick="closeChristmas()">
                                                                                <map name="closeChristmas">
                                                                                        <area shape="circle" coords="394,15,11"  onclick="hideForSale()" style="cursor: pointer"/>
                                                                                </map>
                                                                        </div-->

<div id="TTBingoM">
  <div id="TTBingoHedBg">
    <div id="TTBingoLogo"><img src="/images/bingocrush/ttbingologo.png"  alt="BingoGrid" onClick="goToHomePage()" style="cursor:pointer"/></div>
    <div id="TTBingoLogin" class="TTBingoJoinForm TTBingoRight">
    <?php 
    if(!$sessionData)
    {
    	?>
        	<form action="/auth/login" method="post">
		<div style="height:30px;border:0px solid;width:515px;margin-top:15px;">
    			<input type="text" placeholder="Username"  value="" name="userName" style="color:#666;"  class="text" id="user"/>
			<input type="password" placeholder="Password" value="" name="password" class="text" id="user"/>
			<input type="submit" value="Login" class="TTBingoGradentBtn5" style="margin:-40px 0px 0px 0px ;"  />
		</div>
    	</form>
		<div style="height:40px;border:0px solid;width:440px;float:left;">
			<div style="border:0px solid;width:196px;float:left"><a href="/auth/forgotpassword" style="color:#fff;font-weight:bold">Forgot Username/Password Click here ?</a></div>
			<div style="border:0px solid;width:206px;float:left;margin-left:25px;"><a href="/auth/registration" style="color:#fff;font-weight:bold" >Are you new? <br> Click here to join now</a>	
			</div>		
			<div style="height:40px;border:0px solid;width:470px;float:left;margin-top:20px;margin-left:0px">
			<!--<img src="/images/bingocrush/womeday_spl.gif"  alt="BingoGrid" onclick="openChristmas()" style="cursor:pointer"/>-->
			<div style="margin-top:6px;margin-left:5px;">
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=1374392616114851";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
			<div class="fb-like" data-href="https://www.facebook.com/pages/Bingo-Crush/159660587527531" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
			&nbsp;&nbsp;&nbsp;
			  <a href="https://twitter.com/Bingocrush" class="twitter-follow-button" data-show-count="true" data-show-screen-name="true" >Follow @Bingocrush</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<a href="https://twitter.com/Bingocrush" class="twitter-share-button" data-url="http://bingocrush.co.uk"   data-text="Play Free Online Bingo,Slots,Roulette,keno at http://bingocrush.co.uk" data-via="Bingocrush" >Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

			</div>	
			</div>	
		</div>
	<br>
        	<?php 
     }
      else
        {
        	?>
        	    	<?php 
						if($sessionData)
						{
							?>
            
                        <div class="TTBingoRight1 TTBingoGameL">
                        <?php 
                       $playerId = $sessionData['id'];
                        $imageName = md5("image" . $playerId) . '.jpg';
                        $loginName = $sessionData['authDetails'][0]['login'];
                        $firstName = $sessionData['authDetails'][0]['first_name'];
                        $firstName = "";
                        
                       
                        $buddyBonus = $sessionData['authDetails'][0]['buddy_earnings'];
                        $imagePath = APPLICATION_PATH . "/../public/images/profiles/" . $imageName;
                        if(!file_exists($imagePath))
                        {
                            $imagePath = "/images/profiles/profile-m1.jpg";
                        }
                        else
                        {
                            $imagePath = "/images/profiles/" . $imageName;
                        }
                        
                        $accountVariable = new AccountVariable();
                        $varData = $accountVariable->getData($playerId, 'freeMoney');
                        if($varData)
                        {
                            $freeMoney = floatval($varData['varValue']);
                        }
                        ?>
                        <div class="TTBingoRadius TTBingoborder TTBingoUserInfo ttlog">
                    <div class="TTBingoUserInfoT clearfix">
                     
                      <div class="TTBingoLogOut">
                       
                        <div class="ttusrnme" style="float:left;float: left;margin-left: 15px;margin-top: 3px;margin-right: 25px;"><?php echo empty($firstName)?$loginName:$firstName;?></div>
                         <div class="TTBingoUserPic1"><img src="/images/bingocrush/ttbingouserphoto.png" width="27" height="27"/></div>
                         <div class="prof-arrow"><img src="/images/bingocrush/downarrow.png" width="9" height="4" alt=""></div>
                      </div>
                    </div>
                       
                        </div>
						
						
						<div style="height:40px;border:0px solid;width:470px;float:left;margin-top:20px;margin-left:-260px;">
					
			<!--img src="/images/bingocrush/bir_strip.gif"  alt="BingoGrid" onclick="openChristmas()" style="cursor:pointer"/-->
			<div style="margin-top:6px;margin-left:5px;">
			<div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=1374392616114851";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
			<div class="fb-like" data-href="https://www.facebook.com/pages/Bingo-Crush/159660587527531" data-send="false" data-layout="button_count" data-width="450" data-show-faces="false"></div>
			&nbsp;&nbsp;&nbsp;
			  <a href="https://twitter.com/Bingocrush" class="twitter-follow-button" data-show-count="true" data-show-screen-name="true" >Follow @Bingocrush</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>


<a href="https://twitter.com/Bingocrush" class="twitter-share-button" data-url="http://bingocrush.co.uk"   data-text="Play Free Online Bingo,Slots,Roulette,keno at http://bingocrush.co.uk" data-via="Bingocrush" >Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

			</div>	
			</div>	
                        <?php
                    }
                   ?>
                
                
              </div>
        	    <div class="profile-complete">
                	 <?php 
						if($sessionData)
						{
							
							?>
							
							<div class="TTBingoRight TTBingoGameL">
							<?php 
							$playerId = $sessionData['id'];
							$imageName = md5("image" . $playerId) . '.jpg';
							$loginName = $sessionData['authDetails'][0]['login'];
							$firstName = $sessionData['authDetails'][0]['first_name'];
							$firstName = "";
							
							$balance = $sessionData['authDetails'][0]['balance'];
							$cash = $sessionData['authDetails'][0]['cash'];
							$bonus = $sessionData['authDetails'][0]['bonus_bank'] + $sessionData['authDetails'][0]['bonus_winnings'];
							$buddyBonus = $sessionData['authDetails'][0]['buddy_earnings'];
							
							$imagePath = APPLICATION_PATH . "/../public/images/profiles/" . $imageName;
							if(!file_exists($imagePath))
							{
								$imagePath = "/images/profiles/profile-m1.jpg";
							}
							else
							{
								$imagePath = "/images/profiles/" . $imageName;
							}
							
							$accountVariable = new AccountVariable();
							$varData = $accountVariable->getData($playerId, 'freeMoney');
							if($varData)
							{
								$freeMoney = floatval($varData['varValue']);
							}
							?>
							<div class="TTBingoRadius TTBingoborder TTBingoUserInfo TTBingo-index prof-inactive">
						<div class="TTBingoUserInfoT clearfix">
						  <div class="TTBingoUserPic"><img src="/images/bingocrush/ttbingouserphoto.png" width="49" height="66" /></div>
						  <div class="TTBingoLogOut">
							<div align="right" ><a href="/auth/logout">Logout</a></div>
							<div class="TTBingoWelcome">Welcome</div>
							<div><?php echo empty($firstName)?$loginName:$firstName;?></div>
						  </div>
						</div>
							<div class="clearfix TTBingopad_5">
							<div class="clearfix TTBingoBalnce">
							<div class="TTBingoLeft TTBingoBalncecont">Balance</div>
							<div class="TTBingoLeft">:</div>
							<div  class="TTBingoRight" ><?= $balance ?></div>
							</div>
							<div class="clearfix TTBingoBalnce">
							<div class="TTBingoLeft TTBingoBalncecont">Cash</div>
							<div class="TTBingoLeft">:</div>
							<div  class="TTBingoRight" ><?= $cash ?></div>
							</div>
							<div class="clearfix TTBingoBalnce">
							<div class="TTBingoLeft TTBingoBalncecont">Bonus</div>
							<div class="TTBingoLeft">:</div>
							<div  class="TTBingoRight" ><?= $bonus ?></div>
							</div>
							<div class="clearfix TTBingoLogOut"><a href="/auth/view"> Profile </a><a style="margin-left: 75px;" href="/promotions/referfriend"> Refer A Friend </a></div>
							</div>
							</div>
							</div>
							<?php
							
						}
						else
						{
							?>
							<!--<div class="TTBingoRight TTBingoGameL">
							<div class=" TTBingoJoinl TTBingoRadius">
							<div  class="TTBingoJoinTitle">
							<p>JOIN NOW  & <br />
							GET FREE £20</p>
							<p class="TTBingoJoinTitleSmall">No Card Details Required</p>
							</div>
							<div class="TTBingoJoinForm TTBingoBtnmargt" style="padding:0px">
							<?php
							echo $registrationForm;
							?>
								  </div>
								</div>
							<?php 
						}
						?>
												 
					<!--</div>-->
					
					
					
				  
				  
                </div><!--profile-complete-->	
                    
                   <!-- <a href = "/auth/logout">Logout</a>-->
        	
        	    	<?php
        }
        ?>
    </div>
    <div id="TTBingoHedNav" class="TTBingoRadius ">
      <div id="TTBingoHedNavinn" class=" TTBingoBtninn">
      <?php 
  
  $partial = array('menu.phtml','player');
  $this->navigation()->menu()->setPartial($partial);
  echo $this->navigation()->menu()->render();
  
  ?>
        
      </div>
      
      <div id="TTBingosubNavHover">
	  	<ul id="sub-menu-hover">
	  	</ul>
	  </div>
    </div>
    <div id="TTBingosubNav">
		<ul id="sub-menu">
		</ul>
	</div>

  </div>
  <!-- div class="crumb"><?php echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();; ?> </div-->
  <div class=" TTBingomargt_50">
    
     	<div class=" TTBingoGameR TTBingoLeft TTBingomargl">
      <div class="clearfix">
        <div class="flash-messenger">
          <?=$this->flashMessenger(); ?>
        </div>
        <?=$this->layout()->content ?>
		<?php $this->layout()->content;?>
        <!-- <div class="TTBingoTodaysProm TTBingoLeft TTBingoRadius TTBingoborder">dqw</div>
        <div class="TTBingoTodaysProm TTBingoLeft TTBingoRadius TTBingoborder TTBingomargl">qewrwr</div>-->
      
        
       
      </div>
    </div>
        <?php 
        if($sessionData)
        {
        	/*
        	?>
            
        	<div class="TTBingoRight TTBingoGameL">
        	<?php 
        	$playerId = $sessionData['id'];
        	$imageName = md5("image" . $playerId) . '.jpg';
        	$loginName = $sessionData['authDetails'][0]['login'];
        	$firstName = $sessionData['authDetails'][0]['first_name'];
        	
        	$cash = $sessionData['authDetails'][0]['bank'] + $sessionData['authDetails'][0]['winnings'] + $sessionData['authDetails'][0]['bonus_bank'] + $sessionData['authDetails'][0]['bonus_winnings'];
        	$bonus = 0;
        	if($sessionData['authDetails'][0]['noof_deposits'])
        	{
        		$bonus = $sessionData['authDetails'][0]['bonus_due'];
        	}
        	$buddyBonus = $sessionData['authDetails'][0]['buddy_earnings'];
        	$imagePath = APPLICATION_PATH . "/../public/images/profiles/" . $imageName;
        	if(!file_exists($imagePath))
        	{
        		$imagePath = "/images/profiles/profile-m1.jpg";
        	}
        	else
        	{
        		$imagePath = "/images/profiles/" . $imageName;
        	}
        	
        	$accountVariable = new AccountVariable();
        	$varData = $accountVariable->getData($playerId, 'freeMoney');
        	if($varData)
        	{
        		$freeMoney = floatval($varData['varValue']);
        	}
        	?>
        	<!--div class="TTBingoRadius TTBingoborder TTBingoUserInfo ">
        <div class="TTBingoUserInfoT clearfix">
          <div class="TTBingoUserPic"><img src="/images/bingocrush/ttbingouserphoto.png" width="49" height="66" /></div>
          <div class="TTBingoLogOut">
            <div align="right" ><a href="/auth/logout">Logout</a></div>
            <div class="TTBingoWelcome">Welcome</div>
            <div><?php echo empty($firstName)?$loginName:$firstName;?></div>
          </div>
        </div>
        	<div class="clearfix TTBingopad_5">
        	<div class="clearfix TTBingoBalnce">
        	<div class="TTBingoLeft TTBingoBalncecont">Balance</div>
        	<div class="TTBingoLeft">:</div>

        	<div  class="TTBingoRight" ><?= $cash ?></div>
        	</div>
        	<div class="clearfix TTBingoBalnce">
        	<div class="TTBingoLeft TTBingoBalncecont">Bonus</div>
        	<div class="TTBingoLeft">:</div>
        	<div  class="TTBingoRight" ><?= $bonus ?></div>
        	</div>
        	<div class="clearfix TTBingoBalnce">
        	<div class="TTBingoLeft TTBingoBalncecont">Free Chips</div>
        	<div class="TTBingoLeft">:</div>
        	<div  class="TTBingoRight" ><?= $freeMoney ?></div>
        	</div>
        	<div class="clearfix TTBingoLogOut"><a href="/auth/view"> Profile </a><a style="margin-left: 75px;" href="/index/invite"> Refer A Friend </a></div>
        	</div>
        	</div>
        	<?php
        	*/
		$date = new Zend_Date();
		$day = $date->get(Zend_Date::DAY);
		$month = $date->get(Zend_Date::MONTH_NAME);
		$year = $date->get(Zend_Date::YEAR);
        	?>
	        <div class="TTBingonew">
			 <div style="background-color:#FFF;border:1px solid #CD222B;border-radius:6px;float:left;height:44px;margin-bottom:5px;width:210px;">
			<div style="height:40px;width:40px;line-height:55px;float:left;background-image:url('/images/bingocrush/calender.png')">
			<span style="font-size:26px;padding-left:15px"><?=$day?></span></div>	
			<div style="font-size:24px;float:left;border:0px solid;height:35px;width:90px;line-height:55px;">
			&nbsp;<?=$month?><span style="style="font-size:24px;float:left;">&nbsp;&nbsp;<?=$year?></span>
			</div>
			
		</div>
			 <div style="background: none repeat scroll 0 0 #FFD6DD;border: 1px solid #CD222B;border-radius: 6px 6px 6px 6px;float:left;height:280px;margin-bottom: 10px;width: 210px;">
			 <!--<img src="/images/bingocrush/bingo_230x280.png" alr="Bingo Crush" />-->
			 <img src="/images/bingocrush/deposit-offer.jpg" alr="Bingo Crush" width="210" /><!--after_deposit.jpg -->
			 </div>
	       
               <div style="background-color:#FFF;border: 1px solid #CD222B;border-radius: 6px 6px 6px 6px;float: left;height:250px;margin-bottom: 10px;width: 210px;margin-top:30px">
				<ul class="content_logo">
				<li style="list-style-type:bullet;border-bottom:1px dotted"><!--500% bonus on first deposit. Deposit &#163;10 and get &#163;60 to play. -->1000% bonus - <br>First 3 Deposits <br>300% - 300% - 400%</li>
			    <li style="list-style-type:bullet;border-bottom:1px dotted">300% bonus on all subsequent deposits
				<!--Every month, 10 lucky players will get &#163;25 cash each--> .</li>
				<li style="list-style-type:bullet;border-bottom:1px dotted">Refer your friends now, and get &#163;2 for each registration .</li>
				<li style="list-style-type:bullet;border-bottom:1px dotted">£2000 Mega Bingo Jackpot played on every game.</li>
				</ul>

				

			</div>
              
	        </div>
        	<?php 
        }
        else
        {
        	?>
        	<div class="TTBingoRight TTBingoGameL">
        	<div class=" TTBingoJoinl TTBingoRadius">
        	<div  class="TTBingoJoinTitle">
        	<p>JOIN NOW  & <br />
        	GET FREE £20</p>
        	<p class="TTBingoJoinTitleSmall">No Card Details Required</p>
        	</div>
        	<div class="TTBingoJoinForm TTBingoBtnmargt" style="padding:0px">
        	<?php

        	echo $registrationForm;
        	?>
        	      </div>
        	    </div>
        	    <div class="TTBingonew_before1">
        	    	<img src="/images/bingocrush/bingo_230x280.png"/>
        	    </div>
        	<?php 
        }
        ?>
         
    </div>
	
    
	
  </div>
  
  
  <!-- Including JQuery -->
  <?php
 
    /*
     * FIXME:: Set JQuery enabled in every view instead of in the layout
         */
    $this->JQuery()->enable();
    if($this->JQuery()->isEnabled())
    {
        //TODO:: Change the ui css depending on the frontend
        /*$this->JQuery()->setUiLocalPath($this->baseUrl()."/js/jquery/js/jquery-ui.js")
                        ->addStylesheet($this->baseUrl()."/js/jquery/css/custom-theme/jquery-ui.css");*/
	$this->JQuery()->setUiLocalPath($this->baseUrl()."/js/jquery-ui-1.8.10.custom.min.js");
    	$this->JQuery()->addStylesheet($this->baseUrl()."/css/rummy.tld/jquery-ui-1.8.9.custom.css");
        echo $this->JQuery();
        //echo $this->headMeta();
    }
    $siteHttpUrl = "http://". $_SERVER['HTTP_HOST'];
	$link = $siteHttpUrl . '/facebookauth/auth';
	$facebookAuth = $frontController->getRequest()->getParam('facebookAuth');


	if($facebookAuth)
	{
		?>
  <?php
	}
	$defaultTab = 0;
	if($this->defaultTab)
	{
		$defaultTab = $this->defaultTab;
	}
  ?>
  <?php /*Echo the headscript after appending everything*/?>
  <script type="text/javascript">
<!--
var TabbedPanels1 = new Spry.Widget.TabbedPanel("TabbedPanels1", <?=$defaultTab ?>);
var Accordion1 = new Spry.Widget.Accordion("Accordion1");
//-->
</script>
  <!-- End Body -->
  
</div>


<div class="TTBingoFooter clearfix">
<div class="TTBingoFooterinn">
    <div class="TTBingoFooterAccept TTBingoLeft">
      <div class="TTBingoWeaccepthed">WE ACCEPT</div>
      <div class="TTBingoBtnmargt"><img src="/images/bingocrush/ttbingoacceptcards.png" width="282" height="107" alt="BingoAcceptCards" /></div>
      <div class="TTBingoWeaccepthed TTBingoBtnmargt_20 "><!-- CONNECT WITH US --></div>
      <div class="TTBingoBtnmargt"><!-- <a href="#"><img src="/images/bingocrush/ttbingoficon.png" width="51" height="49" border="0" alt="BingoFacebook" /></a><a href="#"><img src="/images/bingocrush/ttbingogicon.png" width="52" height="48" border="0"  alt="BingoGmail"/></a><a href="#"><img src="/images/bingocrush/ttbingoticon.png" width="51" height="49" border="0" alt="BingoTwitter" /></a> --></div>
    </div>
    <div class="TTBingoFooterNav TTBingoLeft">
      <ul class="TTBingoLeft">
        <li><a href="/content/about">About Us</a></li>
        <li> <a href="/faq">FAQ</a></li>
        <!-- <li><a href="/content/article">Articles</a> </li> -->
        <li><a href="/promotions/referfriend">Tell A Friend</a></li>
      </ul>
      <div class="TTBingoLeft TTBingoBtnmargl_40">
        <ul>
          <li><a href="/content/privacypolicy">Privacy Policy</a></li>
          <li><a href="http://affiliate.bingocrush.co.uk">Affiliates</a></li>
          <li><a href="/content/rules">Rules</a></li>
          
        </ul>
      </div>
      <div class="TTBingoLeft TTBingoBtnmargl_40">
        <ul>
          <li><a href="/content/contact">Contact Us</a></li>
		  <li><a href="/content/terms">Terms of Use</a></li>
        </ul>
      </div>
    </div>
    <div class="TTBingoFooterRight TTBingoLeft">
      <div><a href="#"><img src="/images/bingocrush/ttbingogamble.png" width="124" height="33" border="0"  alt="BingoGambleAware"/></a></div>
      <div class="TTBingoBtnmargt"><a href="#"><img src="/images/bingocrush/ttbingogetflash.png" width="127" height="32" border="0"  alt="BingoGetAdobeFlashPlayer"/></a></div>
      <div class="TTBingoBtnmargt TTBingoBtnmargl_40"><img src="/images/bingocrush/ttbingo18plus.png" width="40" height="53" alt="Bingo18+" /></div>
      <div class="TTBingoBtnmargt"><img src="/images/bingocrush/ttbingo256bit.png" width="172" height="54" alt="BingoSecure" /></div>
    </div>
  </div>
  </div>
   <!-- <div style="margin:-915px 0px 0px 0px;float:left;position:fixed;left:1%;z-index:-1">
	<img src="/images/bingocrush/HP_Banner_left.png"  alt="Bingo" />
	</div>
	
	<div style="margin:-910px 0px 0px 0px;float:right;position:fixed;right:0%;z-index:-1">
	<img src="/images/bingocrush/HP_Banner_right.png"  alt="Bingo" />
	</div>-->
	
	
	<!--<div height="120" width="120" style="float:left;z-index:-1;position:absolute;border:0px;top:400px;left:60px">
	<?php
	 //$uri  = $_SERVER['REQUEST_URI'];
	 //$arr1 = split("/",$uri);
	 //$cnt  = count($arr1);
	 
	 //if($arr1[$cnt-1] == 'promotions')
	 //{
	?>
	<img src="/images/bingocrush/egg1.png"  alt="Bingo" />
	<?php //}elseif($arr1[$cnt-1] == 'referfriend'){ ?>
	<img src="/images/bingocrush/egg2.png"  alt="Bingo" />
	<?php //}elseif($arr1[$cnt-1] == 'gallery'){ ?>
	<img src="/images/bingocrush/egg3.png"  alt="Bingo" />
	<?php //}elseif($arr1[$cnt-1] == 'deposit'){ ?>
	<img src="/images/bingocrush/egg4.png"  alt="Bingo" />
	<?php //}elseif($arr1[$cnt-1] == 'loyalty'){ ?>
	<img src="/images/bingocrush/egg5.png"  alt="Bingo" />
	<?php //}
	?>
	</div>-->
	
<?php 
/*
<!-- Piwik -->
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.bingocrush.com/" : "http://piwik.bingocrush.com/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://piwik.bingocrush.com/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
<!-- End Piwik Tag -->
*/
?>

<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//cdn.zopim.com/?181uRzK3H7TO4l2xOLZRMPeFntzH8fDK';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
<!-- GeoTrust QuickSSL [tm] Smart  Icon tag. Do not edit. -->
<script language="javascript" type="text/javascript" src="//smarticon.geotrust.com/si.js"></script>
<!-- end  GeoTrust Smart Icon tag -->
</body>
</html>
