<?php

/**
 * AccountDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class AccountDetail extends BaseAccountDetail
{
	public function getbuddyslist($playerId)
	{
		$conns = Zenfox_Partition::getInstance()->getConnections(-1);
		
		
		
		$index=0;
		foreach ($conns as $conn)
		{
			$partition = Doctrine_Manager::getInstance()->getConnection($conn);
			$query = Zenfox_Query::create($partition)
			->select('a.player_id,a.email,a.login')
			->from('AccountDetail a')
			->where('a.buddy_id = ?', $playerId);
		
			$results[$index]= $query->fetchArray();
			
			$index++;
			
		}
		return $results;
		
	}
}