<?php

/**
 * BankWithdrawalRecords
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BankWithdrawalRecords extends BaseBankWithdrawalRecords
{
	public function addRecords($data)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$masterConnection = Doctrine_Manager::getInstance()->getConnection($conn);
		
		$date = new Zend_Date();
		$today = $date->get(Zend_Date::W3C);
		
		$this->player_id = $data['playerId'];
		$this->card_id = $data['cardId'];
		$this->csr_id = $data['csrId'];
		$this->gateway_response = $data['response'];
		if($data['status'] != 'PROCESSED')
		{
			$this->status = $data['status'];
			$this->error = $data['error'];
		}
		$this->response_time = $today;
		$this->amount = $data['amount'];
		
		try
		{
			$this->save($masterConnection);
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
			return false;
		}
		
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		$query = Zenfox_Query::create()
					->from('BankWithdrawalRecords b')
					->where('b.player_id = ?', $data['playerId'])
					->orderBy('b.id desc')
					->limit(1);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
			return false;
		}
		return $result[0]['id'];
	}
	
	public function updateSourceId($id, $sourceId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->update('BankWithdrawalRecords b')
					->set('b.source_id', '?', $sourceId)
					->where('b.id = ?', $id);
		
		try
		{
			$query->execute();
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
			return false;
		}
		return true;
	}
}
