<?php

/**
 * EmailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class EmailQueue extends BaseEmailQueue
{
	public function addEmailQueue($userId, $userType, $emailList, $templateId, $message)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$masterConnection = Doctrine_Manager::getInstance()->getConnection($conn);

		$date = new Zend_Date();
		$currentTime = $date->get(Zend_Date::W3C);
		
		$frontendId = Zend_Registry::get('frontendId');
		
		$this->user_id = $userId;
		$this->user_type = $userType;
		$this->email_list = $emailList;
		$this->template_id = $templateId;
		$this->frontend_id = $frontendId;
		$this->status = 'UNPROCESSED';
		$this->message = $message;
		$this->email_req_time = $currentTime;
		
		try
		{
			$this->save($masterConnection);
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
		}
	}
}