<?php

/**
 * Frontend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Frontend extends BaseFrontend
{
	public function getFrontends()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('Frontend');
					
		$result = $query->fetchArray();
		
		return $result;
		
	}
	
	public function getFrontendById($id)
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		//$result = Doctrine::getTable('Frontend')->findOneById($id);
		$query = Zenfox_Query::create()
					->from('Frontend f')
					->whereIn('f.id', $id);
					
		$result = $query->fetchArray();
		return $result;
	}
	
	public function getCurrentFrontend()
	{
		$site = 
		
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		//$result = Doctrine::getTable('Frontend')->findOneById($id);
		$query = Zenfox_Query::create()
					->from('Frontend f')
					->whereIn('f.id', $id);
					
		$result = $query->fetchArray();
		return $result;
	}
	
	public function getBonusSchemeId($frontendId)
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		try
		{
			$result = Doctrine::getTable('Frontend')->findOneById($frontendId);
		}
		catch(Exception $e)
		{
			$filePath = '/home/zenfox/backup_player/error_logs.txt';
		        $fh = fopen($filePath, 'a');
		        fwrite($fh, "GETTING BONUS SCHEME ID->" . $e);
		        fclose($fh);
			return false;
		}
		return $result['default_bonus_scheme_id'];
	}
}
