<?php

/**
 * TableConfigData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TableConfigData extends BaseTableConfigData
{
	public function getConfigDataByFlavour($gameFlavour)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('TableConfigData tcd')
					->where('tcd.game_flavour = ?', $gameFlavour);
					
		$result = $query->fetchArray();
		return $result[0];
	}
	
	public function getAllFlavours()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);

		$query = Zenfox_Query::create()
					->select('tcd.game_flavour')
					->from('TableConfigData tcd');
					
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exeption $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		return $result;
	}
}