<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
<div id="fb-root"></div>
        <script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
        <script type="text/javascript">
            FB.init({
                appId  : '204326862920157',
                status : true, // check login status
                cookie : true, // enable cookies to allow the server to access the session
                xfbml  : true  // parse XFBML
            });
        </script>
<?php

/*
 * Clearing all error messages
 */

//$this->flashMessenger()->clearMessages();

//$siteHttpUrl = "http://". $_SERVER['HTTP_HOST'];
$attributes = array (
        'width' => '100%',
		'height' => '100%',
		'resizable'=>'yes',
		'scrollbars'=>'no',
     );
$chat = $siteHttpUrl. "/games/container/components/chat/rummy-chat/chat.swf";
$games = $siteHttpUrl. "/games/container/components/lobby/rummy-lobby/lobby.swf";
$winner = $siteHttpUrl. "/games/container/components/winner/winner.swf";
$invitefriends = $siteHttpUrl. "/games/container/components/invitefriends/invitefriends.swf";
$machineId = $this->machineId;
$flavour = $this->flavour;
$amountType = $this->amountType;
#$swfFile = $siteHttpUrl . "/games/single-player/" . $flavour . "/" . $this->swfFile;
$swfFile =  "/games/multi-player/rummy/indian-rummy/game.swf";
$containerSwfFile =  "/games/container/container.swf";
$login = $this->login;
$currency = $this->currency?$this->currency:"USD";
$xmlConfig = "/games/container/config.txt";
//$gameConfig = $siteHttpUrl . "/games/single-player/" . $flavour . "/" . $flavour . "_" . $machineId . ".txt";
$gameConfig = "/games/multi-player/rummy/indian-rummy/config.txt";
$frontendId = Zend_Registry::getInstance()->get('frontendId');
$locale = Zend_Registry::getInstance()->get('Zend_Locale');;
$passKey = md5($machineId . md5($this->phpsessid));
$flashVarString = 'game_id='.$machineId.'&game_flavour='.$flavour.'&login='.$login.'|'.$machineId.'|'.$flavour.'&pass_key='.$passKey.'&xml_config='.$xmlConfig.'&amount_type='.$amountType.'&currency='.$currency.'&frontend_id='.$frontendId.'&locale='.$locale.'&game_swf_path='.$swfFile.'&game_config='.$gameConfig.'&chat='.$chat.'&winner='.$winner.'&invitefriends='.$invitefriends;//.'&games='.$games;
$params = array(
			'FlashVars' => $flashVarString,
			'wmode' => 'transparent',
			);
    
//echo $this->htmlFlash($containerSwfFile,$attributes,$params);
?> 
<div class="game" align="center">
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="100%" height="100%" id="GameContainer" align="middle">
	<param name="allowScriptAccess" value="sameDomain" />
	<param name="allowFullScreen" value="false" />
	<!--param name="movie" value="/games/multi-player/lobby/WebContainerLobby.swf" />
	<param name="FlashVars" value="xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" /-->
	<param name="movie" value="/games/container/container.swf" />
	<param name="FlashVars" value="<?=$flashVarString?>" />
	<param name="quality" value="high" />
	<param name="bgcolor" value="#ffffff" />
	<param name="wmode" value="transparent" />
	<!--embed src="/games/multi-player/lobby/WebContainerLobby.swf" flashVars = "xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" quality="high" bgcolor="#000000"-->
	<embed src="/games/container/container.swf" flashVars = "<?=$flashVarString?>" bgcolor="#000000"
				width="100%" height="100%" name="Container" align="middle"
				play="true"
				loop="false"
				quality="high"
				allowScriptAccess="sameDomain"
				type="application/x-shockwave-flash"
				pluginspage="http://www.adobe.com/go/getflashplayer" 
				wmode="transparent"
				>
			</embed>
			</object>
</div>
