<?php //echo "hi";?>
<!--<img src = "http://bingocrush.co.uk/images/bingocrush/coming-soon-vector-sticker.jpg" widht="407" height="407"/>-->
<div style="float:left;margin:30px 0px 0px 20px">
<div style="color: rgb(204, 0, 0); font-weight: bold; margin-bottom: 10px;">
<?php 
echo $this->message;
?>
</div>
<form name="affiliate-contact-form" method="post" action="/help/contact">
<table border="0" width="500" cellpadding="5" cellspacing="0">
<tr>
<td width="30%">Name*</td>
<td ><input type="text" name="name" size="20" value="<?=$this->name ?>" required/></td>
</tr>
<tr>
<td>Email*</td>
<td><input type="text" name="email" size="20" value="<?=$this->email ?>" required/></td>
</tr>
<!--<tr>
<td>Phone</td>
<td><input type="text" name="phone" size="20"/></td>
</tr>-->
<tr>
<td>Message*</td>
<td><textarea cols="25" rows="6" name="message" required><?=$this->postMessage ?></textarea></td>
</tr>
<tr>
<td></td>
<td><input type="submit" name="submit" value="submit"/></td>
</tr>

</table>
</form>
</div>