<div class="ttdownloadm">
  <div class="ttdownloadt">
    <h2>Get TaashTime on your Desktop - Play Rummy without Browsers!</h2>
    <div class="left ttdownloadl">
      <p>Get TaashTime Desktop for free
        on your PC,Mac or Linux</p>
      <ol>
        <li>Seamless Game</li>
        <li>Join Room Faster</li>
        <li>No Browser Delays!</li>
        <li>Play directly From Desktop</li>
      </ol>
    </div>
    <div class="left ttdownloadr" >
      <div class="ttdownloadiconm"><a href="<?=$this->cdnImageServer ?>/downloads/taashtime/desktop/rummy/offline-version/<?=$this->fileName ?>"><img src="/css/rummy.tld/images/ttdownloadbtn.png" width="209" height="55" /></a>
        <p>Problems with this download? <br />
          Try our Offline Installer</p>
        <div class="left ttdownloadicon"><a href="<?=$this->cdnImageServer ?>/downloads/taashtime/desktop/rummy/offline-version/TaashTime.exe"><img src="/css/rummy.tld/images/ttwindows.png" width="32" height="37" /></a></div>
        <div class="left ttdownloadicon"><a href="<?=$this->cdnImageServer ?>/downloads/taashtime/desktop/rummy/offline-version/TaashTime.air"><img src="/css/rummy.tld/images/ttmac.png" width="32" height="37" /></a></div>
        <div class="left ttdownloadicon"><a href="<?=$this->cdnImageServer ?>/downloads/taashtime/desktop/rummy/offline-version/TaashTime.air"><img src="/css/rummy.tld/images/ttapple.png" width="32" height="37" /></a></div>
      </div>
    </div>
  </div>
  <div class="ttdownloadinst">Instructions</div>
  <div class="ttdownloadinstt"><img src="/css/rummy.tld/images/ttinstallimg.png" width="570" height="126" /></div>
  <div class="ttdownloadinst">Minimum System Requirement</div>
  <div class="ttsystemreq">
    <div class="clear">
      <div class="left ttdownloadl">
        <p><strong>Software</strong></p>
      </div>
      <div class="left ttdownloadr">
        <p>Adobe AIR - Install here,
          Flash Player,Download the latest version here</p>
      </div>
    </div>
    <div>
      <div class="left ttdownloadl">
        <p><strong>Hardware</strong></p>
      </div>
      <div class="left ttdownloadr">
        <p>Pentium 350 MHz, 256 M B RAM, Min 56 Kbps Internet 
          -Connection
          10 M B Harddisk Free Space</p>
      </div>
    </div>
    <div>
      <div class="left ttdownloadl">
        <p><strong>Supported Operating System</strong></p>
      </div>
      <div class="left ttdownloadr">
        <p>Windows 98, Windows ME, Windows NT, Windows 2000,
          Windows XP, Windows Vista, Windows 7</p>
      </div>
    </div>
  </div>
</div>
