<div class="ttdownloadm">
  <div class="ttdownloadt">
    <h2>Get TaashTime on your Mobile - Play Rummy without Browsers!</h2>
    <div class="left ttdownloadl">
      <p>Get TaashTime for free on your Mobile</p>
      <ol>
        <li>Seamless Game</li>
        <li>Join Room Faster</li>
        <li>No Browser Delays!</li>
        <li>Play directly From Mobile</li>
      </ol>
    </div>
    <div class="left ttdownloadr" >
      <div class="ttdownloadiconm"><a href="<?=$this->cdnImageServer ?>/downloads/taashtime/mobile/rummy/offline-version/<?=$this->fileName ?>"><img src="/css/rummy.tld/images/ttdownloadbtn.png" width="209" height="55" /></a>
        
      </div>
    </div>
  </div>
</div>
