<?php
$webConfig = Zend_Registry::getInstance()->isRegistered('webConfig')?Zend_Registry::getInstance()->get('webConfig'):'';
$promotionsDir = isset($webConfig['promotionsDir'])?$webConfig['promotionsDir']:'zenfox.tld';

/*
 * FIXME:: Add promotions specific code for all sites so that it can be managed from backend.
 */
?>
<!--
<center>
<table border="0" cellpadding="0" cellspacing="0" align="center">
<tr>
	<td> <img src="/promos/<?=$promotionsDir?>promotion_ipl_1_1.jpg" alt="Promotion" border="0"/></td>
</tr>
<tr>
	<td> <img src="/promos/<?=$promotionsDir?>promotion_ipl_1_2.jpg" alt="Promotion" border="0"/></td>
</tr>
<tr>
	<td> <img src="/promos/<?=$promotionsDir?>promotion_ipl_1_3.jpg" alt="Promotion" border="0"/></td>
</tr>
<tr>
	<td> <img src="/promos/<?=$promotionsDir?>promotion_ipl_1_4.jpg" alt="Promotion" border="0"/></td>
</tr>
</table>
</center>
-->
<center>
<table border="0" cellpadding="0" cellspacing="0" align="center">
<tr>
<td>
<img src="/images/ccl-promotion.jpg" alt="Promotion" border="0"/>
</td>
</tr>
</table>
</center>
