<?php
echo $this->translate("Hi! ") . $this->loginName . $this->translate(". This is your home page.");
?>
<br></br>
<br></br>
<a href = "/ticket/create">
<?php echo $this->translate("Create Ticket");?></a>
<a href = "/ticket/view">
<?php echo $this->translate("View Tickets");?></a>
<a href = "/roulette/index">
<?php echo $this->translate("Roulette Log");?></a>
<a href = "/reconciliation/index">
<?php echo $this->translate("Transactions");?></a>
<a href = "/gaming/index">
<?php echo $this->translate("Games");?></a>
<a href = "/auth/view">
<?php echo $this->translate("My Profile");?></a>
<br></br>
<br></br>
<a href = "/auth/logout">
<?php echo $this->translate("Logout");?></a>
<a href = "/bin/game.html">
<?php echo $this->translate("FlashGame");?></a>