<?php

/**
 * AffiliateFrontend
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class AffiliateFrontend extends BaseAffiliateFrontend
{
	public function getAffiliateFrontends()
	{
		$conn = Zenfox_Partition::getInstance()->getConnections(0);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('AffiliateFrontend');
					
		$result = $query->fetchArray();
		return $result;
	}
	
	public function getAffiliateFrontendById($id)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections(0);
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		$result = Doctrine::getTable('AffiliateFrontend')->findOneById($id);
		
		return $result;
	}
}