<?php

/**
 * BingoWinners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoWinners extends BaseBingoWinners
{
	public function getdatabygamelogid($gamelogIds)
	{
		
		$conns = Zenfox_Partition::getInstance()->getConnections(-1);
		
		foreach($conns as $conn)
		{
			Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	
			$query = Zenfox_Query::create()
			->from('BingoWinners bw')
			->whereIn('bw.gamelog_id',$gamelogIds);
				
			$result[] = $query->fetchArray();	
		}
		if($result)
		{
			return array_merge($result[0], $result[1]);
		}
	//	Zenfox_Debug::dump($conn);//exit();
		return false;
	}
}