<?php

/**
 * BingoGameCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoGameCategory extends BaseBingoGameCategory
{
	public function getcategoriesbygameId($gameId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('BingoGameCategory bgc')
					->where('bgc.game_id =?',$gameId);
		
		try
		{
			$Categoriesdata = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		
		foreach($Categoriesdata as $data)
		{
			$result[] = $data["category_id"];
		}
		return $result;
	}
	
	public function deletecategoriesbygameId($gameId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->delete('BingoGameCategory bgc')
					->where('bgc.game_id =?',$gameId);
		
		try
		{
			 $query->execute();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		
		
		return true;
	}
}