<?php

/**
 * BingoRoomSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoRoomSession extends BaseBingoRoomSession
{
	public function getroomdata($roomId)
	{
		$connection = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);

		$query = Zenfox_Query::create()
				->from('BingoRoomSession brs')
				->where('brs.room_id =?' , $roomId);

		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'Exception');
		}
		return $result;
	}
	
	public function deleteroomsessions($bingoRoomId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->delete('BingoRoomSession rs')
						->where('rs.room_id = ?', $bingoRoomId);
						
		try
		{
			$query->execute();
		}
		catch(Exception $e)
		{
			return false;
		}
		
		return true;
	}
	
	public function insertroomssessions($bingoRoomId,$SessionsData)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		
		$days = 7;
		$hours = 24;
		$dayscount = 1;
		$hourscount = 0;
		$sequence =0;
		
		while($dayscount <= $days)
		{
			while($hourscount < $hours)
			{
				$roomsessionsobj[$hourscount] = new BingoRoomSession();
				
				$roomsessionsobj[$hourscount]->sequence = $sequence;
				$roomsessionsobj[$hourscount]->session_id = $SessionsData[$dayscount."_".$hourscount];
				$roomsessionsobj[$hourscount]->room_id = $bingoRoomId;
				$roomsessionsobj[$hourscount]->duration = 3600;
				$roomsessionsobj[$hourscount]->day = $dayscount;
				
				try
				{
					$roomsessionsobj[$hourscount]->save();
				}
				catch(Exception $e)
				{
					return false;
				}
				
				$sequence++;
				$hourscount++;
			}
			
			$hourscount =0;
			$dayscount++;
		}
		
		
		
		return true;
		
	}
	
}