<?php

/**
 * BingoPattern
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class BingoPattern extends BaseBingoPattern
{
	public function getAllPatternsData()
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->from('BingoPattern');
						
		$result = $query->fetchArray();
		return $result;
	}
	
	public function getPatternData($patternId)
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$result = Doctrine::getTable('BingoPattern')->findOneById($patternId);
		return $result;
	}
	
	public function insertPatternData($patternData)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		$patternobj = new BingoPattern();
		
		$patternobj->name = $patternData["name"];
		$patternobj->description = $patternData["description"];
		$patternobj->pattern = $patternData["pattern"];

		try{
			$patternobj->save();
		}
		catch(Exception $e)
		{
			echo $e;
			return false;
		}
		
		return true;
	}
}