<?php

/**
 * BingoCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoCategory extends BaseBingoCategory
{
	public function getAllCategories()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('BingoCategory bc');
		
		try
		{
			$allCategories = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		return $allCategories;
	}
	
	public function getcategorybyId($categoryId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('BingoCategory bc')
					->where('bc.id =?',$categoryId);
		
		try
		{
			$Categorydata = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		//Zenfox_Debug::dump($allCategories, 'cat');
		return $Categorydata;
	}
	
	public function updatecategorydetails($categorydata)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->update('BingoCategory bc')
    					->set('bc.name', '?', $categorydata["Name"])
    					->set('bc.description', '?', $categorydata["Description"])
    					->set('bc.pre_buy_enabled', '?', $categorydata["PreBuyEnabled"])
    					->set('bc.visible', '?', $categorydata["Visible"])
    					->where('bc.id = ?', $categorydata["Id"]);
						
		try
		{
			$result = $query->execute();
		}
    	catch(Exception $e)
    	{
    		return false;
    	}			
		
		return true;
	}
	
	public function insertcategorydetails($categorydata)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		
		$this->name = $categorydata["Name"];
		$this->description = $categorydata["Description"];
		$this->pre_buy_enabled = $categorydata["PreBuyEnabled"];
		$this->visible = $categorydata["Visible"];
		
		try
		{
			$this->save();
		}
    	catch(Exception $e)
    	{
    		return false;
    	}			
		
		return true;
	}
}