<?php

/**
 * BingoVariablePotPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoVariablePotPayment extends BaseBingoVariablePotPayment
{
	public function getData($gameId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('BingoVariablePotPayment vp')
					->where('vp.game_id = ?', $gameId)
					->orderBy('vp.id');
					
		$result = $query->fetchArray();
		$varPotData = array();
		$i = 0;
		foreach($result as $data)
		{
			$varPotData[$i]['varPotId'] = $data['id'];
			$varPotData[$i]['gameId'] = $data['game_id'];
			$varPotData[$i]['partId'] = $data['part_id'];
			$varPotData[$i]['realReturn'] = $data['real_pot_fraction'];
			$varPotData[$i]['bbsReturn'] = $data['bbs_pot_fraction'];
			$varPotData[$i]['couponCode'] = $data['coupon_code'];
			
			$i++;
		}
		return $varPotData;
	}
}