<?php

/**
 * BonusComponent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class BonusComponent extends BaseBonusComponent
{
	public function getlastbonusclaimedtime($playerId,$gametype,$amounttype)
	{
		$connName = Zenfox_Partition::getInstance()->getCommonConnection($playerId);
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($connName);
		
			$query = Zenfox_Query::create()
						->from('BonusComponent bc')
						->where('bc.player_id = ?', $playerId)
						->andWhere('bc.game_type = ?' , $gametype)
						->andWhere('bc.amount_type = ?' , $amounttype);
						
			try
			{
				$result = $query->fetcharray();
			}
			catch (Exception $e)
			{
				echo $e;
				
				return False;
			}
						
			return $result[0];
			
			
	}
	
	public function insertdata($playerId,$currentTime,$BonusAmount,$gametype,$amounttype)
	{
		$connName = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($connName);
		
		$bonuscomponentobj = new BonusComponent();
		
		$query = Zenfox_Query::create()
						->from('BonusComponent bc')
						->where('bc.player_id = ?', $playerId)
						->andWhere('bc.game_type = ?' , $gametype)
						->andWhere('bc.amount_type = ?' , $amounttype)
						->orderBy('bc.last_time_bonus_claimed');
						
						$result = $query->fetchArray();
						
			
			if($result)
			{
				$query = Zenfox_Query::create()
						->update('BonusComponent bc')
						->set('bc.bonus_claimed', '?', $BonusAmount)
						->set('bc.last_time_bonus_claimed', '?', $currentTime)
						->set('bc.total_bonus_claimed', '?', $result[0]["total_bonus_claimed"]+$BonusAmount)
						->where('bc.player_id = ?', $playerId)
						->andWhere('bc.game_type = ?' , $gametype)
						->andWhere('bc.amount_type = ?' , $amounttype);
						
				try
				{
					$query->execute();
				}
				catch(Exception $e)
				{
					echo $e;
					return false;
				}
						
						
			}
			else
			{
				$bonuscomponentobj->player_id = $playerId;
				$bonuscomponentobj->last_time_bonus_claimed = $currentTime;
				$bonuscomponentobj->bonus_claimed = $BonusAmount;
				$bonuscomponentobj->total_bonus_claimed = $BonusAmount;
				$bonuscomponentobj->game_type = $gametype;
				$bonuscomponentobj->amount_type = $amounttype;
		
				try {
					$bonuscomponentobj->save($partition);
				}
				catch (Exception $e)
				{
					echo $e;
					return false;
				}
			}
		
		
		
		return true;
	}
}