<?php

/**
 * ClickTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class ClickTrack extends BaseClickTrack
{

	private $serverName = '';
	private $frontendId = 1;

	public function construct()
	{

		parent::construct();
		//Zend_Registry::getInstance()->hasKey('frontend_id');

		$zfRegistry = Zend_Registry::getInstance();
		$this->serverName = Zend_Controller_Front::getInstance()->getRequest()->getHttpHost();


		try
		{
			$frontendConfig = $zfRegistry->get('frontendConfig');

		}
		catch(Exception $e)
		{
			$frontendConfig = '';
		}
		$this->frontendId = isset($frontendConfig[$this->serverName]['frontendId'])?$frontendConfig[$this->serverName]['frontendId']:1;

	}

	public function insertdata($data)
	{
		//echo 'in insert data ';
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$clickTrack = $this->existsClickTrack($data);

		if(!$clickTrack)
		{
			//echo 'new click track';
			$this->tracker_id = $data['trackerId'];
			$this->hit_datetime = $data['hitDatetime'];
			$this->hit_date = $data['hitDate'];
			$this->ip_address = $data['ip'];
			$this->click_count = 1;
			$this->frontend_id = $this->frontendId;
			
			try
			{
				$this->save();
			}
			catch(Exception $e)
			{
				//This has no meaning
				return false;
			}
		}
	}
	public function existsClickTrack($data)
	{
//		echo 'in exists click track';
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);

		
		$query = Zenfox_Query::create()
					->from('ClickTrack')
					->where('tracker_id = ?',$data['trackerId'])
					->andWhere('frontend_id = ?',$this->frontendId)
					->andWhere('hit_date = ?',$data['hitDate'])
					->andWhere('ip_address = ?',$data['ip']);
		$result = $query->fetchOne();

//echo $query->getSql();
//echo $data['trackerId'];

//	print_r($result);

		/*
		 * If exists, then update the click_count and return.
		 */
		
		if(isset($result['click_count']))
		{
			//echo 'existing click track '.$result['click_count'];
			$result->click_count = $result['click_count']+1;

			try
			{
				$result->save();
				return true;
			}
			catch (Exception $e)
			{
				return false;
			}
		}
		else
		{
			return false;
		}
		
	}
}
