<?php

/**
 * Csr
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Csr extends BaseCsr
{
	public function createCsr($data)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('Csr c')
					->where('c.alias = ?' , $data['alias']);					
		$result = $query->fetchArray();
		if($result)
		{					
			return -1;
		}
		
		$this->name = $data['name'];
		$this->alias = $data['alias'];
		$this->passwd = $data['passwd'];
		$this->enabled = $data['enabled'];
		$this->save($partition);
		
		$query = Zenfox_Query::create()
					->from('Csr c')
					->orderBy('c.id DESC')
					->limit(1);
		$result = $query->fetchArray();
		if($result)
			$csrId = $result[0]['id'];
		else
			$csrId = 1;
		
		if($data['groups'])
		{//Zenfox_Debug::dump($data['groups'],'groups',true,true);
			foreach($data['groups'] as $group)
			{
				$csrGmsGroup = new CsrGmsGroup();
				$insert = $csrGmsGroup->addCsrGroup($group,$csrId);
			}
		}
		
		return $insert;
	}

	public function getAllCsrs()
	{
		$query = Zenfox_Query::create()
				->from('Csr');
				
		try{
			$result = $query->fetchArray();
			return $result;
		}catch(Exception $e)
		{
			return false;
		}
	}
	
	public function getInfo($id)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
				->from('Csr c')
				->where('c.id = ?' , $id);
				
		try{
			$result = $query->fetchArray();
			return $result;
		}catch(Exception $e)
		{
			return false;
		}
	}
	
	public function editCsr($id,$data,$preGroups)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		if($preGroups)
		{
			foreach($preGroups as $pre)
	    	{
	    		$state=1;
	    		if($data['addedgroups'])
	    		{
	    			foreach($data['addedgroups'] as $group)
	    			{
	    				if ($pre['id'] == $group)
	    				{
	    					$state=0;
	    					break;
	    				}
	    			}
	    		}
	    		if($state)
	    		{
	    			$csrGmsGroup = new CsrGmsGroup();
	    			$result = $csrGmsGroup->deleteCsrGroup($id,$pre['id']);
	    		}
	    	}
    	}
		if($data['groups'])
    	{
			foreach($data['groups'] as $group)
			{
				$csrGmsGroup = new CsrGmsGroup();
				$result = $csrGmsGroup->addCsrGroup($group,$id);
			}
    	}
    	
    	$query = Zenfox_Query::create()
    			->update('Csr c')
    			->set('c.name', '?', $data['name'])
    			->set('c.alias', '?', $data['alias'])
    			->set('c.enabled', '?', $data['enabled'])
    			->where('c.id = ?', $id);
		try
		{
			$result = $query->execute();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		return true;
    	
	}
}