<?php

/**
 * currencyConversion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CurrencyConversion extends BaseCurrencyConversion
{
	public function getConvertedValue($sourceCurrency, $desCurrency, $value)
	{
		/*print('s - ' . $sourceCurrency);
		print('d - ' . $desCurrency);*/
		$convValue = $value;
		if($sourceCurrency && $desCurrency)
		{
			$conn = Zenfox_Partition::getInstance()->getCommonConnection();
			Doctrine_Manager::getInstance()->setCurrentConnection($conn);
			
			$query = Zenfox_Query::create()
						->select('c.conversion_rate')
						->from('CurrencyConversion c')
						->where('c.source_currency = ?', $sourceCurrency)
						->andWhere('c.destination_currency = ?', $desCurrency);
						
			$result = $query->fetchArray();
			if($result)
			{
				$convRate = $result[0]['conversion_rate'];
				$convValue = $value * $convRate;
			}
		}
		
		return $convValue;
	}
}
