<?php

/**
 * Journal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Journal extends BaseJournal
{
		public function insertnote($notedata , $playerId , $csrId)
		{
			$connName = Zenfox_Partition::getInstance()->getConnections($playerId);
			$partition = Doctrine_Manager::getInstance()->getConnection($connName);
			
			$today = new Zend_Date();
			$currentTime = $today->get(Zend_Date::W3C);
			
			$this->player_id=$playerId;
			$this->note = $notedata;
			$this->csr_id = $csrId;
			$this->created = $currentTime;
			$this->last_edited = $currentTime;
			
			$this->save($partition);
		}
		
		public function getnotes( $playerId )
		{
			$connName = Zenfox_Partition::getInstance()->getConnections($playerId);
			//Zenfox_Debug::dump(Doctrine_Manager::getInstance()->getCurrentConnection()->getName(), 'current');
			$partition = Doctrine_Manager::getInstance()->getConnection($connName);
		
			
			
			/*$query = Zenfox_Query::create($partition)
			->select('j.*')
			->from('Journal j')
			->where('j.player_id = ?', $playerId);*/
			
			try 
			{
				 $query = Zenfox_Query::create($partition)
                        ->select('j.*')
                        ->from('Journal j')
                        ->where('j.player_id = ?', $playerId);

				$results = $query->fetchArray();
			}
			catch(Exception $e)
			{
				Zenfox_Debug::dump($e, 'exception', true, true);
			}
			
			return $results;
			
		}
		
}