<?php

/**
 * LeaderBoardTeams
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class LeaderBoardTeams extends BaseLeaderBoardTeams
{
	public function getleaderboardteams($leaderboardId)
	{
		
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('LeaderBoardTeams lbt')
					->where('lbt.leader_board_id = ?',$leaderboardId);
		try{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return False;
		}
		
		//echo "here"; exit;
		return $result;
	}
	
	public function getleaderboardteambyId($leaderboardId,$teamId)
	{
		
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('LeaderBoardTeams lbt')
					->where('lbt.leader_board_id = ?',$leaderboardId)
					->andWhere('lbt.team_id = ?',$teamId);
		
		$result = $query->fetchArray();
		//echo "here"; exit;
		return $result[0];
	}
}