<?php

/**
 * LeaderBoardData
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class LeaderBoardData extends BaseLeaderBoardData
{
	
	public function getleaderboardteamdata($leaderboardId,$teamId,$admin = False)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		if($admin)
		{
			$query = Zenfox_Query::create()
				->select('lbd.player_id, lbd.Variable_1+lbd.Variable_2+lbd.Variable_3 as Points,lbd.prize_credited,lbd.prize_credited_amount')
				->from('LeaderBoardData lbd')
				->where('lbd.leader_board_id = ?' , $leaderboardId)
				->andWhere('lbd.team_id =?', $teamId)
				->orderBy('(lbd.variable_1+lbd.variable_2+lbd.variable_3)  desc');
				
				try
			{
			
				$result = $query->fetchArray();
				
			}
			catch (Exception $e)
			{
				echo $e->getMessage();
				//Zenfox_Debug::dump($e,'exception',true.true);
				return false;
			}
			
			$playerobj = new Player();
			$index = 0;
			foreach ($result as $data)
			{
				
				$playerdetails[$index]["PlayerId"] = $data["player_id"];
				
				
				$details = $playerobj->getPlayerData($data["player_id"]);
				
				
				if(!$details["firstName"])
				{
					$playerdetails[$index]["Login"] = $details["login"];
				}
				else 
				{
					$playerdetails[$index]["Login"] = $details["firstName"];
				}
				
				$playerdetails[$index]["Score"] = $data["Points"];
				$playerdetails[$index]["Prize Credited"] = $data["prize_credited"];
				$playerdetails[$index]["Prize Amount"] = $data["prize_credited_amount"];
				//Zenfox_Debug::dump($data);
				$index++;
			}
			return $playerdetails;
		}
		
		$query = Zenfox_Query::create()
				->select('lbd.leader_board_id,lbd.team_id, lbd.player_id, lbd.Variable_1+lbd.Variable_2+lbd.Variable_3 as Points')
				->from('LeaderBoardData lbd')
				->where('lbd.leader_board_id = ?' , $leaderboardId)
				->andWhere('lbd.team_id =?', $teamId)
				->orderBy('(lbd.variable_1+lbd.variable_2+lbd.variable_3)  desc');
	
			try
			{
			
				$result = $query->fetchArray();
				
			}
			catch (Exception $e)
			{
				echo $e->getMessage();
				//Zenfox_Debug::dump($e,'exception',true.true);
				return false;
			}
			
			$playerobj = new Player();
			$index = 0;
			foreach ($result as $data)
			{
				$playerdetails[$index]["LeaderBoardId"] = $data["leader_board_id"];
				$playerdetails[$index]["TeamId"] = $data["team_id"];
				$playerdetails[$index]["PlayerId"] = $data["player_id"];
				$playerdetails[$index]["Score"] = $data["Points"];
				
				$details = $playerobj->getPlayerData($data["player_id"]);
				
				
				if(!$details["firstName"])
				{
					$playerdetails[$index]["Login"] = $details["login"];
				}
				else 
				{
					$playerdetails[$index]["Login"] = $details["firstName"];
				}
				//Zenfox_Debug::dump($data);
				$index++;
			}
			return $playerdetails;
	}
	
	public function getplayerdata($playerId,$leaderboardId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
				->from('LeaderBoardData lbd')
				->where('lbd.leader_board_id = ?' , $leaderboardId)
				->andWhere('lbd.player_id =?' , $playerId);
				
		$result = $query->fetchArray();
		
		if($result)
		{
			return $result;
		}
		else
		{
			return false;
		}
		
	}
	
	public function insertnewplayer($playerId,$leaderboardId,$teamId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->getCurrentConnection($conn);
		
		
			$this->leader_board_id = $leaderboardId;
			$this->player_id = $playerId;
			$this->team_id = $teamId;
			$this->variable_1 = 0;
			$this->variable_2 = 0;
			$this->variable_3 = 0;
			$this->prize_credited = "NOTCREDITED";
			$this->prize_credited_amount = 0;
			
			try {
			$this->save($partition);
			}
			catch (Exception $e)
			{
				return false;
			}
			
			return true;
		
		
		
	}
	
	public function getTeamsTotalScores($leaderboardId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
				->select('sum(lbd.variable_1+lbd.variable_2+lbd.variable_3) as Total Score , lbd.team_id as TeamId')
				->from('LeaderBoardData lbd')
				->where('lbd.leader_board_id = ?' , $leaderboardId)
				->orderBy('sum(lbd.variable_1+lbd.variable_2+lbd.variable_3) desc')
				->groupby('team_id');
				
		$result = $query->fetchArray();
		
		if($result)
		{
			return $result;
		}
		else
		{
			return false;
		}
	}
	
	public function checkPlayerStatus($leaderboardId,$playerId)
	{
	
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
				->from('LeaderBoardData lbd')
				->where('lbd.leader_board_id = ?' , $leaderboardId)
				->andWhere('lbd.player_id = ?' , $playerId);
				
		$result = $query->fetchArray();
		
		if($result)
		{
			return true;
		}
		else
		{
			return false;
		}
	}
}