<?php

/**
 * MiniflushGamelog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class MiniflushGamelog extends BaseMiniflushGamelog
{
	public function getGamelogsByPlayerId($playerId)
	{
		$connection = Zenfox_Partition::getInstance()->getConnections($playerId);
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('MiniflushGamelog mg')
					->where('mg.player_id = ?', $playerId);
		
		try
		{
			$gameLogs = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
	}
	
	public function getGamelogsBySessionId($sessionId, $gameId, $playerId)
	{
		$connection = Zenfox_Partition::getInstance()->getConnections($sessionId);
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('MiniflushGamelog mg')
					->where('mg.player_id = ?', $playerId)
					->andWhere('mg.session_id = ?', $sessionId)
					->andWhere('mg.gamelog_id = ?', $gameId);
		
		try
		{
			$gameLogs = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		
		return $gameLogs;
	}
}