<?php

/**
 * OnlineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class OnlineTable extends BaseOnlineTable
{
	public function getMachineData($roomId, $flavour)
	{
		//TODO get room id from table
		//$roomId = 1;
		
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('OnlineTable ot')
					->where('ot.room_id = ?', $roomId)
					->andWhere('ot.game_flavour = ?', $flavour);
					
		$result = $query->fetchArray();
		return array(
			'zoneName' => $result[0]['zone_name'],
			'roomId' => $result[0]['room_id'],
			'gameFlavour' => $result[0]['game_flavour'],
			'machineId' => $result[0]['table_config_id']
		);
	}
	
	public function getLiveTables()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('OnlineTable');

		try
		{
			$result = $query->fetchArray();	
			$count = count($result);
		}
		catch (Exception $e)
		{
			$count = "NULL";
		}
		
		
		return $count;
	}
}