<?php

/**
 * PartnerResources
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PartnerResources extends BasePartnerResources implements Zend_Acl_Resource_Interface
{
	public function getResourceId()
	{
		return $this->resource_name;
	}
	
	public function getAllResources()
	{
		$connection = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('PartnerResources pr');
		
		try
		{
			$allResources = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'ex', true, true);
		}
		
		return $allResources;
	}
}