<?php

/**
 * Privilege
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Privilege extends BasePrivilege
{
    public static function findByResources($resources) 
    {
    	//XXX: We can execute this on any database coz all of them are common.
    	//$conn = Doctrine_Manager::getInstance()->getCurrentConnection();

        $ids = array();
        foreach($resources as $resource) 
        {
            $ids[] = $resource->id;
        }
        
        $query = Zenfox_Query::create()
    			->from('Privilege p')
    			->whereIn('p.resource_id', $ids);


    	//FIXME:: Handle Null condition
        return $query->execute();
    }
    
    public function getRole()
    {
    	return Doctrine::getTable('Role')->findOneById($this->role_id);
    }
    
    public function getResource()
    {
    	return Doctrine::getTable('Resource')->findOneById($this->resource_id);
    }
    
 /*   public function getMode()
    {
    	return $this->mode;
    }*/
    /**
     * This function gets all the privileges
     * @return unknown_type
     */
    public function getPrivileges()
    {
    	$query = Zenfox_Query::create()
    						->from('Privilege');
    						
    	$result = $query->fetchArray();
    	
    	return $result;
    						
    }
    /**
     * This function gets the privilege by Id
     * @param $id
     * @return unknown_type
     */
    public function getPrivilegeById($id)
    {
    	$privilege = Doctrine::getTable('Privilege')->findOneById($id);
    	
    	return array(
    			'id' => $privilege['id'],
    			'resourceId' => $privilege['resource_id'],
    			'resourceName' => $privilege['resource_name'],
    			'resourceType' => $privilege['resource_type'],
    			'roleId' => $privilege['role_id'],
    			'roleName' => $privilege['role_name'],
    			'roleType' => $privilege['role_type'],
    			'mode' => $privilege['mode']
    	);
    }
    
    /**
     * this function gets the privilege by Role Id
     * @param $roleId
     * @return unknown_type
     */
    public function getPrivilegesByRoleId($roleId)
    {
    	$query = Zenfox_Query::create()
    						->from('Privilege')
    						->where('role_id = ?',$roleId)
    						->orderBy('mode');
    						
    	$result = $query->fetchArray();
    	
    	return $result;
    }
    
    /**
     * This function gets the privilege by Role and Resource Id
     * @param $roleId
     * @param $resourceId
     * @return unknown_type
     */
    public function getPrivilegeByRoleIdAndResourceId($roleId, $resourceId)
    {
    	$query = Zenfox_Query::create()
    						->from('Privilege')
    						->where('role_id = ?',$roleId)
    						->where('resource_id = ?',$resourceId);
    						
    	$result = $query->fetchOne();
    	return $result;
    }
}