<?php

/**
 * PromotionSchedule
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PromotionSchedule extends BasePromotionSchedule
{
	public function getPromotions($frontendId)
	{
		$connection = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('PromotionSchedule ps')
					->where('ps.frontend_id = ?', $frontendId);
		
		try
		{
			$allPromotions = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		return $allPromotions;
	}
}