<?php

/**
 * TournamentConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TournamentConfig extends BaseTournamentConfig
{
	public function getTournamentDetails($tournamentConfigId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('TournamentConfig tc')
					->where('tc.tournament_config_id = ?', $tournamentConfigId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			
		}
		return $result[0];
	}
	
	
	
	public function gettournamentminilist()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	
		$query = Zenfox_Query::create()
				->from('TournamentConfig t');
	
	
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
	
		}
	
		return $result;
	}
	
	
	
}