<?php

/**
 * TrackerDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class TrackerDetail extends BaseTrackerDetail
{
	public function getTrackerEarnings($trackerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	    
	    $query = Zenfox_Query::create()
	    			->from ('TrackerDetail td')
	    			->where	('td.tracker_id = ?',$trackerId)
	    			->andWhere('variable_name = ?','EARNINGS');
	    			
	    $result = $query->fetchArray();	    	
	    if(!isset($result[0]['variable_value']))
	    {
	    	return 0;
	    }    
	    return $result[0]['variable_value'];
	}
	
	public function getTrackerClicks($trackerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	    
	    $query = Zenfox_Query::create()
	    			->from ('TrackerDetail td')
	    			->where	('td.tracker_id = ?',$trackerId)
	    			->andWhere('variable_name = ?','TOTAL_CLICKS');
	    			
	    $result = $query->fetchArray();
		if(!$result[0]['variable_value'])
	    {
	    	return 0;
	    }
	    return $result[0]['variable_value'];
	}
	
	public function getTrackerRegistrations($trackerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	    
	    $query = Zenfox_Query::create()
	    			->from ('TrackerDetail td')
	    			->where	('td.tracker_id = ?',$trackerId)
	    			->andWhere('variable_name = ?','TOTAL_REGISTRATIONS');
	    			
	    $result = $query->fetchArray();
		if(!$result[0]['variable_value'])
	    {
	    	return 0;
	    }
	    return $result[0]['variable_value'];
	}
	
	public function getTrackerAcquisitions($trackerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	    
	    $query = Zenfox_Query::create()
	    			->from ('TrackerDetail td')
	    			->where	('td.tracker_id = ?',$trackerId)
	    			->andWhere('variable_name = ?','TOTAL_ACQUISITIONS');
	    			
	    $result = $query->fetchArray();
		if(!$result[0]['variable_value'])
	    {
	    	return 0;
	    }
	    return $result[0]['variable_value'];
	}
	
	public function getTrackerDetails($trackerId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	    
	    $query = Zenfox_Query::create()
	    			->from ('TrackerDetail td')
	    			->where	('td.tracker_id = ?',$trackerId);
	    			
	    $result = $query->fetchArray();
	    
	    return $result;
	}
	
	public function addTrackerDetails($trackerId,$variableName,$variableValue)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
	    $partition = Doctrine_Manager::getInstance()->getConnection($conn);
	    
	    $this->tracker_id = $trackerId;
	    $this->variable_name = $variableName;
	    $this->variable_value = $variableValue;
	    
	    $this->save($partition);
	}
	
	public function getVariableValue($trackerId, $varName)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->select('td.variable_value')
					->from('TrackerDetail td')
					->where('td.tracker_id = ?', $trackerId)
					->andWhere('td.variable_name = ?', $varName);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			$filePath = '/home/zenfox/backup_player/error_logs.txt';
            $fh = fopen($filePath, 'a');
            fwrite($fh, "GETTING TRACKER DETAILS->" . $e);
            fclose($fh);
			return NULL;
		}
			
		if($result)
		{
			return $result[0]['variable_value'];
		}
		return NULL;
	}
}