<?php 
$webConfig = Zend_Registry::getInstance()->isRegistered('webConfig')? Zend_Registry::getInstance()->get('webConfig'):'null';
$viewDir = $webConfig['viewDir'];
?>

	<div class="promo">
	<form id='player-cricket-form' action="/index/index" method="post" class="zend_form">
		<div>Who will win today?</div>
		<?php
		if($this->noPlayerId)
		{
			$this->form->getElement('login')->addError('Please enter a username');
			$this->form->getElement('password')->addError('Please enter the password');
			$this->form->getElement('confirmPassword')->addError('Please enter the password');
			$this->form->getElement('email')->addError('Please enter the email');
			//print "<div>You need to be logged in to cast a vote. Please login or signup now to win exciting prizes at nationalrummy</div>";
			print "<div id='error-message'>You need to be logged in to cast a vote. Please login or signup now to win exciting prizes at nationalrummy</div>";
		}
		?>
		<table>
			<tr><td><label id="label-team-1"><?php echo $this->team_1_name;?></label></td><td><label id="label-team-2"><?php echo $this->team_2_name;?></label></td></tr>
			<tr><td><img id="image-team-1" src="<?php echo $this->team_1_image;?>"></img></td><td><img id="vs" src="/images/rummy.tld/vs.png"></img></td><td><img id="image-team-2" src="<?php echo $this->team_2_image;?>"></img></td></tr>
			<tr><td><input id="radio-team-1" type="radio" name="team" value="<?php echo $this->team_1_value;?>" /></td><td><input id="radio-team-2" type="radio" name="team" value="<?php echo $this->team_2_value;?>" /></td></tr>
		</table>
		<div>Pick the winning team, earn Rs 100/-</div>
		<input id ="cricket-form-submit" src="/images/rummy.tld/vote-now.png" type="image" name="submit"/>
	</form>
	
<?php	//echo $this->cricketForm; //<img src="<?php echo "/images/" . $viewDir. "/promo.png"" alt="" width="390" height="310">?>
	</div>
    <div class="reg" id="regForm">
    	<strong><?php echo $this->heading?></strong>
	    <?php
	    echo $this->form;
	    ?>
    <!--div class="submit"><a href="#">Submit</a></div-->
</div>
  
<div id="break">&nbsp; &nbsp; 
</div>

