<?php
$counter = 0;
if($this->messages)
{
	?>
	<table cellpadding="0" cellspacing="0" border="1" width="100%" class="paly-report-forms">
	<tr class="report-head">
	<td><div>ID</div></td>
	<td><div>Subject</div></td>
	<td><div>Date</div></td>
	</tr>
	<?php 
	foreach($this->messages as $message)
	{
		if(($counter%2) == 0)
		{
			?>
			<tr class="even-style1">
			<?php
		}
		else
		{
			?>
			<tr class="odd-style1">
			<?php
		}
		?>
		<td><div>
		<a href ="<?php echo $this->url(array('controller'=>'ticket','action'=>'reply','ticket_id'=>$message['id']));?>">
		<?php 
		echo $message['id'];
		?>
		</a></div></td>
		<td><div>
		<a href ="<?php echo $this->url(array('controller'=>'ticket','action'=>'reply','ticket_id'=>$message['id']));?>">
		<?php 
		$str = substr($message['subject'],0,20);
		echo $str;
		?>
		</a></div></td>
		<td><div>
		<?php
		echo $message['start_date']; 
		?>
		</div></td></tr>
		<?php
		$counter++;
		/*print_r($message['id']);
		echo " ";
		$str = substr($message['subject'],0,20);
		print($str);
		echo " ";
		print_r($message['start_date']);
		echo "<br>"; */
	}
}
else
{
	//echo "No Tickets";
}
?>
</table>