<?
/**
 * Main layout file. Modify this to alter whole look of the site
 */
?>
<? /* This line outputs the doctype we set in the bootstrap */ ?>
<?= $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Affiliate Zenfox</title>
  <? //$this->headLink()->appendStylesheet('/css/global.css') ?>
  <? $this->headLink()->appendStylesheet('/css/affiliate/layout.css') ?>
  <?php /*Appending the files before echoing*/?> 
  <? $this->headLink()->appendStylesheet('/SpryAssets/SpryAccordion.css') ?>
  <? $this->headLink()->appendStylesheet('/SpryAssets/SpryTabbedPanels.css') ?>
  <? $this->headLink()->appendStylesheet('/SpryAssets/SpryTabbedPanel.css') ?>
  <?php /*Echo the headlink after appending everything*/?>
  <?= $this->headLink()?>
 <?php /*Appending the files before echoing*/?>
  <? $this->headScript()->appendFile('/SpryAssets/SpryTabbedPanels.js') ?>
  <? $this->headScript()->appendFile('/SpryAssets/SpryTabbedPanel.js') ?>
  <? $this->headScript()->appendFile('/SpryAssets/SpryAccordion.js') ?>
  <? $this->headScript()->appendFile('/js/menu.js') ?>
  <? $this->headScript()->appendFile('/js/affiliate.js') ?>
  <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
</head>
<style>

</style>
<body>

<!--<div class="nav-bt-strip">&nbsp;</div>
<div id="mainDiv">
  <div id="header">
    <div class="logo">
      <h2>Playdorm</h2>
    </div>
    <img src = "/images/affiliate-headline.png" style="margin-top: 30px;" />-->
  
    
   <!--  <div class="toplinks"><a href="#">HELP</a> | <a href="#">CONTACT</a> | <a href="#">ABOUT YOURGAMES</a></div> -->
    
 <!-- </div>
  <div class="crumb"><?php //echo $this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render(); ?> </div>
  <table cellpadding="0" cellspacing="0" width="100%" border="0" id="page-layout">
      <tr>
          <td valign="top" class="left-nav">
            <?php //echo $this->navigation()->menu(); ?>
        </td>
          <td width="8px">&nbsp;</td>
          <td class="body-content" valign="top"><div class="flash-messenger"><? //$this->flashMessenger(); ?></div><? //$this->layout()->content ?>
          </td>
      </tr>
  </table>-->
  
 <!-- Including JQuery -->
 
<!-- End Body -->
  <!--<div id="footer"> 
    <p>Bingocrush</p> 
  </div>
</div>-->


<div id="main">
        <div id="header">
            <span id="logo">
			<img src = "http://bingocrush.co.uk/images/bingocrush/logo_100.png"  alt="logo"/></span> 
			<div style="float:left;border:0px solid;margin:25px 0px 0px 0px"><img src = "http://bingocrush.co.uk/images/bingocrush/affiliate-headline1.png" /></div>
			 <div id="login">
			   <?php 
				$session = new Zend_Auth_Storage_Session();
				$storedData = $session->read();
				$affiliateId = $storedData['id'];
				if($affiliateId)
				{
					?>
						<!--<div class="toplinks"><a href="/auth/logout">Logout</a></div>-->
						<div style="float:left;margin-left:-77px;border:0px solid">
						<img src = "http://bingocrush.co.uk/images/bingocrush/Affilet_baner.gif" />
						</div>
					<?php
				}else{
			?>
              <form id="form1" action="/auth/login" method="post" enctype="application/x-www-form-urlencoded">
			  <dl class="zend_form">
			  <dt id="alias-label" >
			  <label class="required" for="alias">Alias *</label>
			  </dt>
			  <dd id="alias-element" style="float:left; margin-left:0px">
			  <input type="text" value="" id="alias" name="alias"  placeholder="Username">
			  </dd>
			  <dt id="password-label">
			  <label class="required" for="password">Password *</label>
			  </dt>
			  <dd id="password-element" style="float:left; margin-left:0px">
			  <input type="password" value="" id="password" name="password" placeholder="Password"></dd>
			  <dt id="submit-label"> </dt>
			  <dd id="submit-element">
			  <input class="login-submit" type="submit" value="Submit" id="submit" name="submit">
			  </dd>
			  </dl>
			  </form>
			  <?php } ?>
           <!-- <div id="forgot">
            <a id="forgot" target="_parent" href="#">Forgot Password?</a>
            </div>-->
            </div>
			
           <div id="menu_bg">
                   <ul>
                    <li><a href="/" id="active">Home</a></li>
                    <!--<li><a href="http://affiliate.bingocrush.co.uk/auth/signup">Sign Up</a></li>-->
                    <li><a href="/scheme/product">Product</a></li>
                    <li><a href="/scheme/paymentplans">Payment Plans</a></li>
                    <li><a href="/help/faq">FAQs</a></li>
                    <li><a href="/help/contact">Contact Us</a></li>
					<?php
					if($affiliateId)
				    {
					?>
					<li><a href="/auth/logout">Logout</a></li>
					<?php } ?>
                   </ul>
           </div>   
           
        </div>
        <div id="menu_btm">
		
        </div>
		
        <div id="canves"> 
		<div id="menu" class="left-nav">
		     <?php echo $this->navigation()->menu(); ?>
		</div>
		<div id="right_body">
		<div class="flash-messenger"><?= $this->flashMessenger(); ?></div>
		<?=$this->layout()->content ?>
        </div>
        </div>
        
		 <?php
 
    /*
     * FIXME:: Set JQuery enabled in every view instead of in the layout
         */
    $this->JQuery()->enable();
    if($this->JQuery()->isEnabled())
    {
        //TODO:: Change the ui css depending on the frontend
        $this->JQuery()->setUiLocalPath($this->baseUrl()."/js/jquery/js/jquery-ui.js")
                        ->addStylesheet($this->baseUrl()."/js/jquery/css/custom-theme/jquery-ui.css");
        echo $this->JQuery();
        //echo $this->headMeta();
    }
  ?>

  <?php /*Echo the headscript after appending everything*/?>
  <?= $this->headScript()?>
  <?= $this->headMeta()?>
</div>

<script type="text/javascript">
<!--
var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
var Accordion1 = new Spry.Widget.Accordion("Accordion1");
//-->
</script>

</body>
</html>
