<?php
//echo 'pagecount' . $this->pageCount;
if ($this->pageCount): ?>
<div class="paginationControl">

<!-- First page link -->
<?php if (isset($this->previous)): ?>
<a href="<?= $this->url(array(
				'page' => $this->first, 
				'item' => $this->itemCountPerPage, 
				'toDate' => $this->toDate,
				'fromDate' => $this->fromDate)); ?>">&lt;&lt; First</a> |
<?php else: ?>
<span class="disabled">First</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?= $this->url(array(
				'page' => $this->previous, 
				'item' => $this->itemCountPerPage,
				'toDate' => $this->toDate,
				'fromDate' => $this->fromDate)); ?>">&lt; Previous</a> |
<?php else: ?>
<span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
<?php if ($page != $this->current): ?>
<a href="<?= $this->url(array(
				'page' => $page, 
				'item' => $this->itemCountPerPage,
				'toDate' => $this->toDate,
				'fromDate' => $this->fromDate)); ?>"><?= $page; ?></a> |
<?php else: ?>
<?= $page; ?> |
<?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?= $this->url(array(
				'page' => $this->next, 
				'item' => $this->itemCountPerPage,
				'toDate' => $this->toDate,
				'fromDate' => $this->fromDate)); ?>">Next &gt;</a>
<?php else: ?>
<span class="disabled">Next &gt;</span>
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
<a href="<?= $this->url(array(
				'page' => $this->last, 
				'item' => $this->itemCountPerPage,
				'toDate' => $this->toDate,
				'fromDate' => $this->fromDate)); ?>">Last &gt;&gt;</a>
<?php else: ?>
<span class="disabled">Last</span>
<?php endif; ?>
</div>
<?php endif; ?>