<?php
 echo $this->form;
 if($this->paginator)
{
	if (count($this->paginator))
	{
		$linkArray = array();
		foreach($this->contents as $playerData)
		{
			$linkArray[$playerData['Player Id']] = array(
										'controller' => 'player',
										'action' => 'view',
										'playerId' => $playerData['Player Id']);
		}
		$this->table($this->contents, array('Player Id'), $linkArray);
		
	}

	$pages = get_object_vars($this->paginator->getPages('Sliding'));
	$this->pagination($pages, array(
							'field' => $this->searchField,
							'str' => $this->searchStr));
}
?>