
    <div id="inner-welcome">
      <h2><strong>Welcome Back, <?php echo $this->success["user_name"]?>!</strong></h2></div>
<div id="inner-welcome-back">
<div id="inner-welcome-back-left" class="left">
  <p>This is your personal TAASHTime account. You can play, deposit funds, edit your profile, check your game history and also contact our support team. Enjoy TAASHTime!</p>
  <p><img src="/css/rummy.tld/images/cards-inner.png" width="184" height="168" alt="Cards - Inner!"></p>
</div>
<div id="inner-welcome-back-right" class="right">
  <p><a href="/game"><img src="/css/rummy.tld/images/start-playing.png" width="178" height="57" alt="Start Playing"></a></p>
  <p>&nbsp;</p>
  <p><a href="/banking/deposit"><img src="/css/rummy.tld/images/deposit-funds.png" width="175" height="55" alt="Deposit Funds"></a></p><div id="get-blurb" class="right"><img src="/css/rummy.tld/images/bonus-blurb.png" width="85" height="83" alt="Get Rs. 25/-!" /></div>
</div>
</div>
<div class="clear"></div>
<div id="inner-buttons-box">
<div class="left" id="button-edit-profile"><strong><a href="/auth/edit">Edit Your Profile</a></strong></div>
<div class="right" id="button-support"><strong><a href="/ticket/create">Contact Support</a></strong></div>
<div class="clear"></div>
 <p>&nbsp;</p>
<div class="left" id="button-password"><strong><a href="/auth/changepwd">Change Your Password</a></strong></div>
<div class="right" id="button-funds"><strong><a href="/banking/deposit">Deposit Funds</a></strong></div>

</div>
<div class="clear"></div>
<div id="game-history-top"></div>
<div id="game-history">
  <table width="100%" border="0" cellspacing="0" cellpadding="0" id="game-history-table">
    <tr>
      <th><strong>Date</strong></th>
      <th><strong>Game</strong></th>
      <th><strong>Players</strong></th>
      <th><strong>Winner</strong></th>
      <th><strong>Amount</strong></th>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
    <tr>
      <td>15-June-2011</td>
      <td>Rummy</td>
      <td>Ricky, Bob, Lucy and You</td>
      <td>You!</td>
      <td>Rs. 250/-</td>
    </tr>
  </table> 
  <a href="#"><strong>More Records</strong></a></div>

