<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'privacypolicy'));?>">Privacy Policy</a>
    <a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'terms'));?>">Terms of Service&nbsp;</a>
	<a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'rules'));?>">Game Rules&nbsp;</a>
	<a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'legal'));?>">Legality&nbsp;</a>
	<a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'index', 'action' => 'sitemap'));?>">Site Map&nbsp;</a>
	<a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'contact'));?>">Contact Us&nbsp;</a>
	<a style="text-decoration: none;  color:white;">|</a>
<a style="text-decoration: none;  color:white;" href="<?=$this->url(array('controller' => 'content', 'action' => 'withdrawterms'));?>">Withdrawal Terms&nbsp;</a>
