<?php
                $frontendId = Zend_Registry::getInstance()->get('frontendId');
                $session = new Zend_Auth_Storage_Session();
                $store = $session->read();
                $playerId = $store['id']?$store['id']:-1;
                $frontendId = Zend_Registry::getInstance()->get('frontendId');
                $session = new Zend_Auth_Storage_Session();
                $store = $session->read();
                $playerId = $store['id']?$store['id']:-1;

//if($playerId>0)
//{
$siteHttpUrl = "http://". $_SERVER['HTTP_HOST'];
$attributes = array (
        'width' => '100%',
		'height' => '100%',
		'resizable'=>'yes',
		'scrollbars'=>'no',
     );
//$chat = $siteHttpUrl. "/games/container/components/chat/chat.swf";
//$games = $siteHttpUrl. "/games/container/components/games/games.swf";

//BINGO
if($this->gameName == 'bingo')
{
	$xmlConfig = $siteHttpUrl . "/games/container/config_bingo.txt";
	$gameConfig = $siteHttpUrl . "/games/multi-player/bingo/config.txt";
	$swfFile = $siteHttpUrl . "/games/multi-player/bingo/game.swf";
	$logId = 123;
	$sessionId = $this->phpsessid;
	$login = $this->login;
	$machineId = $this->machineId;
	$flavour = $this->flavour;
	$playerId = $this->playerId;
	$passKey = md5($machineId . md5($sessionId));
	$containerSwfFile = $siteHttpUrl . "/games/container/container_bingo.swf";
	//xml_config=Config.txt&
	//game_config=../multi-player/Bingo/Config.txt&
	//game_swf_path=../multi-player/Bingo/BingoContainer.swf&
	//log_id=123&
	//session_id=123&
	/*player_id=10&
	login=yaswanth|1|RU_US&
	pass_key=iiit123&game_id=1*/
	//}
	$flashVarString = 'game_id='.$machineId.'&login='.$login.'|'.$machineId.'|'.$flavour.'&xml_config='.$xmlConfig.'&game_swf_path='.$swfFile.'&game_config='.$gameConfig.'&log_id='.$logId.'&session_id='.$sessionId.'&player_id='.$playerId.'&pass_key='.$passKey;
	$params = array('FlashVars' => $flashVarString);
	?>
	
	
	<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="100%" height="100%" id="GameContainer" align="middle">
      <param name="allowScriptAccess" value="sameDomain" />
      <param name="allowFullScreen" value="false" />
      <!--param name="movie" value="/games/multi-player/lobby/WebContainerLobby.swf" />
      <param name="FlashVars" value="xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" /-->
      <param name="movie" value="/games/container/container.swf" />
      <param name="FlashVars" value="<?=$flashVarString?>" />
      <param name="quality" value="high" />
      <param name="bgcolor" value="#ffffff" />
      <param name="wmode" value="transparent" />
      <!--embed src="/games/multi-player/lobby/WebContainerLobby.swf" flashVars = "xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" quality="high" bgcolor="#000000"-->
      <embed src="/games/container/container_bingo.swf" flashVars = "<?=$flashVarString?>" bgcolor="#000000"
                  width="100%" height="100%" name="Container" align="middle"
                  play="true"
                  loop="false"
                  quality="high"
                  allowScriptAccess="sameDomain"
                  type="application/x-shockwave-flash"
                  pluginspage="http://www.adobe.com/go/getflashplayer" 
                  wmode="transparent"
                  >
              </embed>
              </object>
	
	
	<?php 
	
}
else
{
	$winner = $siteHttpUrl. "/games/container/components/winner/winner.swf";
	$market = $siteHttpUrl. "/games/container/components/market/market.swf";
	$placeHolder = $siteHttpUrl. "/games/container/components/placeholder/placeholder.swf";
	//$invitefriends = $siteHttpUrl. "/games/container/components/invitefriends/invitefriends.swf";
	$profile = $siteHttpUrl. "/games/container/components/profile/profile.swf";
	//$guide = $siteHttpUrl. "/games/container/components/guide/guide.swf";
	$machineId = $this->machineId;
	$flavour = $this->flavour;
	$amountType = $this->amountType;
	$swfFile = $siteHttpUrl . $this->swfFile; //$siteHttpUrl . "/games/single-player/" . $flavour . "/" . $this->swfFile;
	$containerSwfFile = $siteHttpUrl . "/games/container/container.swf";
	$login = $this->login;
	$currency = $this->currency?$this->currency:"USD";
	$xmlConfig = $siteHttpUrl. "/games/container/config.txt";
	$gameConfig = $siteHttpUrl . $this->configFile;//$siteHttpUrl . "/games/single-player/" . $flavour . "/" . $flavour . "_" . $machineId . ".txt";
	$guideConfig = $siteHttpUrl . $this->guideConfig;
	$sideSlide =  $siteHttpUrl . '/games/container/components/sideslide/sideslide.swf';
	$frontendId = Zend_Registry::getInstance()->get('frontendId');
	$locale = Zend_Registry::getInstance()->get('Zend_Locale');;
	$flashVarString = 'game_id='.$machineId.'&game_flavour='.$flavour.'&login='.$login.'|'.$machineId.'|'.$flavour.'&xml_config='.$xmlConfig.'&amount_type='.$amountType.'&currency='.$currency.'&frontend_id='.$frontendId.'&locale='.$locale.'&game_swf_path='.$swfFile.'&game_config='.$gameConfig.'&winner='.$winner.'&market='.$market.'&profile='.$profile.'&placeholder='.$placeHolder.'&seat_index='.$this->seatIndex;//.'&guide_config='.$guideConfig.'&guide='.$guide.'&sideslide='.$sideSlide;
	$params = array('FlashVars' => $flashVarString);
	echo $this->htmlFlash($containerSwfFile,$attributes,$params);
}

//OLD CODE START
//$passKey = md5($machineId . md5($this->phpsessid));
/*if($flavour=='rummy_test')
{
	$flashVarString = 'game_id='.$machineId.'&game_flavour='.$flavour.'&login='.$login.'|'.$machineId.'|'.$flavour.'&pass_key='.$passKey.'&xml_config='.$xmlConfig.'&amount_type='.$amountType.'&currency='.$currency.'&frontend_id='.$frontendId.'&locale='.$locale.'&game_swf_path='."/games/multi-player/rummy/Rummy.swf".'&game_config='."/games/multi-player/rummy/GameConfig.txt".'&chat='.$chat;//.'&winner='.$winner;

	//$containerSwfFile = $siteHttpUrl . "/games/multi-player/rummy/Container.swf";
$params = array('FlashVars' => $flashVarString, 'SCALE' => 'default');
}
else
{
	$flashVarString = 'game_id='.$machineId.'&game_flavour='.$flavour.'&login='.$login.'|'.$machineId.'|'.$flavour.'&pass_key='.$passKey.'&xml_config='.$xmlConfig.'&amount_type='.$amountType.'&currency='.$currency.'&frontend_id='.$frontendId.'&locale='.$locale.'&game_swf_path='.$swfFile.'&game_config='.$gameConfig.'&chat='.$chat;
$params = array('FlashVars' => $flashVarString);
}*/
//OLD CODE END
//$params = array('FlashVars' => $flashVarString);
//echo $this->htmlFlash($containerSwfFile,$attributes,$params);

//BHARTHI CODE
/*
$xmlConfig = "/games/container/config.txt";
$containerSwfFile = "/games/container/container.swf";
$login = $this->login;
$machineId = $this->machineId;
$flavour = $this->flavour;
$amountType = $this->amountType;
$passKey = md5($machineId . md5($this->phpsessid));

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml">
	<head>	 	
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"></script>
		<script type="text/javascript" src="http://connect.facebook.net/en_US/all.js"></script>
	</head>
	<body>
		<div id="fb-root"></div>
		<div id="flashContent">
			<h1>You need at least Flash Player 9.0 to view this page.</h1>
			<p><a href="http://www.adobe.com/go/getflashplayer"><img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /></a></p>
		</div>  
		<script type="text/javascript">
			alert("Flashvars");
			//Dynamic publishing with swfObject 
			var flashvars = {};
			flashvars.game_id = '<?php echo $machineId; ?>';
			flashvars.game_flavour = '<?php echo $flavour; ?>';
			flashvars.login = '<?php echo $login.'k'; ?>';
			flashvars.pass_key = '<?php echo $passKey; ?>';
			flashvars.xml_config = '<?php echo $xmlConfig; ?>';
			flashvars.amount_type = '<?php echo $amountType; ?>';
			flashvars.currency = 'INR';
			flashvars.frontend_id = '1';
			flashvars.locale = 'en_IN';
			//A 'name' attribute with the same value as the 'id' is REQUIRED for Chrome/Mozilla browsers
			swfobject.embedSWF("<?php echo $containerSwfFile; ?>", "flashContent", "800", "600", "9.0", null,flashvars, null, {name:"flashContent"}); 			
		</script>
		<h1>TaashTime</h1>
	</body>
</html>
*/?>
