<div class = "xyz">
<?php
if($this->paginator)
{
	if(count($this->paginator))
	{
		//Zenfox_Debug::dump($this->contents, 'contents');
		$currentPageNumber = $this->paginator->getCurrentPageNumber();
		$itemsPerPage = $this->paginator->getItemCountPerPage();
		$counter = (($currentPageNumber - 1) * $itemsPerPage) + 1;
		$count = 0;
		$commentNo = 0;
		foreach($this->contents as $commentData)
		{
			?>
			<table cellpadding="0" cellspacing="0" border="1" width="100%" class="palys-report-forms">
			<tr>
			<td>
			<?php
			echo '<b>' . '#' . $counter . '</b>';
			?>
			</td>
			<td>
			<?php
			
			foreach($commentData as $index => $value)
			{
				if($index == 'Posted')
				{
					echo $value;
					?>
					</td>
					</tr>
					<?php
				}
				else
				{
					?>
					<tr>
					<td width = "45%">
					<?php
					if($index == 'User Name')
					{
						echo '<b>' . $value . '</b>' . ' Says';
						
					}
					else
					{
						$str = '';
						$temp = 0;
						for($i = 0; $i < strlen($value); $i++)
						{
							if($value[$i] == ' ')
								$temp++;
							if(($value[$i] == ' ') && ($temp == 3))
								break;
							$str = $str . $value[$i];
						}
						?>
						<a class="dots" style="TEXT-DECORATION: NONE; cursor: pointer;">
						<span onClick='ShowText("<?php echo $commentNo?>"); return false;' >
						<?php 
						echo $str . '....';
						?>
						</span>
						</a>
						
						<span id="<?php echo $commentNo?>" class="box" onClick='HideText("<?php echo $commentNo?>"); return false;' style="display:none">
						<?php echo $value;?>
						</span>

						<?php 
						/*$len = 1;
						$str = '';
						for($i = 1; $i <=strlen($value); $i++)
						{
							$str = $str . $value[$i - 1];
							$len++;
							$temp = $i + 1;
							if(($len > 3) || ($temp > strlen($value)))
							{
								echo $str;
								$str = '';
								$len = 1;
							}
						}*/
						$commentNo++;
					}
					?>
					</td>
					</tr>
					<?php
				}
			}
			$count++;
			$counter++;
			?>
			</table>
			<?php
		}
		?>
		<?php 
		//$this->table($this->contents);
		echo $this->paginationControl($this->paginator, 'Sliding', 'commentsPaginator.phtml', array(
																					'pageAddress' => $this->pageAddress));
	}
}
else
{
	?></div>
	<div class = "palys-report-forms">
	No comments on this page.
<?php
}
?></div>
<?php 
if($this->jsScript)
{
	?>
	<script type="text/javascript" src="/js/jquery/js/jquery.js"></script>
	<script type="text/javascript" src="/js/jquery/js/jquery-ui.js" /></script>
	<script type="text/javascript" src="/js/jquery_comments.js" /></script>
	
	<?php
}
