<script type = "text/javascript">
	window.location ="http://molv3.molsolutions.com/api/login/u_module/purchase.aspx"
                   + "?MerchantID=" + '<?=$this->merchantID?>'
                   + "&Amount=" + '<?=$this->amount?>'
                   + "&MRef_ID=" + '<?=$this->mRef_ID?>'
                   + "&Description=" + '<?=$this->description?>'
                   + "&Currency=" + '<?=$this->currency?>'
                   + "&HeartBeat=" + '<?=$this->heartBeat?>'
                   + "&Signature=" + '<?=$this->signature?>';
</script>