<div class="fluid-content">
	<div class="head1">Banking Details</div>
    <p>Ace2Jak believes in providing the best Online Rummy service to its customers. Along side its world-class Rummy experience, Ace2Jak also provides a varied variety of ways to buy Cash and Coins. 
    The varied modes of payments and the plethora of banks supporting us emphasizes  on the trustworthiness of the site. We take payments in the form of:</p>
    <ul>
    	<li>Netbanking</li>
      	<li>Direct Credit</li>
      	<li>Credit Cards </li>
    </ul>
    
    <div class="head2">Netbaking</div>
    <p>Ace2Jak offers Netbaking services to a number of banks in India. The following are the banks that support us.</p>
    <table border="1" cellspacing="0" cellpadding="0"   >
    	<tr>
    		<th>Payment    Name</th>
          	<th>Payment    Method</th>
          	<th>Support</th>
          	<th>purchase    Time</th>
        </tr>
        <tr>
          	<td>Axis Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttaxis_logo.gif" alt="axis_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Allahabad Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttallahabad_logo.gif" alt="allahabad_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>The Bank of Rajasthan</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttrajasthan_logo.gif" alt="rajasthan_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>South Indian Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttsouthindianbank_logo.gif" alt="southindianbank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Vijaya Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttvijayabank_logo.gif" alt="vijayabank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Bank of Baroda</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofbaroda_logo.gif" alt="bankofbaroda_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Federal Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttfederal_logo.gif" alt="federal_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Dhanlaxmi Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttdhanlaxmi_logo.gif" alt="dhanlaxmi_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Deutsche Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttdeutschebank-logo.gif" alt="deutschebank-logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Bank of Bahrain &amp; Kuwait</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofbahrain-logo.gif" alt="bankofbahrain-logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Karnataka Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttkarnatakabank_logo.gif" alt="karnatakabank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Oriental Bank of Commerce</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttobc_logo.gif" alt="obc_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Standard Chartered</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttstandard_logo.gif" alt="standard_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Indian Overseas Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttiob_logo.gif" alt="iob_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>ICICI Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/tticici_logo.gif" alt="icici_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Union Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttunionbank_logo.gif" alt="unionbank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Yest Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttyesbank_logo.gif" alt="yesbank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Corporation Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttcorporationbank_logo.gif" alt="corporationbank_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>Bank of India</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofindia_logo.gif" alt="bankofindia_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
        <tr>
          	<td>HDFC Bank</td>
          	<td><img border="0" width="99" height="37" src="/css/rummy.tld/images/tthdfc_logo.gif" alt="hdfc_logo" /></td>
          	<td>Yes </td>
          	<td>Instant</td>
        </tr>
    </table>
    <div style="clear: both;"></div>
    <div class="head2">Credit Card</div>
    <p>Credit Cards, the most widely used payment method in the  world is supported by Ace2Jak. We accept Credit cards from different services  around the world through our various payment channels. Currently our processors  support:</p>
    <table border="1" cellspacing="0" cellpadding="0" width="100%">
    	<tr>
          	<th colspan="2"  > Processor Type </th>
        </tr>
        <tr>
          	<td width="319" >VISA</td>
          	<td width="319" ><img src="/css/rummy.tld/images/ttvisa.gif" width="60" height="36" /></td>
        </tr>
        <tr>
          	<td width="319" >Master Card</td>
          	<td width="319" ><img src="/css/rummy.tld/images/ttmastercard_s.gif" width="60" height="36" /></td>
        </tr>
        <tr>
          	<td width="319" >American express</td>
          	<td width="319" ><img src="/css/rummy.tld/images/ttamerican.gif" width="60" height="36" /></td>
        </tr>
      </table>
</div>
