<?php

/**
 * Account
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Account extends BaseAccount
{
	public function getdetails($playerid)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	
		$query = Zenfox_Query::create()
		->from('Account a')
		->where('a.player_id = ?',$playerid);
	
		$result = $query->fetchArray();
		
		//Zenfox_Debug::dump($result);exit();
		return $result[0];
	}
	
	
	public function insertaccount($playerid,$first_name,$last_name,$sex,$dateofbirth,$address,$city,$state,$country,$pin,$phone,$email)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);

		$Query = Doctrine_Query::create()
			->update('Account a')
			->set('a.first_name', '?', $first_name)
			->set('a.last_name', '?', $last_name)
			->set('a.email', '?', $email)
			->set('a.sex', '?', $sex)
			->set('a.dateofbirth', '?', $dateofbirth)
			->set('a.address','?', $address)
			->set('a.city', '?', $city)
			->set('a.state', '?',$state)
			->set('a.country', '?', $country)
			->set('a.pin', '?', $pin)
			->set('a.phone', '?', $phone)
			->set('a.question', '?', "")
			->set('a.hint', '?', "")
			->set('a.answer', '?', "")
			->set('a.newsletter', '?', "")
			->set('a.promotions', '?', "")
			->set('a.black_list', '?', "")
			->where('a.player_id =?', $playerid);
		try {
			$Query->execute();
				
		}
		catch(Exception $e)
				{
			echo $e;
		}
		
	}
	
	
}