<?php

/**
 * AmsSchemeType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class AmsSchemeType extends BaseAmsSchemeType
{
	public function getAmsSchemeTypes()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('AmsSchemeType');
					
		$result = $query->fetchArray();
		return $result;
	}
	
	public function getAmsSchemeType($id)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$amsSchemeType = Doctrine::getTable('AmsSchemeType')->findOneByScheme_type($id);
		
		return array(
				'schemeType' => $amsSchemeType['scheme_type'],
				'schemeName' => $amsSchemeType['scheme_name'],
				'schemeDescription' => $amsSchemeType['scheme_description'],
				'criteria' => $amsSchemeType['criteria'],
				'creditingFactor' => $amsSchemeType['crediting_factor']);
	}
}