<?php

/**
 * BingoFixedPot
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class BingoFixedPot extends BaseBingoFixedPot
{
	public function getData($gameId)
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		//$result = Doctrine::getTable('FixedPot')->findByGameId($gameId)->orderBy('part_id');
		$query = Zenfox_Query::create()
					->from('BingoFixedPot fp')
					->where('fp.game_id = ?', $gameId)
					->orderBy('fp.id');
					
		$result = $query->fetchArray();
		$fixedPotData = array();
		$i = 0;
		foreach($result as $data)
		{
			$fixedPotData[$i]['fixedPotId'] = $data['id'];
			$fixedPotData[$i]['gameId'] = $data['game_id'];
			$fixedPotData[$i]['partId'] = $data['part_id'];
			$fixedPotData[$i]['callNumber']= $data['call_number'];
			$fixedPotData[$i]['realAmount']= $data['real_amount'];
			$fixedPotData[$i]['bbsAmount'] = $data['bbs_amount'];
			$i++;
		}
		return $fixedPotData;
	}
}