<?php

/**
 * BingoRecentWinners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class BingoRecentWinners extends BaseBingoRecentWinners
{
	public function getbingorecentwinnerslist($roomId)
	{
		$connection = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
				
    		$query = Zenfox_Query::create()
    					->select('brw.login as Login , sum(brw.real_won+brw.bbs_won) as Won')
    					->from('BingoRecentWinners brw')
    					->where('brw.room_id =?',$roomId)
    					->groupBy('brw.gamelog_id')
    					->orderBy('brw.gamelog_id desc')
    					->limit('20');
    		
    		try
    		{
    			$result = $query->fetchArray();
    		}
    		catch(Exception $e)
    		{
    			echo "No Recent Winners";
    		}
    		
    		return $result;
    		
	}
}