<?php

/**
 * BingoPjp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class BingoPjp extends BaseBingoPjp
{
	public function getPjpByGameId($gameId)
	{
		$connection = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('BingoPjp bp')
					->where('bp.game_id = ?', $gameId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		$pjpIds = array();
		if($result)
		{
			foreach($result as $bingoPjpData)
			{
				$pjpIds[] = $bingoPjpData['pjp_id'];
			}
		}
		return $pjpIds;
	}
	
	public function getPjpDataByGameId($gameId)
	{
		$connection = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('BingoPjp bp')
					->where('bp.game_id = ?', $gameId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			return false;
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		
		return $result[0];
	}
}