<?php

/**
 * DepositBonus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class DepositBonus extends BaseDepositBonus
{
	public function getBonusPercentage($amount)
	{
		$frontendId = Zend_Registry::get('frontendId');
		
		$connection = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('DepositBonus db')
					->where('db.min_amount <= ?', $amount)
					->andWhere('db.max_amount >= ?', $amount)
					->andWhere('db.frontend_id = ?', $frontendId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
			return NULL;
		}
		return $result[0]['bonus_percentage'];
	}
}