<?php

/**
 * EmailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class EmailQueue extends BaseEmailQueue
{
	public function addEmailQueue($userId, $userType, $emailList, $templateId, $message, $campaignName = NULL)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$masterConnection = Doctrine_Manager::getInstance()->getConnection($conn);

		$date = new Zend_Date();
		$currentTime = $date->get(Zend_Date::W3C);
		
		$frontendId = Zend_Registry::get('frontendId');
		//echo $frontendId;
		$this->user_id = $userId;
		$this->user_type = $userType;
		$this->email_list = $emailList;
		$this->template_id = $templateId;
		$this->frontend_id = $frontendId;
		$this->status = 'UNPROCESSED';
		$this->message = $message;
		$this->email_req_time = $currentTime;
		$this->campaign_name = $campaignName;
		
		try
		{
			$this->save($masterConnection);
		}
		catch(Exception $e)
		{
			//Zenfox_Debug::dump($e, 'exception', true, true);
		}
	}
	
	
	public function addadminEmailQueue($userId, $userType, $emailList, $templateId,  $message, $frontendId =null, $Priority = 7)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$masterConnection = Doctrine_Manager::getInstance()->getConnection($conn);
	
		$date = new Zend_Date();
		$currentTime = $date->get(Zend_Date::W3C);
	
	
		$this->user_id = $userId;
		$this->user_type = $userType;
		$this->email_list = $emailList;
		$this->template_id = $templateId;
		$this->frontend_id = $frontendId;
		$this->status = 'UNPROCESSED';
		$this->priority = $Priority;
		$this->message = $message;
		$this->email_req_time = $currentTime;
	
		try
		{
			$this->save($masterConnection);
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e->getMessage());
		}
	}
	
	public function getcampaignstatus($campaignname)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
	
		$query = Zenfox_Query::create()
		->select('e.status , e.campaign_name , count(e.id) ')
		->from('EmailQueue e')
		->Where('e.campaign_name = ?' ,$campaignname)
		->groupBy('e.status');
	
		try{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			echo $e;
		}
	
		$length = count($result);
		$index =0;
	
		while($length>0)
		{
			$list[$index][campaign_name] = $result[$index][campaign_name];
			$list[$index][status] = $result[$index][status];
			$list[$index][count] = $result[$index][count];
				
			$length--;
			$index++;
		}
	
		return $list;
	
	}
}