<?php

/**
 * FrontendVariables
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class FrontendVariables extends BaseFrontendVariables
{
public function insert($data)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$frontendvariables = new FrontendVariables();
		
		//Zenfox_Debug::dump($data, 'data', true, true);
		$variableData = $this->getData($data['frontend_id'], $data['variableName']);
		$varId = $variableData['frontend_id'];
		if($varId)
		{
			$update = $this->update($data);
			return $update;
		}
		else
		{
			/*if($data['variableName'] == 'freeMoney')
			{
				$accountVariable->var_id = -4;
			}*/
			
			$frontendvariables->frontend_id = $data['frontend_id'];
			$frontendvariables->variable_name = $data['variableName'];
			$frontendvariables->variable_value = $data['variableValue'];
			$frontendvariables->variable_type = 'STRING';
			try
			{
				$frontendvariables->save();
			}
			catch(Exception $e)
			{
				echo $e->getMessage();
				return false;		
			}
			return true;
		}
		//Zenfox_Debug::dump($data, 'data', true, true);
	}
	
	public function update($data)
	{
		//Zenfox_Debug::dump($data, 'data', true, true);
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->update('FrontendVariables fv')
					->set('fv.variable_value', '?', $data['variableValue'])
					->where('fv.frontend_id = ?', $data['frontend_id'])
					->andWhere('fv.variable_name = ?', $data['variableName']);
					
		try
		{
			$query->execute();
		}
		catch(Exception $e)
		{
			echo $e;
			return false;
		}
		return true;
	}
	
	public function getData($frontendId, $varName)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('FrontendVariables fv')
					->where('fv.frontend_id = ?', $frontendId)
					->andWhere('fv.variable_name = ?', $varName);
					
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
		}
		if($result)
		{
			return array(
				'frontend_id' => $result[0]['frontend_id'],
				'variableValue' => $result[0]['variable_value']
			);
		}
		return false;
	}
}