<?php

/**
 * GmsGroupGmsMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class GmsGroupGmsMenu extends BaseGmsGroupGmsMenu
{

	public function addGroupMenu($groupId,$menuId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$this->gms_group_id = $groupId;
		$this->gms_menu_id = $menuId;
		$this->save($partition);
	}
	
	public function getMenus($groupId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
				->from('GmsGroupGmsMenu g')
				->where('g.gms_group_id = ?' , $groupId);
		
		$result = $query->fetchArray();
		
		$menuArray = array();
		if($result)
		{
			foreach($result as $menu)
			{
				$menuArray[] = $menu['gms_menu_id'];
			}
		}
		if( $menuArray )
		{
			$query = Zenfox_Query::create()
					->from('GmsMenu m')
					->whereIn('m.id',$menuArray);
		
			$result = $query->fetchArray();		
			return $result;
		}
	}
	
	public function deleteGroupMenu($groupId,$menuId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
			
		$query = Zenfox_Query::create()
					->delete('GmsGroupGmsMenu g')
					->where('g.gms_menu_id = ?',$menuId)
					->andWhere('g.gms_group_id = ?' , $groupId);
		
		$ans = $query->execute();
	}
}