<?php

/**
 * GmsGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class GmsGroup extends BaseGmsGroup
{
	public function getAllGroups()
	{
		$query = Zenfox_Query::create()
				->from(GmsGroup);
		
		try{
			
			return $query->fetchArray();
		}catch(Exception $e){
			return false;
		}	
	}
	
	public function createGroup($data)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$this->name = $data['name'];
		$this->description = $data['desc'];
		$this->save($partition);
		
		$query = Zenfox_Query::create()
					->from('GmsGroup g')
					->orderBy('g.id DESC')
					->limit(1);
		$result = $query->fetchArray();
		if($result)
			$groupId = $result[0]['id'];
		else
			$groupId = 1;
		
		if($data['menus'])
		{
			foreach($data['menus'] as $menu)
			{
				$groupMenu = new GmsGroupGmsMenu();
				$insert = $groupMenu->addGroupMenu($groupId,$menu);
			}
		}
		
		if($data['csrs'])
		{
			foreach($data['csrs'] as $csr)
			{
				$csrGroup = new CsrGmsGroup();
				$insert = $csrGroup->addCsrGroup($groupId,$csr);
			}
		}
		
		return $insert;
		
	}
	
	public function getInfo($id)
	{
		$query = Zenfox_Query::create()
				->from('GmsGroup g')
				->where('g.id = ?' , $id);
				
		try{
			$result = $query->fetchArray();
			return $result;
		}catch(Exception $e)
		{
			return false;
		}
	}	
	
	
	public function editGroup($id,$data,$preCsrs,$preMenus)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$partition = Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		if($preCsrs)
		{
			foreach($preCsrs as $pre)
	    	{
	    		$state=1;
	    		if($data['addedcsrs'])
	    		{
	    			foreach($data['addedcsrs'] as $csr)
	    			{
	    				if ($pre['id'] == $csr)
	    				{
	    					$state=0;
	    					break;
	    				}
	    			}
	    		}
	    		if($state)
	    		{
	    			$csrGroup = new CsrGmsGroup();
	    			$result = $csrGroup->deleteCsrGroup($pre['id'],$id);
	    		}
	    	}
    	}
		if($data['csrs'])
    	{
			foreach($data['csrs'] as $csr)
			{
				$csrGroup = new CsrGmsGroup();
				$result = $csrGroup->addCsrGroup($id,$csr);
			}
    	}
    	
		if($preMenus)
		{
			foreach($preMenus as $pre)
	    	{
	    		$state=1;
	    		if($data['addedmenus'])
	    		{
	    			foreach($data['addedmenus'] as $menu)
	    			{
	    				if ($pre['id'] == $menu)
	    				{
	    					$state=0;
	    					break;
	    				}
	    			}
	    		}
	    		if($state)
	    		{
	    			$menuGroup = new GmsGroupGmsMenu();
	    			$result = $menuGroup->deleteGroupMenu($id,$pre['id']);
	    		}
	    	}
    	}
		if($data['menus'])
    	{
			foreach($data['menus'] as $menu)
			{
				$menuGroup = new GmsGroupGmsMenu();
				$result = $menuGroup->addGroupMenu($id,$menu);
			}
    	}
    	
		$query = Doctrine_Query::create()
    			->update('GmsGroup g')
    			->set('g.name', '?', $data['name'])
    			->set('g.description', '?', $data['desc'])
    			->where('g.id = ?', $id);
		$result = $query->execute();
		return $result;
    
	}
}