<?php

/**
 * LeaderBoardConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class LeaderBoardConfig extends BaseLeaderBoardConfig
{
	public function getactiveleaderbords()
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('LeaderBoardConfig lbc')
					->where('lbc.status = ?','STARTED')
					->orderby('lbc.start_time asc' )
					->limit(1);
		
		$result = $query->fetchArray();
		
		return $result;
	}
	
	public function getleaderboardconfbyId($leaderboardId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('LeaderBoardConfig lbc')
					->where('lbc.leader_board_id = ?',$leaderboardId);
		try {
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			echo $e;
			exit;
		}
		
		return $result;
	}
}