<?php

/**
 * MobileBonus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class MobileBonus extends BaseMobileBonus
{
	public function getBonusByLevel($levelId, $gameGroupId)
	{
		$connection = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('MobileBonus mb')
					->where('mb.level_id = ?', $levelId)
					->andWhere('mb.gamegroup_id = ?', $gameGroupId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
		
		return $result[0];
	}
}