<?php

/**
 * Newsletter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Newsletter extends BaseNewsletter
{
	public function addNewEmail($email)
	{
		$frontendId = Zend_Registry::get('frontendId');
		
		$isEmailExist = $this->_checkEmailExist($email, $frontendId);
		
		if($isEmailExist)
		{
			return "You have already subscribed";
		}
		
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		$master = Doctrine_Manager::getInstance()->getConnection($conn);
		
		$date = new Zend_Date();
		$currentTime = $date->get(Zend_Date::W3C);
		
		$this->email = $email;
		$this->frontend_id = $frontendId;
		$this->subscription_date = $currentTime;
		
		try
		{
			$this->save($master);
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'ex', true, true);
		}
		
		return "Thank you for subscribing newsletter on RummyBazaar.";
	}
	
	private function _checkEmailExist($email, $frontendId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('Newsletter n')
					->where('n.email = ?', $email)
					->andWhere('n.frontend_id = ?', $frontendId);
		
		try
		{
			$result = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'ex', true, true);
		}
		
		return $result;
	}
}