<?php

/**
 * OnlineTournaments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class OnlineTournaments extends BaseOnlineTournaments
{
	public function getOnlineDetails($tournamentId)
	{
		$conn = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
					->from('OnlineTournaments ot')
					->where('ot.tournament_id = ?', $tournamentId);
		
		$result = $query->fetchArray();
		if($result)
		{
			return $result[0];
		}
		return 0;
		//Zenfox_Debug::dump($result, 'result', true, true);
	}
}