<?php

/**
 * Partners
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class Partners extends BasePartners implements Zend_Acl_Role_Interface
{
	public function getRoleId()
	{
	
	}
	
	public function getAllPartners()
	{
		$connection = Zenfox_Partition::getInstance()->getMasterConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
	
		$query = Zenfox_Query::create()
					->from('Partners');
	
		try
		{
			$allPartners = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
		}
	
		return $allPartners;
	}
	
	public function createAuthSession($sessionData)
	{
		$authSession = new Zenfox_Auth_Storage_Session();
		$authSession->write($sessionData);
	}
	
	public function deleteAuthSession()
	{
		$authSession = new Zenfox_Auth_Storage_Session();
		$authSession->clear();
	}
}