<?php

/**
 * PartnerPrivileges
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class PartnerPrivileges extends BasePartnerPrivileges
{
	public function getAllPrivileges()
	{
		$connection = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($connection);
		
		$query = Zenfox_Query::create()
					->from('PartnerPrivileges pp');
		
		try
		{
			$allPrivileges = $query->fetchArray();
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'ex', true, true);
		}
		
		return $allPrivileges;
	}
}