<?php

/**
 * roomsSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class RoomsSession extends BaseRoomsSession
{
	public function getSessionData($bingoRoomId)
	{
		$conn = Zenfox_Partition::getInstance()->getCommonConnection();
		Doctrine_Manager::getInstance()->setCurrentConnection($conn);
		
		$query = Zenfox_Query::create()
						->from('RoomsSession rs')
						->where('rs.room_id = ?', $bingoRoomId)
						->orderBy('rs.day');
						
		$result = $query->fetchArray();
		return $result;
	}
}