<?php

/**
 * WireTransfer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class WireTransfer extends BaseWireTransfer
{
	public function addRecords($data)
	{
		$conn = Zenfox_Partition::getInstance()->getConnections($data['playerId']);
		$partition = Doctrine_Manager::getInstance()->getConnection($conn);
		
		$date = new Zend_Date();
		$currentTime = $date->get(Zend_Date::W3C);
		
		$this->player_id = $data['playerId'];
		$this->account_number = $data['acNumber'];
		$this->account_holder_name = $data['acName'];
		$this->bank_name = $data['bankName'];
		$this->bank_trans_id = $data['bankTransId'];
		$this->amount = $data['transAmount'];
		$this->requested_time = $currentTime;
		
		try
		{
			$this->save($partition);
		}
		catch(Exception $e)
		{
			Zenfox_Debug::dump($e, 'exception', true, true);
			return NULL;
		}
		return true;
	}
}