<div class="fluid-content">
	<div class="head1">About Ace2Jak</div>
	<p>Ace2jak.com is an online rummy site and is a recognition of the enormous popularity of rummy in India, and a formal expression of our commitment to deliver to our players the Best Rummy Experience in the World.</p>
	<p>Ace2jak is managed by a professional management team with several years of experience in the online games industry.It is an all-time classic card games which is now available online at Ace2jak! You can be a part of this ever-growing online mania. Hone your skills while enjoying the magical gaming environment ofAce2jak in our user friendly platform for practice or for real money. </p>
	<p>Ace2jak is the first and only online Rummy community where you can experience a real multiplayer online Rummy game sessions of up to four players at a time. Join thousands of players from all over the world in exciting and dashing real money multiplayer ring games and tournaments!</p>
</div>