 <?php
/*
                                $groups = $this->groups;
                                $gameFlavours = $this->gameFlavours;
                                $allGameDetails = $this->allGameDetails;
                                                                
<div class="TabbedPanelContent">
                                                                        <!--div class="game-titles"><p>Rummy</p>
                                                                        </div-->
                                                                        <div class="game-list">
                                                                        <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="550" height="400" id="WebContainerLobby" align="middle">
        <param name="allowScriptAccess" value="sameDomain" />
        <param name="allowFullScreen" value="false" />
        <!--param name="movie" value="/games/multi-player/lobby/WebContainerLobby.swf" />
        <param name="FlashVars" value="xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" /-->
        <param name="movie" value="/games/container/web-container.swf" />
        <param name="FlashVars" value="xml_config=/games/container/config.txt&lobby_swf_path=/games/container/components/lobby/rummy-lobby/lobby.swf" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <param name="wmode" value="transparent" />
        <!--embed src="/games/multi-player/lobby/WebContainerLobby.swf" flashVars = "xml_config=/games/multi-player/lobby/Config.txt&lobby_swf_path=/games/multi-player/lobby/lobby/Lobby.swf" quality="high" bgcolor="#000000"-->
        <embed src="/games/container/web-container.swf" flashVars = "xml_config=/games/container/config.txt&lobby_swf_path=/games/container/components/lobby/rummy-lobby/lobby.swf" quality="high" bgcolor="#000000"
                                width="670" height="502" name="Web Container" align="middle"
                                play="true"
                                loop="false"
                                quality="high"
                                allowScriptAccess="sameDomain"
                                type="application/x-shockwave-flash"
                                pluginspage="http://www.adobe.com/go/getflashplayer" 
                                wmode="transparent"
                                >
                        </embed>
                        </object>
</div>
                                                                        </div>
*/
//Use Relative Path, Problem In Loading Game With HTTPS Header
//$hostAddress = $this->hostAddress;
$hostAddress = "";
?>
<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="100%" height="502" id="WebContainerLobby" align="middle">
<!--    <param name="allowScriptAccess" value="sameDomain" /> -->
<param name="allowScriptAccess" value="always" />
        <param name="allowFullScreen" value="false" />
        <param name="movie" value="<?=$hostAddress?>/games/container/web-container.swf" />
        <param name="FlashVars" value="base_url=<?=$hostAddress?>&xml_config=<?=$hostAddress?>/games/container/config.txt&lobby_swf_path=<?=$hostAddress?>/games/container/components/lobby/rummy-lobby/lobby.swf&user_name=<?php echo $this->name;?>&balance=<?php echo $this->cash;?>&bonus=<?php echo $this->bonus;?>&loyalty_points=<?php echo $this->loyaltyPoints;?>&image_path=<?php echo $this->imagePath;?>&free_chips=<?php echo $this->freeChips;?>" />
        <param name="quality" value="high" />
        <param name="bgcolor" value="#ffffff" />
        <embed src="<?=$hostAddress?>/games/container/web-container.swf" flashVars = "base_url=<?=$hostAddress?>&xml_config=<?=$hostAddress?>/games/container/config.txt&lobby_swf_path=<?=$hostAddress?>/games/container/components/lobby/rummy-lobby/lobby.swf&user_name=<?php echo $this->name;?>&balance=<?php echo $this->cash;?>&bonus=<?php echo $this->bonus;?>&loyalty_points=<?php echo $this->loyaltyPoints;?>&free_chips=<?php echo $this->freeChips;?>&image_path=<?php echo $this->imagePath;?>" quality="high" bgcolor="#000000"
                                width="100%" height="502" name="Keno" align="middle"
                                play="true"
                                loop="false"
                                quality="high"
                                allowScriptAccess="sameDomain"
                                type="application/x-shockwave-flash"
                                pluginspage="http://www.adobe.com/go/getflashplayer">
                        </embed>
                        </object>
