<?php
echo $this->form;

if($this->paginator)
{
	if (count($this->paginator))
	{		
		$linkArrays = array();
		//Temp is used to print the table headings only for one time
		foreach($this->contents as $tableData)
		{
			$linkArrays[$tableData['Id']] = array(
					'controller' => 'affiliatesearch',
					'action' => 'view',
			        'id' => $tableData['Id']);								
		}
		$this->table($this->contents, 'Id', $linkArrays);		
	}		
	echo $this->paginationControl(
						$this->paginator,
						'Sliding',
						'playerPaginator.phtml',
						array(
							'searchField' => $this->searchField,
							'match' => $this->match,						 	
							'accountType' => '',
							'searchString' => $this->searchStr));
}?>



