<div class="aboutus_div" style="border:1px solid #CD222B;border-radius:5px;">
<div class="ttinnnerpad" class="TTBingogameName TTBingoBtnmargt"><div class="TTBingogameName TTBingoBtnmargt">About Bingo Bible</div>
<p style="margin-left:10px;margin-right: 10px;">Bingobible  is owned by Progaming Winners online Limited.Progaming Winners online is a registered company in Costa Rica. We provide you with the best online bingo services under its remote gambling license issued by the Government of Costa-Rica.</p>
<p style="margin-left:10px;margin-right: 10px;">Bingo Bible is powered by “Logic Dice”. Logic Dice is a vibrant, technologically driven company focused on making great products in the Gaming industry. The company is dedicated to providing software which is innovative, fun and focused on creating a great player experience.</p>
<p style="margin-left:10px;margin-right: 10px;">All games on this site are fully audited and extensively tested to ensure fair play and honest payouts. As part of our commitment to fair play all our gaming software systems use a Random Number Generator (‘RNG’) to make sure all game outcome results are truly random.</p>
<p style="margin-left:10px;margin-right: 10px;">We take every precaution to protect our customers' information. When submitting sensitive information via the website, our customers' information is protected both on-line and off-line. All sensitive information (such as credit card number and/or personal details) entered on the site is encrypted and protected with the best encryption software in the industry - SSL 128 bit.</p>
<p style="margin-left:10px;margin-right: 10px;">Bingo Bible offers 90-ball and 75-ball Bingo games &amp; a choice of over 15 Slots and a varieties of instant games with 24/7 Customer Support.</p>
<p style="margin-left:10px;margin-right: 10px;">All New players get an amazing offer of FREE £20 on registering with us. Also get 500% bonus on first deposit.</p> 
<p style="text-decoration:underline;margin-left:10px;margin-right: 10px;"><strong>Our Registered Address</strong></p>
<p style="margin-left:10px;margin-right: 10px;">Progaming Winners Online <br />
Casa 795, Barrio Dent, San Pedro <br />
San José. Costa Rica<br />
 11501 </p>
</div>
</div>