<div class="zenfox-content" style="border:1px solid #CD222B;border-radius:5px;margin-top:-20px">
<!--<div  class="heading1">--><div class="TTBingogameName TTBingoBtnmargt">Bingo Bible’s Basic &amp; Pay-out Rules</div><!--</div>-->
	<p>
    <strong>Basic Rules </strong></p>
	<div  class="heading2">Types of Games</div>
		<p style="margin-left:10px;margin-right: 10px;">
			1)	Players are only permitted to have only one account for the website and the personal details supplied for this account will be confirmed through our verification process.
		<p style="margin-left:10px;margin-right: 10px;">2)	We may take the decision to close account/s, make void all activity on duplicate accounts and/or reclaim any illegitimately paid bonuses or pay-outs where the following has occurred:
		<p style="margin-left:10px;margin-right: 10px;">a)	Our verification process identifies additional accounts opened by you;
		<p style="margin-left:10px;margin-right: 10px;">b)	Our service to you has previously been permanently terminated; ordeliberate attempts to falsify account details may lead to the closure of ALL related accounts.
		<p style="margin-left:10px;margin-right: 10px;">3)	Newbies who have not made a deposit will not be able to request a withdrawal on winnings derived from the Sign up bonus. Sign up bonus is offered to all the players to check our site; any winnings from sign up bonus will not be eligible for a pay-out. If requested for a pay-out, all the winnings will be deducted and the account will be reset to zero. A player is requested to make a deposit and continue to play. Any winnings derived from the deposit made will be eligible for the pay-out.
		<p style="margin-left:10px;margin-right: 10px;">4)	You are solely responsible for keeping your account details and password secure and secret, and for any purchases and/or losses that may occur on your account.
		<p style="margin-left:10px;margin-right: 10px;">5)	All account closure requests would take 24 to 48 hours from the time requested.                                                                                
		<div  class="heading3" ><strong>Withdrawal Rules</strong></div>
		<p style="margin-left:10px;margin-right: 10px;">
			In order to request a withdrawal, a member must have an active account and met our wagering requirements</p>
		<p style="margin-left:10px;margin-right: 10px;">1)	Upon requesting a withdrawal, a player is agreeing to and accepting that he/she understands all of our withdrawal Terms &amp; Conditions.</p>
		<p style="margin-left:10px;margin-right: 10px;">2)	The minimum pay-out request is £40 and the maximum is £500 per week.In a month, a maximum of £3000 will be approved. Higher withdrawal amount are subject to a longer processing period.</p>
		<p style="margin-left:10px;margin-right: 10px;">3)	Bingo Bible will only process ONE pay-out per account per week. In an event a player having multiple pay-out requests in the same week, the Accounting Department will decline all subsequent requests and send them back to the player’s account.</p>
		<p style="margin-left:10px;margin-right: 10px;">4)	To be eligible for a pay-out, a member must have made one or more deposits of £20 in the past 30 days prior to the request of their pay-out.</p>
		<p style="margin-left:10px;margin-right: 10px;">5)	Pay-out requests is processed twice a week i.e. Mondays&amp;Thursdays. All pay-out requests must be received before 10 AM GMT, failing which; the requests will be processed on the next processing day.</p>
		<p style="margin-left:10px;margin-right: 10px;">6)	Deposit andfree bonus/cash given must be wagered three (3) times on bingo games or eight (8) times on casino/instant games prior to requesting a pay-out.</p>
		<p style="margin-left:10px;margin-right: 10px;">7)	All Bonuses will be deducted upon a pay-out request. In case, you flow back/reverse your withdrawal request, the deducted bonuses will be credited back to your account.</p>
		<p style="margin-left:10px;margin-right: 10px;">8)	Pay-out flow backs are not considered as deposits. Therefore it will not be eligible for any deposit bonuses</p>
		<p style="margin-left:10px;margin-right: 10px;">9)	Pay-outs will be approved to the appropriate account through which the deposits were made.</p>
		<p style="margin-left:10px;margin-right: 10px;">10)	Players using Ukash can receive their winnings through cheque/gift vouchers. For cheques £5.00 will be deducted from the pay-out amount. The cheques/gift vouchers will only be sent out every other week on approved withdrawals.</p>
		<p style="margin-left:10px;margin-right: 10px;">11)	Bingo Bible guarantees that if a player has met the wager rule, provided correct details and has sent in their verification documents, the pay-out request will be processed promptly as per the set guidelines.</p>
		<p style="margin-left:10px;margin-right: 10px;">12)	Bingo Bible reserves the right to edit, add or remove Terms and Conditions from the payout guidelines without prior notice to players. It is a player’s responsibility to periodically check the guidelines on the Terms &amp; Conditions in order to be fully informed and up to date with every rule and thus avoid unnecessary discrepancies.</p>
		<div  class="heading3" ><strong>How do I validate/verify my account for speedy pay-outs?</strong></div>
		<p style="margin-left:10px;margin-right: 10px;">
		  At Bingo Bible, we understand and believe the faster you get your winnings, the happier you’ll be. That’s why we encourage all players to send their account verification documents to the Accounting Department (payouts@bingobible.co.uk) to prevent any delay in receiving your well-deserved winnings.
		</p>
		<p style="margin-left:10px;margin-right: 10px;"><b>Please Provide:</b></p>
			<ul>
			  <li>Proof of address (for example – utility bill, phone bill, CC bill, etc.)</li>
			  <li>Any copy of a Government issued Photo ID.</li>
			</ul>			
		
		<p style="margin-left:10px;margin-right: 10px;">	
			Preferably, please scan and email to payouts@bingobible.co.uk		</p>
		<p style="margin-left:10px;margin-right: 10px;">Not to worry, you just have to validate/verify your account once. However, the Accounting Department from time to time may request random accounts on pay-out days with pending withdrawals for further verification as part of our security checks. This is a random procedure and there is no pre-determined selection process.</p>
</div>
