<div class="terms-new" style="border:1px solid #CD222B;border-radius:5px;padding-right: 10px;">
<div class="TTBingogameName TTBingoBtnmargt">General Terms and Conditions</div>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">1)	INTRODUCTION </div><!--</h2>-->
<ol>
  
    <li>	Please ensure that you read and understand these terms prior to registering with us. We recommend that you print out the terms and store them safely along with all your confirmation e-mails, hand written correspondence, transaction data, rules and payment methods relevant to your use of our services.</li>


    <li> To complement the more generic terms there are specific rules (&quot;rules&quot;), which govern the particular event and games that you play.</li>
  
   <li>By entering any details into, and/ or playing any games on our websites, or by opening an account with Bingo Bible, you agree that</li>
  <ul>
    <li> You have understood and accepted these terms and our Privacy Policy</li>
    <li> You have the mental capability to take responsibility for your own actions and can enter into a contract with us, which is enforceable by law</li>
    <li> You are bound by the applicable rules relating to the games you are playing</li>
    <li> You are responsible for complying with your applicable local or national laws and will not access our website from a country where we have restricted access for commercial or legal reasons</li>
    
  </ul>
  <li> These terms will always take precedence where there are considered to be inconsistencies between the terms and any of the content contained within the rules, the help section, the Privacy Policy.</li>
  <li> You are advised to check the terms for any updates as your continued use of our websites will be regarded as acceptance of the latest version of the terms and Privacy Policy</li>
  <li> If you do not accept any changes that have been made to the terms you should stop using our website. Any bets or wagers received, but not settled prior to the introduction of the updated terms, will be subject to the version of the terms applicable at the time your bet or wager was received.</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt"> 2)	Opening An Account</div><!-- </h2> -->
<ol>
<li> In order to place a bet or play a game via the websites, you will need to open an account with Bingo Bible. As part of opening your account you will be required to provide personal details such as your name, date of birth, address, telephone number and e-mail address. </li>
<li> Players are only permitted to have one account for the websites and these personal details supplied for this account will be confirmed through our verification process.</li>
<li> We may take the decision to close account/s, make void all activity on duplicate account/s and/or reclaim any illegitimately paid bonuses or payouts where the following has occurred</li>
<ul>
  <li>Our verification process identifies additional accounts opened by You</li>
  <li>Our service to You has previously been permanently terminated</li>
  <li>Deliberate attempts to falsify account details may lead to the closure of ALL related accounts.</li>
</ul>
</ol>

<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">3) ACCOUNT VERIFICATION</div> <!--</h2>-->
<ol>
<li>	As a condition of opening an account You confirm and we are entitled to verify that: </li>
<ul>
  <li> You are over 18 years of age</li>
  <li> You are reminded that it may be an offence for you to participate in gambling if You are under 18 years of age or the age at which gambling or gaming activities are legal under the law or jurisdiction that applies to You</li>
  <li> You have provided Your correct and full name</li>
  <li> You are resident at Your stated address</li>
  <li> You are not party to a current self-exclusion agreement with us. As part of this process there may be requests for supporting ID which you will be advised of at the time.</li>
</ul>

<li> Through random check and account verification, if we are unable to verify Your details or You are ultimately shown to be underage or unable and/or unwilling to provide proof of Your residential address, or other information required to verify Your identity, we may:</li>
<ul>
  <li> Freeze Your account and/or</li>
  <li> Prevent You from placing any further bets until these verification checks are completed satisfactorily</li>
  <li> All winnings will be forfeited and the account will be reset to zero and be permanently closed for future.</li>
  <li> We may decide to carry out further verification checks or request extra documents to confirm Your identity, age and address at any time. This is to satisfy our license obligations, routine security checks and to safeguard the integrity of your account</li>
</ul>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">4) USERNAME, PASSWORD, &amp; PLAYER INFORMATION</div><!--</h2>-->
<ol>
<li> It is important for You to be aware of the following username and password information</li>
<ul>
  <li>The username and password You choose to enable access must be kept secure and personal</li>
  <li>If You think Your password may be known by someone else You can change it, at any time,</li>
  <li>Lost or forgotten passwords can be reset via the website or customer services, at any time, upon successful verification of supplementary account details that you will be asked to supply.</li>
</ul>
<li> Be careful when choosing security details that may be known by family members, particularly children or anyone under 18. Any third party, including anyone under 18, must not be permitted to use your account and cannot accept any winnings on your behalf</li>
<li> We will not be liable if you disclose your username, password, or account number to another party. If a third party becomes aware of your username, password or account number, then bets or wagers placed by third parties will be considered valid. You should contact us in any circumstances where you believe your account has been compromised.</li>
<li> It is your sole responsibility to ensure that the information supplied to us is at all times both accurate and current, and to advise us of any changes at the earliest opportunity. Failure to do so may cause your account to be suspended, if any routine verification checks raise a difference that we have not been made aware of.</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">5)	DEPOSITS AND WITHDRAWALS </div><!--</h2>-->
<ol>
<li> You must ensure that you use a payment method which belongs to you and is registered in your name. Only one payment method can be used on an account at any given time. Where more than one payment method has been used we reserve the right to ensure that payouts are made in accordance with rules designed to minimize fraud. This can include partial payments to previously used deposit types, where applicable.</li>
<li> No withdrawal will be processed until we have satisfactorily completed the verification process.</li>
<li> If required, it will remain your responsibility to report any winnings and losses to your local law or tax or other authorities. We will not be liable to these authorities for any of your personal taxes.</li>
<li> Deposits made by bank transfer, debit or credit cards will not be charged by us, although your payment provider may make a charge. However, you should be aware that some credit card companies regard betting transactions as &quot;cash&quot; and may attach a fixed and/or interest charge from the date of payment. Withdrawals to UK debit cards, credit cards and via bank transfer to UK bank accounts will also not be charged.</li>
<li> Bank charges will apply to the transfer of deposits and withdrawals to international bank accounts. Payment of these charges will be your responsibility and may vary according to the amount of money transferred.</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">6)	FREEZING AND CLOSING AN ACCOUNT</div><!--</h2>-->
<ol>
<li> There may be circumstances where we are required to freeze the money in your account which will prevent you from placing any bets/wager on the website, and at the same time supply relevant customer details to the applicable authority, regulator, external party etc. These actions will be taken where we have reason to believe that your account may be used for, including but not limited to, the following activities :</li>
<ul>
  <li> Fraud or attempt to defraud. You will be liable to pay us, on demand, all costs, charges or losses experienced by us, as a result of any fraudulent activity by you. This will include any direct, indirect or consequential losses, any loss of profit and loss of reputation, arising directly or indirectly from your fraud, dishonesty or criminal act.</li>
  <li> Money laundering, including where this is linked to terrorist funding</li>
  <li> Involvement in collusion, game rigging or cheating of any kind</li>
  <li> We have reason to believe you are under 18 years old</li>
  <li> You are in a jurisdiction (or citizen of a jurisdiction) that makes the provision of our products or services to you or your use of them illegal</li>
  <li> You are trying to use our website and or play games from any other territory where we do not accept Players</li>
  <li> Bonus or promotional abuse</li>
  <li> If our investigations are ongoing and unresolved issues still remain, we will continue to freeze Your Account or we may take the decision to close it</li>
</ul>
<li> We have the right to close your account at any time for any reason.</li>
<li> You can close your account at any time, so long as no money is owed to us. If you want to close your account you should inform us through an e-mail using the details found in our Contact Us section. Should you wish to resume online gaming with us, you will be required to reactivate the existing account, as you cannot open a new account.</li>
<li> You agree not to make any chargebacks, reversals or cancel any deposits into your account.</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">7)	DORMANT ACCOUNTS</div><!--</h2>-->
<ol>
<li> For standard (deposit/debit) accounts, if your account has not been used to place a bet for 400 days your account will be deemed dormant and subject to Dormancy Fees.</li>
<li> When an account becomes dormant, we will charge a Dormancy Fee of 5% of the account balance on the day the account is considered dormant, or an amount of £2 (or currency equivalent), whichever is greater. The Dormancy Fee will be charged on the day the account is considered dormant, and the first day of each calendar month thereafter.</li>
<li> The Dormancy Fee will continue to be deducted until either the account balance has been reduced to zero, or your account is reactivated by you placing a bet.</li>
<li> We will endeavor to make every effort to contact you, using the most recent details that we have been provided by you, with regards to your account balance before your account becomes dormant.</li>
<li> When activity resumes on an account which has been inactive for a period we may perform additional security checks to ensure access is legitimate and to safeguard the integrity of your account. This may result in a request for additional information and/or the temporary suspension of your account while the checks are carried out, especially if any of your personal details, payment details or contact information has become out-of-date.</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">8)	SECURITY </div></h2>
<ol>
<li> We use a variety of security technologies to protect your personal information from unauthorized use, access or disclosure. All our employees and data processors that have access to, and are associated with processing your information are obliged to respect your privacy and maintain confidentiality.</li>
<li> All financial information is transmitted and processed using secure connections through leading e-commerce payment companies. </li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">9)	PROMOTIONAL OFFERS</div><!--</h2>-->
<ol>
<li> From time to time we offer new and/or existing Players various promotional offers</li>
<li> The terms of these promotional offers will be clearly stated for each individual promotion. It is your responsibility to ensure that these terms are fulfilled in order to qualify for the respective bonus, credit or prize.</li>
<li> If there is any ambiguity between these Terms and the promotion specific Terms, then these terms will prevail.</li>
<li> Promotional offers are restricted to one per customer, unless otherwise stated in the terms.</li>
<li> Any winnings from promotional bonuses will not be qualified for withdrawal and Bingo Bible has the right to deduct all the winnings from promotional bonuses and reset the account. </li>
</ol>

<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">10)	PLACING YOUR BETS</div><!--</h2>-->
<ol>
<li> Your ability to place a bet is limited by the amount of money available in your account. At the time your bet is placed and accepted, the corresponding stake value is deducted from your available account balance.</li>
<li> We recommend that you retain a copy of any transaction records, merchant policies and/or our terms. If at any time there is disagreement regarding the bet details then we will refer to our records of the transaction and base our subsequent decision on this information.</li>
<li> We make every effort to ensure that errors or mistakes do not occur in any Game. We reserve the right to void winnings or cash-ins enabled by wins resulting from any obvious error or mistake or any technical fault (including, but not limited to, incorrect game pay-outs) with any of the games offered. You will forfeit any winnings/losses that result from such errors or mistakes or technical faults &amp; refund the bet amount. In the event of a discrepancy between the result showing on your system/interface end and the game's server software end, the result showing on the game's server software shall be the official and governing result of the Game.</li>
<li> The Company reserves the right, in its sole discretion and without notice to you, to add new activities or games or to discontinue any activity or game at any time.</li>
<li> We may decide to refuse a bet or any part of the bet offered to us, void any accepted bets and withhold settlement, if we believe You are in breach of any of the terms of our Agreement including but not limited to where we are of the belief that:</li>
<ul>
  <li>You are under 18 years of age;</li>
  <li> You are involved in fraud, collusion, game rigging or cheating of any kind</li>
  <li> You are trying to use our services from a restricted territory</li>
  <li> You are placing bets or wagers that are in contravention of the laws in Your country or place of residence</li>
</ul>
<li>In addition, any such breach will be regarded as a material breach and entitle us to terminate our Agreement with You immediately</li>
</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">11)	COMPLAINTS AND DISPUTES</div><!--</h2>--><ol>
<li> In this section any &quot;complaint” which refers to the general conduct of the licensed activities, other than the settlement of the transaction itself, will remain categorised as a complaint through the internal complaints procedure. Ultimately it will be the Customer Relationship’s Manager Response, where escalated, which represents the final stage of this procedure.</li>
<li> Where the &quot;complaint&quot; refers to the settlement of a gaming transaction, it will become a dispute where:</li>
<ul>
  <li> It is not resolved at the first stage of the complaints procedure and is escalated to the Customer Relationship’s Manage;</li>
  <li> Following the response from the Customer Relationship’s Manager, the complainant remains dissatisfied and subsequently refers the matter to the applicable external body for adjudication.</li>
  <li> During this process, all live chat and e-mail communications with you and any other person may be archived. If the contents of these communications are disputed, then we will consult these records and these will be key in our decision making process, unless additional evidence is presented.</li>
  <li> During the resolution process you must agree not to reveal the existence or detail of any complaints or disputes to any third party, which could include discussions in chat rooms or equivalent forums. If confidentiality is broken, then so are the terms applying to this process and as a result the resolution process will be put on hold. In these circumstances we will also have the ability to freeze and potentially close your account.</li>
</ul>
<li> Complaints Procedure</li>
<li>The complaints procedure is as follows:</li>
<ul>
  <li> You should initially contact Customer Services through live chat or e-mail</li>
  <li> An advisor will investigate the enquiry and respond to it. The advisor will log the chat/e-mail and make notes on their response</li>
  <li> Should Your enquiry not be resolved at this stage, the matter should be referred by you, in writing, to Customer Support</li>
  <li>At this point it will be recorded as a complaint;</li>
  <li> The Customer Support Team will review your complaint and communicate their decision to you. If you remain dissatisfied you may escalate the matter to the Customer Relationship’s Manager, at which time it will be recorded as a dispute if it relates to a betting transaction.</li>
  <li> Upon receipt of an escalated complaint, the Customer Relationship’s Manager will obtain a report from the Customer Support Team, carry out any further necessary investigation and respond to you</li>
  <li> The Customer Relationship’s Manager Response represents the final stage of the internal complaints and disputes procedure.</li>
</ul>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">12)	IT FAILURE</div><!--</h2>--><ol>
<li> If the software or hardware serving the websites experiences unexpected system flaws, faults or errors we will make reasonable endeavours to resolve the problem within an acceptable time-frame.</li>
<li> We shall not be liable to You if:</li>
<ul>
<li> Account settlement (or other elements of the services) issues arise as a result of systems' errors, communications' errors, bugs or viruses; or</li>
<li> Damage to Your computer equipment or software results in a loss of data by you;</li>
</ul>
<li> We also reserve the right to void all affected games and take necessary action to correct such errors. However we are not required to provide any back up network and/or systems or similar services.</li>
<li> You agree that we shall not be responsible for any loss, including loss of winnings, resulting from the websites, failure to operate correctly because of, but not limited to the following:</li>
<ul>
  <li> Any delay or interruption in operation or transmission</li>
  <li> System failures, software error bugs, viruses or other faults (including errors or omissions in content)</li>
  <li> Any loss or corruption of data or communication or lines failure</li>
  <li> Any person's misuse of the websites (including content of such websites); or</li>
  <li> Any other factors beyond our control</li>
</ul>

</ol>
<!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">13)	ALTERATION OF THE WEBSITE </div><!--</h2>--><ol>
<li> To ensure the continued provision of the websites, and dependent on our good judgement, we may at any time decide to carry out software maintenance or modify any games delivered via the websites.</li>
<li> As a result of maintenance requirements and/or a change to any of the games offered on it, we may restrict, from time to time, Your access to the websites (in whole or in part). We will try, although we cannot guarantee, to undertake these modifications or maintenance requirements during times which minimise the impact upon our players.</li>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">14)	EVENTS OUTSIDE OUR CONTROL</div><!--</h2>--><ol>
<li>if events occur which are outside our reasonable control then we will not be liable or responsible for any failure to perform, or delay in performance of, any of our obligations under these terms. If any such events should arise our obligations will be suspended for the duration of the applicable event. The time for performing these obligations will then be extended by a period equivalent to the duration of such event. We will use our reasonable endeavours to resume normal operations despite the occurrence of any such event.</li>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">15)	WARRANTIES</div><!--</h2>--><ol>
<li> You acknowledge and agree that your access to and use of the website is at your sole option, discretion and risk.</li>
<li> You further acknowledge that your access to and use of the websites is permitted solely in strict accordance with these terms and that any winnings will only be paid if won in accordance with our terms.</li>
<li> We will try to operate the websites using reasonable skill and care and substantially as described in these terms. You acknowledge and accept that the services available are provided &quot;as is&quot;. No warranties or representations are therefore applicable to any subsequent faults and failings.</li>
<li> Any representation, warranty, condition or guarantee whether express or implied (including without limitation any implied warranty of satisfactory quality, fitness for purpose, completeness or accuracy, uninterrupted provision, or non-infringement or warranty that the websites or services available will be timely, secure or error free or that the websites or applicable servers are free of viruses, bugs or other malicious programs or that their use will meet Your requirements) are hereby excluded to the fullest extent permitted by law.</li>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">16)LIABILITY</div><!--</h2>--><ol>
<li> Other than our obligation to pay you winnings which have been genuinely won in accordance with our terms and subject always to our rules, our maximum liability to you arising out of or in connection with your access to and use of the websites and the services and/or these terms whether for breach of contract, or tort (including negligence) or otherwise will be limited:</li>
<li> In respect of a single transaction in relation to which the liability in question has arisen, to the amount of bets or wager placed by you from your account in respect of such transaction;</li>
<ul>
  <li> The amount of bets or stakes placed by You from Your account in relation to such product during such six month period; or</li>
  <li> Ten thousand pounds (£10,000)</li>
</ul>
<li> Under no circumstances will we be liable to you in contract, tort (including negligence), breach of statutory duty or otherwise under or in connection with these terms, Your use of, or inability to use, the websites or the services, any of our chat rooms or any software, materials or other information on our websites, or services available from there, for:</li>
<ul>
  <li> Any injury, loss, claim (other than pursuant to term 17.1), loss of profits, opportunity or revenue, loss of business or agreements, loss of goodwill, loss of use or corruption of software, loss or corruption of data or loss of anticipated savings;</li>
  <li> Loss or damage to property, or injury;</li>
  <li> General damages or any direct, indirect, special, incidental, consequential, exemplary or punitive damages of any kind.The above conditions are applicable even if such losses are foreseeable or if we have been notified by you of the possibility of such losses arising.</li>
</ul>
<li> You specifically acknowledge, agree and accept that we are not liable to You for the following:</li>
<ul>
  <li> Any defamatory, offensive or illegal conduct of any customer or third party;</li>
  <li> Any loss, including any loss of winnings, arising from the use, abuse or misuse of your account or any of our services and the corresponding websites, whether by you or a third party</li>
  <li> Any loss, including loss of winnings, incurred in the sending of information to our websites by you or by a third party</li>
  <li> IT failures which are caused by the hardware or software equipment which You or other players are using to access the website</li>
  <li> Acts or omissions by Your internet service provider or other third party with whom You have contracted to gain access to the websites or the internet generally</li>
  <li> Any technical failures, system breakdowns, defects, delays, interruptions, manipulated or improper data transmission, loss or corruption of data, communications' lines failure, distributed denial of service attacks, or bugs or viruses or any other adverse technological consequence to service</li>
  <li> The accuracy, completeness or currency of any information services provided including without limitation, prices, runners, times, results or general statistics or any live scores, statistics and intermediate results shown on our websites</li>
  <li> Any link contained, or the websites or content contained, on any internet sites linked to and from the websites.</li>
  <li> Nothing in these terms shall operate so as to exclude or restrict our liability for death or personal injury caused by our negligence, or for fraud.</li>
</ul>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">17)	INTELLECTUAL PROPERTY</div><!--</h2>--><ol>
<li> You acknowledge and agree that the following intellectual property rights which include but are not limited to Intellectual Property on our websites, in our e-mails and in any other correspondence,  shall at all times remain vested in us</li>
<ul>
<li> Any trademarks, logos and trade names</li>
<li> Domain names, database rights and all related software, including content published or used on it.</li></ul>
<li> All website material, including design, text, graphics, music, sound, photographs, video, including their selection and arrangement, software compilations, are the copyright of Bingo Bible</li>
<li> You are granted a non-exclusive, non-transferable, revocable, personal licence to such intellectual property rights for the sole purpose of displaying this website on your personal computer and for transacting with it in strict accordance with these terms. Any other use of such material and content (&quot;Material&quot;) is strictly prohibited. In particular you agree not to (and agree not to assist or facilitate any third party to) copy, reproduce, transmit, publish, display, distribute, commercially exploit, tamper with or create derivative works of such material.</li>
<li> If any of the website material is downloadable or can be printed, then such material can only be downloaded to a single personal computer and hard copies may only be printed for your own personal and non-commercial use. No right, title or interest in any downloaded materials or software is transferred to you by downloading.</li>
<li> You may not transfer, copy, reproduce, distribute, exploit or make any other use of this website material other than to display on Your computer screen or to view the content on a print out. Our website must not be linked to any other website without our permission.</li>
<li> In addition, any use by you or a third party of the websites or products will be considered void if such use is illegal, mechanically or electronically reproduced, if not obtained through legitimate channels or if such use contain printing, production, typographical, mechanical, electronic or any other errors.</li>
<li> We will not be liable to you for any losses nor be liable to pay You any winnings if we have reasonable cause to believe that You have engaged in any activity prohibited by this term 18.</li>
</ol><!--<h2>--> <div class="TTBingogameName TTBingoBtnmargt">18)	GOVERNING LAW AND JURISDICTION</div> <!--</h2>--><ol>
<li> This Agreement and all other additional terms are governed by the laws of Costa Rica</li>
<li> The courts of Costa Rica shall have the non-exclusive jurisdiction to settle any disputes relating to these terms.</li>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">19)	WAIVER </div><!--</h2>--><ol>
<li> If we do not enforce the carrying out of any of your obligations or if we do not apply any of our permitted rights or remedies we shall not be prevented from enforcing such rights or remedies or requiring you to fulfil your obligations moving forward.</li>
</ol><!--<h2>--><div class="TTBingogameName TTBingoBtnmargt">20)	ADDITIONAL TERMS</div><!--</h2>-->
<ol>
<li> 	These terms, and all the associated documents referred to in these terms, comprise the entire agreement between us and supersede all prior communications and understandings relating to the subject matter of our relationship.</li>
<li> A verbal or written declaration by any employee or agent of The Bingo Bible Team should not be regarded as a variation of these terms or an authorised statement relating to website or service quality. We shall have no liability to you for any unauthorised statement except where fraud or fraudulent misrepresentation can be demonstrated.</li>
</ol>
</div>