<?php
if(!$this->post)
{
	?>
	<div class="head1"> Your last five successful transactions </div>
	<?php
	if($this->contents)
	{
		$this->acetable($this->contents);
	}
	else
	{
		?>
		<p>No Records Found</p>
		<?php 
	}
	?>
	<div class="head2"> Create custom report </div>
	<?php
}

echo $this->form;
if($this->paginator)
{
	if (count($this->paginator))
	{
		$this->acetable($this->contents);
	}
	?>
	<div class="tresultpagination">
		<?php
		$pages = get_object_vars($this->paginator->getPages('Sliding'));
		$this->acepagination($pages);
		?>
	</div>
	<?php 
}
