

<?php 

/*
 * <!--img src="/css/rummy.tld/images/Shivaratri_tournament.png" width="630" height="835" border="0" usemap="#tournament-map" />

<map name="tournament-map">
<area shape="rect" coords="476,179,600,221"  href="/tournament/register" />
</map-->
<script type="text/javascript">

function displaysubnav()
{
	if(document.getElementById('popup').style.display== 'none')
	{
		document.getElementById('popup').style.display='block';
		document.getElementById('popup2').style.display='none';
	}
	else
	{
		document.getElementById('popup').style.display='none';
		
	}
}
function displaysubnav1()
{
	
	if(document.getElementById('popup2').style.display== 'none')
	{
		document.getElementById('popup2').style.display='block';
		document.getElementById('popup').style.display='none';
	}
	else
	{
		document.getElementById('popup2').style.display='none';
	}
}
</script>

        <div class="inner-content">
          <div id="tournamentM">
          <h1>Sivaratri Tournament Results</h1>
            <table width="100%" border="0" cellspacing="2" cellpadding="0" style="font-family:Arial, Helvetica, sans-serif; font-size:13px; color:#484848; border:#9e1515 solid 0px ">
              <tr>
                <td valign="top"><table width="100%" border="1"  bordercolor="#FF0000" cellspacing="0" cellpadding="3" style="border:#24728b solid 1px">
                    <tr>
                      <td colspan="2" align="center" bgcolor="#9e1515" style="color:#FFF; font-size:14px; padding:0px"><div  class="tttournmentbg"><strong>Tournament 1</strong> </div></td>
                    </tr>
                    <tr>
                      <td width="52%" align="center" ><strong style="color:#000">Place</strong></td>
                      <td width="48%" align="center"><strong style="color:#000">Name</strong></td>
                    </tr>
                    <tr>
                      <td align="center"><strong>1<span >st</span></strong></td>
                      <td align="center">luckystar</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>2nd</strong></td>
                      <td align="center">Sharath</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>3rd</strong></td>
                      <td align="center"> tami1</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>Consolation</strong></td>
                      <td align="center"><a href="#" style="color:#445eb3; font-size:13px; font-weight:bold; color:#9e1515; text-decoration:none"  onclick="displaysubnav();">View Here</a></td>
                    </tr>
                  </table></td>
                <td valign="top"><table width="100%" border="1" cellspacing="0" cellpadding="3" style=" border:#24728B solid 1px">
                    <tr>
                      <td colspan="2" align="center" bgcolor="#9e1515" style="color:#FFF; font-size:14px; padding:0px"><div  class="tttournmentbg"><strong>Tournament 2</strong></div></td>
                    </tr>
                    <tr>
                      <td align="center"><strong style="color:#000">Place</strong></td>
                      <td align="center"><strong style="color:#000">Name</strong></td>
                    </tr>
                    <tr>
                      <td align="center"><strong>1st</strong></td>
                      <td align="center">luckystar</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>2nd</strong></td>
                      <td align="center">ratan55</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>3rd</strong></td>
                      <td align="center">manjugopi</td>
                    </tr>
                    <tr>
                      <td align="center"><strong>Consolation</strong></td>
                      <td align="center"><a href="#" style="color:#445eb3; font-size:13px; font-weight:bold; color:#9e1515; text-decoration:none"  onclick="displaysubnav1();" >View Here</a></td>
                    </tr>
                  </table></td>
              </tr>
            </table>
                  <div>
            <div class="pop-up" id="popup" style="display:none;"> <h2>Tournament1</h2><img src="/css/rummy.tld/images/winnerslist 1.png" />
              
            </div>
          </div>
          <div>
            <div class="pop-up" id="popup2" style="display:none;"> <h2>Tournament2</h2><img src="/css/rummy.tld/images/winnerslist 2.png" />
    
  </div>
          </div>
          </div>
    
          <a style="position:absolute;" href="#" class="top">Back To Top</a>
        </div>
*/
?>

