 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script type="text/javascript" src="http://taashtime.tld/invitation/dark/generate_notification_form/js/jquery.tools.js"></script>
    <script type="text/javascript" src="http://taashtime.tld/invitation/dark/generate_notification_form/js/jquery.uniform.min.js"></script>
    
     <script src="http://taashtime.tld/temp/jquery-ui-1.8.14.custom.min.js" type="text/javascript"></script>
     <script type="text/javascript" src="http://taashtime.tld/temp/ttw-notification-center.js"></script>
    <script type="text/javascript" src="http://taashtime.tld/temp/forms.js"></script>
    
<link type="text/css" rel="stylesheet" href="http://taashtime.tld/temp/css/messages.css"></link>
<body>   
<h1 id="testing" >Form comes here</h1>
</body>

