 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<script type="text/javascript" src="http://taashtime.tld/invitation/dark/generate_notification_form/js/jquery.tools.js"></script>
    <script type="text/javascript" src="http://taashtime.tld/invitation/dark/generate_notification_form/js/jquery.uniform.min.js"></script>
    
    <script type="text/javascript" src="http://taashtime.tld/temp/formmessages.js"></script>
    
<link type="text/css" rel="stylesheet" href="http://taashtime.tld/temp/css/messages.css"></link>
<body>   
<h1 id="testing" >Form comes here</h1>
</body>