<div class="fluid-content">
	<div class="head1">Contact Us</div>
	<p>We understand your zeal towards rummy and thus, promise you a ride where fun and safety, and, entertainment and security go hand in hand. With every challenge surpassed, you grow as a winner and emerge as a successful individual with confidence spilling from your rims.</p>
	<p>For more information on our rummy rules, privacy policy, terms of service or if you have any questions or grievances, mail us at support@Ace2jak.com. We are more than happy to be of any service.</p>
	
	<div class="head2">Address</div>
	<p>Srinture Technologies India Private Limited,<br/>
	Level:-1, AM@10, MB TOWERS,</br>
	Road:-10,Banjarahills,</br>
	Hyderabad-500034,<br/>
	Andhrapradesh, India.</p>
	
	<div class="head2">Emails</div>
	<p>Support@ace2jak.com,<br/>
	Info@ace2jak.com</p>
	
	<div class="head2">Phone</div>
	<p>+91-4046464868</p>
</div>
