<?php /*
<!-- 
<div class="zenfox-content">

	<div  class="heading1" >Legal Implications of the Service</div>
		<p>There are often many questions that arise when it comes to the legality of this service. We expect that the explanations provided below help answer most of them.</p>
	
	<div  class="heading2" >Gambling vs. Games of Skill</div>
	<p>According to Indian law, wagering or betting on games of chance is considered to be gambling.</p> 
	
	<div  class="heading3" >Games of Chance</div>
	<p>According to Indian law, gambling refers to the act of wagering on games of chance. Any game where the outcome is primarily dependant on chance is referred to as a game a chance. Games of chance come under the purview of gambling.</p>
	
	<div  class="heading3" >Games of Skill</div>
	<p>Games of Skill on the other hand are games whose outcome is primarily dependant on skill of the entities(individuals) playing. 
		As per the Supreme Court in 1996,</p> 
		<p><i>"A game of skill, on the other hand - although the element of chance necessarily cannot be entirely eliminated --is one in which success depends principally upon the superior knowledge, training, attention, experience and adroitness of the player. Golf, chess and even Rummy are considered to be games of skill. The Courts have reasoned that there are few games, if any, which consist purely of chance or skill, and as such a game of chance is one in which the element of chance predominates over the element of skill, and a game of skill is one in which the element of skill predominates over the element of chance. It is the dominant element --"skill" or "chance" -- which determines the character of the game."	</i></p>
		<p>Games of skill are specifically excluded from the definition of gambling as per the Gambling Act.</p>
		<p>According to an article in the Indian Express,</P>
		<p><i>"The Public Gambling Act of 1867 explicitly excludes games of "mere skill" from the prohibition. The Supreme Court has held that when a game relies on the element of skill, it cannot be a game of mere chance, and must therefore be analysed to determine whether chance or skill predominates."</i></p>
		
	<div  class="heading2" > Is Rummy a Game of Skill </div>
	<p>The Supreme Court and several state high courts have discussed the matter and come up with several rulings. The gist of such rulings can be summed up by one ruling from the high court. 
	<p><i>"Rummy, on the other hand, requires certain amount of skill because the fall of the cards has to be memorised and the building up of Rummy requires considerable skill in holding and discarding cards. We cannot, therefore, say that the game of Rummy is a game of entire chance. It is mainly and preponderantly a game of skill. The chance in Rummy is of the same character as the chance in a deal at a game of bridge."</i></p>
	<p>A Supreme Court ruling of 1967 (State of Andhra Pradesh vs K. Satyanarayan) states that Rummy cannot be called a "game of entire chance" and "is mainly and preponderantly a game of skill".</p>
	
	<div  class="heading2" >Is playing Rummy for real money legal on Taashtime.com?</div>
	<p>
		Yes, playing rummmy for real money is absolutely legal on taashtime.com.
		Not only is it legal, it is also protected under the Constitution of India. According to a court ruling, playing games of skill for cash can be considered as a business activity. By this definition, this activity is protected under the Indian Constitution - Article 19[1](g).
	</p>
	<p>In case of any more questions on the same, please write to us at legal [AT] taashtime [dot] com</p>
</div>
-->
<!-- 
<div class="zenfox-content">
	<div class = "main-header">It Is Legal !! Know More…</div>
	<div  class="heading1" >Legal Implications of the Service</div>
		<p>There are often many questions that arise when it comes to the legality of this cards service. We expect that the explanations provided below help answer most of them.</p>
	
	<div  class="heading2" >Is playing card game Rummy for real money legal on Taashtime.com?</div>
	<p>
		Yes, playing online card game rummy for real money is absolutely legal on <a href = "http://taashtime.com">Taashtime</a> Not only is it legal, it is also protected under the Constitution of India. According to a court ruling, playing games of skill to win cash can be considered as a business activity. By this definition, this activity is protected under the Indian Constitution - Article 19[1](g).
		
	</p>
	<p>So now you can enjoy your favourite game Rummy, and at the same time win huge amounts of cash at Taashtime, without worrying about Legality issues. Have fun, play more, sharpen your skills at Rummy, and earn easy online money!!</p>
	<p>In case of any more questions on the same, please write to us at legal [AT] taashtime [dot] com</p>
	
	<div  class="heading3" >What is a Game of Skill?</div>
	<p>Games of Skill are games whose outcome is primarily dependant on skill of the entities (individuals) playing. As per the Supreme Court in 1996,</p> 
		<p><i>"A game of skill, on the other hand - although the element of chance necessarily cannot be entirely eliminated --is one in which success depends principally upon the superior knowledge, training, attention, experience and adroitness of the player. Golf, chess and even Rummy are considered to be games of skill. The Courts have reasoned that there are few games, if any, which consist purely of chance or skill, and as such a game of chance is one in which the element of chance predominates over the element of skill, and a game of skill is one in which the element of skill predominates over the element of chance. It is the dominant element --"skill" or "chance" -- which determines the character of the game." </i></p>
		<p>Games of skill are specifically excluded from the definition of gambling as per the Public Gambling Act.</p>
		<p>According to an article in the Indian Express,</P>
		<p><i>"The Public Gambling Act of 1867 explicitly excludes games of "mere skill" from the prohibition. The Supreme Court has held that when a game relies on the element of skill, it cannot be a game of mere chance, and must therefore be analysed to determine whether chance or skill predominates."</i></p>
	
	<div  class="heading2" > Is Rummy a Game of Skill ? </div>
	<p>Yes! Online Rummy games offered on this website are games of skill. Almost all laws in relation to gambling in force in the states of India provide that they shall not restrict games of skill. Under these laws, gambling relates to wagering and betting on games of chance and uncertain events where chance is a dominant factor.
	<p>The Supreme Court and several state high courts have discussed the matter and come up with several rulings. The gist of such rulings can be summed up by one ruling from the high court. </p> 
	<p><i>"Rummy, on the other hand, requires certain amount of skill because the fall of the cards has to be memorised and the building up of Rummy requires considerable skill in holding and discarding cards. We cannot, therefore, say that the game of Rummy is a game of entire chance. It is mainly and preponderantly a game of skill. The chance in Rummy is of the same character as the chance in a deal at a game of bridge."</i></p>
	<p>A Supreme Court ruling of 1967 (State of Andhra Pradesh vs K. Satyanarayan) states that Rummy cannot be called a "game of entire chance" and "is mainly and preponderantly a game of skill". </p>
		
	<div  class="heading2" >Gambling vs. Games of Skill</div>
	<p>According to Indian law, wagering or betting on games of chance is considered to be gambling.</p> 
	
	<div  class="heading3" >Games of Chance</div>
	<p>According to Indian law, gambling refers to the act of wagering on games of chance. Any game where the outcome is primarily dependant on chance or luck is referred to as a game a chance. Games of chance come under the purview of gambling.</p>
	
	<div  class="heading3" >Game of skill</div>
	<p>Games of Skill on the other hand are games whose outcome is primarily dependant on skill of the entities (individuals) playing.</p>
	<p>So, all in all <b>rummy is game of skill and intelligence</b>. The more you play, the more you will excel in it. If you are looking for a perfect online rummy site, join us and enjoy the games and chat at live tables. Have a look at our <a href = "http://taashtime.com/promotions">Exciting Promotions</a> to win fabulous cash prizes.</p>
	<p>In case of any more questions on the same, please write to us at legal@taashtime.com</p>
	
</div>
-->
*/
?>
<div class="ttinnnerpad">
<h2><strong>It Is Legal!! Know More…</strong></h2>
<p>
<h3><strong>Legal Implications of the Service</strong></h3>
</p>
<p class="bottom">There are often many questions that arise when it comes to the legality of this cards service. We expect that the explanations provided below help answer most of them.</p>
<p>&nbsp</p>
<h3><strong>Is playing card game Rummy for real money legal on Taashtime.com?</strong></h3>
<p>Yes, playing online card game rummy for real money is absolutely legal on <a href = "http://taashtime.com">Taashtime</a> Not only is it legal, it is also protected under the Constitution of India. According to a court ruling, playing games of skill to win cash can be considered as a business activity. By this definition, this activity is protected under the Indian Constitution - Article 19[1](g).</p>
<p>So now you can enjoy your favourite game Rummy, and at the same time win huge amounts of cash at Taashtime, without worrying about Legality issues. Have fun, play more, sharpen your skills at Rummy, and earn easy online money!!</p>
<p class="bottom">In case of any more questions on the same, please write to us at <b>legal [AT] taashtime [dot] com</b></p>
<p>&nbsp</p>
<h3><strong>Is Rummy a Game of Skill?</strong></h3>
<p>Yes! Online Rummy games offered on this website are games of skill. Almost all laws in relation to gambling in force in the states of India provide that they shall not restrict games of skill. Under these laws, gambling relates to wagering and betting on games of chance and uncertain events where chance is a dominant factor.
<p>The Supreme Court and several state high courts have discussed the matter and come up with several rulings. The gist of such rulings can be summed up by one ruling from the high court. </p>
<p><i>"Rummy, on the other hand, requires certain amount of skill because the fall of the cards has to be memorised and the building up of Rummy requires considerable skill in holding and discarding cards. We cannot, therefore, say that the game of Rummy is a game of entire chance. It is mainly and preponderantly a game of skill. The chance in Rummy is of the same character as the chance in a deal at a game of bridge."</i></p>
<p class="bottom">A Supreme Court ruling of 1967 (State of Andhra Pradesh vs K. Satyanarayan) states that Rummy cannot be called a "game of entire chance" and "is mainly and preponderantly a game of skill". </p>
<p>&nbsp</p>
<h3><strong>Gambling vs. Games of Skill</strong></h3>
<p class="bottom">According to Indian law, wagering or betting on games of chance is considered to be gambling.</p>
<p>&nbsp</p>
<h3><strong>Games of Chance</strong></h3>
<p class="bottom">According to Indian law, gambling refers to the act of wagering on games of chance. Any game where the outcome is primarily dependant on chance or luck is referred to as a game a chance. Games of chance come under the purview of gambling.</p>
<p>&nbsp</p>
<h3><strong>Games of skill</strong></h3>
<p>Games of Skill on the other hand are games whose outcome is primarily dependant on skill of the entities (individuals) playing.</p>
<p>So, all in all <b>rummy is game of skill and intelligence</b>. The more you play, the more you will excel in it. If you are looking for a perfect online rummy site, join us and enjoy the games and chat at live tables. Have a look at our <a href = "/promotions">exciting promotions</a> to win fabulous cash prizes.</p>
<p class="bottom">In case of any more questions on the same, please write to us at legal@taashtime.com</p>
<p>&nbsp;</p></div>
