<div class="fluid-content">
	
	<div class="head1">Terms &amp; Conditions: </div>
	<p>This user agreement which includes those terms and conditions set out below and those incorporated by reference including the terms of the Privacy Policy and the Ace2jak game Rules is an agreement between you, the company, its licensors, subsidiaries, associates, affiliates and partners which governs your use of the products and services provided by the www.Ace2jak.com website and our associated software. By using any of the Services you are agreeing to all the terms of this Agreement.</p>
	<p>If any of the terms of the Agreement are determined to be unlawful, invalid, void or unenforceable for any reason, it shall not affect the validity and enforceability of the remaining terms. Any failure or delay on our part to act or exercise any right or remedy with respect to a breach of any of the terms of this Agreement by you shall not be construed as a waiver of our right to act with respect to the said breach or any prior, concurrent, subsequent or similar breaches.</p>
	
	<div class="head2">Agreement</div>
	<p>You must make sure that you read, understand and agree with all the terms and conditions contained in the Agreement, before you may use the Services on the website. Please use the Services only if you have read and understood the Agreement and agree to abide by its terms and conditions. If you have any questions about the Agreement please contact us atinfo@Ace2jak.com.</p>
	<p>We reserve the right to amend, modify or change any of the terms of this Agreement at any time, and it is advisable to regularly look at these terms. We shall give notice of such changes either by email notification to the email address provided to us by you upon registration, or by posting the amended Agreement on the website. Such modifications could include changes to any of our Game Rules. If you do not agree with the terms of the amended Agreement, you may terminate your use of the Services by notifying us that you wish to terminate your Accounts. Your continued use of the Services will be deemed to constitute your acceptance of the changes to the Agreement.</p>
	
	<div class="head2">Ownership</div>
	<p>Use of the Ace2jak.com name and any of the other names or marks associated with the website, the Services or the Software is strictly forbidden, unless it is used with the express written permission of the Company. The website, the Services and the Software, including its code, documentation, appearance, structure, and organization is an exclusive product of the Company, which retains all rights, tangible and intangible, to the Ace2jak.com website, the games therein, software, codes, copies, modifications, or merged parts.</p>
	
	<div class="head2">Eligibility</div>
	<p>In order to use the Services, a User must register for two separate virtual accounts in the manner as provided in this Agreement, and truthfully and accurately provide all mandatory information.</p>
	<ul>
		<li>In order to participate in Practice Games, you must be at least 18 years old.</li>
		<li>In order to participate in Real Chip Games, you must satisfy the following criteria at all times:</li>
		<li>You must be at least 21 years old, and must not suffer from any disability or impairment which would prevent you from assuming the responsibilities contained in the Agreement, or from participating in the Games which are offered as part of the Services.</li>
		<li>You must be a resident of India</li>
		<li>You must access the Services while located within an Eligible Territory,</li>
		<li>You must possess a valid PAN number that will be associated with your Accounts and which you will provide to us upon request,</li>
		<li>You must satisfy yourself that it is legal for you to participate in Real Chip Games in the specific jurisdiction from which you are accessing the Services.</li>
		<li>The '‘Eligible Territory' is defined as being the territory of India excluding the states of Assam and Orissa. ‘Real Chip Games’ are defined as being any games or tournaments which are part of the Services and require the User to maintain a non-zero cash balance in their Accounts. Any game other than a Real Chip Game made available by the Company through the website or the Software is defined as a 'Practice Game'. All Real Chip Games and Practice Games shall be collectively defined as 'Games'.</li>
		<li>Users who do not fulfill the above criteria are expressly barred from participating in Real Chip Games, and would not be entitled to receive any prizes which they may win as a result of participation in Real Chip Games.</li>
		<li>You understand and acknowledge that participation in Real Chip Games may result in financial loss to you, and agree that your participation is completely voluntary. You undertake full responsibility for any such financial losses, and agree that you will not under any circumstances hold the Company responsible for such losses.</li>
		<li>You understand and accept that by viewing or using the website or availing of any Services, or using communication features on the website, you may be exposed to content posted by other Users which you may find offensive, objectionable or indecent. You may bring such content posted by other Users to our notice that you may find offensive, objectionable or indecent and we reserve the right to act upon it as we may deem fit. The decision taken by us on this regard shall be final and binding on you.</li>
	</ul>
	
	<div class="head2">Description of Services</div>
	<ul>
		<li>We provide all our valid, registered Users an opportunity to access and play online games of skill. The Company provides software and IT services to enable games of skill to be played with other individuals over the internet.</li>
		<li>The Services provided by the Company are for entertainment purpose only and are only intended to facilitate games of skill.</li>
		<li>We levy a charge for Real Chip Games, which is inclusive of service tax as may be applicable. The Service Charge could vary from time to time and from one Real Chip Game to another.</li>
	</ul>
	
	<div class="head2">Your Account</div>
	<p>Each User shall have two virtual accounts. All chips bought by the Users through the mechanism as set out below shall reside in the first virtual account and any winnings in Real Chips Games or any Bonus Amounts received in accordance with this Agreement shall reside in the second virtual account. To additionally clarify for you, the Winnings and Bonus Account consists of two parts:</p>
	<p>The first part contains the winnings of the User  while the second part contains any bonus amounts that may be credited by the Company to the Users at its sole discretion.</p>
	<ul>
		<li>Your Accounts are to be used solely by you and cannot be handled by anybody else.</li>
		<li>You undertake that all the information provided by you at the time of opening the Accounts, or provided subsequently by you upon request by the Company, is true, complete and correct. </li>
		<li>You further also undertake to keep all of such information which has been provided by you up to date at all times, by making all necessary changes or intimating the Company when such details change. </li>
		<li>You undertake to provide all proofs relating to any such information, including copies of documents such as your PAN card, or address and identity proof, upon request by the Company. </li>
		<li>You understand that our Company may take steps to verify any such information provided by you. Your continued use of the Services, including but not limited to your ability to make Cash Credits and Cash Withdrawals in accordance with the terms of this Agreement, is subject to the Company’s continued satisfaction that all such details provided by you are true, complete and correct.</li>
		<li>You are strictly prohibited from using the Services by means of Accounts registered in the name of any other individual.</li>
		<li>Should you in any case attempt to open more than one Chips Account or Winnings and Bonus Account, under your own name or under any other name, or should you attempt to use the service by means of any other person's Accounts, we will be entitled to close all your Accounts and bar you from accessing or using the Services in the future without notice.</li>
		<li>You shall not share your password to your Accounts, or any other confidential or sensitive information associated with your Accounts, with any other individual. The Company will not responsible if your Accounts are accessed by others using your password or other confidential details or information.</li>
	</ul>
	
	<div class="head2">Cash balance in your game accounts</div>
	<p>In order to participate in Real Chip Games, you are required to maintain a Cash Balance at all times in your Accounts.</p>
	<p>The Cash Balance will comprise of two components- Monies residing in your Chips Account and monies residing in your Winnings and Bonus Accounts. In relation to such Cash Balance, you undertake/ understand the following:</p>
	<p>All credits to your Account made by you must be through the third-party payment gateway(s) made available on the website by the Company. The Company is not responsible for authorization/denial of any such transactions, and such transactions are subject to and must be undertaken in accordance with the terms and conditions specified by such third-party payment gateways. The Company may however reverse any transaction, in which case the relevant amount would be refunded to the instrument/account which was used to perform the transaction.</p>
	<p>It is further agreed and acknowledged by the Users that all credits in the Chips Account made by the respective Users shall at all times be held by the Company in trust, for and on behalf of the respective Users till such amount is deducted from the Chips Account to enable the Users to participate and play the Real Chip Games.</p>
	<p>All transactions on the website must be conducted in only in Indian Rupees.</p>
	<p>Any winnings in Real Chip Games will be credited exclusively to the Winnings Component of your Winnings and Bonus Account. Any Bonus Amount shall also be credited exclusively to the Bonus Component of your Winnings and Bonus Accounts in accordance with this Agreement,</p>
	<p>The Users agree and acknowledge that the Company shall act as the agent of the respective winner in a Real Chips Game and is authorized to collect and receive the winning amount from the other participants in the game and shall hold the same in the Winnings Component of the Winnings and Bonus Account, in trust for and on behalf of the winner until such time as the User may decide to utilize it to play a Real Chips Game or withdraw the same, in accordance with the terms and conditions of this Agreement.</p>
	<p>The Users further agree and acknowledge that the Company shall hold the Bonus Amount (if any) in the Bonus Component of the Winnings and Bonus Account in trust, for and on behalf of the respective users until such time as the User may decide to utilize it to play a Real Chips Game or withdraw it, in accordance with the terms and conditions of this Agreement.</p>
	<p>A cash amount corresponding to the aggregate of the amounts in the Chips Account and the Winnings and Bonus Accounts of all Users is maintained in unencumbered and non-interest bearing bank account(s) by the Company at all times; separate from other funds of the Company. Such Cash Balances are available to be withdrawn at any time by Users, subject to specific restrictions contained in the Agreement. To the extent permitted by law, the claims of Users over amounts corresponding to their Cash Balances will be given preference over all other claims.</p>
	<p>Any withdrawal of amounts from your Accounts may be carried out only in accordance with the terms of this Agreement.</p>
	<p>The Company may impose per-session limits or daily limits, or other types of limits, upon your ability to perform cash credits or Cash Withdrawals, in order to encourage responsible playing as well as to prevent any unauthorized or illegal activity. You will be informed of such limits, if the apply, at the time when they are imposed, and you will also be informed of any change to such limits. While you may request that such limits be modified, the Company reserves the right to impose and modify such limits using its sole discretion.</p>
	<p>Cash Withdrawals may be requested by you at any time, subject to any limits which have been imposed and in accordance with the terms and conditions of this Agreement. Such Cash Withdrawal will be affected by the Company by way of bank transfer to your bank account. Your preference in this regard will be given due consideration. Please note that any Cash Withdrawal will be affected by the Company only in favor of an Indian Rupee account in your name.</p>
	<p>Cash credits and Cash Withdrawals are subject to any charges or fees levied or charged by banks, payment gateways, processors, or other financial institutions or intermediaries.</p>
	<p>The Cash Balance does not carry any interest. The Cash Balance is not transferable or negotiable, except to the extent as may be expressly permitted by the Agreement. Further, no cash withdrawal will be allowed from the Cash Balance associated with the Accounts of each User, unless the relevant User has played sufficient number of Real Chip Games (which may be determined solely by the Company in its discretion) subsequent to the last recorded Cash Credit.</p>
	<p>Except in the manner as provided in this Agreement, no Cash Withdrawal would be permitted from the Chips Account. Cash Withdrawals may be permitted only from the Winnings Component, garnered by participation in the requisite number of Real Chip Games (as determined by the Company in its discretion) and the Bonus Amounts residing in the Bonus Component credited by the Company. To additionally clarify, any Cash Withdrawal would be permitted exclusively from the Winnings and Bonus Account. When the respective User chooses to withdraw such winnings from the Winnings and Bonus Account, the Company on receipt of the request in the specified form would transfer the specified amount to the Users</p>
	<p>Cash Credits made for participation in the Real Chip Games are not available for Cash Withdrawals and the same may be utilized only to gain a seat on the table or in a tournament. Thus no Cash Withdrawal is permitted by redeeming the chips in the Chips Account.</p>
	<p>Accordingly, while purchasing chips from the Cash Balance in order to gain a seat on the table or in a tournament, the non refundable component, i.e. the Chips Account, gets deducted first followed by the refundable component, that is, the Winnings and Bonus Account, to ensure the maximum possible part of the left over amount in the Cash Balance is available for refund through Cash Withdrawal. Further, within the Winnings and Bonus Account, the Bonus Component gets deducted first while purchasing chips followed by the Winnings Component.</p>
	<p>In the event that, for a period of more than six months, you (i) maintain a Cash Balance of Rs. 300 or more, and (ii) fail to participate in a Real Chip Game, the Company reserves the right to hold in trust, forfeit or otherwise deal with the entire amount in the Chips Account as it deems fit. Further the Company shall refund the entire amount in the Winnings and Bonus Account to you by issuing an account payee cheque in your name which will be sent by registered post to the correspondence address associated with your Accounts. In the event the cheque is returned to us without being en-cashed on two separate occasions, the Company reserves the right to hold the amount in the Winnings and Bonus Account in trust, forfeit such amount, or otherwise deal with such amount as it deems fit. In the event that, for a period of more than six months, you (i) maintain a Cash Balance of less than Rs. 300, and (ii) fail to participate in a Real Chip Game, the Company reserves the right to hold the amount of such Cash Balance in trust, forfeit such Cash Balance, or otherwise deal with such Cash Balance as it deems fit.</p>
	<p>The Company is obligated to deduct tax at source in case of Real Chip Games upon winnings of more than Rs. 10,000/-, as the case may be. In such cases, winnings shall be credited to your Winnings and Bonus Account after deducting TDS @ 30%. Please note that in accordance with this agreement, you must possess a valid PAN and provide your PAN details and proofs thereof immediately upon request, in order to enable us to credit such winnings and allow for Cash Withdrawals in this respect. These requirements and provisions may be modified from time to time in accordance with changes to the relevant tax and other laws.</p>
	<p>The Prize Pool is automatically split between 2, 3 or 4 players in certain Tournaments under certain scenarios as mentioned in the Game Rules. We reserve the right to amend, modify or change the rules for automatic splitting of the Prize Pool at any time. By registering and/or participating in any tournament, you agree to these Rules for automatic splitting of the Prize Pool.</p>
	
	<div class="head2">Miscellaneous</div>
	<p>You are prohibited from:</p>
	<p>Undertaking any activity through the Services, the website or the Software that may be construed as money laundering (either under the Prevention of Money Laundering Act, 2002 or otherwise), including, without limitation, deliberately losing Real Chip Games to particular User(s), other forms of collusive or fraudulent activity designed to transfer funds to or from other individuals, or making cash credits through a credit card or similar financial instrument and attempting to make Cash Withdrawals in another form without participating in Real Chip Games.</p>
	<p>Posting, publishing or otherwise making available to other Users through our Services,website or Software, any content which is obscene, defamatory, illegal, prejudicial to the Company, or is otherwise offensive without being illegal.</p>
	<p>Undertaking any activity which may be harmful to other Users or interfere with the functioning of the website, the Software or the Services, including but not limited to attempting to decompile the Software, intercept communications with the website, attempting to mask or spoof your IP address, or uploading or spreading viruses or computer contaminants (as defined in the Information Technology Act, 2000 or such other laws as may be in force in India).</p>
	<p>Employees, directors, consultants and agents of the Company, and any of their immediate relatives, are prohibited from participating in Real Chip Games in any manner, except any participation which may be required in the course of their employment.</p>
	
	<div class="head2">Ace2jak game Rules</div>
	<p>You agree to abide by the rules and regulations of each of the Games as published and periodically updated. You should ensure that you have read and understood the rules and regulations of the Games. These Game Rules form part of the Agreement and can be found on the Website. Please read them before using the Services. We may make additional Games available as part of the Services. This Agreement will apply to any Game Rules relating to such Games. We will let you know about, and give you the opportunity to read, such Game Rules at the time of introducing additional Games to the website. We reserve the right to determine the results and winners of each of the Games in accordance with the Game Rules. By registering and/or participating in any Game or tournament you agree by these determinations. We will post lists of winners on the website following each Game.</p>
	
	<div class="head2">System Failures</div>
	<p>In the event of a server crash, breakdown, software defect, technical failure or any other failure attributable to the Company or otherwise, including any natural disaster or other act of god, which results in disruption to a Game, such Game shall be canceled, any associated amounts will be refunded to participating Users in their respective virtual accounts from where such amounts have been withdrawn, and no Service Charge will be levied upon such Game. You accept that the Company is not liable to you in such cases in any manner, except to the extent hereby stated.</p>
	<p>The Company is not liable for any potential winnings from any unfinished Game.</p>
	
	<div class="head2">Intellectual Property</div>
	<p>All rights, tangible and intangible, including copyright and other intellectual property rights, with regard to the Services, the website and the Software, and any content or information displayed or contained therein, belong exclusively to the Company, unless expressly provided otherwise. The Company is merely permitting the User to play Games online and not use the same for any other commercial gain, and no right of any nature whatsoever is being passed on the user by virtue of permitting him / her to play the Game. Using the Services, the website and the Software does not, expressly or impliedly, give you ownership of any intellectual property rights in the Services,website or Software or the content or information you access.</p>
	<p>While the Company retains all rights, including copyright, over any content which may be generated by Users, including but not limited to the contents of chat messages or message boards/forums, you acknowledge that the Company is not responsible for such User-generated Content. You understand that you will be accessing such User-generated Content at your own risk, and will not hold the Company responsible for an obscene, defamatory, illegal or otherwise offensive User-generated Content which may be displayed or accessible.</p>
	<p>Our Services,website or Software may display content which does not belong to the Company. The Company is not responsible for such content, and this content is the sole responsibility of the person or entity that makes it available.</p>
	
	<div class="head2">Breach and Consequences</div>
	<p>You acknowledge and agree that in the event you commit a breach (as may be determined by the Company in its sole discretion) of any of the terms of the Agreement, or the Company in its sole discretion determines that your continued access to the Services is prejudicial to the Company, other users or the public interest, the Company may take any one or more of the following steps:</p>
	<ul>
		<li>Suspend or delete your Account(s),</li>
		<li>Bar you from using or accessing the Services in the future,</li>
		<li>Freeze, seize or forfeit any Cash Balance(s) associated with your Account(s),</li>
		<li>Impose restrictions upon your ability to play certain types of Games,</li>
		<li>Report any suspicious or potentially illegal activity to legal or governmental authorities, and to entities including banks, payment gateways, processors, or other financial institutions or intermediaries.</li>
		<li>Any such actions as enumerated above which may be taken by the Company would be without prejudice to any other legal or equitable rights/remedies available to the Company.</li>
	</ul>
	
	<div class="head2">Limitation of Liability and Indemnity</div>
	<p>The Company shall not be liable for any claim, loss, injury, or damages (direct, indirect, incidental or any other kind whatsoever) arising from or in connection with your use of the Services, the website or the Software.</p>
	<p>Notwithstanding anything to the contrary contained in the Agreement, you agree that our maximum aggregate liability for all your claims against us, in all circumstances other than for valid Redemption of any Cash Balance in your Accounts, shall be limited to Rs. 2,000/- only.</p>
	<p>You agree to indemnify and hold harmless the Company against any claims, actions, suits, damages, penalties, or awards brought against us by any entity or individual in connection with or in respect of your use of the Services, the website or the Software.</p>
	
	<div class="head2">Disclaimer</div>
	<p>The Company expressly disclaims all responsibility and liability for any harm resulting from:</p>
	<ul>
		<li>Your participation in, or cancellation of, any Game,</li>
		<li>Any activity or transactions with third parties whom you may have connected to through the Services, the website or the Software, and</li>
		<li>Any User-generated Content, including any violation of intellectual property rights with respect to such User-generated Content.</li>
	</ul>
	
	<div class="head2">Warranty</div>
	<p>The Company makes no warranty or representations about the accuracy or completeness of the content contained on the website, the Services or the Software. The website, the Services and the Software, and all content, materials, information, services, and products contained therein, including, without limitation, text, graphics, and links, are provided ‘as is’ and without warranties of any kind, whether express or implied.</p>
	<p>The Company disclaims all warranties, express and implied with regard to the merchantability and fitness for a particular purpose, non-infringement, freedom from computer virus etc. of the website, the Services or the Software. The Company does not represent or warrant that the functions contained in the website, the Services or the Software will be uninterrupted or error-free, that defects will be corrected, or that they or the server that makes the website, the Services or the Software available are free of viruses or other harmful components.</p>
	<p>The Company also reserves the right to limit your use of the Services or participation in any Game, or terminate your Account, in case it determines that you have intentionally caused any malfunction or disruption of the Services. The Company is not liable for any potential winnings from any unfinished Real Chip Games.</p>
	
	<div class="head2">Additional charges that may apply</div>
	<p>Certain additional charges may be levied upon you by the Company, or by payment gateways, banks or other intermediaries, at the time of purchase of chips and Cash Withdrawals. You agree to pay any such additional charges, which may vary between various banks, payment processors or other intermediaries.</p>
	
	<div class="head2">Use of Services</div>
	<p>Commercial use of the Services, website or Software is strictly forbidden. The User is only allowed to use the Software for his/her personal entertainment. Under no circumstances shall a User be permitted to use his/her Accounts for any purpose other than for playing the Games. The Company reserves the right to monitor any effort to establish multiple accounts; in the event the Company discovers that you have opened more than one Chips Account or Winnings and Bonus Account per person, all additional accounts will be closed without notice and continued violation will result in the termination of any and all of your Accounts and the Company may void any associated winnings.</p>
	<p>The User may not attempt to modify, decompile, reverse-engineer or disassemble the Software in any way. The use of external player assistance programs  or artificial intelligence, including, without limitation, ‘robots’ is strictly forbidden in connection with the Services, the website, the Software and the Games. All actions taken in relation to the Games by a User must be executed personally by the User through the user interface accessible by use of the website and/or the Software. You agree that the company may take steps to detect and prevent the use of EPA Programs, robots/ bots, or any form of artificial intelligence. Such action may include, but is not limited to, the examination of software programs running concurrently on the User's computer.</p>
	
	<div class="head2">Collusion and Fraud Prevention</div>
	<p>In order to ensure fair play for all users of the Services, we have taken steps that will prevent you from colluding with other players in order to win/lose or otherwise determine the outcome of a Game. By accepting the Agreement you agree that you will not play the any Game in partnership with or by communicating with other players to give undue benefit to you or other players. In case a player is found to be involved in such activities the Company has the right to withhold the Cash Balance in your Accounts and to cancel and close the Accounts without any communication to you. The Company retains the sole right to determine what constitutes collusive or fraudulent activity in relation to the Services, and its decision in such matters shall be final. In the event the Company finds collusion, fraud or any other unfair practices, it has the right to cancel any such Games and refund the points/amounts involved in any such Games.</p>
	
	<div class="head2">Refunds</div>
	<p>In case of an accidental/ erroneous cash credit or other similar event, you may request for a refund of such Cash Credit transaction within 2 weeks of initiating such transaction. The Company, after determining in its sole discretion whether such Refund request is genuine, and that you have the requisite Cash Balance in your Accounts, will process the Refund request within 2 weeks. Any Refund will be carried out only to the instrument which was used to carry out the corresponding Cash Credit transaction, and no requests for an alternate mode of Refund will be entertained under any circumstances.</p>
	
	<div class="head2">Bonus Amounts</div>
	<p>The Company may, from time to time, credit bonus amounts to your Winnings and Bonus Account in connection with promotional offers or other schemes. Notwithstanding anything contained elsewhere in the Agreement, Bonus Amount Issued or Cash Withdrawals or Refunds in respect of such Bonus Amounts shall be processed/ fulfilled solely at the discretion of the Company, and the User has no automatic right to a Cash Withdrawal or Refund in respect of such Bonus Amounts.</p>
	
	<div class="head2">Disconnections</div>
	<p>The Company will not be liable for any network disconnections on the User’s computer or any other external networks. In case of any disruption of services while a Game is in progress, the Company will cancel the Game and refund the points/ Real Chips irrespective of the status of the Game.</p>
	<p>While participating in a Real Chip Game, a User takes full responsibility for the risk of internet disconnection or communication interferences between their computer and the Company’s servers, any lag or freezing of the game or Software, and any problems attributable to their own computer or network connection. Other than a crash of the Company’s servers, the Company does not take any responsibility for any of the player's disconnections from the server.</p>
	<p>As the Company is aware that internet disconnections or other disruptions may occur, players will remain on the table and can continue to play the Game once the connection is back online, until they are eliminated.</p>
	
	<div class="head2">Third Party websites</div>
	<p>The website may provide links to third-party web sites. Third parties and third party web sites may have different privacy policies, terms and conditions and business practices than we do. Your dealings or communications with any party other than the Company are solely between you and that third party. Reference on the website to any product, process, publication or service of any third party by trade name, domain name, trademark, trade identity, service mark, logo, and manufacturer or otherwise does not constitute or imply its endorsement or recommendation by the Company.</p>
	
	<div class="head2">Governing Law</div>
	<p>This Agreement shall in all respects be governed and interpreted by, and construed in accordance with, the laws of India.</p>
	
	<div class="head2">Jurisdiction</div>
	<p>All disputes, complaints, differences etc, shall be subject to the exclusive jurisdiction of the courts at Hyderabad, Andhra Pradesh, India.</p>
	
	<div class="head2">Reach us</div>
	<p>In case of any questions or complaints, feel free to contact us any time at info@Ace2jak.com. In case of any change of your personal information, please contact Customer Service at info@Ace2jak.com. If you forget your password, or suspect that your password or your Accounts has been manipulated, please contact info@Ace2jak.com.</p>
	
	<div class="head2">Terms and conditions-Accepted</div>
	<p>You undertake to have read and abide by the above terms and conditions.</p>
	
	<div class="head2">Termination of account</div>
	<p>You can cease using the Services and can terminate your Accounts at any time, by writing to us at info@Ace2jak.com and informing us of your intention. Subject to such restrictions as may be applicable to Cash Withdrawals in accordance with the terms and conditions of this Agreement, the Company will refund the remaining amount of your Cash Balance to you at this time.</p>
</div>