<div class="ttinnnerpad"><h2><strong>Withdrawal Policy</strong></h2>

<p>In order for a player to be able to withdraw money from TaashTime, they need to meet the conditions as explained hereunder:</p>

<ul class="bullet-normal">
	<li> The player should have played at least one cash game</li>
	<li> The player must have purchased a minimum of 100 TaashCash through the site</li>
	<li> The player can withdraw a minimum of INR 500 and a maximum of INR 5000 per withdrawal</li>
	<li> The player can withdraw from their winnings and the bonuses awarded to them</li>
	<li> A withdrawal request for any unplayed amount shall be considered as a Refund</li>
	<li> All other standard Terms and conditions shall apply to Player</li>
	<li> Should have a minimum deposit of 100 INR in the last 30 days </li>
	<li> Any winnings from bonus due amount are not eligible for withdrawal</li>
	<li> Bonus due amount will be reset to zero, once the withdrawal request is made. If the withdrawal request is declined, the deducted bonus due amount at the time of withdrawal request will be credited back</li>
	<li> Free money players can play only Rs10 games. To bet on higher tables, free money players should make a minimum deposit of Rs 100.</li>
	<li> Maximum balance a free money player can have is Rs 100. In case of higher amounts, the account balance will be reset to Rs. 100.</li>
	<li> Any winnings from non depositors or free money players will be credited to cash due account.</li>
	<li> Prior processing a withdrawal, player should have a minimum deposit of Rs. 100 in the last 30 days.</li>
	<li> Any winnings from the free signup offer are not cashable.</li>
</ul>

<h2><strong>Withdrawal Process</strong></h2> 
<ul class="bullet-normal">
	<li> To make a withdrawal request, the player must enter the details required on the Withdrawal Request <a href="/withdrawal/request">Page</a></li>
	<li> As soon as you make a withdrawal request, the amount requested shall be blocked in your account and your balance displayed shall be deducted of the same amount.</li>
	<li> Once the withdrawal is processed, your accounts shall be updated appropriately. </li>
	<li> The player can withdraw for free only once in a month. Any further withdrawals shall attract a fee of INR 100 per withdrawal.</li>
	<li> Withdrawals are processed once a week on Thursday.</li>
	<li> Withdrawals submitted post 12:00 PM on Wednesday shall be processed during the next week's cycle.</li>
	<li> Upon the successful processing of a withdrawal application, the money due (less any fees and taxes payable) shall be transferred directly to the player's bank account OR sent by check to the address provided by the player, as per the records of the site.</li>
</ul>

<h2><strong>Flowback Process</strong></h2>
<ul class="bullet-normal">
	<li>Should the player choose to discontinue the withdrawal process, he/she can flowback the amount requested for withdrawal</li>
	<li>The Flowback mechanism is present in the Banking page</li>
	<li>The player can specify the amount they wish to flowback and play with</li>
	<li>All flowbacks reflect immediately </li>
	<li>All flowbacks are free! There is no charge associated with the same.</li>
</ul>

<!-- h2><strong>Withdrawal Policy</strong></h2>
<p>In order for a player to be able to withdraw money from <?php echo $this->frontendShortName;?>, they need to meet the conditions as explained hereunder:</p>
<ul class="bullet-normal">
	<li>The player should have played at least one cash game</li>
	<li>The player should have played with a multiple of the sum of deposit and bonus awarded with the same. </li>
	<li>The player must have deposited a minimum of <?php echo $this->minDeposit; ?> </li>
	<li>The player must have played in at least one cash game</li>
	<li>The player should have bonus balance less than their real money balance (post withdrawal) </li>
	<li>The player can withdraw a minimum of <?php echo $this->minWithdrawAmount; ?> and a maximum of <?php echo $this->maxWithdrawAmount ?> per withdrawal</li>
	<li>The player can withdraw for free only <?php echo $this->freeWithdrawTimes; ?> in a month. 
	</li>
	<li>Withdrawals are processed once a week on <?php echo $this->processingDay;?>. </li>
	<li>Withdrawals submitted post 12:00 PM on <?php echo $this->processingPreviousDay; ?> shall be processed during the next week's cycle. </li>
	<li>Upon the successful processing of a withdrawal application, the money due shall be sent by check to the address provided by the player, as per the records of the site or directly to the player's bank account. </li>
</ul--></div>
