<form name="deposit-form" method="POST" action="https://www.moneybookers.com/app/payment.pl">
	<input type="hidden" name="pay_to_email" value="nikhil@fortuity.in" />
	<input type="hidden" name="return_url" value="http://playrummynow.tld" />
	<input type="hidden" name="status_url" value="http://playrummynow.tld/banking/fundbonus" />
	<input type="hidden" name="status_url2" value="mailto:nikhil@fortuity.in" />
	<input type="hidden" name="language" value="EN" />
	<input type="hidden" name="amount" value="100" />
	<input type="hidden" name="currency" value="INR" />
	<input type="hidden" name="detail1_description" value="Description" />
	<input type="hidden" name="detail1_text" value="Text Description" />
	<input type="submit" name="Submit" value="Submit" />
</form>