<div class=" ttbankdtls">
  <div class="ttcolactive">Banking Details</div>
  <div>
    <p>Taashtime believes in providing the best Online Rummy  service to its customers. Along side its world-class Rummy experience,  Taashtime also provides a varied variety of ways to buy TaashCash and FunCoins.  The varied modes of payments and the plethora of banks supporting us emphasizes  on the trustworthiness of the site. We take payments in the form of:</p>
    <ul>
      <li>Netbanking</li>
      <li>Direct Credit</li>
      <li>Credit Cards </li>
      <li>MOL (Money OnLine)</li>
      <li>Door to Door banking</li>
    </ul>
    <div><strong>Netbaking</strong></div>
    <div>
      <p>Taashtime offers Netbaking services to a number of banks in India. The following are the banks that support us.</p>
      <table border="1" cellspacing="0" cellpadding="0"   >
        <tr>
          <th>Payment    Name</th>
          <th>Payment    Method</th>
          <th>Support</th>
          <th>purchase    Time</th>
        </tr>
        <tr>
          <td><a href="https://global.mol.com/in/portal/en/Registration.aspx" target="_blank">MOL</a></td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttmol_logofoot.gif" alt="mol_logofoot" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Axis Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttaxis_logo.gif" alt="axis_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Allahabad Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttallahabad_logo.gif" alt="allahabad_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>The Bank of Rajasthan</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttrajasthan_logo.gif" alt="rajasthan_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>South Indian Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttsouthindianbank_logo.gif" alt="southindianbank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Vijaya Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttvijayabank_logo.gif" alt="vijayabank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Bank of Baroda</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofbaroda_logo.gif" alt="bankofbaroda_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Federal Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttfederal_logo.gif" alt="federal_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Dhanlaxmi Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttdhanlaxmi_logo.gif" alt="dhanlaxmi_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Deutsche Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttdeutschebank-logo.gif" alt="deutschebank-logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Bank of Bahrain &amp; Kuwait</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofbahrain-logo.gif" alt="bankofbahrain-logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Karnataka Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttkarnatakabank_logo.gif" alt="karnatakabank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Oriental Bank of Commerce</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttobc_logo.gif" alt="obc_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Standard Chartered</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttstandard_logo.gif" alt="standard_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Indian Overseas Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttiob_logo.gif" alt="iob_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>ICICI Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/tticici_logo.gif" alt="icici_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Union Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttunionbank_logo.gif" alt="unionbank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Yest Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttyesbank_logo.gif" alt="yesbank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Corporation Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttcorporationbank_logo.gif" alt="corporationbank_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>Bank of India</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/ttbankofindia_logo.gif" alt="bankofindia_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
        <tr>
          <td>HDFC Bank</td>
          <td><img border="0" width="99" height="37" src="/css/rummy.tld/images/tthdfc_logo.gif" alt="hdfc_logo" /></td>
          <td>Yes </td>
          <td>Instant</td>
        </tr>
      </table>
    </div>
    <div><strong>Direct Credit</strong></div>
    <div>
      <p>Taashtime also accepts Direct Credit. This enables customers to transfer cash from the safety of their bank account without logging in through Taashtime. We accept Direct Credit from any bank in the world (except for restricted Jurisdictions).</p>
      <div>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <th>&nbsp;</th>
            <th  style="border-left:#484848 solid 1px">RBS</th>
            <th style="border-left:#484848 solid 1px">ICICI</th>
          </tr>
          <tr>
            <td><strong>A/c Name</strong></td>
            <td>Fortuity Infotech Pvt. Ltd.</td>
            <td>Fortuity Infotech Pvt. Ltd.</td>
          </tr>
          <tr>
            <td><strong>A/c No</strong></td>
            <td>1719764</td>
            <td>16845965</td>
          </tr>
          <tr>
            <td><strong>IFSC</strong></td>
            <td>ABNA0100317</td>
            <td>ICICI0000008</td>
          </tr>
          <tr>
            <td><strong>Bank</strong></td>
            <td>The Royal Bank of Scotland N.V.</td>
            <td>ICICI Bank</td>
          </tr>
          <tr>
            <td><strong>Branch</strong></td>
            <td>Hyderabad</td>
            <td>Khairtabad</td>
          </tr>
          <tr>
            <td><strong>Address</strong></td>
            <td>Stamford Park<br>
              Door No 8-2-269/4/B, Road No. 2, Banjara Hills,<br>
              Hyderabad 500 034,</td>
            <td>6-2-1012, Tgv Mansions, Opp. Institution Of Engineers, Khairatabad, Hyderabad. 500004 </td>
          </tr>
        </table>
      </div>
    </div>
    <div><strong>Credit Card</strong></div>
    <div>
      <p>Credit Cards, the most widely used payment method in the  world is supported by Taashtime. We accept Credit cards from different services  around the world through our various payment channels. Currently our processors  support:</p>
      <table border="1" cellspacing="0" cellpadding="0" width="100%">
        <tr>
          <th colspan="2"  > Processor Type </th>
        </tr>
        <tr>
          <td width="319" >VISA</td>
          <td width="319" ><img src="/css/rummy.tld/images/ttvisa.gif" width="60" height="36" /></td>
        </tr>
        <tr>
          <td width="319" >Master Card</td>
          <td width="319" ><img src="/css/rummy.tld/images/ttmastercard_s.gif" width="60" height="36" /></td>
        </tr>
        <tr>
          <td width="319" >American express</td>
          <td width="319" ><img src="/css/rummy.tld/images/ttamerican.gif" width="60" height="36" /></td>
        </tr>
      </table>
    </div>
    <div><strong>MOL</strong></div>
    <div>
      <p><strong>MOLPoints</strong> is an online micropayment system developed and  operated by MOL AccessPortal Berhad. This payment system enables consumers  nationwide to purchase products and services through the MOL portal and pay for  their purchases at over 540,000 channels across more than 75 countries  worldwide WITHOUT the use of a credit card.<br />
        MOL Image</p>
    </div>
    <div><strong>Door to Door Banking</strong></div>
    <div>
      <p>At Taashtime, we believe in  providing premium service to our esteemed customers. Our door to door service  is another way to prove that. We provide door to door collection mechanism in  over 12 cities in India through our various channel partners.</p>
      <table border="0" cellspacing="0" cellpadding="0" width="100%" >
        <tr>
          <th  >City </th>
          <th   >No.of Centers </th>
        </tr>
        <tr>
          <td > Ahmedabad </td>
          <td   >111</td>
        </tr>
        <tr>
          <td >Bangalore</td>
          <td   >81</td>
        </tr>
        <tr>
          <td >Chandigarh</td>
          <td   >36</td>
        </tr>
        <tr>
          <td >Chennai</td>
          <td   >117</td>
        </tr>
        <tr>
          <td >Faridabad</td>
          <td   >27</td>
        </tr>
        <tr>
          <td >Ghaziabad</td>
          <td   >29</td>
        </tr>
        <tr>
          <td >Gurgaon </td>
          <td   >23</td>
        </tr>
        <tr>
          <td >Hyderabad</td>
          <td   >83</td>
        </tr>
        <tr>
          <td >Kolkata</td>
          <td   >167</td>
        </tr>
        <tr>
          <td >Mumbai</td>
          <td   >103</td>
        </tr>
        <tr>
          <td >Navi Mumbai</td>
          <td   >5</td>
        </tr>
        <tr>
          <td >New Delhi</td>
          <td   >98</td>
        </tr>
        <tr>
          <td >Noida</td>
          <td   >5</td>
        </tr>
        <tr>
          <td >Pune</td>
          <td   >38</td>
        </tr>
        <tr>
          <td >Thane</td>
          <td   >5</td>
        </tr>
        <tr>
          <td >Visakhapatnam</td>
          <td   >44</td>
        </tr>
      </table>
    </div>
  </div>
</div>
