<?php
echo $this->form;
echo $this->message;
/*?>
<center>
<p>Want more cash?! Here are the ways to get it.</p>
<br>
<table border="0" align="center">
	<tr>
		<img src="/promos/rummy.tld/promotion2.jpg" usemap="#promo2" border=0/>
		<img src="/promos/rummy.tld/promotion1.jpg" usemap="#promo1" border=0/>
		<br>
		<img src="/promos/rummy.tld/promotion3.jpg" usemap="#promo3" border=0/>
		<img src="/promos/rummy.tld/promotion4.jpg" usemap="#promo4" border=0/>
	</tr>
</table>
</center>
<map name="promo1">
	<area shape="rect" coords="0,0,250,250" href="http://nationalrummy.com/game">
</map>
<map name="promo2">
	<area shape="rect" coords="0,0,250,250" href="http://nationalrummy.com">
</map>
<map name="promo3">
	<area shape="rect" coords="0,0,250,250" href="http://nationalrummy.com">
</map>
<map name="promo4">
	<area shape="rect" coords="0,0,250,250" href="http://nationalrummy.com">
</map>
