<?php /*
$webConfig = Zend_Registry::getInstance()->isRegistered('webConfig')? Zend_Registry::getInstance()->get('webConfig'):'null';
$viewDir = $webConfig['viewDir'];

<div>
	<div class="promo">
	<img src="<?php echo "/images/" . $viewDir. "/promo.png" ?> " alt="" width="390" height="310">"></img>
	*/?>
		<?php /*
		if($this->noPlayerId)
		{
			$this->form->getElement('login')->addError('Please enter a username');
			$this->form->getElement('password')->addError('Please enter the password');
			$this->form->getElement('confirmPassword')->addError('Please enter the password');
			$this->form->getElement('email')->addError('Please enter the email');
			//print "<div>You need to be logged in to cast a vote. Please login or signup now to win exciting prizes at taashtime</div>";
			print "<div id='error-message'>You need to be logged in to cast a vote. Please login or signup now to win exciting prizes at taashtime</div>";
		}
		if($this->noTeam)
		{
			print "<div id='error-message'>Please select a team.</div>";
		}
		if($this->voteCast)
		{
		?>
			<div id='vote-message'>Your vote is casted</div>
			<div align="center">
			<p>
				If your chosen team wins, you get Rs. 100. <br>Else you get Rs. 50.<br>
				You can change your vote anytime before the match ends.<br>
				Please <a href="/" alt="Re-cast your vote">Click Here</a> if you want to change your vote.
			</p>
			</div>
		<?php 
		}
		else
		{
		?>
		<div>Who will win today?</div>
		<table>
			<tr><td><label id="label-team-1"><?php echo $this->team_1_name;?></label></td><td><label id="label-team-2"><?php echo $this->team_2_name;?></label></td></tr>
			<tr><td><img id="image-team-1" src="<?php echo $this->team_1_image;?>"></img></td><td><img id="vs" src="/images/rummy.tld/vs.png"></img></td><td><img id="image-team-2" src="<?php echo $this->team_2_image;?>"></img></td></tr>
			<tr><td><input id="radio-team-1" <?php echo $this->team_1_checked;?> type="radio" name="team" value="<?php echo $this->team_1_value;?>" /></td><td><input id="radio-team-2" <?php echo $this->team_2_checked;?> type="radio" name="team" value="<?php echo $this->team_2_value;?>" /></td></tr>
		</table>
		<div>Pick the winning team, earn Rs 100/-</div>
		<input id ="cricket-form-submit" src="/images/rummy.tld/vote-now.png" type="image" name="submit"/>
		<?php
		}*/
		?>
	
	
<?php
/*	//echo $this->cricketForm; //<img src="<?php echo "/images/" . $viewDir. "/promo.png"" alt="" width="390" height="310">
	</div>
    <div class="reg" id="regForm">
    	<strong><?php echo $this->heading?></strong>
    	*/?>
    	<?php 
    	if($this->form)
    	{
	    	?>
	    	<div id="join-now">
	    	<h2 class="pad-t-20"><strong><?php echo $this->heading?></strong></h2>
	    	<div id="get-blurb-home" class="right"><img src="/css/rummy.tld/images/get-25-blurb.png" width="97" height="98" alt="Get Rs. 25/-!" /></div>
	    	<div class="reg" id="regForm">
	    		<?php
	    		echo $this->form;
	    		?>
	    		</div>
	    		</div>
	    		<!-- 
	    		<div id="break">&nbsp; &nbsp; 
</div>
-->
	    		<?php 
    	}
    	else
    	{
			?>
    	
    	<div id="my-account-box"><div id="profile-photo" class="right"><a href = "/auth/image"><img src="<?php echo $this->imagePath;?>" width="53" height="52" alt="Profile Photo"></a></div>
        <h3 class="pad-t-20"><strong>My Account</strong></h3>

<div id="my-account">
<p class="left pad-t-20 my-acc-left"><strong>Balance:</strong></p>
<p class="left color-blue pad-l-15 pad-t-20"><strong>
<?php 
echo $this->cash;
?>
</strong></p>
<div class="clear"></div>
<p class="left my-acc-left"><strong>Bonus:</strong></p>
<p class="left color-blue pad-l-15"><strong>
<?php 
echo $this->bonus;
?>
</strong></p>
<div class="clear"></div>
<p class="left my-acc-left"><strong>Points:</strong></p>
<p class="left color-blue pad-l-15 my-acc-left"><strong>
<?php 
echo $this->loyality;
?>
</strong></p>
<div class="clear"></div>
</div>

<p class="bottom"><strong><a href="#">My Game History</a></strong></p></div>
	    <?php
	    echo $this->form;
	    ?>
    <!--div class="submit"><a href="#">Submit</a></div-->
<?php  		
    	}
  


