
		<div id="flashContent">
			<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="/games/bingocrush/container/web-container" align="middle">
				<param name="movie" value="/games/bingocrush/container/web-container.swf" />
					<param name="FlashVars" value="base_url=&theme=bingo&xml_config=/games/bingocrush/container/<?=$this->gameConfig?>.txt&game_config=/games/bingocrush/multi-player/bingo/<?=$this->gameConfig?>.txt&game_swf_path=<?=$this->swfPath ?>&log_id=123&session_id=<?=$this->sessionId?>&player_id=<?=$this->playerId?>&login=<?=$this->loginName?>&pass_key=<?=$this->password?>&image_path=<?=$this->imagePath?>&game_id=<?=$this->gameId ?>&game_flavour=<?=$this->flavour ?>&amount_type=BONUS&balance_amount=250&wagered_currency=<?=$this->currency?>&pjp_win_amount=100&locale=en_US" />
				<param name="quality" value="high" />
				<param name="bgcolor" value="#000000" />
				<param name="play" value="true" />
				<param name="loop" value="true" />
				<param name="wmode" value="window" />
				<param name="scale" value="showall" />
				<param name="menu" value="true" />
				<param name="devicefont" value="false" />
				<param name="salign" value="" />
				<param name="allowScriptAccess" value="sameDomain" />
				<!--[if !IE]>-->
				<object type="application/x-shockwave-flash" data="/games/bingocrush/container/web-container.swf" width="100%" height="100%">
					<param name="movie" value="/games/bingocrush/container/web-container.swf" />
					<param name="FlashVars" value="base_url=&theme=bingo&xml_config=/games/bingocrush/container/<?=$this->gameConfig?>.txt&game_config=/games/bingocrush/multi-player/bingo/<?=$this->gameConfig?>.txt&game_swf_path=<?=$this->swfPath ?>&log_id=123&session_id=<?=$this->sessionId?>&player_id=<?=$this->playerId?>&login=<?=$this->loginName?>&pass_key=<?=$this->password?>&image_path=<?=$this->imagePath?>&game_id=<?=$this->gameId ?>&game_flavour=<?=$this->flavour ?>&amount_type=BONUS&balance_amount=250&wagered_currency=<?=$this->currency?>&pjp_win_amount=100&locale=en_US" />
					<param name="quality" value="high" />
					<param name="bgcolor" value="#000000" />
					<param name="play" value="true" />
					<param name="loop" value="true" />
					<param name="wmode" value="window" />
					<param name="scale" value="showall" />
					<param name="menu" value="true" />
					<param name="devicefont" value="false" />
					<param name="salign" value="" />
					<param name="allowScriptAccess" value="sameDomain" />
				<!--<![endif]-->
					<a href="http://www.adobe.com/go/getflash">
						<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" />
					</a>
				<!--[if !IE]>-->
				</object>
				<!--<embed src="/games/bingo-beta/container/web-container.swf" flashVars = "xml_config=/games/bingo-beta/container/config.txt&game_config=/games/bingo-beta/multi-player/bingo/config.txt&game_swf_path=/games/bingo-beta/multi-player/bingo/game.swf&log_id=123&session_id=123&player_id=10&bet_amount=10&game_id=<?=$this->gameId ?>&login=yaswanth|1|RU_US&pass_key=iiit123&selected_numbers=[1,2,3,4,5,6,25,30,56,76]&generated_numbers=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]&win_string=[1,2,3,4,5,6]&win_amount=10&balance_amount=250&wagered_currency=USD&pjp_win_amount=100&locale=en_US" quality="high" bgcolor="#ffffff"
				width="800" height="600" name="Keno" align="middle"
				play="true"
				loop="false"
				quality="high"
				allowScriptAccess="sameDomain"
				type="application/x-shockwave-flash"
				pluginspage="http://www.adobe.com/go/getflashplayer">
			</embed>-->
				<!--<![endif]-->
			</object>
		</div>
	
