<center>
<div style="width:640px" id="__ss_7490083"> <strong
style="display:block;margin:12px 0 4px"><a
href="http://www.slideshare.net/nationalrummy/a-beginners-guide-to-indian-rummy-nationalrummy-7490083"
title="A beginner’s guide to indian rummy nationalrummy">A Beginner’s
Guide to Indian Rummy at National Rummy</a></strong> <iframe
src="http://www.slideshare.net/slideshow/embed_code/7490083"
width="640" height="480" frameborder="0" marginwidth="0"
marginheight="0" scrolling="no"></iframe> 
<!-- div style="padding:5px 0
12px"> View more <a
href="http://www.slideshare.net/">presentations</a> from <a
href="http://www.slideshare.net/nationalrummy">nationalrummy</a> </div> </div-->
</center>

