<?php 
echo $this->form ;
echo $this->table($this->value);
?>

<script type="text/javascript" >
	document.getElementById("frontend").style.display = "none";
	document.getElementById("frontend-label").style.display = "none";

	document.getElementById("affiliate").style.display = "none";
	document.getElementById("affiliate-label").style.display = "none";

	document.getElementById("tracker").style.display = "none";
	document.getElementById("tracker-label").style.display = "none";

	
	AnalyticsForms() 
	
</script>