<h3>Player Speaks</h3>
	<ul class="speaks">
		<li><img src="<?php echo "/images/" . $this->imagesDir . "../profiles/pic24.jpg"?>" width="50" height="50" alt=""> <div>This site is great. I have played on other sites but the feel of this site is fantastic! I wish them all the success going forward! <strong>Madhu Avasthi</strong> </div></li>
		<li><img src="<?php echo "/images/" . $this->imagesDir . "../profiles/pic29.jpg"?>" width="50" height="50" alt=""> <div>I like playing rummy with my family and this site lets me do that in a great way! The private rooms are just awesome!<strong>Sreeram Vinoth</strong></div></li>
		<li><img src="<?php echo "/images/" . $this->imagesDir . "../profiles/pic38.jpg"?>" width="50" height="50" alt=""> <div>Living in small towns, I could play rummy in the local ladies clubs. After moving to Mumbai, I have been cut off from my friends and missed rummy. This site has allowed me to connect with them again. Thanks nationalrummy.com!<strong>Neeraja Thakur</strong></div></li>
		<li><img src="<?php echo "/images/" . $this->imagesDir . "../profiles/pic92.jpg"?>" width="50" height="50" alt=""> <div>I love rummy and I love this site. It is great!<strong>Sumit Narayan</strong></div></li>
	</ul>
   </div>

