<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
<title>Taashnetwork Partner</title>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
<style media="all" type="text/css">
@import "/css/partner/ace2jak/style.css";
@import "/js/jquery/css/custom-theme/jquery-ui.css";
</style>
</head>
<body>
<div id="main">
  <div id="header"> <a href="http://taashnetwork.com/" target="_blank" class="logo"><img src="/images/partner/ace2jak/taashnetwork.png" height="44" alt="" /></a>
  <?php 
    	$partial = array('top_menu.phtml','partner');
		$this->navigation()->menu()->setPartial($partial);
		echo $this->navigation()->menu()->render();
	?>
    <!-- <ul id="top-navigation">
      <li class="active"><span><span>Homepage</span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Users</a></span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Orders</a></span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Settings</a></span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Statistics</a></span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Design</a></span></span></li>
      <li><span><span><a href="http://all-free-download.com/free-website-templates/">Contents</a></span></span></li>
    </ul> -->
  </div>
  <div id="middle">
    <div id="left-column">
      <?php 
    	$partial = array('menu.phtml','partner');
		$this->navigation()->menu()->setPartial($partial);
		echo $this->navigation()->menu()->render();
	?>
     <!--  <ul class="nav">
        <li><a href="http://all-free-download.com/free-website-templates/">Lorem Ipsum dollar</a></li>
        <li><a href="http://all-free-download.com/free-website-templates/">Dollar</a></li>
        <li><a href="http://all-free-download.com/free-website-templates/">Lorem dollar</a></li>
        <li><a href="http://all-free-download.com/free-website-templates/">Ipsum dollar</a></li>
        <li><a href="http://all-free-download.com/free-website-templates/">Lorem Ipsum dollar</a></li>
        <li class="last"><a href="http://all-free-download.com/free-website-templates/">Dollar Lorem Ipsum</a></li>
      </ul>
      <a href="http://all-free-download.com/free-website-templates/" class="link">Link here</a> <a href="http://all-free-download.com/free-website-templates/" class="link">Link here</a> --> 
     </div>
    <div id="center-column">
    <?php 
    echo $this->layout()->content;
    ?>
      <!-- <div class="top-bar"> <a href="http://all-free-download.com/free-website-templates/" class="button">ADD NEW </a>
        <h1>Contents</h1>
        <div class="breadcrumbs"><a href="http://all-free-download.com/free-website-templates/">Homepage</a> / <a href="http://all-free-download.com/free-website-templates/">Contents</a></div>
      </div> -->
      <br />
      <!-- <div class="select-bar">
        <label>
        <input type="text" name="textfield" />
        </label>
        <label>
        <input type="submit" name="Submit" value="Search" />
        </label>
      </div> -->
      <!-- <div class="table"> <img src="/images/partner/ace2jak/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/images/partner/ace2jak/bg-th-right.gif" width="7" height="7" alt="" class="right" />
        <table class="listing" cellpadding="0" cellspacing="0">
          <tr>
            <th class="first" width="177">Header Here</th>
            <th>Header</th>
            <th>Head</th>
            <th>Header</th>
            <th>Header</th>
            <th>Head</th>
            <th>Header</th>
            <th class="last">Head</th>
          </tr>
          <tr>
            <td class="first style1">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr class="bg">
            <td class="first style2">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr>
            <td class="first style3">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr class="bg">
            <td class="first style1">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr>
            <td class="first style2">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr class="bg">
            <td class="first style3">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
          <tr>
            <td class="first style4">- Lorem Ipsum </td>
            <td><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
            <td><img src="/images/partner/ace2jak/hr.gif" width="16" height="16" alt="" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td><img src="/images/partner/ace2jak/edit-icon.gif" width="16" height="16" alt="edit" /></td>
            <td><img src="/images/partner/ace2jak/login-icon.gif" width="16" height="16" alt="login" /></td>
            <td><img src="/images/partner/ace2jak/save-icon.gif" width="16" height="16" alt="save" /></td>
            <td class="last"><img src="/images/partner/ace2jak/add-icon.gif" width="16" height="16" alt="add" /></td>
          </tr>
        </table>
        <div class="select"> <strong>Other Pages: </strong>
          <select>
            <option>1</option>
          </select>
        </div>
      </div> -->
      <!-- <div class="table"> <img src="/images/partner/ace2jak/bg-th-left.gif" width="8" height="7" alt="" class="left" /> <img src="/images/partner/ace2jak/bg-th-right.gif" width="7" height="7" alt="" class="right" />
        <table class="listing form" cellpadding="0" cellspacing="0">
          <tr>
            <th class="full" colspan="2">Header Here</th>
          </tr>
          <tr>
            <td class="first" width="172"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr>
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
          <tr class="bg">
            <td class="first"><strong>Lorem Ipsum</strong></td>
            <td class="last"><input type="text" class="text" /></td>
          </tr>
        </table>
        <p>&nbsp;</p>
      </div> -->
    </div>
    <!-- <div id="right-column"> <strong class="h">INFO</strong>
      <div class="box">Detect and eliminate viruses and Trojan horses, even new and unknown ones. Detect and eliminate viruses and Trojan horses, even new and </div>
    </div> -->
  </div>
  <div id="footer"></div>
</div>
<!-- <div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div> -->
<?php 
$this->JQuery()->setLocalPath("http://code.jquery.com/jquery-1.9.1.js");
$this->JQuery()->setUiLocalPath("http://code.jquery.com/ui/1.10.2/jquery-ui.js");
echo $this->JQuery();
?>
<script src = "/js/jquery.clockpick.js"></script>
</body>
</html>