<?php echo 'Running Keno Machine details'?>
<br></br>
<br></br>
<table border='1'>
<?php 
foreach($this->runningKenoData as $key => $value)
{?>
	<tr>
		<td>
			<?=$key?>
		</td>
		<td>
			<?=$value?>
		</td>
	</tr>
	
<?}?>
</table>
<br></br>
<br></br>
<?php echo 'Pjp Details'?>
<br></br>
<br></br>
<?php
foreach($this->pjpMachines as $pjpMachine)
{?>
	<table border='1'>
	<?php
	foreach($pjpMachine as $key => $value)
	{?>
		<tr>
			<td>
				<?=$key?>
			</td>
			<td>
				<?=$value?>
			</td>
		</tr>
			
	<?}?>
	</table>
	<br></br>
	<br></br>
<?}?>

<a href = "<?php echo $this->url(array(
							'controller' => 'keno',
							'action' => 'edit',
							'id' => $this->runningKenoData['runningKenoId']));
			?>">
			<?php echo 'edit'?>
	</a>

