<?php
$authSession = new Zenfox_Auth_Storage_Session();
$sessionData = $authSession->read();

$iterator = new RecursiveIteratorIterator ( $this->container, RecursiveIteratorIterator::SELF_FIRST );
$prevDepth = - 1;
foreach ( $iterator as $page ) {
	if($sessionData){
		if(($page->getHref () == '/') || strpos($page->getHref (), 'logout')){
			continue;
		}
	}
	if ($page->isVisible() && $this->navigation()->accept($page)) {
		$depth = $iterator->getDepth ();
		$isActive = $page->isActive ( true );
		if (($depth != 1) && ($depth > $prevDepth)) {
			$html [] = '<ul class="nav" id="main-menu">' . "\n";
		} else if($depth > $prevDepth){
			$html [] = '<ul class="dropdown-menu sub-menu" id="nav-menu-sub">' . "\n";
		}	else if ($prevDepth > $depth) {
			for($i = $prevDepth; $i > $depth; $i --) {
				$html [] = '</li>' . "\n";
				$html [] = '</ul>' . "\n";
			}
			$html [] = '    </li>' . "\n";
		} else {
			$html [] = '    </li>' . "\n";
		}
		if($depth != 0 && $depth >= $prevDepth){
			$html [] = '<li>';
			$html [] = '<a href="' . $page->getHref () . '">'  . $page->getLabel () . '</a>' . "\n";
		}
		else{
			$class = "";
			if($isActive)
			{
				$class="active";
			}
			$onclick = "()";
			$href = $page->getHref();
			$style = "";
			if(strpos($page->getHref (), 'game')){
				$onclick = "openGame('/game', 1000, 675)";
				$href = "#";
			}
			$html [] = '<li ' . $style . ' class="dropdown ' . $class . '">';
			$html [] = '<a id="' . $class . '" href="' . $href . '" onclick="' . $onclick . '" class="dropdown-toggle" data-hover="dropdown">'  . $page->getLabel () . '</a>' . "\n";
		}
		$prevDepth = $depth;
	}
}
if($depth != 0)
{
	$html [] = '</li>' . "\n";
    $html [] = '</ul>' . "\n";
}
$html [] = '</li>';
$html [] = '</ul>';
echo join ( PHP_EOL, $html );